#define song_atthespeedoflightfull 0
#define song_chaozfantasy 1
#define song_clutterfunk 2
#define song_electroman_adventures 3
#define song_deadlocked 4
#define song_clutterfunk_2 5
#define song_practice 6
#define song_cant_let_go_remix 7
#define song_polargeist 8
#define song_hexagon_force 9
#define song_toe_2 10
#define song_fingerdash 11
#define song_chaoz_airflow 12
#define song_clubstep_full 13
#define song_geometrical_dominator 14
#define song_back_on_track_full 15
#define song_electrodynamix 16
#define song_the_challenge 17
#define song_beep_beep 18
#define song_time_machine 19
#define song_dash 20
#define song_cant_electroman 21
#define song_menu_theme_b_sides 22
#define song_clubstep 23
#define song_atthespeedoflight 24
#define song_atthespeedoflight2 25
#define song_back_on_track 26
#define song_base_after_base 27
#define song_blast_processing 28
#define song_chaoz_impact 29
#define song_accelerate 30
#define song_against_the_odds_redux 31
#define song_cant_let_go 32
#define song_cycles 33
#define song_atthespeedoflight3 34
#define song_stereo_madness 35
#define song_jumper 36
#define song_xstep 37
#define song_theory_of_everything 38
#define song_candyland 39
#define song_menu_theme 40
#define song_dry_out 41
#define song_scheming_weasel 42
#define song_beast_mode_gdw_cut 43
#define song_max 44