#define song_base_after_base 0
#define song_subtle_oddities 1
#define song_clubstep 2
#define song_eon 3
#define song_back_on_track 4
#define song_whats_a_future_funk 5
#define song_clutterfunk 6
#define song_dash 7
#define song_time_machine 8
#define song_deadlocked 9
#define song_menu_theme 10
#define song_practice 11
#define song_endgame 12
#define song_polargeist 13
#define song_toe_2 14
#define song_electrodynamix 15
#define song_fingerdash 16
#define song_hexagon_force 17
#define song_geometrical_dominator 18
#define song_electroman_adventures 19
#define song_blast_processing 20
#define song_death_moon 21
#define song_stereo_madness 22
#define song_jumper 23
#define song_cycles 24
#define song_eighto 25
#define song_hell 26
#define song_dry_out 27
#define song_cant_let_go 28
#define song_xstep 29
#define song_theory_of_everything 30
#define song_scheming_weasel 31
#define song_max 32