#define song_okiba_crackdown 0
#define song_fingerbang 1
#define song_freedom_dive 2
#define song_lost 3
#define song_infernoplex_full 4
#define song_ultimatedestruction 5
#define song_dance_of_the_violins 6
#define song_dash_full 7
#define song_candyland 8
#define song_subtle_oddities 9
#define song_atthespeedoflightfull 10
#define song_windfall 11
#define song_time_machine_full 12
#define song_the_seven_seas 13
#define song_stereo_madness_2 14
#define song_the_angel 15
#define song_chaozfantasy 16
#define song_whats_a_future_funk 17
#define song_clutterfunk 18
#define song_megalovania 19
#define song_electroman_adventures 20
#define song_deadlocked 21
#define song_practice 22
#define song_atthespeedoflight2 23
#define song_just_right_full 24
#define song_rainbow_tylenol 25
#define song_cant_let_go_remix 26
#define song_isolation 27
#define song_polargeist 28
#define song_idols 29
#define song_fingerdash 30
#define song_clutterfunk_2 31
#define song_beep_beep 32
#define song_chaoz_airflow 33
#define song_geometrical_dominator 34
#define song_check_out 35
#define song_electrodynamix 36
#define song_hsad 37
#define song_back_on_track_full 38
#define song_clubstep_full 39
#define song_toe_2 40
#define song_magic_touch 41
#define song_hexagon_force 42
#define song_eighto_full 43
#define song_jumper 44
#define song_dash 45
#define song_infernoplex 46
#define song_time_machine 47
#define song_jumper_full 48
#define song_stalemate_full 49
#define song_death_moon 50
#define song_endgame 51
#define song_holography 52
#define song_haunted_woods 53
#define song_jack_russel 54
#define song_power_trip 55
#define song_menu_theme_b_sides 56
#define song_clubstep 57
#define song_atthespeedoflight 58
#define song_sonic_blaster 59
#define song_back_on_track 60
#define song_blast_processing 61
#define song_the_challenge 62
#define song_thoughts 63
#define song_base_after_base 64
#define song_endorphins 65
#define song_pyrophoric 66
#define song_stalemate 67
#define song_eighto 68
#define song_just_right 69
#define song_mayhem 70
#define song_midnight 71
#define song_glitch_gremlin 72
#define song_ground_to_krusty_krab 73
#define song_kesobomb 74
#define song_press_start 75
#define song_against_the_odds_redux 76
#define song_cycles 77
#define song_cant_electroman 78
#define song_dry_out_full 79
#define song_emeht_unem 80
#define song_accelerate 81
#define song_stereo_madness 82
#define song_atthespeedoflight3 83
#define song_glint 84
#define song_xo 85
#define song_xstep 86
#define song_theory_of_everything 87
#define song_kratos 88
#define song_ninox 89
#define song_ssendam_oerets 90
#define song_dry_out 91
#define song_chaoz_impact 92
#define song_ground_to_space 93
#define song_mayhem_short 94
#define song_years_gdw_cut 95
#define song_repmuj 96
#define song_flow 97
#define song_golden_haze 98
#define song_ludicrous_speed 99
#define song_metamorphosis 100
#define song_problematic 101
#define song_scheming_weasel 102
#define song_menu_theme 103
#define song_cant_let_go 104
#define song_driving_by_night 105
#define song_youve_been_trolled 106
#define song_round_1_gdw_cut 107
#define song_space_pirates_gdw_cut 108
#define song_beast_mode_gdw_cut 109
#define song_machina_gdw_cut 110
#define song_payload_gdw_cut 111
#define song_max 112