INCLUDE common_oversize.ld
INCLUDE c-in-ram.ld

/* set bank start positions before the
default linker script does it for me */

__prg_rom_0 = 0xa000;
__prg_rom_1 = 0xa000;
__prg_rom_2 = 0xa000;
__prg_rom_3 = 0xa000;
__prg_rom_4 = 0xa000;
__prg_rom_5 = 0xa000;
__prg_rom_6 = 0xa000;
__prg_rom_7 = 0xa000;
__prg_rom_8 = 0xa000;
__prg_rom_9 = 0xa000;
__prg_rom_10 = 0xa000;
__prg_rom_11 = 0xa000;
__prg_rom_12 = 0xa000;
__prg_rom_13 = 0xa000;
__prg_rom_14 = 0xa000;
__prg_rom_15 = 0xa000;

__prg_rom_16 = 0xa000;
__prg_rom_17 = 0xa000;
__prg_rom_18 = 0xa000;
__prg_rom_19 = 0xa000;
__prg_rom_20 = 0xa000;
__prg_rom_21 = 0xa000;
__prg_rom_22 = 0xa000;
__prg_rom_23 = 0xa000;
__prg_rom_24 = 0xa000;
__prg_rom_25 = 0xa000;
__prg_rom_26 = 0xa000;
__prg_rom_27 = 0xa000;
__prg_rom_28 = 0xa000;
__prg_rom_29 = 0xa000;
__prg_rom_30 = 0xa000;
__prg_rom_31 = 0xa000;

__prg_rom_32 = 0xa000;
__prg_rom_33 = 0xa000;
__prg_rom_34 = 0xa000;
__prg_rom_35 = 0xa000;
__prg_rom_36 = 0xa000;
__prg_rom_37 = 0xa000;
__prg_rom_38 = 0xa000;
__prg_rom_39 = 0xa000;
__prg_rom_40 = 0xa000;
__prg_rom_41 = 0xa000;
__prg_rom_42 = 0xa000;
__prg_rom_43 = 0xa000;
__prg_rom_44 = 0xa000;
__prg_rom_45 = 0xa000;
__prg_rom_46 = 0xa000;
__prg_rom_47 = 0xa000;

__prg_rom_48 = 0xa000;
__prg_rom_49 = 0xa000;
__prg_rom_50 = 0xa000;
__prg_rom_51 = 0xa000;
__prg_rom_52 = 0xa000;
__prg_rom_53 = 0xa000;
__prg_rom_54 = 0xa000;
__prg_rom_55 = 0xa000;
__prg_rom_56 = 0xa000;
__prg_rom_57 = 0xa000;
__prg_rom_58 = 0xa000;
__prg_rom_59 = 0xa000;
__prg_rom_60 = 0xa000;
__prg_rom_61 = 0xa000;
__prg_rom_62 = 0xa000;
__prg_rom_63 = 0xa000;

__prg_rom_64 = 0xa000;
__prg_rom_65 = 0xa000;
__prg_rom_66 = 0xa000;
__prg_rom_67 = 0xa000;
__prg_rom_68 = 0xa000;
__prg_rom_69 = 0xa000;
__prg_rom_70 = 0xa000;
__prg_rom_71 = 0xa000;
__prg_rom_72 = 0xa000;
__prg_rom_73 = 0xa000;
__prg_rom_74 = 0xa000;
__prg_rom_75 = 0xa000;
__prg_rom_76 = 0xa000;
__prg_rom_77 = 0xa000;
__prg_rom_78 = 0xa000;
__prg_rom_79 = 0xa000;

__prg_rom_80 = 0xa000;
__prg_rom_81 = 0xa000;
__prg_rom_82 = 0xa000;
__prg_rom_83 = 0xa000;
__prg_rom_84 = 0xa000;
__prg_rom_85 = 0xa000;
__prg_rom_86 = 0xa000;
__prg_rom_87 = 0xa000;
__prg_rom_88 = 0xa000;
__prg_rom_89 = 0xa000;
__prg_rom_90 = 0xa000;
__prg_rom_91 = 0xa000;
__prg_rom_92 = 0xa000;
__prg_rom_93 = 0xa000;
__prg_rom_94 = 0xa000;
__prg_rom_95 = 0xa000;

__prg_rom_96 = 0xa000;
__prg_rom_97 = 0xa000;
__prg_rom_98 = 0xa000;
__prg_rom_99 = 0xa000;
__prg_rom_100 = 0xa000;
__prg_rom_101 = 0xa000;
__prg_rom_102 = 0xa000;
__prg_rom_103 = 0xa000;
__prg_rom_104 = 0xa000;
__prg_rom_105 = 0xa000;
__prg_rom_106 = 0xa000;
__prg_rom_107 = 0xa000;
__prg_rom_108 = 0xa000;
__prg_rom_109 = 0xa000;
__prg_rom_110 = 0xa000;
__prg_rom_111 = 0xa000;

__prg_rom_112 = 0xa000;
__prg_rom_113 = 0xa000;
__prg_rom_114 = 0xa000;
__prg_rom_115 = 0xa000;
__prg_rom_116 = 0xa000;
__prg_rom_117 = 0xa000;
__prg_rom_118 = 0xa000;
__prg_rom_119 = 0xa000;
__prg_rom_120 = 0xa000;
__prg_rom_121 = 0xa000;
__prg_rom_122 = 0xa000;
__prg_rom_123 = 0xa000;
__prg_rom_124 = 0xa000;
__prg_rom_125 = 0xa000;


INCLUDE prg-rom-banked-mode-1_oversize.ld