#define song_stereo_madness_foreverbound 0
#define song_back_on_track_djvi 1
#define song_polargeist_step 2
#define song_dry_out_djvi 3
#define song_base_after_base_djvi 4
#define song_cant_let_go 5
#define song_jumper 6
#define song_time_machine 7
#define song_cycles 8
#define song_xstep 9
#define song_clutterfunk 10
#define song_theory_of_everything 11
#define song_electroman_adventures 12
#define song_clubstep_ 13
#define song_electrodynamix 14
#define song_hexagon_force_waterflame 15
#define song_blast_processing_waterflame 16
#define song_theory_2 17
#define song_geometrical_dominator_waterflame 18
#define song_deadlocked_f-777 19
// #define song_practice_ocularnebula 20
#define song_at_the_speed_of_light 21
#define song_max 22
#define sfx_death 0
#define sfx_max 1