#define song_okiba_crackdown 0
#define song_fingerbang 1
#define song_nine_circles 2
#define song_atthespeedoflightfull 3
#define song_thermodynamix_full 4
#define song_every_end_pt2 5
#define song_infernoplex_full 6
#define song_youve_been_trolled 7
#define song_dash_full 8
#define song_scheming_weasel 9
#define song_the_angel 10
#define song_moon_fries 11
#define song_time_machine_full 12
#define song_clutterfunk 13
#define song_miami_hotline_vol_3 14
#define song_base_after_base 15
#define song_future_funk_pt1 16
#define song_apoplexy 17
#define song_golden_haze_full 18
#define song_accelerate 19
#define song_every_end_pt1 20
#define song_2nes 21
#define song_practice 22
#define song_just_right_full 23
#define song_supernova 24
#define song_polargeist 25
#define song_theory_of_everything 26
#define song_toe_2 27
#define song_press_start 28
#define song_electroman_adventures 29
#define song_geometrical_dominator 30
#define song_fingerdash 31
#define song_shiawase_vip 32
#define song_electrodynamix 33
#define song_free_mind 34
#define song_back_on_track_full 35
#define song_bit_of_a_vibe 36
#define song_beep_beep 37
#define song_future_funk_pt2 38
#define song_eighto_full 39
#define song_endgame 40
#define song_idols 41
#define song_magic_touch 42
#define song_hexagon_force 43
#define song_slash_inferno 44
#define song_astronomical_expedition 45
#define song_factory_time 46
#define song_bad_apple 47
#define song_isolation 48
#define song_clutterfunk_2 49
#define song_cryogenic 50
#define song_animation_warrior_theme 51
#define song_check_out 52
#define song_explorers 53
#define song_death_moon 54
#define song_flow 55
#define song_blast_processing 56
#define song_ludicrous_speed 57
#define song_rainbow_tylenol 58
#define song_fantasy 59
#define song_megalovania 60
#define song_midnight 61
#define song_extraordinary_excitement 62
#define song_haunted_woods 63
#define song_pursuit 64
#define song_against_the_odds_redux 65
#define song_every_madness 66
#define song_final_battle 67
#define song_clubstep 68
#define song_raining_tacos 69
#define song_sonic_blaster 70
#define song_snow 71
#define song_stalemate 72
#define song_tiny_tunes 73
#define song_endorphins 74
#define song_fire_aura 75
#define song_infiltration 76
#define song_airborne_robots 77
#define song_menu_theme 78
#define song_mayhem_re_nes 79
#define song_power_trip 80
#define song_dry_out_full 81
#define song_lost 82
#define song_ultimatedestruction 83
#define song_xenogenesis 84
#define song_cant_let_go 85
#define song_deadlocked 86
#define song_chaozfantasy 87
#define song_infinite_power 88
#define song_cycles 89
#define song_blacklight 90
#define song_glitch_gremlin 91
#define song_select_payment_type 92
#define song_kesobomb 93
#define song_meltdown 94
#define song_subtle_oddities 95
#define song_the_seven_seas 96
#define song_ground_to_space 97
#define song_holography 98
#define song_stereo_madness_2 99
#define song_windfall 100
#define song_stereo_madness 101
#define song_jawbreaker 102
#define song_pyrophoric_legacy_remix 103
#define song_xo 104
#define song_xstep 105
#define song_dance_of_the_violins 106
#define song_driving_by_night 107
#define song_fairydust 108
#define song_kratos 109
#define song_chaoz_impact 110
#define song_jumper_full 111
#define song_meowstuff 112
#define song_ninox 113
#define song_problematic 114
#define song_the_challenge 115
#define song_max 116