#define song_okiba_crackdown 0
#define song_emeht_unem 1
#define song_nine_circles 2
#define song_fingerbang 3
#define song_every_end_pt2 4
#define song_glint 5
#define song_freedom_dive 6
#define song_golden_haze 7
#define song_candyland 8
#define song_infernoplex_full 9
#define song_accelerate 10
#define song_dash_full 11
#define song_subtle_oddities 12
#define song_windfall 13
#define song_atthespeedoflightfull 14
#define song_press_start 15
#define song_eighto 16
#define song_time_machine_full 17
#define song_kesobomb 18
#define song_the_angel 19
#define song_power_trip 20
#define song_whats_a_future_funk 21
#define song_clutterfunk 22
#define song_pursuit 23
#define song_endgame 24
#define song_every_end_pt1 25
#define song_deadlocked 26
#define song_infernoplex 27
#define song_practice 28
#define song_hsad 29
#define song_beep_beep 30
#define song_thermodynamix 31
#define song_check_out 32
#define song_isolation 33
#define song_polargeist 34
#define song_clutterfunk_2 35
#define song_fingerdash 36
#define song_idols 37
#define song_toe_2 38
#define song_dash 39
#define song_chaoz_airflow 40
#define song_stalemate_full 41
#define song_geometrical_dominator 42
#define song_clubstep_full 43
#define song_time_machine 44
#define song_electrodynamix 45
#define song_payload_gdw_cut 46
#define song_back_on_track_full 47
#define song_eighto_full 48
#define song_hexagon_force 49
#define song_magic_touch 50
#define song_cycles 51
#define song_electroman_adventures 52
#define song_atthespeedoflight2 53
#define song_death_moon 54
#define song_rainbow_tylenol 55
#define song_blacklight 56
#define song_clubstep 57
#define song_haunted_woods 58
#define song_jack_russel 59
#define song_menu_theme_b_sides 60
#define song_megalovania 61
#define song_sonic_blaster 62
#define song_every_madness 63
#define song_back_on_track 64
#define song_blast_processing 65
#define song_atthespeedoflight 66
#define song_youve_been_trolled 67
#define song_driving_by_night 68
#define song_stalemate 69
#define song_fire_aura 70
#define song_infiltration 71
#define song_airborne_robots 72
#define song_base_after_base 73
#define song_endorphins 74
#define song_ninox 75
#define song_atthespeedoflight3 76
#define song_just_right 77
#define song_mayhem 78
#define song_miami_hotline_vol_3 79
#define song_chaozfantasy 80
#define song_glitch_gremlin 81
#define song_infinite_power 82
#define song_xenogenesis 83
#define song_against_the_odds_redux 84
#define song_the_challenge 85
#define song_dry_out_full 86
#define song_holography 87
#define song_the_seven_seas 88
#define song_stereo_madness 89
#define song_xstep 90
#define song_ludicrous_speed 91
#define song_stereo_madness_2 92
#define song_xo 93
#define song_theory_of_everything 94
#define song_ground_to_space 95
#define song_kratos 96
#define song_midnight 97
#define song_ssendam_oerets 98
#define song_dance_of_the_violins 99
#define song_jumper_full 100
#define song_meowstuff 101
#define song_pyrophoric 102
#define song_tiny_tunes 103
#define song_ultimatedestruction 104
#define song_dry_out 105
#define song_jumper 106
#define song_chaoz_impact 107
#define song_metamorphosis 108
#define song_problematic 109
#define song_repmuj 110
#define song_cant_let_go 111
#define song_flow 112
#define song_lost 113
#define song_scheming_weasel 114
#define song_round_1_gdw_cut 115
#define song_space_pirates_gdw_cut 116
#define song_machina_gdw_cut 117
#define song_years_gdw_cut 118
#define song_menu_theme 119
#define song_beast_mode_gdw_cut 120
#define song_max 121