#define song_menu_theme_b_sides 0
#define song_okiba_crackdown 1
#define song_fingerbang 2
#define song_payload_gdw_cut 3
#define song_nine_circles 4
#define song_thermodynamix_full 5
#define song_years_gdw_cut 6
#define song_driving_by_night 7
#define song_every_end_pt2 8
#define song_freedom_dive 9
#define song_scheming_weasel 10
#define song_infernoplex_full 11
#define song_kratos 12
#define song_accelerate 13
#define song_dash_full 14
#define song_meltdown 15
#define song_subtle_oddities 16
#define song_cycles 17
#define song_atthespeedoflightfull 18
#define song_glitch_gremlin 19
#define song_the_angel 20
#define song_endorphins 21
#define song_whats_a_future_funk 22
#define song_clutterfunk 23
#define song_pursuit 24
#define song_time_machine 25
#define song_every_end_pt1 26
#define song_deadlocked 27
#define song_beep_beep 28
#define song_practice 29
#define song_hsad 30
#define song_dash 31
#define song_just_right_full 32
#define song_check_out 33
#define song_isolation 34
#define song_polargeist 35
#define song_clutterfunk_2 36
#define song_fingerdash 37
#define song_idols 38
#define song_chaoz_airflow 39
#define song_stalemate_full 40
#define song_emeht_unem 41
#define song_toe_2 42
#define song_factory_time 43
#define song_menu_theme 44
#define song_geometrical_dominator 45
#define song_endgame 46
#define song_hexagon_force 47
#define song_electrodynamix 48
#define song_eighto_full 49
#define song_magic_touch 50
#define song_electroman_adventures 51
#define song_chaozfantasy 52
#define song_death_moon 53
#define song_jack_russel 54
#define song_miami_hotline_vol_3 55
#define song_rainbow_tylenol 56
#define song_haunted_woods 57
#define song_press_start 58
#define song_sonic_blaster 59
#define song_clubstep 60
#define song_every_madness 61
#define song_megalovania 62
#define song_back_on_track 63
#define song_blast_processing 64
#define song_fire_aura 65
#define song_glint 66
#define song_base_after_base 67
#define song_infiltration 68
#define song_power_trip 69
#define song_tiny_tunes 70
#define song_airborne_robots 71
#define song_mayhem 72
#define song_pyrophoric 73
#define song_xo 74
#define song_blacklight 75
#define song_infinite_power 76
#define song_kesobomb 77
#define song_xenogenesis 78
#define song_against_the_odds_redux 79
#define song_extraordinary_excitement 80
#define song_holography 81
#define song_the_seven_seas 82
#define song_machina_gdw_cut 83
#define song_stereo_madness 84
#define song_metamorphosis 85
#define song_stereo_madness_2 86
#define song_windfall 87
#define song_ssendam_oerets 88
#define song_xstep 89
#define song_theory_of_everything 90
#define song_candyland 91
#define song_ground_to_space 92
#define song_midnight 93
#define song_chaoz_impact 94
#define song_dance_of_the_violins 95
#define song_lost 96
#define song_meowstuff 97
#define song_ninox 98
#define song_ultimatedestruction 99
#define song_dry_out 100
#define song_jumper 101
#define song_flow 102
#define song_ludicrous_speed 103
#define song_problematic 104
#define song_repmuj 105
#define song_cant_let_go 106
#define song_the_challenge 107
#define song_golden_haze 108
#define song_youve_been_trolled 109
#define song_round_1_gdw_cut 110
#define song_space_pirates_gdw_cut 111
#define song_beast_mode_gdw_cut 112
#define song_max 113