#define sfx_death 0
#define sfx_click 1
#define sfx_level_complete 2
#define sfx_coin 3
#define sfx_chest_open 4
#define sfx_orbs 5
#define sfx_diamonds 6
#define sfx_exit_level 7
#define sfx_start_level 8
#define sfx_invalid 9
#define sfx_achievement_get 10
#define sfx_max 11