#define song_nine_circles 0
#define song_future_funk_pt1 1
#define song_hungryman_adventures 2
#define song_cosmic_dolphin 3
#define song_sunslammer 4
#define song_somewhere_in_a_forest 5
#define song_practice 6
#define song_dastardly 7
#define song_unity 8
#define song_astronomical_expedition 9
#define song_future_funk_pt2 10
#define song_carefree_victory_remix 11
#define song_clutterfunk_2 12
#define song_emeht_unem 13
#define song_clownparty_remix 14
#define song_endgame 15
#define song_solar_wind 16
#define song_aether_new 17
#define song_mario_kart_7__rainbow_road_remix 18
#define song_stereo_madness 19
#define song_cycles 20
#define song_c_madness 21
#define song_deep_swim 22
#define song_ground_to_retray 23
#define song_midnight 24
#define song_stalemate_greif_cut 25
#define song_load 26
#define song_speed_racer 27
#define song_scheming_weasel 28
#define song_youve_been_trolled 29
#define song_max 30