#define song_menu_theme_22 0
#define song_subtle_oddities 1
#define song_kesobomb 2
#define song_atthespeedoflight 3
#define song_atthespeedoflightfull 4
#define song_practice 5
#define song_magic_touch 6
#define song_atthespeedoflight2 7
#define song_eighto 8
#define song_check_out 9
#define song_death_moon 10
#define song_atthespeedoflight3 11
#define song_hell 12
#define song_holography 13
#define song_scheming_weasel 14
#define song_ninox 15
#define song_speed_racer 16
#define song_lost 17
#define song_pyrophoric 18
#define song_max 19