#define song_nine_circles 0
#define song_scheming_weasel 1
#define song_every_end_pt2 2
#define song_subtle_oddities 3
#define song_eighto 4
#define song_atthespeedoflightfull 5
#define song_miami_hotline_vol_3 6
#define song_invisible_light 7
#define song_eon 8
#define song_atthespeedoflight2 9
#define song_every_end_pt1 10
#define song_thermodynamix 11
#define song_emeht_unem 12
#define song_practice 13
#define song_every_madness 14
#define song_windfall 15
#define song_magic_touch 16
#define song_clubstep 17
#define song_atthespeedoflight 18
#define song_lost 19
#define song_sonic_blaster 20
#define song_atthespeedoflight3 21
#define song_stalemate 22
#define song_hell 23
#define song_holography 24
#define song_pyrophoric 25
#define song_kratos 26
#define song_fairydust 27
#define song_max 28