.include "metatiles_macro.inc"

Metatile "EMPTY", $00, $00, $00, $00, PAL_0, COL_NONE

Metatile "BG1",   $1a, $1b, $2a, $2b, PAL_1, COL_ALL
Metatile "BG2",   $1a, $1b, $1a, $1b, PAL_1, COL_ALL
Metatile "HALF_SLAB_BOTTOM",   $00, $00, $24, $25, PAL_0, COL_BOTTOM

Metatile "BG4",   $ff, $ff, $ff, $ff, PAL_1, COL_ALL
Metatile "BG5",   $1b, $1b, $2b, $2b, PAL_1, COL_ALL
Metatile "BG6",   $1b, $1b, $1b, $1b, PAL_1, COL_ALL
Metatile "BG7",   $20, $21, $30, $31, PAL_0, COL_NONE
Metatile "MED_SAW_TOP_LEFT",   $00, $e1, $e4, $e5, PAL_0, COL_DEATH_BOTTOM
Metatile "MED_SAW_TOP_RIGHT",   $e2, $e3, $e6, $e7, PAL_0, COL_DEATH_BOTTOM
Metatile "MED_SAW_BOTTOM_LEFT",  $e8, $e9, $00, $ed, PAL_0, COL_DEATH_TOP
Metatile "MED_SAW_BOTTOM_RIGHT",  $ea, $eb, $ee, $ef, PAL_0, COL_DEATH_TOP
Metatile "BG12",  $ff, $ff, $ff, $ff, PAL_1, COL_ALL
Metatile "BG13",  $ff, $ff, $ff, $ff, PAL_1, COL_ALL
Metatile "BG14",  $ff, $ff, $ff, $ff, PAL_1, COL_ALL
Metatile "BG15",  $ff, $ff, $ff, $ff, PAL_1, COL_ALL

Metatile "BLOCK",       $20, $21, $30, $31, PAL_0, COL_ALL
Metatile "SPIKE_UP",    $ac, $ad, $32, $33, PAL_0, COL_DEATH
Metatile "SPIKE_HALF",  $00, $00, $8f, $9f, PAL_0, COL_DEATH_BOTTOM

Metatile "TOP_WAVY_BOTTOM_SPIKE",    $7, $7, $36, $37, PAL_0, COL_DEATH
Metatile "TOP_SPIKE_BOTTOM_WAVY",    $2e, $2f,  $6, $6, PAL_0, COL_DEATH
Metatile "SLAB_SPIKE",      $24, $25, $34, $35, PAL_0, COL_ALL

Metatile "HALF_PAD_SPIKE",$24, $25, $36, $37, PAL_0, COL_ALL
Metatile "CEILING_SPIKE", $2e, $2f, $00, $00, PAL_0, COL_DEATH_TOP
Metatile "GROUND_SPIKE",  $00, $00, $36, $37, PAL_0, COL_DEATH_BOTTOM

Metatile "HALF_SLAB",     $24, $25, $00, $00, PAL_0, COL_TOP

Metatile "RIGHT_SPIKE",     $0c, $ae, $1c, $be, PAL_0, COL_DEATH
Metatile "DOWN_SPIKE",      $2c, $2d, $bc, $bd, PAL_0, COL_DEATH
Metatile "LEFT_SPIKE",      $af, $0f, $bf, $1f, PAL_0, COL_DEATH
Metatile "HALF_RIGHT_SPIKE",$28, $00, $38, $00, PAL_0, COL_DEATH
Metatile "HALF_DOWN_SPIKE", $26, $27, $00, $00, PAL_0, COL_DEATH_TOP
Metatile "HALF_LEFT_SPIKE", $00, $29, $00, $39, PAL_0, COL_DEATH


Metatile "CHECKERBOARD",    $40, $41, $50, $51, PAL_0, COL_ALL
Metatile "CHECKERBOARD_1",  $44, $45, $56, $57, PAL_0, COL_ALL
Metatile "CHECKERBOARD_2",  $46, $43, $56, $53, PAL_0, COL_ALL
Metatile "CHECKERBOARD_3",  $46, $47, $54, $55, PAL_0, COL_ALL
Metatile "CHECKERBOARD_4",  $42, $47, $52, $57, PAL_0, COL_ALL
Metatile "CHECKERBOARD_5",  $40, $45, $52, $57, PAL_0, COL_ALL
Metatile "CHECKERBOARD_6",  $44, $41, $56, $53, PAL_0, COL_ALL
Metatile "CHECKERBOARD_7",  $46, $43, $54, $51, PAL_0, COL_ALL
Metatile "CHECKERBOARD_8",  $42, $47, $50, $55, PAL_0, COL_ALL
Metatile "CHECKERBOARD_9",  $48, $47, $56, $57, PAL_0, COL_ALL
Metatile "CHECKERBOARD_10",  $46, $49, $56, $57, PAL_0, COL_ALL
Metatile "CHECKERBOARD_11",  $46, $47, $56, $59, PAL_0, COL_ALL
Metatile "CHECKERBOARD_12",  $46, $47, $58, $57, PAL_0, COL_ALL
Metatile "CHECKERBOARD_13",  $42, $43, $52, $53, PAL_0, COL_ALL
Metatile "CHECKERBOARD_14",  $44, $45, $54, $55, PAL_0, COL_ALL
Metatile "CHECKERBOARD_15",  $46, $47, $56, $57, PAL_0, COL_NONE
Metatile "CHECKERBOARD_16",  $40, $41, $52, $53, PAL_0, COL_ALL
Metatile "CHECKERBOARD_17",  $44, $41, $54, $51, PAL_0, COL_ALL
Metatile "CHECKERBOARD_18",  $42, $43, $50, $51, PAL_0, COL_ALL
Metatile "CHECKERBOARD_19",  $40, $45, $50, $55, PAL_0, COL_ALL

Metatile "ORB_OUTLINE",     $60, $61, $70, $71, PAL_0, COL_NONE
Metatile "PAD_UP_OUTLINE",  $00, $00, $62, $63, PAL_0, COL_NONE
Metatile "PAD_DOWN_OUTLINE",$72, $73, $00, $00, PAL_0, COL_NONE

Metatile "POLARGEIST_SPECIAL",  $40, $41, $52, $53, PAL_0, COL_TOP
Metatile "DOUBLE_GRAVEL_LEFT", $03, $04, $13, $14, PAL_0, COL_ALL
Metatile "DOUBLE_GRAVEL_MIDDLE", $04, $04, $14, $14, PAL_0, COL_ALL
Metatile "DOUBLE_GRAVEL_RIGHT", $04, $05, $14, $15, PAL_0, COL_ALL
Metatile "DOUBLE_GRAVEL_STANDALONE", $02, $05, $12, $15, PAL_0, COL_ALL
Metatile "GRAVEL_LEFT_TOP_WAVY_BOTTOM", $03, $04, $6, $06, PAL_0, COL_ALL
Metatile "GRAVEL_MIDDLE_TOP_WAVY_BOTTOM", $4, $4, $6, $6, PAL_0, COL_ALL
Metatile "GRAVEL_RIGHT_TOP_WAVY_BOTTOM", $4, $5, $6, $6, PAL_0, COL_ALL
Metatile "GRAVEL_STANDALONE_TOP_WAVY_BOTTOM", $2, $5, $6, $6, PAL_0, COL_ALL

Metatile "XSTEP_FULL_OUTLINE", $C6, $C7, $D6, $D7, PAL_0, COL_ALL
Metatile "XSTEP_TOP_OUTLINE", $CA, $CB, $DC, $DD, PAL_0, COL_ALL
Metatile "XSTEP_RIGHT_OUTLINE", $CC, $C9, $DC, $D9, PAL_0, COL_ALL
Metatile "XSTEP_BOTTOM_OUTLINE", $CC, $CD, $DA, $DB, PAL_0, COL_ALL
Metatile "XSTEP_LEFT_OUTLINE", $C8, $CD, $D8, $DD, PAL_0, COL_ALL
Metatile "XSTEP_TOP_LEFT_OUTLINE", $C6, $CB, $D8, $DD, PAL_0, COL_ALL
Metatile "XSTEP_TOP_RIGHT_OUTLINE", $CA, $C7, $DC, $D9, PAL_0, COL_ALL
Metatile "XSTEP_BOTTOM_RIGHT_OUTLINE", $CC, $C9, $DA, $D7, PAL_0, COL_ALL
Metatile "XSTEP_BOTTOM_LEFT_OUTLINE", $C8, $CD, $D6, $DB, PAL_0, COL_ALL
Metatile "XSTEP_TOP_LEFT_DOT", $CE, $CD, $DC, $DD, PAL_0, COL_ALL
Metatile "XSTEP_TOP_RIGHT_DOT", $CC, $CF, $DC, $DD, PAL_0, COL_ALL
Metatile "XSTEP_BOTTOM_RIGHT_DOT", $CC, $CD, $DC, $DF, PAL_0, COL_ALL
Metatile "XSTEP_BOTTOM_LEFT_DOT", $CC, $CD, $DE, $DD, PAL_0, COL_ALL
Metatile "XSTEP_LEFT_RIGHT_OUTLINE", $C8, $C9, $D8, $D9, PAL_0, COL_ALL
Metatile "XSTEP_TOP_BOTTOM_OUTLINE", $CA, $CB, $DA, $DB, PAL_0, COL_ALL
Metatile "XSTEP_NO_OUTLINE", $CC, $CD, $DC, $DD , PAL_0, COL_NONE

Metatile "XSTEP_LEFT_TOP_RIGHT_OUTLINE", $C6, $C7, $D8, $D9, PAL_0, COL_ALL
Metatile "XSTEP_TOP_RIGHT_BOTTOM_OUTLINE", $CA, $C7, $DA, $D7, PAL_0, COL_ALL
Metatile "XSTEP_LEFT_RIGHT_BOTTOM_OUTLINE", $C8, $C9, $D6, $D7, PAL_0, COL_ALL
Metatile "XSTEP_TOP_LEFT_BOTTOM_OUTLINE", $C6, $CB, $D6, $DB, PAL_0, COL_ALL
Metatile "XSTEP_TOP_GRAVEL_LEFT", $03, $04, $00, $00, PAL_0, COL_TOP
Metatile "XSTEP_TOP_GRAVEL_MIDDLE", $4, $04, $0, $0, PAL_0, COL_TOP
Metatile "XSTEP_TOP_GRAVEL_RIGHT", $4, $5, $0, $0, PAL_0, COL_TOP
Metatile "XSTEP_TOP_GRAVEL_STANDALONE", $2, $5, $0, $0, PAL_0, COL_TOP
Metatile "XSTEP_BOTTOM_GRAVEL_LEFT", $0, $0, $13, $14, PAL_0, COL_BOTTOM
Metatile "XSTEP_BOTTOM_GRAVEL_MIDDLE", $0, $0, $14, $14, PAL_0, COL_BOTTOM
Metatile "XSTEP_BOTTOM_GRAVEL_RIGHT", $0, $0, $14, $15, PAL_0, COL_BOTTOM
Metatile "XSTEP_BOTTOM_GRAVEL_STANDALONE", $0, $0, $12, $15, PAL_0, COL_DEATH
Metatile "XSTEP_BOTTOM_WAVE", $0, $0, $6, $6, PAL_0, COL_DEATH_BOTTOM
Metatile "XSTEP_TOP_WAVE", $7, $7, $0, $0, PAL_0, COL_DEATH_TOP
Metatile "XSTEP_RIGHT_STALLAGMITES", $0, $9, $0, $19, PAL_0, COL_DEATH
Metatile "XSTEP_LEFT_STALLAGMITES", $8, $0, $18, $0, PAL_0, COL_DEATH


Metatile "BLACK_FULL_BORDER", $c2, $c3, $d2, $d3, PAL_0, COL_ALL
Metatile "BLACK_TOP", $d0, $d0, $10, $10, PAL_0, COL_ALL
Metatile "BLACK_RIGHT", $10, $c1, $10, $c1, PAL_0, COL_ALL
Metatile "BLACK_BOTTOM", $10, $10, $d1, $d1, PAL_0, COL_ALL
Metatile "BLACK_LEFT", $c0, $10, $c0, $10, PAL_0, COL_ALL
Metatile "BLACK_TOP_LEFT", $c2, $d0, $c0, $10, PAL_0, COL_ALL
Metatile "BLACK_TOP_RIGHT", $d0, $c3, $10, $c1, PAL_0, COL_ALL
Metatile "BLACK_BOTTOM_RIGHT", $10, $c1, $d1, $d3, PAL_0, COL_ALL
Metatile "BLACK_BOTTOM_LEFT", $c0, $10, $d2, $d1, PAL_0, COL_ALL
Metatile "BLACK_TOP_LEFT_DOT", $c4, $10, $10, $10, PAL_0, COL_ALL
Metatile "BLACK_TOP_RIGHT_DOT", $10, $c5, $10, $10, PAL_0, COL_ALL
Metatile "BLACK_BOTTOM_RIGHT_DOT", $10, $10, $10, $d5, PAL_0, COL_ALL
Metatile "BLACK_BOTTOM_LEFT_DOT", $10, $10, $d4, $10, PAL_0, COL_ALL
Metatile "BLACK_LEFT_RIGHT", $c0, $c1, $c0, $c1, PAL_0, COL_ALL
Metatile "BLACK_TOP_BOTTOM", $d0, $d0, $d1, $d1, PAL_0, COL_ALL
Metatile "BLACK_NONE", $10, $10, $10, $10, PAL_0, COL_ALL

Metatile "BLACK_TOP_LEFT_RIGHT", $c2, $c3, $c0, $c1, PAL_0, COL_ALL
Metatile "BLACK_TOP_RIGHT_BOTTOM", $d0, $c3, $d1, $d3, PAL_0, COL_ALL
Metatile "BLACK_LEFT_RIGHT_BOTTOM", $c0, $c1, $d2, $d3, PAL_0, COL_ALL
Metatile "BLACK_TOP_LEFT_BOTTOM", $c2, $d0, $d2, $d1, PAL_0, COL_ALL
Metatile "BIG_SAW_TOP_LEFT", $00, $4b, $5a, $5b, PAL_0, COL_DEATH_BOTTOM
Metatile "BIG_SAW_TOP_MIDDLE", $4c, $4d, $5c, $5d, PAL_0, COL_DEATH
Metatile "BIG_SAW_TOP_RIGHT", $4e, $00, $5e, $5f, PAL_0, COL_DEATH_BOTTOM
Metatile "BIG_SAW_MIDDLE_LEFT", $6a, $6b, $7a, $7b, PAL_0, COL_DEATH
Metatile "BIG_SAW_MIDDLE_MIDDLE", $6c, $6d, $7c, $7d, PAL_0, COL_DEATH
Metatile "BIG_SAW_MIDDLE_RIGHT", $6e, $6f, $7e, $7f, PAL_0, COL_DEATH
Metatile "BIG_SAW_BOTTOM_LEFT", $64, $65, $00, $75, PAL_0, COL_DEATH_TOP
Metatile "BIG_SAW_BOTTOM_MIDDLE", $66, $67, $76, $77, PAL_0, COL_DEATH
Metatile "BIG_SAW_BOTTOM_RIGHT", $68, $69, $78, $00, PAL_0, COL_DEATH_TOP
Metatile "SMALL_SAW", $4a, $4f, $74, $79, PAL_0, COL_DEATH
Metatile "GLASS_SQUARE", $3a, $3b, $3e, $3f, PAL_0, COL_ALL
Metatile "SMALL_SAW_BOTTOM_HALF", $00, $00, $4a, $4f, PAL_0, COL_DEATH_BOTTOM
