.include "metatiles_macro.inc"

Metatile "EMPTY", $00, $00, $00, $00, PAL_0, COL_NONE

Metatile "BG1",   $1a, $1b, $2a, $2b, PAL_1, COL_ALL
Metatile "BG2",   $1a, $1b, $1a, $1b, PAL_1, COL_ALL
Metatile "BG3",   $00, $00, $24, $25, PAL_1, COL_ALL

Metatile "BG4",   $ff, $ff, $ff, $ff, PAL_1, COL_ALL
Metatile "BG5",   $1b, $1b, $2b, $2b, PAL_1, COL_ALL
Metatile "BG6",   $1b, $1b, $1b, $1b, PAL_1, COL_ALL
Metatile "BG7",   $20, $21, $30, $31, PAL_0, COL_NONE
Metatile "BG8",   $ff, $ff, $ff, $ff, PAL_1, COL_ALL
Metatile "BG9",   $ff, $ff, $ff, $ff, PAL_1, COL_ALL
Metatile "BG10",  $ff, $ff, $ff, $ff, PAL_1, COL_ALL
Metatile "BG11",  $ff, $ff, $ff, $ff, PAL_1, COL_ALL
Metatile "BG12",  $ff, $ff, $ff, $ff, PAL_1, COL_ALL
Metatile "BG13",  $ff, $ff, $ff, $ff, PAL_1, COL_ALL
Metatile "BG14",  $ff, $ff, $ff, $ff, PAL_1, COL_ALL
Metatile "BG15",  $ff, $ff, $ff, $ff, PAL_1, COL_ALL

Metatile "BLOCK",       $20, $21, $30, $31, PAL_0, COL_ALL
Metatile "SPIKE_UP",    $ac, $ad, $32, $33, PAL_0, COL_DEATH
Metatile "SPIKE_HALF",  $00, $00, $8f, $9f, PAL_0, COL_DEATH

Metatile "YELLOW_PAD",    $ff, $ff, $ff, $ff, PAL_1, COL_NONE
Metatile "YELLOW_ORB",    $ff, $ff, $ff, $ff, PAL_1, COL_NONE
Metatile "PINK_PAD",      $ff, $ff, $ff, $ff, PAL_1, COL_NONE

Metatile "HALF_PAD_SPIKE",$24, $25, $36, $37, PAL_0, COL_ALL
Metatile "CEILING_SPIKE", $2e, $2f, $00, $00, PAL_0, COL_DEATH
Metatile "GROUND_SPIKE",  $00, $00, $36, $37, PAL_0, COL_DEATH

Metatile "HALF_SLAB",     $24, $25, $00, $00, PAL_0, COL_ALL

Metatile "RIGHT_SPIKE",     $0c, $ae, $1c, $be, PAL_0, COL_DEATH
Metatile "DOWN_SPIKE",      $2c, $2d, $bc, $bd, PAL_0, COL_DEATH
Metatile "LEFT_SPIKE",      $af, $0f, $bf, $1f, PAL_0, COL_DEATH
Metatile "HALF_RIGHT_SPIKE",$28, $00, $29, $00, PAL_0, COL_DEATH
Metatile "HALF_DOWN_SPIKE", $26, $27, $00, $00, PAL_0, COL_DEATH
Metatile "HALF_LEFT_SPIKE", $00, $29, $00, $39, PAL_0, COL_DEATH


Metatile "CHECKERBOARD",    $40, $41, $50, $51, PAL_0, COL_ALL
Metatile "CHECKERBOARD_1",  $44, $45, $56, $57, PAL_0, COL_ALL
Metatile "CHECKERBOARD_2",  $46, $43, $56, $53, PAL_0, COL_ALL
Metatile "CHECKERBOARD_3",  $46, $47, $54, $55, PAL_0, COL_ALL
Metatile "CHECKERBOARD_4",  $42, $47, $52, $57, PAL_0, COL_ALL
Metatile "CHECKERBOARD_5",  $40, $45, $52, $57, PAL_0, COL_ALL
Metatile "CHECKERBOARD_6",  $44, $41, $56, $53, PAL_0, COL_ALL
Metatile "CHECKERBOARD_7",  $46, $43, $54, $51, PAL_0, COL_ALL
Metatile "CHECKERBOARD_8",  $42, $47, $50, $55, PAL_0, COL_ALL
Metatile "CHECKERBOARD_9",  $48, $47, $56, $57, PAL_0, COL_ALL
Metatile "CHECKERBOARD_10",  $46, $49, $56, $57, PAL_0, COL_ALL
Metatile "CHECKERBOARD_11",  $46, $47, $56, $59, PAL_0, COL_ALL
Metatile "CHECKERBOARD_12",  $46, $47, $58, $57, PAL_0, COL_ALL
Metatile "CHECKERBOARD_13",  $42, $43, $52, $53, PAL_0, COL_ALL
Metatile "CHECKERBOARD_14",  $44, $45, $54, $55, PAL_0, COL_ALL
Metatile "CHECKERBOARD_15",  $46, $47, $56, $57, PAL_0, COL_NONE
Metatile "CHECKERBOARD_16",  $40, $41, $52, $53, PAL_0, COL_ALL
Metatile "CHECKERBOARD_17",  $44, $41, $54, $51, PAL_0, COL_ALL
Metatile "CHECKERBOARD_18",  $42, $43, $50, $51, PAL_0, COL_ALL
Metatile "CHECKERBOARD_19",  $40, $45, $50, $55, PAL_0, COL_ALL

Metatile "ORB_OUTLINE",     $60, $61, $70, $71, PAL_0, COL_NONE
Metatile "PAD_UP_OUTLINE",  $00, $00, $62, $63, PAL_0, COL_NONE
Metatile "PAD_DOWN_OUTLINE",$72, $73, $00, $00, PAL_0, COL_NONE