#define stereo_madness  0
#define back_on_track  1
#define polargeist  2
#define dryout  3
#define base_after_base  4
#define cant_let_go  5
#define jumper  6
#define time_machine  7
#define cycles  8
#define xstep  9
#define clutterfunk  0x0A
#define theory_of_everything  0x0B
#define electroman_adventures  0x0C
#define clubstep  0x0D
#define electrodynamix  0x0E
#define hexagon_force  0x0F
#define toe_2  0x10
#define retray  0x11
#define sonar  0x12
#define the_challenge  0x13
#define dreamer  0x14
#define kappaclysm  0x15
#define revolution  0x16
#define lightningroad  0x17
#define nightmare  0x18
#define demonpark  0x19
#define death_moon  0x20
#define decode  0x21
#define problematic  0x22
#define firetemple 0x23
#define eon  0x24
#define pgclubstep  0x25
#define luckydraw  0x26
#define test4  0X27