#define stereo_madness  0
#define back_on_track  1
#define polargeist  2
#define dryout  3
#define base_after_base  4
#define cant_let_go  5
#define jumper  6
#define time_machine  7
#define cycles  8
#define xstep  9
#define clutterfunk  0x0A
#define theory_of_everything  0x0B
#define electroman_adventures  0x0C
#define clubstep  0x0D
#define electrodynamix  0x0E
#define hexagon_force  0x0F
#define blast_processing  0x10
#define toe_2  0x11
#define retray  0x12
#define sonar  0x13
#define the_challenge  0x14
#define level_easy  0x15
#define dreamer  0x16
#define kappaclysm  0x17
#define revolution  0x18
#define aprettyeasylevel  0x19
#define lightningroad  0x1A
#define nightmare  0x1B
#define demonpark  0x1C
#define death_moon  0x1D
#define decode  0x1E
#define dear_nostalgists  0x1F
#define super_cycles  0x20
#define problematic  0x21
#define firetemple 0x22
#define eon  0x23
#define pgclubstep  0x24
#define stalemate  0x25
#define luckydraw  0x26
#define test4  0X27