#ifdef FLAG_ENABLE_TEST_LEVELS
	#define LEVEL_COUNT 256
#else
	#define LEVEL_COUNT (OFFICIAL_LEVEL_COUNT)
#endif

#ifdef FLAG_ENABLE_TEST_LEVELS
	#define LEVEL_COUNT2 256
#else
	#define LEVEL_COUNT2 (OFFICIAL_LEVEL_COUNT+COMMUNITY_LEVEL_COUNT)
#endif

#define MAX_ICONS 27 //total icons
#define MAX_FIREBALLS 20
#define MAX_PRACTICE_POINTS 8
#define max_loaded_sprites 16
#define MAX_LEVEL_COMPLETE 0x60

#define NINJABANK 94
#define MOUSEBANK 96
#define LETTERBANK 111
#define MENUBANK 98
#define MENUICONBANK 102
#define LEVELCOMPLETEBANK 106
#define PRACTICECOMPLETEBANK 110

#define SPIKESA 0
#define SPIKESB 2
#define SPIKESC 4
#define BLOCKSA 6
#define BLOCKSB 8
#define BLOCKSC 10
#define BLOCKSD 12
#define SAWBLADESA 14
#define SLOPESA 16

#define DECO1 28
#define DECOCLOUD 32
#define EXTRASPRITES1 36

#define FAMISTUDIO_STATE_SIZE 172
#define FAMISTUDIO_OUTPUT_BUF_SIZE 11

#if !__THE_ALBUM
#define MOVEMENT_BANK "XCD_BANK_01"
#define BACKGROUND_RENDER_BANK "XCD_BANK_02"
#define DIALOG_BOX_BANK "XCD_BANK_02"
#define SCROLL_BANK	"XCD_BANK_04"
#define SPRITE_RENDER_BANK "XCD_BANK_04"
#define PLAYER_RENDER_BANK "XCD_BANK_05"
#define RESETLEVEL_BANK "XCD_BANK_05"
#endif
#define GROUND_BANK "XCD_BANK_06"
#if !__HUGE_ROM
#define LVLDONE_BANK "XCD_BANK_06"
#else
#define LVLDONE_BANK "XCD_BANK_08"
#endif	