#define song_clutterfunk 0
#define song_stalemate 1
#define song_practice 2
#define song_haunted_woods 3
#define song_dash 4
#define song_eon_vs_system 5
#define song_polargeist 6
#define song_time_machine 7
#define song_fingerdash 8
#define song_infernoplex 9
#define song_endgame 10
#define song_electrodynamix 11
#define song_geometrical_dominator 12
#define song_hexagon_force_vs_system 13
#define song_toe_2 14
#define song_atthespeedoflight2 15
#define song_death_moon 16
#define song_electroman_adventures 17
#define song_stereo_madness_2 18
#define song_clubstep 19
#define song_blast_processing 20
#define song_atthespeedoflight 21
#define song_back_on_track 22
#define song_base_after_base 23
#define song_the_challenge 24
#define song_just_right 25
#define song_stereo_madness 26
#define song_cycles 27
#define song_midnight 28
#define song_against_the_odds_redux 29
#define song_dry_out 30
#define song_jumper 31
#define song_xstep 32
#define song_theory_of_everything 33
#define song_deadlocked 34
#define song_retray 35
#define song_cant_let_go 36
#define song_scheming_weasel 37
#define song_menu_theme 38
#define song_problematic 39
#define song_driving_by_night 40
#define song_max 41