#define song_okiba_crackdown 0
#define song_fingerbang 1
#define song_nine_circles 2
#define song_thermodynamix_full 3
#define song_every_end_pt2 4
#define song_freedom_dive 5
#define song_infernoplex_full 6
#define song_menu_theme 7
#define song_subtle_oddities 8
#define song_atthespeedoflightfull 9
#define song_machina_gdw_cut 10
#define song_the_angel 11
#define song_beast_mode_gdw_cut 12
#define song_pyrophoric 13
#define song_whats_a_future_funk 14
#define song_accelerate 15
#define song_clutterfunk 16
#define song_chaozfantasy 17
#define song_every_end_pt1 18
#define song_deadlocked 19
#define song_mayhem 20
#define song_practice 21
#define song_just_right 22
#define song_base_after_base 23
#define song_just_right_full 24
#define song_stalemate 25
#define song_thermodynamix 26
#define song_isolation 27
#define song_sonic_blaster 28
#define song_2nes 29
#define song_polargeist 30
#define song_fingerdash 31
#define song_atthespeedoflight 32
#define song_clubstep 33
#define song_chaoz_airflow 34
#define song_toe_2 35
#define song_megalovania 36
#define song_back_on_track 37
#define song_geometrical_dominator 38
#define song_electrodynamix 39
#define song_haunted_woods 40
#define song_eighto_full 41
#define song_jack_russel 42
#define song_electroman_adventures 43
#define song_hexagon_force 44
#define song_magic_touch 45
#define song_rainbow_tylenol 46
#define song_death_moon 47
#define song_factory_time 48
#define song_time_machine 49
#define song_cryogenic 50
#define song_dash 51
#define song_check_out 52
#define song_clutterfunk_2 53
#define song_hsad 54
#define song_beep_beep 55
#define song_idols 56
#define song_menu_theme_b_sides 57
#define song_infernoplex 58
#define song_stalemate_full 59
#define song_atthespeedoflight2 60
#define song_bit_of_a_vibe 61
#define song_emeht_unem 62
#define song_endgame 63
#define song_free_mind 64
#define song_payload_gdw_cut 65
#define song_driving_by_night 66
#define song_fantasy 67
#define song_press_start 68
#define song_every_madness 69
#define song_pursuit 70
#define song_ultimatedestruction 71
#define song_blast_processing 72
#define song_fire_aura 73
#define song_infiltration 74
#define song_airborne_robots 75
#define song_endorphins 76
#define song_power_trip 77
#define song_miami_hotline_vol_3 78
#define song_pyrophoric_apparently_too_many_creative_liberties_mix 79
#define song_xenogenesis 80
#define song_eighto 81
#define song_glitch_gremlin 82
#define song_infinite_power 83
#define song_years_gdw_cut 84
#define song_cycles 85
#define song_blacklight 86
#define song_glint 87
#define song_kesobomb 88
#define song_against_the_odds_redux 89
#define song_jumper 90
#define song_extraordinary_excitement 91
#define song_meltdown 92
#define song_candyland 93
#define song_holography 94
#define song_the_seven_seas 95
#define song_windfall 96
#define song_atthespeedoflight3 97
#define song_stereo_madness_2 98
#define song_xo 99
#define song_stalemate_greif_cut 100
#define song_stereo_madness 101
#define song_xstep 102
#define song_kratos 103
#define song_ssendam_oerets 104
#define song_theory_of_everything 105
#define song_the_challenge 106
#define song_dance_of_the_violins 107
#define song_ground_to_space 108
#define song_midnight 109
#define song_chaoz_impact 110
#define song_fairydust 111
#define song_meowstuff 112
#define song_ninox 113
#define song_tiny_tunes 114
#define song_dry_out 115
#define song_ludicrous_speed 116
#define song_metamorphosis 117
#define song_problematic 118
#define song_repmuj 119
#define song_cant_let_go 120
#define song_flow 121
#define song_golden_haze 122
#define song_lost 123
#define song_scheming_weasel 124
#define song_youve_been_trolled 125
#define song_round_1_gdw_cut 126
#define song_space_pirates_gdw_cut 127
#define song_max 128