#define song_okiba_crackdown 0
#define song_nine_circles 1
#define song_thermodynamix_full 2
#define song_every_end_pt2 3
#define song_the_challenge 4
#define song_atthespeedoflightfull 5
#define song_the_angel 6
#define song_youve_been_trolled 7
#define song_clutterfunk 8
#define song_miami_hotline_vol_3 9
#define song_base_after_base 10
#define song_future_funk_pt1 11
#define song_apoplexy 12
#define song_clubstep 13
#define song_every_end_pt1 14
#define song_hungryman_adventures 15
#define song_practice 16
#define song_careless 17
#define song_haunted_woods 18
#define song_thermodynamix 19
#define song_pursuit 20
#define song_thermodynamix_acheron 21
#define song_fantasy 22
#define song_isolation 23
#define song_polargeist 24
#define song_theory_of_everything 25
#define song_toe_2 26
#define song_tetris_remix_final 27
#define song_fingerdash 28
#define song_rainbow_tylenol 29
#define song_geometrical_dominator 30
#define song_shiawase_vip 31
#define song_electrodynamix 32
#define song_death_moon 33
#define song_dash 34
#define song_future_funk_pt2 35
#define song_hexagon_force 36
#define song_infernoplex 37
#define song_bit_of_a_vibe 38
#define song_magic_touch 39
#define song_astronomical_expedition 40
#define song_factory_time 41
#define song_clutterfunk_2 42
#define song_cryogenic 43
#define song_check_out 44
#define song_try_this 45
#define song_time_machine 46
#define song_atthespeedoflight2 47
#define song_lost 48
#define song_driving_by_night 49
#define song_endgame 50
#define song_free_mind 51
#define song_electroman_adventures 52
#define song_pyrophoric 53
#define song_slash_inferno 54
#define song_blast_processing 55
#define song_dance_of_the_violins 56
#define song_megalovania 57
#define song_deadlocked 58
#define song_every_madness 59
#define song_windfall 60
#define song_final_battle 61
#define song_glitch_gremlin 62
#define song_supernova 63
#define song_accelerate 64
#define song_raining_tacos 65
#define song_sonic_blaster 66
#define song_back_on_track 67
#define song_snow 68
#define song_tiny_tunes 69
#define song_fire_aura 70
#define song_somewhere_in_a_forest 71
#define song_stalemate 72
#define song_menu_theme_b_sides 73
#define song_endorphins 74
#define song_infiltration 75
#define song_power_trip 76
#define song_menu_theme 77
#define song_birdbrain 78
#define song_just_right 79
#define song_mayhem_re_nes 80
#define song_cant_let_go 81
#define song_infinite_power 82
#define song_pyrophoric_apparently_too_many_creative_liberties_mix 83
#define song_xenogenesis 84
#define song_blacklight 85
#define song_chaozfantasy 86
#define song_chaoz_impact 87
#define song_eighto 88
#define song_cycles 89
#define song_c_madness 90
#define song_kesobomb 91
#define song_subtle_oddities 92
#define song_against_the_odds_redux 93
#define song_ground_to_space 94
#define song_jawbreaker 95
#define song_meltdown 96
#define song_extraordinary_excitement 97
#define song_golden_haze 98
#define song_holography 99
#define song_stereo_madness_2 100
#define song_emeht_unem 101
#define song_stereo_madness 102
#define song_atthespeedoflight3 103
#define song_stalemate_greif_cut 104
#define song_xo 105
#define song_xstep 106
#define song_desert_city 107
#define song_kratos 108
#define song_pyrophoric_legacy_remix 109
#define song_the_explorer 110
#define song_fairydust 111
#define song_midnight 112
#define song_off_to_mars 113
#define song_slow_down 114
#define song_ultimatedestruction 115
#define song_dry_out 116
#define song_jumper 117
#define song_meowstuff 118
#define song_ninox 119
#define song_select_payment_type 120
#define song_menu_theme_human_capturing_mix 121
#define song_menu_theme_e_side 122
#define song_scheming_weasel 123
#define song_flow 124
#define song_moon_fries 125
#define song_problematic 126
#define song_max 127