#define song_okiba_crackdown 0
#define song_payload_gdw_cut 1
#define song_menu_theme 2
#define song_fingerbang 3
#define song_nine_circles 4
#define song_emeht_unem 5
#define song_driving_by_night 6
#define song_thermodynamix_full 7
#define song_every_end_pt2 8
#define song_glint 9
#define song_freedom_dive 10
#define song_repmuj 11
#define song_accelerate 12
#define song_infernoplex_full 13
#define song_dash_full 14
#define song_windfall 15
#define song_cycles 16
#define song_subtle_oddities 17
#define song_atthespeedoflightfull 18
#define song_chaozfantasy 19
#define song_pyrophoric_apparently_too_many_creative_liberties_mix 20
#define song_the_angel 21
#define song_miami_hotline_vol_3 22
#define song_time_machine_full 23
#define song_stalemate 24
#define song_whats_a_future_funk 25
#define song_clutterfunk 26
#define song_jack_russel 27
#define song_every_end_pt1 28
#define song_infernoplex 29
#define song_deadlocked 30
#define song_hsad 31
#define song_practice 32
#define song_idols 33
#define song_dash 34
#define song_just_right_full 35
#define song_clutterfunk_2 36
#define song_thermodynamix 37
#define song_clubstep_full 38
#define song_isolation 39
#define song_polargeist 40
#define song_factory_time 41
#define song_fingerdash 42
#define song_cryogenic 43
#define song_chaoz_airflow 44
#define song_check_out 45
#define song_hexagon_force 46
#define song_toe_2 47
#define song_geometrical_dominator 48
#define song_magic_touch 49
#define song_electrodynamix 50
#define song_eighto_full 51
#define song_back_on_track_full 52
#define song_beep_beep 53
#define song_space_pirates_gdw_cut 54
#define song_stereo_madness 55
#define song_bit_of_a_vibe 56
#define song_stalemate_full 57
#define song_time_machine 58
#define song_atthespeedoflight2 59
#define song_extraordinary_excitement 60
#define song_against_the_odds_redux 61
#define song_endgame 62
#define song_free_mind 63
#define song_electroman_adventures 64
#define song_death_moon 65
#define song_mayhem 66
#define song_base_after_base 67
#define song_press_start 68
#define song_rainbow_tylenol 69
#define song_2nes 70
#define song_fantasy 71
#define song_pursuit 72
#define song_every_madness 73
#define song_haunted_woods 74
#define song_megalovania 75
#define song_clubstep 76
#define song_atthespeedoflight 77
#define song_sonic_blaster 78
#define song_machina_gdw_cut 79
#define song_back_on_track 80
#define song_blast_processing 81
#define song_fire_aura 82
#define song_pyrophoric 83
#define song_endorphins 84
#define song_infiltration 85
#define song_power_trip 86
#define song_ultimatedestruction 87
#define song_airborne_robots 88
#define song_just_right 89
#define song_xenogenesis 90
#define song_xo 91
#define song_blacklight 92
#define song_eighto 93
#define song_glitch_gremlin 94
#define song_infinite_power 95
#define song_the_challenge 96
#define song_dry_out_full 97
#define song_kesobomb 98
#define song_meltdown 99
#define song_the_seven_seas 100
#define song_jumper 101
#define song_atthespeedoflight3 102
#define song_holography 103
#define song_stereo_madness_2 104
#define song_stalemate_greif_cut 105
#define song_xstep 106
#define song_candyland 107
#define song_kratos 108
#define song_midnight 109
#define song_ssendam_oerets 110
#define song_theory_of_everything 111
#define song_dance_of_the_violins 112
#define song_fairydust 113
#define song_ground_to_space 114
#define song_jumper_full 115
#define song_beast_mode_gdw_cut 116
#define song_dry_out 117
#define song_chaoz_impact 118
#define song_ludicrous_speed 119
#define song_meowstuff 120
#define song_ninox 121
#define song_tiny_tunes 122
#define song_cant_let_go 123
#define song_flow 124
#define song_golden_haze 125
#define song_lost 126
#define song_metamorphosis 127
#define song_problematic 128
#define song_scheming_weasel 129
#define song_menu_theme_b_sides 130
#define song_youve_been_trolled 131
#define song_round_1_gdw_cut 132
#define song_years_gdw_cut 133
#define song_max 134