; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Famidash music:
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1
; FAMISTUDIO_USE_ARPEGGIO = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1
; FAMISTUDIO_USE_DELTA_COUNTER = 1
; FAMISTUDIO_USE_PHASE_RESET = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_famidash_music44:=music_data_famidash_music44

music_data_famidash_music44:
	.byte 4
	.word @instruments
	.word @samples-5
; 00 : Stereo Madness
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 327,273
; 01 : xStep
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word 266,221
; The DPCM aligner used to be here
; 03 : Golden Haze
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word 286,238
; 04 : XO
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.word 167,139

.export music_data_famidash_music44
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env10,@env8,@env39,@env0 ; 00 : hat
	.word @env22,@env26,@env2,@env0 ; 01 : snare
	.word @env25,@env28,@env27,@env0 ; 02 : clap
	.word @env12,@env40,@env27,@env0 ; 03 : kick
	.word @env20,@env23,@env27,@env0 ; 04 : blank
	.word @env1,@env23,@env27,@env0 ; 05 : echo
	.word @env49,@env23,@env27,@env0 ; 06 : triangle pluck 2
	.word @env45,@env23,@env33,@env0 ; 07 : Instrument 4
	.word @env42,@env23,@env27,@env0 ; 08 : tight noise kick layer
	.word @env41,@env8,@env2,@env0 ; 09 : cymbal
	.word @env21,@env23,@env27,@env0 ; 0a : Instrument 2
	.word @env11,@env23,@env27,@env0 ; 0b : clutterfunk sax
	.word @env20,@env23,@env5,@env0 ; 0c : electroman lead
	.word @env36,@env4,@env27,@env0 ; 0d : tight triangle kick
	.word @env34,@env47,@env29,@env0 ; 0e : octave arp
	.word @env36,@env9,@env27,@env0 ; 0f : tight triangle snare
	.word @env17,@env23,@env29,@env0 ; 10 : Duty 2
	.word @env43,@env23,@env30,@env0 ; 11 : shift string
	.word @env17,@env23,@env27,@env0 ; 12 : DMC: drums + bass
	.word @env14,@env23,@env15,@env0 ; 13 : shift string lite
	.word @env48,@env23,@env27,@env0 ; 14 : blank instant decay
	.word @env31,@env23,@env27,@env0 ; 15 : Instrument 1
	.word @env24,@env23,@env27,@env0 ; 16 : infernoplex_piano
	.word @env18,@env23,@env7,@env0 ; 17 : xo_voice
	.word @env3,@env23,@env35,@env0 ; 18 : xstep wub
	.word @env16,@env23,@env6,@env0 ; 19 : endgame lead
	.word @env38,@env23,@env27,@env19 ; 1a : death moon lead 2

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cb,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$13
@env2:
	.byte $c1,$c0,$00,$01
@env3:
	.byte $00,$c3,$c7,$c8,$c8,$ca,$c8,$c0,$00,$07
@env4:
	.byte $da,$d0,$ce,$c4,$00,$03
@env5:
	.byte $c2,$c1,$03,$c0,$02,$c0,$00,$01
@env6:
	.byte $c2,$c2,$c0,$00,$00
@env7:
	.byte $c3,$7f,$00,$00
@env8:
	.byte $bd,$c0,$00,$01
@env9:
	.byte $e3,$e2,$e1,$e0,$00,$03
@env10:
	.byte $00,$c8,$c4,$c2,$c0,$00,$04
@env11:
	.byte $05,$ce,$cf,$00,$02,$cc,$c8,$c5,$c2,$c0,$00,$09
@env12:
	.byte $00,$cd,$c9,$c5,$c2,$c1,$c0,$00,$06
@env13:
	.byte $c0,$c4,$c7,$00,$00
@env14:
	.byte $08,$c5,$c6,$c7,$08,$c6,$00,$05,$c6,$04,$c5,$07,$c4,$05,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$14
@env15:
	.byte $c1,$c0,$c0,$c1,$c0,$00,$00
@env16:
	.byte $00,$cf,$cd,$cb,$c7,$c7,$ca,$00,$06
@env17:
	.byte $00,$cf,$7f,$00,$02
@env18:
	.byte $00,$cf,$ce,$cd,$cc,$cc,$cb,$cb,$ca,$03,$c9,$00,$0a
@env19:
	.byte $00,$c0,$c4,$c1,$bf,$be,$bd,$be,$bf,$00,$08
@env20:
	.byte $04,$cf,$00,$01,$ca,$c6,$c4,$c2,$c0,$00,$08
@env21:
	.byte $00,$c8,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$0d
@env22:
	.byte $00,$cd,$cb,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env23:
	.byte $c0,$7f,$00,$01
@env24:
	.byte $00,$ce,$02,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$c9,$c9,$c8,$c7,$c6,$c5,$c3,$00,$10
@env25:
	.byte $00,$cf,$ca,$cc,$ca,$c9,$c8,$c6,$c5,$c4,$c2,$c1,$c0,$00,$0c
@env26:
	.byte $c6,$cc,$00,$01
@env27:
	.byte $7f,$00,$00
@env28:
	.byte $bc,$c1,$c0,$00,$02
@env29:
	.byte $c2,$7f,$00,$00
@env30:
	.byte $c1,$c2,$c1,$c0,$00,$00
@env31:
	.byte $00,$c3,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$0d
@env32:
	.byte $00,$c0,$bb,$b8,$b7,$b9,$bd,$c3,$c7,$c9,$c8,$c5,$00,$01
@env33:
	.byte $c1,$7f,$00,$00
@env34:
	.byte $00,$c9,$c7,$c5,$00,$03
@env35:
	.byte $c1,$c2,$c3,$00,$02
@env36:
	.byte $00,$cf,$03,$c0,$00,$03
@env37:
	.byte $c0,$c0,$cc,$00,$00
@env38:
	.byte $00,$cf,$ca,$c8,$00,$03
@env39:
	.byte $c0,$c1,$00,$00
@env40:
	.byte $c9,$cf,$00,$01
@env41:
	.byte $18,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c7,$c6,$02,$c5,$c5,$c4,$02,$c3,$03,$c2,$c2,$00,$15,$c2,$c2,$c1,$03,$c0,$00,$1c
@env42:
	.byte $00,$cf,$c0,$c1,$c0,$00,$04
@env43:
	.byte $08,$c4,$c5,$c6,$08,$c5,$00,$05,$c5,$04,$c4,$07,$c3,$05,$c2,$02,$c1,$02,$c0,$00,$12
@env44:
	.byte $c0,$c3,$c7,$00,$00
@env45:
	.byte $0b,$cf,$ca,$ca,$c9,$02,$c8,$02,$c7,$00,$08,$c7,$c5,$c3,$c2,$c1,$c0,$00,$10
@env46:
	.byte $00,$c0,$bf,$02,$c0,$c0,$c1,$c1,$c1,$00,$01
@env47:
	.byte $c0,$c0,$cc,$cc,$00,$00
@env48:
	.byte $00,$cf,$cf,$cb,$c8,$c5,$c3,$c2,$c1,$c0,$00,$09
@env49:
	.byte $00,$cf,$cf,$c0,$00,$03

@samples:
	.byte $2a+.lobyte(FAMISTUDIO_DPCM_PTR),$a8,$0b,$40,$02 ; 00 BSV (Pitch:11)
	.byte $54+.lobyte(FAMISTUDIO_DPCM_PTR),$7f,$0c,$40,$02 ; 01 BSV_1 (Pitch:12)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$a7,$4f,$40,$03 ; 02 Choir Ahh A (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$4f,$40,$09 ; 03 Choir Ahh B (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$4f,$40,$04 ; 04 Choir Ahh C (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$4d,$40,$05 ; 05 Choir Ahh C# (Pitch:13)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4c,$40,$05 ; 06 Choir Ahh D (Pitch:12)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4e,$40,$05 ; 07 Choir Ahh D (Pitch:14)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4f,$40,$05 ; 08 Choir Ahh D (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4f,$40,$06 ; 09 Choir Ahh E (Pitch:15)
	.byte $38+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4f,$40,$06 ; 0a Choir Ahh G (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$09 ; 0b continue (Pitch:15)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$01 ; 0c demon level (Pitch:15)
	.byte $2a+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$03 ; 0d EON_AH (Pitch:15)
	.byte $11+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 0e fdbass A# (Pitch:15)
	.byte $23+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$00 ; 0f fdbass B (Pitch:15)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$07,$40,$00 ; 10 fdbass C (Pitch:7)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$09,$40,$00 ; 11 fdbass C (Pitch:9)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0a,$40,$00 ; 12 fdbass C (Pitch:10)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0c,$40,$00 ; 13 fdbass C (Pitch:12)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 14 fdbass C (Pitch:15)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$05,$40,$00 ; 15 fdbass C# (Pitch:5)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 16 fdbass C# (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$07,$40,$00 ; 17 fdbass D (Pitch:7)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$08,$40,$00 ; 18 fdbass D (Pitch:8)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0a,$40,$00 ; 19 fdbass D (Pitch:10)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0b,$40,$00 ; 1a fdbass D (Pitch:11)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0f,$40,$00 ; 1b fdbass D (Pitch:15)
	.byte $6b+.lobyte(FAMISTUDIO_DPCM_PTR),$2b,$0e,$40,$00 ; 1c fdkick (Pitch:14)
	.byte $5e+.lobyte(FAMISTUDIO_DPCM_PTR),$78,$0f,$40,$01 ; 1d hi (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$38,$0f,$40,$01 ; 1e is a (Pitch:15)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$6d,$0f,$40,$02 ; 1f machine (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e0,$0e,$40,$07 ; 20 MUSIC_PCM_DS-geo (Pitch:14)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$08 ; 21 one (Pitch:15)
	.byte $52+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$40,$04 ; 22 OrchHitA.dmc (Pitch:12)
	.byte $52+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$40,$04 ; 23 OrchHitA.dmc (Pitch:14)
	.byte $52+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$04 ; 24 OrchHitA.dmc (Pitch:15)
	.byte $6a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$40,$03 ; 25 OrchHitF.dmc (Pitch:12)
	.byte $6a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$03 ; 26 OrchHitF.dmc (Pitch:15)
	.byte $64+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$40,$04 ; 27 OrchHitG.dmc (Pitch:12)
	.byte $64+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$40,$04 ; 28 OrchHitG.dmc (Pitch:14)
	.byte $64+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$04 ; 29 OrchHitG.dmc (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$40,$04 ; 2a OrchHitG#.dmc (Pitch:10)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$40,$04 ; 2b OrchHitG#.dmc (Pitch:12)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$40,$04 ; 2c OrchHitG#.dmc (Pitch:13)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$40,$04 ; 2d OrchHitG#.dmc (Pitch:14)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$04 ; 2e OrchHitG#.dmc (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$0a ; 2f PressStart (mp3c (Pitch:15)
	.byte $2f+.lobyte(FAMISTUDIO_DPCM_PTR),$57,$0f,$40,$0b ; 30 run (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$41,$0f,$34,$00 ; 31 snare (Pitch:15)
	.byte $0f+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0f,$40,$01 ; 32 this (Pitch:15)
	.byte $38+.lobyte(FAMISTUDIO_DPCM_PTR),$e7,$0f,$40,$07 ; 33 three (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$37,$0f,$40,$02 ; 34 time (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$d6,$0f,$40,$08 ; 35 two (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$0a ; 36 untitled (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0e,$40,$0b ; 37 voc1 (Pitch:14)
	.byte $0f+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$0e,$40,$0b ; 38 voc2 (Pitch:14)
	.byte $14+.lobyte(FAMISTUDIO_DPCM_PTR),$1e,$0e,$40,$0b ; 39 voc3 (Pitch:14)
	.byte $1c+.lobyte(FAMISTUDIO_DPCM_PTR),$4b,$0e,$40,$0b ; 3a voc4 (Pitch:14)

@song0ch0:
	.byte $46, $06, $53, $4f, $00
@song0ref6:
	.byte $8a
@song0ref7:
	.byte $25, $81, $2c, $81, $25, $81, $2c, $81, $25, $81, $2c, $81, $25, $81, $2c, $81, $20, $81, $27, $81, $20, $81, $27, $81
	.byte $20, $81, $27, $81, $20, $81, $27, $81, $4f, $01, $22, $81, $29, $81, $22, $81, $29, $81, $22, $81, $29, $81, $22, $81
	.byte $29, $81, $1e, $81, $25, $81, $1e, $81, $25, $81, $1e, $81, $25, $81, $1e, $81, $25, $81, $4f, $02
	.byte $41, $40
	.word @song0ref7
@song0ref78:
	.byte $4f, $01, $25, $00
@song0ref82:
	.byte $2c, $75, $25, $7f, $25, $75, $2c, $7f, $2c, $75, $25, $7f, $25, $75, $2c, $7f, $2c, $75, $25, $7f, $25, $75, $2c, $7f
	.byte $2c, $75, $25, $7f, $20, $75, $2c, $7f, $27, $75, $20, $7f, $20, $75, $27, $7f, $27, $75, $20, $7f, $20, $75, $27, $7f
	.byte $27, $75, $20, $7f, $20, $75, $27, $7f, $27, $75, $20, $7f, $22, $75, $27, $7f, $29, $75, $22, $7f, $22, $75, $29, $7f
	.byte $29, $75, $22, $7f, $22, $75, $29, $7f, $29, $75, $22, $7f, $22, $75, $29, $7f, $29, $75, $22, $7f, $1e, $75, $29, $7f
	.byte $25, $75, $1e, $7f, $1e, $75, $25, $7f, $25, $75, $1e, $7f, $1e, $75, $25, $7f, $25, $75, $1e, $7f, $1e, $75, $25, $7f
	.byte $25, $75, $1e, $7f, $4f, $01, $25, $75, $25, $7f
	.byte $41, $3e
	.word @song0ref82
	.byte $45, $9d, $7f
	.byte $41, $42
	.word @song0ref78
	.byte $7f
	.byte $41, $40
	.word @song0ref82
	.byte $7f
	.byte $41, $40
	.word @song0ref82
	.byte $7f
	.byte $41, $3e
	.word @song0ref82
	.byte $45, $fd, $ff, $76, $4f, $03, $aa
@song0ref240:
	.byte $31, $83, $31, $83, $31, $83, $31, $83, $31, $83, $31, $83, $30, $83, $30, $83, $30, $83, $30, $83, $30, $81, $31, $77
	.byte $83, $31, $83, $31, $83, $31, $83, $31, $83, $31, $81, $78, $81, $33, $83, $33, $83, $33, $83, $33, $83, $33, $81, $79
	.byte $31, $83, $31, $83, $31, $81, $7a, $81, $31, $83, $7b, $31, $83, $31, $83, $30, $81, $7c, $81, $30, $83, $30, $83, $30
	.byte $7d, $83, $30, $81, $31
@song0ref317:
	.byte $83, $31, $83, $31, $83, $31, $83, $31, $83, $31, $83, $33, $83, $33, $83, $33, $83, $35, $7e, $83, $35, $81, $7f, $4f
	.byte $03
	.byte $41, $17
	.word @song0ref240
	.byte $41, $11
	.word @song0ref317
	.byte $33, $83, $33, $81
	.byte $41, $17
	.word @song0ref240
	.byte $41, $12
	.word @song0ref317
	.byte $83, $35, $81, $45, $87, $44, $00
@song0ch1:
	.byte $78, $53, $4f, $03
	.byte $41, $14
	.word @song0ref6
	.byte $4f, $01, $20, $81, $27, $81, $20, $81, $27, $71, $20, $78, $20, $71, $27, $78, $27, $71, $20, $78, $22, $71, $27, $78
	.byte $29, $71, $22, $78, $22, $71, $29, $76, $29, $71, $22, $76, $22, $71, $29, $76, $29, $71, $22, $76, $22, $71, $88, $29
	.byte $76, $8a, $29, $71, $88, $22, $76, $4f, $03, $8a, $1e, $71, $88, $29, $76, $8a, $25, $71, $88, $1e, $76, $8a, $1e, $71
	.byte $88, $25, $76, $8a, $25, $71, $88, $1e, $76, $8a, $1e, $71, $88, $25, $76, $8a, $25, $71, $88, $1e, $76, $8a, $1e, $71
	.byte $88, $25, $76, $8a, $25, $71, $88, $1e, $76, $8a, $25, $71, $a4, $1e, $76, $8a, $2c, $71, $88, $25, $76, $8a, $25, $71
	.byte $88, $2c, $76, $8a, $2c, $71, $88, $25, $76, $8a, $25, $71, $88, $2c, $76, $8a, $2c, $71, $88, $25, $76, $8a, $25, $71
	.byte $88, $2c, $76, $8a, $2c, $71, $88, $25, $76, $4f, $01, $8a, $20, $71, $88, $2c, $76, $8a, $27, $71, $88, $20, $76, $8a
	.byte $20, $71, $88, $27, $76, $8a, $27, $71, $88, $20, $76, $8a, $20, $72, $88, $27, $76, $8a, $27, $72, $88, $20, $76, $8a
	.byte $20, $72, $88, $27, $76, $8a, $27, $72, $88, $20, $76, $8a, $22, $72, $88, $27, $76, $8a, $29, $72, $88, $22, $76, $8a
	.byte $22, $72, $88, $29, $76, $8a, $29, $72, $88, $22, $76, $8a, $22, $72, $88, $29, $76, $8a, $29, $72, $88, $22, $76, $8a
	.byte $22, $72, $88, $29, $76, $8a, $29, $72, $88, $22, $76, $8a, $1e, $72, $88, $29, $76, $8a, $25, $72, $88, $1e, $76, $8a
	.byte $1e, $72, $88, $25, $76, $8a, $25, $72, $88, $1e, $76, $8a, $1e, $72, $88, $25, $76, $8a, $25, $72, $88, $1e, $76, $8a
	.byte $1e, $72, $88, $25, $76, $8a, $25, $72, $88, $1e, $7a, $4b, .lobyte(@env13), .hibyte(@env13), $a2, $19, $9d, $4d, $14
	.byte $9d, $4b, .lobyte(@env44), .hibyte(@env44), $16, $9d, $4b, .lobyte(@env13), .hibyte(@env13), $12, $9d, $4d, $19, $9d
	.byte $4d, $14, $9d, $4b, .lobyte(@env44), .hibyte(@env44), $16, $9d, $4b, .lobyte(@env13), .hibyte(@env13), $12, $9d, $45
	.byte $9d, $7c, $4b, .lobyte(@env23), .hibyte(@env23), $4c, $4f, $03, $a8
@song0ref717:
	.byte $25, $81, $25, $81, $25, $81, $25, $25, $25, $25, $83, $25, $81, $25, $25, $83, $24, $83, $24, $83, $24, $24, $83, $24
	.byte $83, $24, $25, $81, $25, $81, $25, $81, $25, $25, $81, $25, $83, $25, $81, $25, $25, $25, $81, $27, $83, $27, $83, $27
	.byte $27, $83, $27, $83, $27, $4f, $03
	.byte $41, $32
	.word @song0ref717
	.byte $29, $29, $81, $29, $4f, $03
	.byte $41, $35
	.word @song0ref717
	.byte $4f, $03
	.byte $41, $32
	.word @song0ref717
	.byte $29, $29, $81, $29, $4f, $03
	.byte $41, $35
	.word @song0ref717
	.byte $4f, $03
	.byte $41, $32
	.word @song0ref717
	.byte $29, $29, $81, $29, $4f, $03
	.byte $41, $35
	.word @song0ref717
	.byte $4f, $03
	.byte $41, $32
	.word @song0ref717
	.byte $29, $29, $81, $29, $4f, $01, $aa
@song0ref824:
	.byte $25, $78, $25, $81, $7c, $25, $78, $25, $81, $7c, $25, $78, $25, $81, $7c, $25, $78, $25, $81, $7c, $25, $78, $25, $81
	.byte $7c, $25, $78, $25, $81, $7c, $24, $78, $24, $81, $7c, $24, $78, $24, $81, $7c, $24, $78, $24, $81, $7c, $24, $78, $24
	.byte $81, $7c, $24, $78, $24, $7c
	.byte $41, $12
	.word @song0ref824
	.byte $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $27, $78, $27
	.byte $7c
	.byte $41, $20
	.word @song0ref824
	.byte $7c
	.byte $41, $12
	.word @song0ref824
	.byte $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $29, $78, $29, $81, $7c, $29, $78, $29
	.byte $45, $87, $44, $00
@song0ch2:
	.byte $ff, $ff, $a4
@song0ref945:
	.byte $19, $9d, $14, $9d, $16, $9d, $12, $9d, $19, $9d, $14, $9d, $16, $9d, $12, $9d, $00, $9d
@song0ref963:
	.byte $19, $81, $25, $19, $83, $25, $19, $83, $25, $19, $83, $25, $19, $14, $81, $20, $14, $83, $20, $14, $83, $20, $14, $83
	.byte $20, $14, $16, $81, $22, $16, $83, $22, $16, $83, $22, $16, $83, $22, $16, $12, $81, $1e, $12, $83, $1e, $12, $83, $1e
	.byte $12, $83, $1e, $12
	.byte $41, $34
	.word @song0ref963
	.byte $41, $34
	.word @song0ref963
	.byte $41, $34
	.word @song0ref963
	.byte $41, $34
	.word @song0ref963
	.byte $41, $34
	.word @song0ref963
	.byte $41, $34
	.word @song0ref963
	.byte $41, $34
	.word @song0ref963
	.byte $41, $11
	.word @song0ref945
	.byte $87, $44, $00
@song0ch3:
	.byte $ff, $ef, $71, $88, $1f, $72, $81, $73, $81, $74, $81, $75, $81, $76, $81, $77, $81, $78, $81, $79, $92, $1f, $81, $a8
	.byte $21, $81, $7f
@song0ref1070:
	.byte $82, $14, $81, $80, $21, $23, $86, $14, $80, $23, $21, $81, $82, $14, $81, $80, $21, $23
@song0ref1088:
	.byte $86, $14, $81, $80, $21, $81, $82, $14, $81, $80, $21, $23, $86, $14, $80, $23, $21, $81, $82, $14, $81, $80, $21, $23
	.byte $86, $14, $81, $80, $21, $81
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $1c
	.word @song0ref1070
	.byte $8f, $71, $a4, $1f, $72, $81, $73, $81, $75, $81, $77, $81, $7a, $81, $7c, $81, $7f, $81
	.byte $41, $14
	.word @song0ref1088
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $82, $14, $81, $80, $21, $23, $86, $14, $80, $23, $21, $81, $82, $14, $81, $80, $21, $23, $92, $1f, $8d, $45, $ed, $ff
	.byte $89, $44, $00
@song0ch4:
	.byte $ff, $ff
@song0ref1223:
	.byte $87, $32, $8d, $32, $8d, $32, $8d, $32, $8d, $32, $8d, $32, $8d, $32, $8d, $32, $85
	.byte $41, $11
	.word @song0ref1223
	.byte $9f
@song0ref1244:
	.byte $1d, $81, $14, $81, $32, $81, $14, $85, $14, $81, $32, $81, $14, $81, $1d, $81, $13, $81, $32, $81, $13, $85, $13, $81
	.byte $32, $81, $13, $81, $1d, $81, $1a, $81, $32, $81, $1a, $85, $1a, $81, $32, $81, $1a, $81, $1d, $81, $12, $81, $32, $81
	.byte $12, $85, $12, $81, $32, $81, $12, $81
	.byte $41, $38
	.word @song0ref1244
	.byte $41, $38
	.word @song0ref1244
	.byte $41, $38
	.word @song0ref1244
	.byte $41, $38
	.word @song0ref1244
	.byte $41, $38
	.word @song0ref1244
	.byte $41, $38
	.word @song0ref1244
	.byte $41, $38
	.word @song0ref1244
	.byte $00, $fd, $ff, $89, $44, $00
@song1ch0:
	.byte $46, $06, $4e, $ff
@song1ref5:
	.byte $a6
@song1ref6:
	.byte $16, $81, $00, $16, $81, $00, $48, $0b, $16, $00, $48, $0b, $16, $00, $48, $0b, $16, $00, $12, $81, $11, $81, $0f, $81
	.byte $00, $0f, $81, $00, $0f, $81, $00, $0f, $83, $11, $81, $50, $a0, $1d, $27, $43, $1b, $18, $81, $00, $18, $81, $00, $18
	.byte $81, $16, $81, $18, $81, $50, $db, $24, $29, $43, $1d
@song1ref65:
	.byte $19, $81, $16, $81, $00, $16, $81, $00, $16, $81, $18, $81, $00, $14, $81, $00, $48, $0a, $14, $00, $4e, $ff
	.byte $41, $3f
	.word @song1ref6
	.byte $4e, $ff
	.byte $41, $3f
	.word @song1ref6
	.byte $4e, $ff
@song1ref97:
	.byte $16, $81, $00, $16, $81, $00, $48, $0b, $16, $00, $16, $81, $00, $16, $81, $00, $48, $0b, $16, $00
	.byte $41, $10
	.word @song1ref97
@song1ref120:
	.byte $48, $0b, $16, $00, $48, $0b, $16, $00, $48, $0b, $16, $00, $48, $0b, $16, $00, $48, $0b, $16, $00, $48, $0b, $16, $00
	.byte $48, $0b, $16, $00, $48, $0b, $16, $00, $48, $0b, $16, $00, $48, $0b, $16, $00, $48, $0b, $16, $00, $48, $0b, $16, $00
	.byte $48, $05, $16, $48, $05, $16, $48, $05, $16, $48, $05, $16, $48, $05, $16, $48, $05, $16, $48, $05, $16, $48, $05, $16
	.byte $77, $b0
@song1ref194:
	.byte $0a, $7f, $0a, $0a, $0a, $77, $06, $7f, $06, $06, $06, $77, $05, $7f, $05, $05, $05, $81, $81, $05, $05, $77, $06, $7f
	.byte $06, $06, $06, $77, $06, $7f, $06, $06, $06, $77, $0a, $7f, $0a, $0a, $0a, $77, $0a, $7f, $50, $ed, $16, $17, $50, $ee
	.byte $17, $18, $50, $ef, $18, $19, $77
	.byte $41, $10
	.word @song1ref194
@song1ref252:
	.byte $77, $0a, $7f, $0a, $0a, $0a, $77, $0a, $7f, $0a, $0a, $0a, $77, $0c, $7f, $0c, $0c, $0c, $77, $08, $7f, $08, $08, $08
	.byte $77
	.byte $41, $20
	.word @song1ref194
	.byte $77
	.byte $41, $10
	.word @song1ref194
	.byte $41, $10
	.word @song1ref252
	.byte $77
	.byte $41, $20
	.word @song1ref194
	.byte $77
	.byte $41, $10
	.word @song1ref194
	.byte $41, $10
	.word @song1ref252
	.byte $77
	.byte $41, $20
	.word @song1ref194
	.byte $77
	.byte $41, $10
	.word @song1ref194
	.byte $41, $10
	.word @song1ref252
	.byte $77
	.byte $41, $20
	.word @song1ref194
	.byte $77
	.byte $41, $10
	.word @song1ref194
	.byte $41, $10
	.word @song1ref252
	.byte $77
	.byte $41, $20
	.word @song1ref194
	.byte $77
	.byte $41, $10
	.word @song1ref194
	.byte $41, $10
	.word @song1ref252
	.byte $76, $4f, $01, $88, $0a, $85, $06, $85, $05, $85, $00, $85, $06, $83, $00, $06, $83, $00, $0a, $85, $00, $85, $4f, $01
	.byte $0a, $85, $06, $85, $05, $85, $00, $85, $0a, $83, $00, $0a, $83, $00, $0c, $85, $08, $85, $00, $8d, $44, $00
@song1ch1:
	.byte $83, $77, $4e, $04
	.byte $41, $1d
	.word @song1ref5
@song1ref385:
	.byte $1b, $81, $18, $81, $00, $18, $81, $00, $18, $81, $16, $81, $18, $81, $1d, $81
	.byte $41, $0e
	.word @song1ref65
	.byte $83, $83, $4e, $04
	.byte $41, $1d
	.word @song1ref6
	.byte $41, $10
	.word @song1ref385
	.byte $41, $0e
	.word @song1ref65
	.byte $83, $83, $4e, $04
	.byte $41, $1d
	.word @song1ref6
	.byte $41, $10
	.word @song1ref385
	.byte $41, $0e
	.word @song1ref65
	.byte $83, $83, $4e, $04
	.byte $41, $10
	.word @song1ref97
	.byte $41, $10
	.word @song1ref97
	.byte $41, $1e
	.word @song1ref120
	.byte $00, $95, $74, $88
@song1ref447:
	.byte $50, $dd, $31, $3d, $43, $50, $6a, $3d, $1b, $81, $00, $97, $50, $dd, $31, $3d, $43, $50, $6a, $3d, $1b, $81, $00, $97
	.byte $50, $dd, $31, $3d, $43, $50, $6a, $3d, $1b, $81, $00, $97, $50, $dd, $31, $3d, $43, $50, $6a, $3d, $1b, $81, $00, $00
	.byte $95
	.byte $41, $13
	.word @song1ref447
@song1ref499:
	.byte $76, $4e, $00, $9c, $22, $95, $74, $88, $50, $dd, $31, $3d, $43, $50, $6a, $3d, $1b, $81, $00, $76, $9c, $1e, $8d, $22
	.byte $85, $74, $88, $50, $dd, $31, $3d, $43, $50, $68, $3d, $25, $76, $9c, $25, $81, $22, $8d, $1d, $83, $43, $06, $74, $88
	.byte $50, $dd, $31, $3d, $43, $50, $6a, $3d, $1b, $81, $00, $76, $9c, $22, $8d, $24, $85, $74, $88, $50, $dd, $31, $3d, $43
	.byte $50, $6a, $3d, $1b, $81, $00
	.byte $41, $1f
	.word @song1ref499
	.byte $7f, $a2, $22, $85
@song1ref584:
	.byte $50, $16, $2e, $2a, $43, $1e, $83
@song1ref591:
	.byte $50, $06, $2a, $29, $43, $1d, $85, $78, $81, $7f, $1d, $43, $1d, $50, $fa, $29, $2a, $43, $1e, $8b, $50, $ea, $2a, $2e
	.byte $43, $22, $87, $76, $4f, $01, $88, $50, $eb, $2e, $33, $43, $27, $7f, $a2, $50, $15, $33, $2e, $43, $22, $83, $50, $16
	.byte $2e, $2a, $43, $1e, $83, $50, $06, $2a, $29, $43, $1d, $85, $78, $81, $7f, $1d, $43, $1d, $50, $e4, $29, $2e, $43, $22
	.byte $8b, $50, $f6, $2e, $30, $43, $24, $83, $50, $14, $30, $2c, $43, $20, $83, $50, $f5, $2c, $2e, $43, $22, $83
	.byte $41, $28
	.word @song1ref584
	.byte $22, $43, $22, $50, $16, $2e, $2a, $43, $1e, $1e, $1e
	.byte $41, $23
	.word @song1ref591
	.byte $00, $8d, $44, $00
@song1ch2:
	.byte $88, $16, $9d, $0f, $9d, $18, $9d, $16, $9d, $16, $9d, $0f, $9d, $18, $9d, $16, $9d, $16, $9d, $0f, $9d, $18, $9d, $16
	.byte $9d, $9a, $01, $00, $fb, $88
@song1ref737:
	.byte $1d, $85, $19, $85, $18, $85, $18, $00, $18, $81, $19, $85, $19, $85, $1d, $85, $1d, $50, $fa, $29, $2a, $50, $fa, $2a
	.byte $2b, $50, $fa, $2b, $2c, $1d, $85, $19, $85, $18, $85, $18, $00, $18, $81, $1d, $85, $1d, $85, $1f, $85, $1b, $85
	.byte $41, $26
	.word @song1ref737
	.byte $41, $26
	.word @song1ref737
	.byte $41, $26
	.word @song1ref737
	.byte $41, $26
	.word @song1ref737
	.byte $41, $26
	.word @song1ref737
	.byte $9a, $01, $88, $16, $83, $9e, $01, $88, $12, $83, $9a, $01, $88, $11, $83, $9e, $01, $88, $11, $00, $81, $9a, $01, $88
	.byte $12, $83, $9e, $01, $88, $12, $83, $9a, $01, $88, $16, $83, $9e, $01, $88, $16, $00, $81, $9a, $01, $88, $16, $83, $9e
	.byte $01, $88, $12, $83, $9a, $01, $88, $11, $00, $81, $9e, $01, $88, $11, $00, $81, $9a, $01, $88, $16, $83, $9e, $01, $88
	.byte $16, $83, $18, $85, $14, $85, $00, $8d, $44, $00
@song1ch3:
	.byte $92, $21, $8d, $78, $95, $00, $d7, $79, $22, $81, $80
@song1ref893:
	.byte $21, $85, $21, $85, $21, $85, $21, $85, $21, $85, $21, $85, $21, $85
	.byte $41, $0e
	.word @song1ref893
	.byte $21, $85, $21, $81, $7f
@song1ref915:
	.byte $92, $22, $8d, $72, $88, $22, $8d, $71, $9f, $72, $8f, $73, $87, $74, $85, $75, $85, $76, $83, $77, $83, $78, $81, $79
	.byte $81, $7a, $83, $7b, $81, $7c, $81, $7d, $83, $7e, $81, $7f, $81
	.byte $41, $13
	.word @song1ref915
@song1ref955:
	.byte $92, $20, $81, $80, $1f, $81
@song1ref961:
	.byte $84, $20, $81, $80, $1f, $81, $90, $20, $81, $80, $1f, $1f, $84, $20, $81, $80, $1f, $81, $90, $20, $81, $80, $1f, $1f
	.byte $41, $10
	.word @song1ref961
	.byte $41, $0f
	.word @song1ref961
@song1ref991:
	.byte $81, $84, $20, $81, $80, $1f, $1f, $90, $20, $81, $80, $1f, $81, $84, $20, $81, $80, $1f, $1f
	.byte $41, $14
	.word @song1ref955
	.byte $41, $10
	.word @song1ref961
	.byte $41, $0f
	.word @song1ref961
	.byte $41, $0d
	.word @song1ref991
	.byte $41, $14
	.word @song1ref955
	.byte $41, $10
	.word @song1ref961
	.byte $41, $0f
	.word @song1ref961
	.byte $41, $0d
	.word @song1ref991
	.byte $41, $14
	.word @song1ref955
	.byte $41, $10
	.word @song1ref961
	.byte $41, $0f
	.word @song1ref961
	.byte $81, $84, $20, $81, $80, $1f, $1f, $83, $1f, $85, $1f, $1f
	.byte $41, $14
	.word @song1ref955
	.byte $41, $10
	.word @song1ref961
	.byte $41, $0f
	.word @song1ref961
	.byte $41, $0d
	.word @song1ref991
	.byte $41, $14
	.word @song1ref955
	.byte $41, $10
	.word @song1ref961
	.byte $41, $0f
	.word @song1ref961
	.byte $81, $84, $20, $81, $80, $1f, $1f, $83, $1f, $85, $1f, $1f
	.byte $41, $14
	.word @song1ref955
	.byte $41, $10
	.word @song1ref961
	.byte $41, $0f
	.word @song1ref961
	.byte $81, $84, $20, $81, $80, $1f, $1f, $83, $1f, $85, $1f, $1f, $92, $20, $8d, $44, $00
@song1ch4:
	.byte $52, $80, $00, $fd
@song1ref1119:
	.byte $1d, $85, $1d, $85, $1d, $85, $1d, $85, $1d, $85, $1d, $85, $1d, $85
	.byte $41, $0e
	.word @song1ref1119
	.byte $1d, $85
@song1ref1138:
	.byte $1d, $81, $1d, $81, $1d, $81, $1d, $81, $1d, $81, $1d, $81, $1d, $81
	.byte $41, $0e
	.word @song1ref1138
	.byte $41, $0e
	.word @song1ref1138
	.byte $1d, $81, $1d, $81, $1d, $81, $1d, $81, $1d, $81, $1d, $1d, $1d, $1d, $1d, $1d, $1d, $1d, $1d, $1d, $1d, $1d, $1d, $1d
	.byte $1d, $1d, $1d, $fd
@song1ref1186:
	.byte $1d, $1a, $1a, $1a, $32, $12, $12, $12, $1d, $19, $19, $19, $32, $81, $19, $19, $1d, $12, $12, $12, $32, $12, $12, $12
	.byte $1d, $1a, $1a, $1a, $32, $1a, $1a, $1a
	.byte $41, $11
	.word @song1ref1186
@song1ref1221:
	.byte $1a, $1a, $1a, $32, $1a, $1a, $1a, $1d, $1b, $1b, $1b, $32, $13, $13, $13
	.byte $41, $20
	.word @song1ref1186
	.byte $41, $11
	.word @song1ref1186
	.byte $41, $0f
	.word @song1ref1221
	.byte $41, $20
	.word @song1ref1186
	.byte $41, $11
	.word @song1ref1186
	.byte $41, $0f
	.word @song1ref1221
	.byte $41, $20
	.word @song1ref1186
	.byte $41, $11
	.word @song1ref1186
@song1ref1260:
	.byte $1a, $1a, $1a, $32, $1a, $1a, $1a, $1b, $1b, $1b, $1b, $13, $13, $13, $13
	.byte $41, $20
	.word @song1ref1186
	.byte $41, $11
	.word @song1ref1186
	.byte $41, $0f
	.word @song1ref1221
	.byte $41, $20
	.word @song1ref1186
	.byte $41, $11
	.word @song1ref1186
	.byte $41, $0f
	.word @song1ref1260
	.byte $00, $fd, $8f, $44, $00
; The DPCM aligner used to be here
@song3ch0:
	.byte $46, $06, $9f, $8a, $19, $81, $00, $99, $9f, $9f, $76, $4f, $01
@song3ref14:
	.byte $96
@song3ref15:
	.byte $1d, $45, $1d, $81, $45, $81, $22, $45, $22, $45, $25, $45, $20, $81, $45, $81, $78, $4f, $01
@song3ref34:
	.byte $22
@song3ref35:
	.byte $81, $45, $81, $22, $45, $20, $45, $22, $81, $45, $81, $22, $81, $45, $81, $7a, $4f, $01
@song3ref53:
	.byte $22, $45, $25, $81, $45, $81, $22, $45, $20, $81, $45, $81, $20, $81, $45, $81, $7b
@song3ref70:
	.byte $22, $45, $25, $81, $45, $81, $20, $45, $22, $81, $45, $81, $22, $81, $45, $81, $7c
	.byte $41, $10
	.word @song3ref15
	.byte $7d
	.byte $41, $10
	.word @song3ref34
	.byte $7e
	.byte $41, $10
	.word @song3ref53
	.byte $7f
	.byte $41, $10
	.word @song3ref70
	.byte $41, $10
	.word @song3ref15
	.byte $20
	.byte $41, $0f
	.word @song3ref35
	.byte $41, $10
	.word @song3ref53
	.byte $41, $10
	.word @song3ref70
	.byte $41, $10
	.word @song3ref15
	.byte $20
	.byte $41, $0f
	.word @song3ref35
	.byte $41, $10
	.word @song3ref53
	.byte $49, .lobyte(@env32), .hibyte(@env32), $22, $45, $96, $25, $81, $45, $81, $20, $45, $22, $81, $45, $81, $50, $e9, $2e
	.byte $3a, $81, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $81
@song3ref152:
	.byte $49, .lobyte(@env46), .hibyte(@env46), $1d, $81, $96, $29, $81, $00, $81, $22, $81, $22, $81, $25, $81, $29, $81, $00
	.byte $81, $20
	.byte $41, $0f
	.word @song3ref35
	.byte $41, $10
	.word @song3ref53
	.byte $41, $10
	.word @song3ref70
	.byte $41, $11
	.word @song3ref152
	.byte $41, $0f
	.word @song3ref35
	.byte $41, $10
	.word @song3ref53
	.byte $41, $10
	.word @song3ref70
	.byte $b2, $22, $00, $29, $81, $00, $81, $25, $00, $22, $00, $25, $00, $29, $81, $00, $81, $96, $20
	.byte $41, $0f
	.word @song3ref35
	.byte $41, $10
	.word @song3ref53
	.byte $41, $10
	.word @song3ref70
@song3ref222:
	.byte $8a
@song3ref223:
	.byte $22, $81, $29, $85, $22, $81, $22, $81, $25, $81, $29, $85, $20, $85, $22, $81, $20, $81, $22, $85, $22, $85, $22, $81
	.byte $25, $85, $22, $81, $20, $85, $20, $85, $22, $81, $25, $85, $20, $81, $22, $85, $22, $85
	.byte $41, $22
	.word @song3ref223
	.byte $20, $85, $78, $22, $81, $20, $85, $00, $85, $4b, .lobyte(@env37), .hibyte(@env37), $98, $50, $14, $29, $1d, $89, $4b
	.byte .lobyte(@env23), .hibyte(@env23), $4c, $96, $1d, $81, $00, $85, $4b, .lobyte(@env37), .hibyte(@env37), $98, $16, $85
	.byte $4d, $1b, $85, $4d, $88, $08, $85, $4b, .lobyte(@env23), .hibyte(@env23), $4c, $96, $22, $81, $20, $81, $00, $85, $4b
	.byte .lobyte(@env37), .hibyte(@env37), $98, $16, $83, $45, $4d, $16, $83, $45, $4d, $14, $83, $45, $4b, .lobyte(@env23)
	.byte .hibyte(@env23), $4c, $96, $22, $81, $29, $81, $4b, .lobyte(@env37), .hibyte(@env37), $98, $12, $83, $45, $4d, $11
@song3ref352:
	.byte $83, $45, $4d, $40, $05, $83, $45, $4b, .lobyte(@env23), .hibyte(@env23), $4c, $96, $22, $81, $29, $81, $1d, $8d, $00
	.byte $4b, .lobyte(@env37), .hibyte(@env37), $98, $50, $11, $29, $1d, $8b, $00, $89, $4d, $20, $81, $4d, $50, $f5, $20, $22
	.byte $81, $43, $16, $45, $4d, $50, $f5, $20, $22, $81, $43, $16
@song3ref402:
	.byte $45, $70, $51, $02, $80, $4b, .lobyte(@env23), .hibyte(@env23), $4c, $96, $2c, $9d, $8a, $2c, $00, $77, $2c, $00, $76
	.byte $2c, $00, $75, $2c, $00, $74, $2c, $00, $73, $2c, $00, $72, $2c, $00, $71, $2c, $78, $00, $44, $00
@song3ch1:
	.byte $8a, $1d, $85, $77, $1d, $85, $75, $1d, $85, $72, $1d, $85, $7f, $20, $85, $77, $20, $85, $75, $20, $85, $72, $20, $85
	.byte $7f, $22, $85, $77, $22, $85, $75, $22, $85, $72, $22, $85, $7f, $22, $85, $75, $22, $85, $7f, $22, $85, $22, $85, $75
	.byte $4e, $fe
	.byte $41, $10
	.word @song3ref14
	.byte $77
	.byte $41, $10
	.word @song3ref34
	.byte $79
	.byte $41, $20
	.word @song3ref53
	.byte $75, $4e, $fe
	.byte $41, $10
	.word @song3ref15
	.byte $77
	.byte $41, $10
	.word @song3ref34
	.byte $79
	.byte $41, $20
	.word @song3ref53
	.byte $75, $4e, $fe
	.byte $41, $10
	.word @song3ref15
	.byte $77
	.byte $41, $10
	.word @song3ref34
	.byte $79
	.byte $41, $20
	.word @song3ref53
	.byte $7f
	.byte $41, $10
	.word @song3ref15
	.byte $20
	.byte $41, $0f
	.word @song3ref35
	.byte $22, $45, $25, $81, $45, $81, $22, $45, $20, $81, $00, $81, $20, $81, $45, $81, $49, .lobyte(@env32), .hibyte(@env32)
	.byte $22, $81, $96, $25, $81, $00, $81, $20, $81, $22, $81, $00, $81, $50, $e9, $2e, $3a, $81, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $00, $81
@song3ref582:
	.byte $1d, $45, $29, $81, $45, $81, $22, $45, $22, $45, $25, $45, $29, $81, $45, $81, $20, $81, $45, $81, $22, $45, $20, $45
	.byte $50, $e9, $2e, $3a, $81, $00, $81, $22, $81, $45, $81, $22, $45, $25, $81, $45, $81, $22, $45, $50, $e2, $2c, $3c, $81
	.byte $00, $81, $20, $81, $45, $81
	.byte $41, $10
	.word @song3ref70
	.byte $41, $30
	.word @song3ref582
	.byte $41, $10
	.word @song3ref70
	.byte $41, $30
	.word @song3ref582
	.byte $41, $10
	.word @song3ref70
	.byte $41, $2a
	.word @song3ref222
	.byte $41, $22
	.word @song3ref223
	.byte $20, $85, $78, $22, $81, $20, $85, $00, $85, $4b, .lobyte(@env37), .hibyte(@env37), $98, $50, $28, $1d, $11, $89, $4b
	.byte .lobyte(@env23), .hibyte(@env23), $4c, $96, $1d, $81, $00, $85, $4b, .lobyte(@env37), .hibyte(@env37), $98, $0a, $85
	.byte $4d, $0f, $85, $4d, $88, $08, $85, $4b, .lobyte(@env23), .hibyte(@env23), $4c, $96, $22, $81, $20, $81, $00, $85, $4b
	.byte .lobyte(@env37), .hibyte(@env37), $98, $0a, $83, $45, $4d, $0a, $83, $45, $4d, $08, $83, $45, $4b, .lobyte(@env23)
	.byte .hibyte(@env23), $4c, $96, $22, $81, $29, $81, $4b, .lobyte(@env37), .hibyte(@env37), $98, $06, $83, $45, $4d, $05
	.byte $41, $0c
	.word @song3ref352
	.byte $4b, .lobyte(@env37), .hibyte(@env37), $98, $50, $22, $1d, $11, $8b, $00, $89, $4d, $14, $81, $4d, $50, $ea, $14, $16
	.byte $81, $43, $0a, $45, $4d, $50, $ea, $14, $16, $81, $43, $0a
	.byte $41, $14
	.word @song3ref402
@song3ch2:
	.byte $8e
@song3ref780:
	.byte $1d, $81, $00, $81, $8c, $1d, $00, $83, $1d, $00, $83, $1d, $00, $83, $8e, $20, $81, $00, $81, $8c, $20, $00, $83, $20
	.byte $00, $83, $20, $00, $83, $8e, $22, $81, $00, $81, $8c, $22, $00, $83, $22, $00, $83, $22, $00, $83, $8e, $22, $81, $00
	.byte $81, $8c, $22, $00, $83, $8e, $22, $81, $00, $81, $22, $81, $00, $81
	.byte $41, $36
	.word @song3ref780
	.byte $41, $36
	.word @song3ref780
	.byte $41, $36
	.word @song3ref780
	.byte $41, $2a
	.word @song3ref780
	.byte $89, $22, $81, $00, $81, $22, $81, $00, $81
	.byte $41, $36
	.word @song3ref780
	.byte $41, $36
	.word @song3ref780
	.byte $41, $36
	.word @song3ref780
	.byte $41, $36
	.word @song3ref780
	.byte $41, $36
	.word @song3ref780
	.byte $41, $36
	.word @song3ref780
	.byte $41, $27
	.word @song3ref780
	.byte $9f, $44, $00
@song3ch3:
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $92, $40, $0a, $83, $45
@song3ref905:
	.byte $94, $40, $0a, $81, $86, $40, $01, $81
@song3ref913:
	.byte $40, $01, $81
@song3ref916:
	.byte $40, $01, $81, $94, $40, $0a, $81, $86, $40, $01, $81, $92, $40, $0a, $83, $45, $94, $40, $0a, $81, $86, $40, $01, $81
	.byte $40, $01, $81, $00, $81, $94, $40, $0a, $81, $00, $81, $78
@song3ref952:
	.byte $40, $0a, $81, $86, $40, $01, $81, $94, $40, $0a, $81, $86, $40, $01, $81, $94, $40, $0a, $81, $86, $40, $01, $75, $81
	.byte $41, $0c
	.word @song3ref905
	.byte $41, $11
	.word @song3ref913
	.byte $41, $21
	.word @song3ref916
	.byte $94, $40, $0a, $81, $86, $40, $01, $81, $00, $9d, $7f, $92
@song3ref997:
	.byte $40, $0a, $83, $45, $00, $85, $82, $03, $81, $00, $89, $92
@song3ref1009:
	.byte $40, $0a, $83, $45, $00, $85, $82, $03, $81, $00
@song3ref1019:
	.byte $89, $92, $40, $0a, $83, $45, $00, $85, $82, $03, $81, $00, $81, $92, $40, $0a, $83, $45
	.byte $41, $1a
	.word @song3ref997
	.byte $41, $0d
	.word @song3ref1019
	.byte $40, $0a, $83, $45, $00, $85, $82, $03, $81, $00, $89, $92, $21, $85, $74, $21, $85, $73, $21, $83, $72, $81, $21, $85
	.byte $7f
	.byte $41, $15
	.word @song3ref1009
	.byte $40, $0a, $83, $45, $00, $85, $82, $03, $81, $00, $89, $92, $40, $0a, $85, $94, $01, $81, $86, $40, $01, $81, $7b, $94
	.byte $01, $81, $86, $40, $01, $81, $94, $01, $81, $86, $40, $01, $81, $78, $94
	.byte $41, $0c
	.word @song3ref952
	.byte $94, $40, $0a, $81, $86, $40, $01, $81, $78, $94
	.byte $41, $0c
	.word @song3ref952
	.byte $94, $40, $0a, $81, $86, $40, $01, $81, $00, $9d, $9f, $9f, $9f, $97, $70, $51, $07, $a0, $88, $01, $85, $7f, $92
@song3ref1149:
	.byte $40, $0a, $8d, $40, $0c, $85, $00, $85, $40, $0a, $8d, $40, $0c, $85, $00, $85
	.byte $41, $0c
	.word @song3ref1149
	.byte $41, $0c
	.word @song3ref1149
	.byte $41, $0c
	.word @song3ref1149
	.byte $44, $00
@song3ch4:
	.byte $19, $9d, $13, $9d, $1a, $9d, $1a, $8d
@song3ref1185:
	.byte $1a, $85, $1a, $85, $19, $85, $19, $85, $19, $85, $19, $85, $13, $85, $13, $85, $13, $85, $13, $85, $1a, $85, $1a, $85
	.byte $1a, $85, $1a, $85, $1a, $85, $1a, $85
	.byte $41, $20
	.word @song3ref1185
	.byte $41, $20
	.word @song3ref1185
	.byte $41, $1c
	.word @song3ref1185
	.byte $00, $9d
@song3ref1228:
	.byte $1d, $81
@song3ref1230:
	.byte $1a, $81, $1a, $81, $1a, $81, $32, $81, $1a, $81, $1a, $81, $1a, $81
@song3ref1244:
	.byte $1d, $81, $14, $81, $14, $81, $14, $81, $32, $81, $14, $81, $14, $81, $14, $81, $1d, $81, $13, $81, $13, $81, $13, $81
	.byte $32, $81, $13, $81, $1d, $81, $13, $81
	.byte $41, $12
	.word @song3ref1228
	.byte $41, $2e
	.word @song3ref1230
	.byte $41, $10
	.word @song3ref1228
	.byte $00, $9d
	.byte $41, $20
	.word @song3ref1244
	.byte $41, $10
	.word @song3ref1228
	.byte $00, $9d, $9f, $9f, $9f, $9f, $9f, $9f, $9f
@song3ref1302:
	.byte $1d, $81, $19, $81, $19, $81, $1d, $19, $32, $81, $1d, $1a, $1d, $1a, $1a, $81, $1d, $81, $18, $81, $18, $81, $18, $81
	.byte $32, $81, $13, $81, $13, $81, $13, $81, $1d, $81, $1a, $81, $1d, $81, $1a, $81, $32, $81, $1a, $81, $1d, $81, $1a, $81
	.byte $1d, $81, $12, $81, $1d, $81, $19, $81, $32, $81, $19, $81, $1d, $81, $19, $81
	.byte $41, $32
	.word @song3ref1302
	.byte $00, $89, $32, $81, $00, $89, $44, $00
@song4ch0:
	.byte $46, $06, $9f
@song4ref4:
	.byte $78, $4e, $01, $a0
@song4ref8:
	.byte $50, $f1, $1e, $20, $14, $81, $23, $00, $81, $0f, $85, $1e, $81, $00, $85
@song4ref23:
	.byte $50, $f8, $1d, $1e, $12, $81, $22, $00, $81, $0d, $85, $1d, $85, $00, $81
	.byte $41, $15
	.word @song4ref8
	.byte $00, $1d, $1e, $50, $12, $29, $25, $19
@song4ref49:
	.byte $50, $f4, $16, $17, $0b, $81, $1b, $8b, $00, $89
@song4ref59:
	.byte $1e, $89, $00, $81, $1d, $89, $00, $81
	.byte $41, $08
	.word @song4ref49
	.byte $83, $20, $87, $1d, $85, $1e, $85
	.byte $41, $0f
	.word @song4ref49
	.byte $41, $0c
	.word @song4ref49
	.byte $85, $00, $85
	.byte $41, $0c
	.word @song4ref8
@song4ref89:
	.byte $50, $f5, $18, $19, $0d, $81, $1d, $00, $81, $0b, $85, $1b, $85, $00, $81
	.byte $41, $0c
	.word @song4ref8
	.byte $41, $0c
	.word @song4ref89
	.byte $41, $09
	.word @song4ref8
	.byte $00, $87
	.byte $41, $09
	.word @song4ref89
@song4ref118:
	.byte $81, $19, $85, $51, $ff, $40, $17, $89, $78, $51, $ff, $20, $17, $91, $78, $51, $ff, $40, $1b, $89, $78, $51, $ff, $40
	.byte $1d, $81, $00, $8d, $7f, $4e, $00, $ac
@song4ref150:
	.byte $31, $85, $33, $81, $2e, $91, $2c, $85, $31, $81, $2e, $91, $36, $85, $35, $81, $2e, $91, $2c, $83, $2e, $83, $27, $91
	.byte $41, $18
	.word @song4ref4
	.byte $41, $15
	.word @song4ref8
	.byte $00, $1d, $1e, $50, $12, $29, $25, $19, $7f, $51, $fe, $20, $88, $2c, $91, $78, $00, $89, $a0
	.byte $41, $08
	.word @song4ref59
	.byte $7f, $51, $fe, $20, $88, $20, $91, $78, $00, $89, $a0, $1e, $83, $20, $87, $1d, $85, $19, $85, $7c, $51, $fe, $20, $88
	.byte $20, $91, $75, $00, $89, $a0
	.byte $41, $08
	.word @song4ref59
	.byte $1b, $91, $00, $89, $1e, $8d, $1d, $81, $00, $89, $78
	.byte $41, $0c
	.word @song4ref8
	.byte $41, $0c
	.word @song4ref89
	.byte $41, $0c
	.word @song4ref8
	.byte $41, $0c
	.word @song4ref89
	.byte $41, $09
	.word @song4ref8
	.byte $00, $87
	.byte $41, $09
	.word @song4ref89
	.byte $41, $25
	.word @song4ref118
	.byte $4e, $00
	.byte $41, $0c
	.word @song4ref150
	.byte $4e, $00, $2a, $85, $2e, $81, $2c, $8d, $51, $fe, $00, $29, $9f, $81, $00, $9d, $44, $00
@song4ch1:
	.byte $9f, $8b, $ae, $19, $16, $16, $81, $14, $12, $50, $f8, $1e, $20, $81, $14, $81, $00, $87, $0d, $14, $14, $14, $81, $14
	.byte $81, $14, $14, $12, $16, $83, $14, $12, $00, $81, $19, $16, $16, $14, $14, $12, $50, $f8, $1e, $20, $81, $14, $81, $00
	.byte $89, $14, $14, $14, $81, $14, $14, $14, $81, $12, $16, $83, $14, $12, $83, $00, $87
@song4ref358:
	.byte $0d, $19, $16, $16, $16, $87, $19, $85, $14, $85, $16, $83, $0f, $83, $12, $81, $14, $85
@song4ref376:
	.byte $00, $83, $0d, $14, $14, $81, $14, $83, $12, $83, $00, $87, $0f, $0f, $17, $16, $14, $14, $83, $12, $85, $00, $87, $0f
	.byte $14, $16, $16, $81, $16, $85, $19, $85, $14, $85, $16, $85, $83, $16, $81, $14, $12, $50, $2c, $19, $12, $81
	.byte $41, $0c
	.word @song4ref376
	.byte $14, $14, $81, $12, $83
@song4ref430:
	.byte $16, $16, $16, $19
@song4ref434:
	.byte $19, $16, $16, $81, $16, $81, $14, $81, $00, $85
@song4ref444:
	.byte $14, $14, $14, $14, $14, $81, $14, $14, $81, $12, $83, $00, $83, $0f
	.byte $41, $0d
	.word @song4ref430
	.byte $81, $0f, $0f
	.byte $41, $0b
	.word @song4ref444
@song4ref467:
	.byte $0f, $0f, $17, $81, $16, $83, $14, $83, $12, $12, $12, $14, $14, $81, $14, $14, $14, $81
@song4ref485:
	.byte $14, $14, $14, $14, $14, $12, $12, $50, $35, $1b, $12, $81, $0d, $16, $81, $16, $14, $12, $14, $0f, $85, $00, $81, $14
	.byte $81, $14, $14, $14, $12, $14, $81, $14, $83, $12, $0f, $00, $83, $12, $81, $14, $14, $14, $14, $14, $81, $12, $81
	.byte $41, $18
	.word @song4ref4
	.byte $4e, $01
	.byte $41, $09
	.word @song4ref8
	.byte $20, $1e, $81, $00, $81
	.byte $41, $0c
	.word @song4ref23
	.byte $7f, $4e, $00, $8b, $ae, $12, $14, $14, $81, $14, $12, $12, $14, $14, $81, $00, $89, $12, $14, $14, $81, $14, $12, $14
	.byte $81, $14, $81, $81, $12, $0f, $00, $83, $12, $14, $14, $14, $14, $12, $16, $83, $14, $14, $81, $00, $83, $12, $12, $14
	.byte $14, $14, $14, $14, $16, $81, $19, $81, $87, $16, $14, $81, $00, $85
	.byte $41, $1b
	.word @song4ref358
	.byte $85, $16, $51, $fe, $60, $14, $8b, $7f, $00, $81, $14, $83, $14, $83, $14, $83, $12, $83, $0f, $81, $14, $81, $14, $83
	.byte $14, $83, $14, $81, $14, $83, $12, $85, $00, $83, $16, $81, $16, $81, $17, $16, $81, $14, $81, $12, $81, $14, $87, $0f
	.byte $83, $00, $93, $17, $17, $17, $17
	.byte $41, $18
	.word @song4ref434
	.byte $41, $0d
	.word @song4ref430
	.byte $81, $0f, $0f
	.byte $41, $0b
	.word @song4ref444
	.byte $41, $11
	.word @song4ref467
	.byte $14
	.byte $41, $2c
	.word @song4ref485
	.byte $41, $18
	.word @song4ref4
	.byte $4e, $01
	.byte $41, $09
	.word @song4ref8
	.byte $20, $1e, $81, $00, $81
	.byte $41, $0c
	.word @song4ref23
	.byte $4e, $01
	.byte $41, $18
	.word @song4ref8
	.byte $4e, $01
	.byte $41, $09
	.word @song4ref8
	.byte $85, $51, $ff, $00, $1d, $9f, $81, $00, $9d, $44, $00
@song4ch2:
	.byte $9f, $88
@song4ref727:
	.byte $14, $89, $1b, $91, $12, $89, $19, $91
	.byte $41, $08
	.word @song4ref727
@song4ref738:
	.byte $17, $9d, $1b, $8d, $19, $8d, $17, $9d, $1b, $8d, $19, $8d
	.byte $41, $0b
	.word @song4ref738
	.byte $85, $00, $85
@song4ref756:
	.byte $14, $89, $1b, $91, $19, $89, $17, $91
	.byte $41, $08
	.word @song4ref756
	.byte $41, $08
	.word @song4ref756
@song4ref770:
	.byte $14, $9d, $17, $89, $19, $81, $00, $8d
	.byte $41, $08
	.word @song4ref727
	.byte $41, $08
	.word @song4ref756
	.byte $41, $08
	.word @song4ref727
	.byte $41, $08
	.word @song4ref727
	.byte $41, $0c
	.word @song4ref738
	.byte $b4, $0b, $9d, $0f, $8d, $0d, $8d, $0b, $9d, $0f, $8d, $0d, $81, $00, $89, $88
	.byte $41, $08
	.word @song4ref756
	.byte $41, $08
	.word @song4ref756
	.byte $41, $08
	.word @song4ref756
	.byte $41, $08
	.word @song4ref770
	.byte $41, $08
	.word @song4ref727
	.byte $41, $08
	.word @song4ref756
	.byte $41, $08
	.word @song4ref727
	.byte $17, $89, $1b, $8d, $19, $a1, $0d, $9d, $44, $00
@song4ch3:
	.byte $7c, $82, $1e, $85, $1e, $85, $1e, $85, $1e, $85, $77
@song4ref852:
	.byte $20, $00, $83, $25, $00, $87, $20, $00, $25, $00, $83
	.byte $41, $0b
	.word @song4ref852
	.byte $41, $0b
	.word @song4ref852
	.byte $41, $0b
	.word @song4ref852
@song4ref872:
	.byte $20, $00, $9b, $20, $00, $8b, $20, $00, $8b
	.byte $41, $09
	.word @song4ref872
	.byte $41, $09
	.word @song4ref872
	.byte $41, $09
	.word @song4ref872
@song4ref890:
	.byte $7a
@song4ref891:
	.byte $20, $00, $83, $84, $2d, $00, $83, $82, $20, $00, $83, $84, $2d, $00, $83, $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $08
	.word @song4ref891
	.byte $8b
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $77, $82
@song4ref984:
	.byte $20, $00, $83, $25, $00, $83, $20, $00, $83, $25, $00, $83
	.byte $41, $0c
	.word @song4ref984
	.byte $41, $0c
	.word @song4ref984
	.byte $41, $09
	.word @song4ref984
	.byte $1e, $00, $83
	.byte $41, $0c
	.word @song4ref890
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $08
	.word @song4ref891
	.byte $8b
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82
	.byte $41, $0c
	.word @song4ref891
	.byte $82, $20, $85, $20, $85, $20, $85, $20, $85, $44, $00
@song4ch4:
	.byte $9f, $bf, $bf, $bf, $bf, $bf, $bf
@song4ref1090:
	.byte $1d, $00
@song4ref1092:
	.byte $83, $32, $00, $83, $1d, $00, $83, $32, $00, $83
	.byte $41, $0c
	.word @song4ref1090
	.byte $41, $0c
	.word @song4ref1090
	.byte $41, $0c
	.word @song4ref1090
	.byte $41, $0c
	.word @song4ref1090
	.byte $41, $0c
	.word @song4ref1090
	.byte $41, $0c
	.word @song4ref1090
	.byte $41, $08
	.word @song4ref1090
@song4ref1123:
	.byte $8b
@song4ref1124:
	.byte $1d, $00, $13, $81, $32, $00, $13, $81
@song4ref1132:
	.byte $1d, $00, $18, $81, $32, $00, $18, $81, $1d, $00, $12, $81, $32, $00, $12, $81, $1d, $00, $11, $81, $32, $00, $11, $81
	.byte $41, $12
	.word @song4ref1124
@song4ref1159:
	.byte $11, $81, $32, $00, $11, $81
@song4ref1165:
	.byte $1d, $00, $16, $81, $32, $00, $16, $81
	.byte $41, $20
	.word @song4ref1124
	.byte $41, $20
	.word @song4ref1124
	.byte $41, $08
	.word @song4ref1165
	.byte $41, $08
	.word @song4ref1165
	.byte $41, $0a
	.word @song4ref1132
	.byte $41, $0e
	.word @song4ref1159
	.byte $41, $08
	.word @song4ref1165
	.byte $41, $0a
	.word @song4ref1132
	.byte $11, $81, $32, $00, $11
@song4ref1202:
	.byte $81, $1d, $81, $00, $81, $1d, $81, $00
	.byte $41, $08
	.word @song4ref1202
	.byte $41, $08
	.word @song4ref1202
	.byte $41, $08
	.word @song4ref1202
	.byte $41, $08
	.word @song4ref1202
	.byte $41, $08
	.word @song4ref1202
	.byte $41, $08
	.word @song4ref1202
	.byte $81, $1d, $81, $00, $89
	.byte $41, $12
	.word @song4ref1124
	.byte $41, $0e
	.word @song4ref1159
	.byte $41, $12
	.word @song4ref1124
	.byte $41, $0e
	.word @song4ref1159
	.byte $41, $12
	.word @song4ref1124
	.byte $41, $0e
	.word @song4ref1159
	.byte $41, $08
	.word @song4ref1165
	.byte $41, $08
	.word @song4ref1165
	.byte $1d, $00, $16, $81, $32, $00, $11, $81, $1d, $00
	.byte $41, $21
	.word @song4ref1123
	.byte $41, $12
	.word @song4ref1124
	.byte $41, $0e
	.word @song4ref1159
	.byte $41, $20
	.word @song4ref1124
	.byte $41, $08
	.word @song4ref1165
	.byte $41, $0a
	.word @song4ref1132
	.byte $41, $0a
	.word @song4ref1092
	.byte $1d, $00, $83, $1d, $00, $83, $1d, $00, $83, $1d, $00, $83, $44, $00
