// Generated by export.py using data in metadata.json

#if !__VS_SYSTEM

const char musicSoundTestString00[ 8] = "SCHEMING";
const char musicSoundTestString01[13] = "8$BIT$AGAINST";
const char musicSoundTestString02[ 8] = "DANCE$OF";
const char musicSoundTestString03[10] = "DRIVING$BY";
const char musicSoundTestString04[ 6] = "GLITCH";
const char musicSoundTestString05[ 8] = "INFINITE";
const char musicSoundTestString06[ 6] = "SELECT";
const char musicSoundTestString07[ 5] = "SLASH";
const char musicSoundTestString08[ 7] = "STEREO$";
const char musicSoundTestString09[ 6] = "SUBTLE";
const char musicSoundTestString0A[ 8] = "ULTIMATE";
const char musicSoundTestString0B[ 7] = "WHATS$A";
const char musicSoundTestString0C[ 4] = "MENU";
const char musicSoundTestString0D[ 8] = "CLUBSTEP";
const char musicSoundTestString0E[ 8] = "PRACTICE";
const char musicSoundTestString0F[ 6] = "WEASEL";
const char musicSoundTestString10[14] = "THE$ODDS$REDUX";
const char musicSoundTestString11[13] = "CHAOZ$FANTASY";
const char musicSoundTestString12[12] = "CHAOZ$IMPACT";
const char musicSoundTestString13[ 9] = "CHECK$OUT";
const char musicSoundTestString14[13] = "CLUTTERFUNK$2";
const char musicSoundTestString15[ 9] = "CRYOGENIC";
const char musicSoundTestString16[11] = "THE$VIOLINS";
const char musicSoundTestString17[10] = "DEATH$MOON";
const char musicSoundTestString18[ 5] = "NIGHT";
const char musicSoundTestString19[ 7] = "ENDGAME";
const char musicSoundTestString1A[12] = "FACTORY$TIME";
const char musicSoundTestString1B[ 7] = "FANTASY";
const char musicSoundTestString1C[ 9] = "FIRE$AURA";
const char musicSoundTestString1D[ 7] = "GREMLIN";
const char musicSoundTestString1E[12] = "INFILTRATION";
const char musicSoundTestString1F[ 5] = "POWER";
const char musicSoundTestString20[ 8] = "KESOBOMB";
const char musicSoundTestString21[11] = "MAGIC$TOUCH";
const char musicSoundTestString22[ 8] = "MELTDOWN";
const char musicSoundTestString23[ 9] = "MEOWSTUFF";
const char musicSoundTestString24[ 5] = "NINOX";
const char musicSoundTestString25[10] = "POWER$TRIP";
const char musicSoundTestString26[10] = "PYROPHORIC";
const char musicSoundTestString27[13] = "RAINING$TACOS";
const char musicSoundTestString28[12] = "PAYMENT$TYPE";
const char musicSoundTestString29[ 7] = "INFERNO";
const char musicSoundTestString2A[ 4] = "SNOW";
const char musicSoundTestString2B[ 9] = "MADNESS$2";
const char musicSoundTestString2C[ 8] = "ODDITIES";
const char musicSoundTestString2D[10] = "TINY$TUNES";
const char musicSoundTestString2E[11] = "DESTRUCTION";
const char musicSoundTestString2F[11] = "FUTURE$FUNK";
const char musicSoundTestString30[11] = "XENOGENESIS";
const char musicSoundTestString31[ 7] = "MUDSTEP";
const char musicSoundTestString32[ 7] = "DJ$NATE";
const char musicSoundTestString33[12] = "OCULARNEBULA";
const char musicSoundTestString34[13] = "KEVIN$MACLEOD";
const char musicSoundTestString35[11] = "ELITEFERREX";
const char musicSoundTestString36[ 9] = "PARAGONX9";
const char musicSoundTestString37[12] = "MADHOUSEDUDE";
const char musicSoundTestString38[10] = "WATERFLAME";
const char musicSoundTestString39[10] = "NERDBOY628";
const char musicSoundTestString3A[ 4] = "F777";
const char musicSoundTestString3B[11] = "SOUNDHOLICK";
const char musicSoundTestString3C[ 8] = "REINNBOW";
const char musicSoundTestString3D[ 7] = "VISAGER";
const char musicSoundTestString3E[10] = "CLOUDFIELD";
const char musicSoundTestString3F[ 8] = "KID2WILL";
const char musicSoundTestString40[ 9] = "BOSSFIGHT";
const char musicSoundTestString41[ 9] = "THEFATRAT";
const char musicSoundTestString42[ 9] = "RYMDKRAFT";
const char musicSoundTestString43[ 5] = "ROMOS";
const char musicSoundTestString44[11] = "MASTERSWORD";
const char musicSoundTestString45[ 7] = "DAVINCE";
const char musicSoundTestString46[ 8] = "MEGANEKO";
const char musicSoundTestString47[10] = "BOOM$KITTY";
const char musicSoundTestString48[11] = "PARRY$GRIPP";
const char musicSoundTestString49[13] = "CRAFTY$JUMPER";
const char musicSoundTestString4A[11] = "WF$TEM$BKIT";
const char musicSoundTestString4B[12] = "FOREVERBOUND";
const char musicSoundTestString4C[11] = "LEMON$DEMON";
const char musicSoundTestString4D[ 9] = "FANTOMENK";
const char musicSoundTestString4E[ 5] = "TMM43";
const char musicSoundTestString4F[ 8] = "LEMKUUJA";


const char* const xbgmtextsUpper[] = {
	NULL,
	NULL,
	NULL,
	musicSoundTestString00,
	musicSoundTestString01,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	musicSoundTestString02,
	NULL,
	musicSoundTestString03,
	NULL,
	NULL,
	NULL,
	NULL,
	musicSoundTestString04,
	NULL,
	musicSoundTestString05,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	musicSoundTestString06,
	musicSoundTestString07,
	NULL,
	musicSoundTestString08,
	musicSoundTestString09,
	NULL,
	musicSoundTestString0A,
	musicSoundTestString0B,
	NULL,
};

const uint8_t xbgmtextsUpperSize[] = {
	0,
	0,
	0,
	sizeof(musicSoundTestString00),
	sizeof(musicSoundTestString01),
	0,
	0,
	0,
	0,
	0,
	sizeof(musicSoundTestString02),
	0,
	sizeof(musicSoundTestString03),
	0,
	0,
	0,
	0,
	sizeof(musicSoundTestString04),
	0,
	sizeof(musicSoundTestString05),
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	sizeof(musicSoundTestString06),
	sizeof(musicSoundTestString07),
	0,
	sizeof(musicSoundTestString08),
	sizeof(musicSoundTestString09),
	0,
	sizeof(musicSoundTestString0A),
	sizeof(musicSoundTestString0B),
	0,
};


const char* const xbgmtextsLower[] = {
	musicSoundTestString0C,
	musicSoundTestString0D,
	musicSoundTestString0E,
	musicSoundTestString0F,
	musicSoundTestString10,
	musicSoundTestString11,
	musicSoundTestString12,
	musicSoundTestString13,
	musicSoundTestString14,
	musicSoundTestString15,
	musicSoundTestString16,
	musicSoundTestString17,
	musicSoundTestString18,
	musicSoundTestString19,
	musicSoundTestString1A,
	musicSoundTestString1B,
	musicSoundTestString1C,
	musicSoundTestString1D,
	musicSoundTestString1E,
	musicSoundTestString1F,
	musicSoundTestString20,
	musicSoundTestString21,
	musicSoundTestString22,
	musicSoundTestString23,
	musicSoundTestString24,
	musicSoundTestString25,
	musicSoundTestString26,
	musicSoundTestString27,
	musicSoundTestString28,
	musicSoundTestString29,
	musicSoundTestString2A,
	musicSoundTestString2B,
	musicSoundTestString2C,
	musicSoundTestString2D,
	musicSoundTestString2E,
	musicSoundTestString2F,
	musicSoundTestString30,
};

const uint8_t xbgmtextsLowerSize[] = {
	sizeof(musicSoundTestString0C),
	sizeof(musicSoundTestString0D),
	sizeof(musicSoundTestString0E),
	sizeof(musicSoundTestString0F),
	sizeof(musicSoundTestString10),
	sizeof(musicSoundTestString11),
	sizeof(musicSoundTestString12),
	sizeof(musicSoundTestString13),
	sizeof(musicSoundTestString14),
	sizeof(musicSoundTestString15),
	sizeof(musicSoundTestString16),
	sizeof(musicSoundTestString17),
	sizeof(musicSoundTestString18),
	sizeof(musicSoundTestString19),
	sizeof(musicSoundTestString1A),
	sizeof(musicSoundTestString1B),
	sizeof(musicSoundTestString1C),
	sizeof(musicSoundTestString1D),
	sizeof(musicSoundTestString1E),
	sizeof(musicSoundTestString1F),
	sizeof(musicSoundTestString20),
	sizeof(musicSoundTestString21),
	sizeof(musicSoundTestString22),
	sizeof(musicSoundTestString23),
	sizeof(musicSoundTestString24),
	sizeof(musicSoundTestString25),
	sizeof(musicSoundTestString26),
	sizeof(musicSoundTestString27),
	sizeof(musicSoundTestString28),
	sizeof(musicSoundTestString29),
	sizeof(musicSoundTestString2A),
	sizeof(musicSoundTestString2B),
	sizeof(musicSoundTestString2C),
	sizeof(musicSoundTestString2D),
	sizeof(musicSoundTestString2E),
	sizeof(musicSoundTestString2F),
	sizeof(musicSoundTestString30),
};


const char* const xbgmtextsOriginalArtist[] = {
	musicSoundTestString31,
	musicSoundTestString32,
	musicSoundTestString33,
	musicSoundTestString34,
	musicSoundTestString35,
	musicSoundTestString36,
	musicSoundTestString36,
	musicSoundTestString37,
	musicSoundTestString38,
	musicSoundTestString39,
	musicSoundTestString3A,
	musicSoundTestString3B,
	musicSoundTestString3C,
	musicSoundTestString38,
	musicSoundTestString3D,
	musicSoundTestString3E,
	musicSoundTestString3F,
	musicSoundTestString40,
	musicSoundTestString36,
	musicSoundTestString41,
	musicSoundTestString42,
	musicSoundTestString43,
	musicSoundTestString44,
	musicSoundTestString45,
	musicSoundTestString46,
	musicSoundTestString47,
	musicSoundTestString39,
	musicSoundTestString48,
	musicSoundTestString49,
	musicSoundTestString4A,
	musicSoundTestString38,
	musicSoundTestString4B,
	musicSoundTestString4C,
	musicSoundTestString4D,
	musicSoundTestString4E,
	musicSoundTestString4F,
	musicSoundTestString41,
};

const uint8_t xbgmtextsOriginalArtistSize[] = {
	sizeof(musicSoundTestString31),
	sizeof(musicSoundTestString32),
	sizeof(musicSoundTestString33),
	sizeof(musicSoundTestString34),
	sizeof(musicSoundTestString35),
	sizeof(musicSoundTestString36),
	sizeof(musicSoundTestString36),
	sizeof(musicSoundTestString37),
	sizeof(musicSoundTestString38),
	sizeof(musicSoundTestString39),
	sizeof(musicSoundTestString3A),
	sizeof(musicSoundTestString3B),
	sizeof(musicSoundTestString3C),
	sizeof(musicSoundTestString38),
	sizeof(musicSoundTestString3D),
	sizeof(musicSoundTestString3E),
	sizeof(musicSoundTestString3F),
	sizeof(musicSoundTestString40),
	sizeof(musicSoundTestString36),
	sizeof(musicSoundTestString41),
	sizeof(musicSoundTestString42),
	sizeof(musicSoundTestString43),
	sizeof(musicSoundTestString44),
	sizeof(musicSoundTestString45),
	sizeof(musicSoundTestString46),
	sizeof(musicSoundTestString47),
	sizeof(musicSoundTestString39),
	sizeof(musicSoundTestString48),
	sizeof(musicSoundTestString49),
	sizeof(musicSoundTestString4A),
	sizeof(musicSoundTestString38),
	sizeof(musicSoundTestString4B),
	sizeof(musicSoundTestString4C),
	sizeof(musicSoundTestString4D),
	sizeof(musicSoundTestString4E),
	sizeof(musicSoundTestString4F),
	sizeof(musicSoundTestString41),
};


#else

const char* const xbgmtextsUpper[] = {};
const uint8_t xbgmtextsUpperSize[] = {};
const char* const xbgmtextsLower[] = {};
const uint8_t xbgmtextsLowerSize[] = {};
const char* const xbgmtextsOriginalArtist[] = {};
const uint8_t xbgmtextsOriginalArtistSize[] = {};

#endif



CODE_BANK_PUSH("RODATA")

#if !__VS_SYSTEM

const uint8_t xbgmlookuptable[] = {
	song_menu_theme_22,
	song_clubstep,
	song_practice,
	song_scheming_weasel,
	song_against_the_odds_redux,
	song_chaoz_fantasy_extended,
	song_speed_racer,
	song_check_out,
	song_clutterfunk_2,
	song_cryogenic,
	song_dance_of_the_violins,
	song_death_moon,
	song_driving_by_night,
	song_endgame,
	song_factory_time,
	song_fantasy,
	song_fire_aura,
	song_glitch_gremlin,
	song_infiltration,
	song_infinite_power,
	song_kesobomb,
	song_magic_touch,
	song_meltdown,
	song_meowstuff,
	song_ninox,
	song_power_trip,
	song_pyrophoric_legacy_remix,
	song_raining_tacos,
	song_select_payment_type,
	song_slash_inferno,
	song_snow,
	song_stereo_madness_2,
	song_subtle_oddities,
	song_tiny_tunes,
	song_ultimatedestruction,
	song_whats_a_future_funk,
	song_xenogenesis,
};

#else

const uint8_t xbgmlookuptable[] = {
	song_endgame,
};

#endif

CODE_BANK_POP()
