#define song_chaoz_fantasy_extended 0
#define song_subtle_oddities 1
#define song_whats_a_future_funk 2
#define song_sonic_blaster 3
#define song_magic_touch 4
#define song_check_out 5
#define song_menu_theme_22 6
#define song_clutterfunk_2 7
#define song_holography 8
#define song_practice 9
#define song_death_moon 10
#define song_clubstep 11
#define song_stalemate 12
#define song_driving_by_night 13
#define song_endorphins 14
#define song_glitch_gremlin 15
#define song_eighto 16
#define song_power_trip 17
#define song_cycles 18
#define song_stereo_madness_2 19
#define song_pyrophoric 20
#define song_kesobomb 21
#define song_hell 22
#define song_meowstuff 23
#define song_stereo_madness 24
#define song_ninox 25
#define song_lost 26
#define song_dance_of_the_violins 27
#define song_tiny_tunes 28
#define song_cant_let_go 29
#define song_scheming_weasel 30
#define song_speed_racer 31
#define song_max 32