; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Project uses release notes, you must set FAMISTUDIO_USE_RELEASE_NOTES = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Volume slides are used, you must set FAMISTUDIO_USE_VOLUME_SLIDES = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Slide notes are used on the noise channel, you must set FAMISTUDIO_USE_NOISE_SLIDE_NOTES = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Arpeggios are used, you must set FAMISTUDIO_USE_ARPEGGIO = 1.
; Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.
; DPCM Delta Counter effect is used, you must set FAMISTUDIO_USE_DELTA_COUNTER = 1.
; Phase Reset effect is used, you must set FAMISTUDIO_USE_PHASE_RESET = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_famidash_music8=music_data_famidash_music8
.endif

music_data_famidash_music8:
	.byte 6
	.word @instruments
	.word @samples-5
; 00 : Meowstuff
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256
; 01 : Stereo Madness
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word 327,273
; The DPCM aligner used to be here
; 03 : Ninox
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word 251,209
; 04 : Hell
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.word 348,290
; 05 : Menu Theme (2.2)
	.word @song5ch0
	.word @song5ch1
	.word @song5ch2
	.word @song5ch3
	.word @song5ch4
	.word 262,218
; 06 : Tiny Tunes
	.word @song6ch0
	.word @song6ch1
	.word @song6ch2
	.word @song6ch3
	.word @song6ch4
	.word 274,228

.export music_data_famidash_music8
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env8,@env6,@env41,@env0 ; 00 : hat
	.word @env20,@env26,@env2,@env0 ; 01 : snare
	.word @env9,@env42,@env28,@env0 ; 02 : kick
	.word @env1,@env23,@env28,@env0 ; 03 : echo
	.word @env49,@env23,@env28,@env0 ; 04 : blank instant decay
	.word @env17,@env23,@env28,@env0 ; 05 : blank
	.word @env25,@env23,@env28,@env0 ; 06 : clap no app
	.word @env3,@env23,@env30,@env0 ; 07 : sample
	.word @env44,@env6,@env2,@env0 ; 08 : cymbal
	.word @env39,@env23,@env28,@env0 ; 09 : triangle pluck 4
	.word @env25,@env29,@env28,@env0 ; 0a : clap
	.word @env13,@env23,@env4,@env0 ; 0b : endgame lead
	.word @env24,@env23,@env28,@env0 ; 0c : infernoplex_piano
	.word @env22,@env23,@env28,@env0 ; 0d : blank string
	.word @env14,@env23,@env28,@env12 ; 0e : I don't know what to name this
	.word @env47,@env23,@env28,@env0 ; 0f : menu acc
	.word @env14,@env23,@env28,@env0 ; 10 : DMC: drums + bass
	.word @env37,@env23,@env28,@env38 ; 11 : jaezu lead
	.word @env34,@env23,@env28,@env0 ; 12 : Instrument 1
	.word @env50,@env23,@env28,@env0 ; 13 : blank slower string
	.word @env45,@env23,@env32,@env0 ; 14 : shift string
	.word @env36,@env48,@env30,@env0 ; 15 : octave arp
	.word @env51,@env23,@env35,@env0 ; 16 : death moon lead
	.word @env14,@env23,@env28,@env31 ; 17 : Extreme pitch up
	.word @env18,@env23,@env27,@env15 ; 18 : Kap lead
	.word @env21,@env23,@env28,@env0 ; 19 : triangle pluck 3
	.word @env19,@env6,@env28,@env0 ; 1a : rel hats

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cb,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$13
@env2:
	.byte $c1,$c0,$00,$01
@env3:
	.byte $00,$c9,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$00,$08
@env4:
	.byte $c2,$c2,$c0,$00,$00
@env5:
	.byte $00,$c0,$bd,$bb,$ba,$ba,$bc,$bf,$c1,$c4,$c6,$c6,$c5,$c3,$00,$01
@env6:
	.byte $bd,$c0,$00,$01
@env7:
	.byte $00,$c0,$b9,$b5,$b6,$bc,$c4,$ca,$cb,$c7,$00,$01
@env8:
	.byte $00,$c8,$c4,$c2,$c0,$00,$04
@env9:
	.byte $00,$cd,$c9,$c5,$c2,$c1,$c0,$00,$06
@env10:
	.byte $c0,$c4,$c7,$00,$00
@env11:
	.byte $c0,$c4,$c0,$00,$00
@env12:
	.byte $00,$c3,$cb,$cf,$d5,$c0,$c3,$ca,$cd,$d4,$c0,$c4,$c8,$cf,$d6,$dd,$e3,$e6,$e7,$e8,$ea,$eb,$ed,$ee,$f0,$f2,$f6,$fa,$fd,$ff,$00,$1d
@env13:
	.byte $00,$cf,$cd,$cb,$c7,$c7,$ca,$00,$06
@env14:
	.byte $00,$cf,$7f,$00,$02
@env15:
	.byte $00,$c0,$03,$c0,$c0,$c1,$c0,$02,$bf,$c0,$c0,$c0,$00,$03
@env16:
	.byte $00,$c0,$02,$bf,$05,$be,$0e,$bf,$05,$c0,$04,$c1,$05,$c2,$0e,$c1,$05,$c0,$c0,$00,$01
@env17:
	.byte $04,$cf,$00,$01,$ca,$c6,$c4,$c2,$c0,$00,$08
@env18:
	.byte $00,$ca,$7f,$00,$02
@env19:
	.byte $00,$c8,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$0d
@env20:
	.byte $00,$cd,$cb,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env21:
	.byte $00,$cf,$02,$c0,$00,$03
@env22:
	.byte $08,$c5,$c6,$c7,$08,$c6,$00,$05,$c6,$c6,$c5,$02,$c4,$02,$c3,$02,$c2,$02,$c1,$c1,$c0,$00,$14
@env23:
	.byte $c0,$7f,$00,$01
@env24:
	.byte $00,$ce,$02,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$c9,$c9,$c8,$c7,$c6,$c5,$c3,$00,$10
@env25:
	.byte $00,$cf,$ca,$cc,$ca,$c9,$c8,$c6,$c5,$c4,$c2,$c1,$c0,$00,$0c
@env26:
	.byte $c6,$cc,$00,$01
@env27:
	.byte $c0,$c1,$c2,$00,$02
@env28:
	.byte $7f,$00,$00
@env29:
	.byte $bc,$c1,$c0,$00,$02
@env30:
	.byte $c2,$7f,$00,$00
@env31:
	.byte $00,$c0,$03,$bf,$04,$be,$07,$bd,$07,$bc,$09,$bb,$06,$ba,$05,$b9,$02,$b8,$04,$b7,$03,$b6,$05,$b5,$04,$b4,$08,$b3,$05,$b2,$06,$b1,$05,$b0,$05,$af,$06,$ae,$05,$ad,$05,$ac,$09,$ab,$05,$aa,$07,$a9,$08,$a8,$07,$a7,$06,$a6,$0e,$a5,$09,$a4,$11,$a3,$06,$a2,$17,$a1,$04,$a0,$00,$41
@env32:
	.byte $c1,$c2,$c1,$c0,$00,$00
@env33:
	.byte $00,$c0,$c0,$bf,$06,$c0,$03,$c1,$06,$c0,$00,$01
@env34:
	.byte $00,$c3,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$0d
@env35:
	.byte $c1,$7f,$00,$00
@env36:
	.byte $00,$c9,$c7,$c5,$00,$03
@env37:
	.byte $0d,$c6,$c8,$ca,$cc,$03,$cb,$03,$ca,$03,$c9,$00,$0a,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$1c
@env38:
	.byte $00,$c0,$07,$c0,$c1,$c2,$c3,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$00,$03
@env39:
	.byte $00,$cf,$03,$c0,$00,$03
@env40:
	.byte $c0,$c0,$cc,$00,$00
@env41:
	.byte $c0,$c1,$00,$00
@env42:
	.byte $c9,$cf,$00,$01
@env43:
	.byte $c0,$c0,$c3,$00,$00
@env44:
	.byte $18,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c7,$c6,$02,$c5,$c5,$c4,$02,$c3,$03,$c2,$c2,$00,$15,$c2,$c2,$c1,$03,$c0,$00,$1c
@env45:
	.byte $08,$c4,$c5,$c6,$08,$c5,$00,$05,$c5,$04,$c4,$07,$c3,$05,$c2,$02,$c1,$02,$c0,$00,$12
@env46:
	.byte $c0,$c3,$c7,$00,$00
@env47:
	.byte $00,$c8,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$06,$c1,$07,$c0,$00,$10
@env48:
	.byte $c0,$c0,$cc,$cc,$00,$00
@env49:
	.byte $00,$cf,$cf,$cb,$c8,$c5,$c3,$c2,$c1,$c0,$00,$09
@env50:
	.byte $0c,$c2,$c3,$c4,$c5,$c6,$c6,$c7,$04,$c6,$00,$09,$c6,$c6,$c5,$02,$c4,$02,$c3,$02,$c2,$02,$c1,$c1,$c0,$00,$18
@env51:
	.byte $00,$cf,$ca,$c9,$c8,$c7,$c6,$c6,$c5,$00,$08

@samples:
	.byte $11+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 00 fdbass A# (Pitch:15)
	.byte $23+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$00 ; 01 fdbass B (Pitch:15)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$07,$40,$00 ; 02 fdbass C (Pitch:7)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$09,$40,$00 ; 03 fdbass C (Pitch:9)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0a,$40,$00 ; 04 fdbass C (Pitch:10)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0c,$40,$00 ; 05 fdbass C (Pitch:12)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 06 fdbass C (Pitch:15)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$05,$40,$00 ; 07 fdbass C# (Pitch:5)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$08,$40,$00 ; 08 fdbass C# (Pitch:8)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$09,$40,$00 ; 09 fdbass C# (Pitch:9)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0a,$40,$00 ; 0a fdbass C# (Pitch:10)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0b,$40,$00 ; 0b fdbass C# (Pitch:11)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0e,$40,$00 ; 0c fdbass C# (Pitch:14)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 0d fdbass C# (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$07,$40,$00 ; 0e fdbass D (Pitch:7)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0a,$40,$00 ; 0f fdbass D (Pitch:10)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0b,$40,$00 ; 10 fdbass D (Pitch:11)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0c,$40,$00 ; 11 fdbass D (Pitch:12)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0f,$40,$00 ; 12 fdbass D (Pitch:15)
	.byte $6b+.lobyte(FAMISTUDIO_DPCM_PTR),$2b,$0e,$40,$00 ; 13 fdkick (Pitch:14)
	.byte $7e+.lobyte(FAMISTUDIO_DPCM_PTR),$78,$0f,$40,$02 ; 14 hi (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$41,$0f,$34,$00 ; 15 snare (Pitch:15)

@song0ch0:
	.byte $46, $03, $a2, $2b, $85, $2c, $85, $2e, $85, $45, $85, $27, $85, $45, $85, $2c, $85, $45, $85, $00, $ed, $86
@song0ref23:
	.byte $2c, $85, $38, $89, $38, $89, $36, $89, $36, $89, $36, $8d, $35, $89, $35, $89, $34, $89, $34, $89, $36, $85, $2c, $85
	.byte $38, $89, $38, $89, $36, $89, $36, $89, $36, $85, $36, $89, $36, $89, $38, $a5
	.byte $41, $27
	.word @song0ref23
	.byte $8d, $79, $a2, $27, $85, $2e, $85, $2b, $85, $2c, $85, $2e, $85, $30, $85, $31, $85, $33, $85, $45, $85, $2c, $85, $45
	.byte $85, $29, $85, $45, $85, $2b, $85, $2c, $85, $2b, $85, $2e, $85, $27, $85, $45, $85, $24, $85, $27, $85, $2c, $85, $2e
	.byte $85, $30, $85, $45, $85, $2c, $85, $45, $85, $29, $85, $45, $85, $2b, $85, $2c, $85, $2e, $85, $33, $85, $27, $85, $45
	.byte $85, $2c, $85, $28, $85, $27, $85, $25, $85, $24, $85, $27, $85, $2c, $85, $2e, $85, $30, $85, $45, $85, $30, $85, $2e
	.byte $85, $2c, $85, $45, $85, $27, $85, $25, $85, $24, $85, $27, $85, $2c, $85, $27, $85, $2b, $85, $29, $85, $27, $85, $30
	.byte $85, $2e, $85, $2c, $85
@song0ref191:
	.byte $2e, $85, $30, $85, $33, $85, $30, $85, $2e, $85, $30, $85, $2c, $85, $45, $85, $00, $ed, $ff, $ff, $ff, $86, $38, $85
	.byte $38, $89, $38, $89, $3c, $89, $3c, $89, $3c, $85, $3d, $85, $3d, $89, $3d, $89, $3f, $89, $3f, $89, $a2
@song0ref236:
	.byte $2c, $81, $2e, $81, $30, $85, $2c, $85, $27, $85, $45, $85, $00, $85, $25, $85, $24, $85, $25, $85, $27, $85, $2c, $85
	.byte $20, $85, $45, $85, $00, $95, $20, $81, $22, $81, $24, $85, $20, $85, $27, $85, $45, $85, $00, $85, $27, $85, $27, $85
	.byte $25, $85, $27, $85, $45, $85, $00, $a5
	.byte $41, $18
	.word @song0ref236
	.byte $41, $14
	.word @song0ref191
	.byte $44, $00
@song0ch1:
	.byte $79, $a2, $1d, $85, $45, $85, $1b, $8d, $45, $8d, $20, $8d, $45, $8d, $00, $dd, $86
@song0ref318:
	.byte $27, $85, $30, $89, $30, $89, $2e, $89, $2e, $89, $2e, $8d, $2c, $89, $2c, $89, $2e, $89, $2e, $89, $30, $85, $27, $85
	.byte $30, $89, $30, $89, $2e, $89, $2e, $89, $2e, $85, $2e, $89, $2e, $89, $30, $a5
	.byte $41, $28
	.word @song0ref318
	.byte $7f
	.byte $41, $14
	.word @song0ref23
	.byte $34, $85
	.byte $41, $14
	.word @song0ref23
	.byte $34, $85
	.byte $41, $14
	.word @song0ref23
	.byte $34, $85
	.byte $41, $14
	.word @song0ref23
	.byte $34, $85, $00, $fd, $ff, $ff, $ff, $78, $4f, $01, $a6, $24, $9d, $22, $9d, $25, $9d, $24, $9d, $24, $9d, $22, $9d, $25
	.byte $9d, $27, $9d, $4f, $01, $24, $9d, $22, $9d, $25, $9d, $24, $9d, $24, $9d, $22, $9d, $25, $9d, $27, $9d, $77, $8f, $76
	.byte $8f, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $70, $8f, $00, $fd, $ff, $44, $00
@song0ch2:
	.byte $af
@song0ref448:
	.byte $8a
@song0ref449:
	.byte $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85
	.byte $14, $85, $20, $85, $14, $85, $20, $85
@song0ref481:
	.byte $14, $85, $20, $83, $00, $81, $20, $83, $00, $81, $23, $85, $00, $81
@song0ref495:
	.byte $20, $85, $1e, $85, $20, $85
@song0ref501:
	.byte $0d, $85, $00, $81, $0d, $85, $00, $81, $0f, $85, $00, $81, $0f, $85, $00, $81, $8c, $0f, $85, $0f, $85, $8a, $14, $85
	.byte $20, $83, $00, $81, $20, $83, $00, $81, $23, $85, $00, $81, $25, $85, $23, $85, $20, $85, $1e, $85, $00, $81, $1e, $85
	.byte $00, $81, $20, $85, $00, $9d
	.byte $41, $48
	.word @song0ref481
	.byte $41, $3c
	.word @song0ref481
	.byte $41, $22
	.word @song0ref501
	.byte $41, $2e
	.word @song0ref495
	.byte $41, $14
	.word @song0ref501
	.byte $00, $fd, $ff, $ff, $bf
	.byte $41, $20
	.word @song0ref448
	.byte $19, $85, $25, $85, $19, $85, $25, $85, $1b, $85, $27, $85
@song0ref590:
	.byte $1b, $85, $27
@song0ref593:
	.byte $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $19, $85, $25, $85, $19, $85, $25
	.byte $85, $1b, $85, $27, $85, $23, $85, $22
	.byte $41, $1d
	.word @song0ref593
	.byte $41, $23
	.word @song0ref590
	.byte $85, $00, $fd, $ff
	.byte $41, $20
	.word @song0ref449
	.byte $44, $00
@song0ch3:
	.byte $af, $74, $82
@song0ref644:
	.byte $1d, $81, $00, $81, $72, $20, $81, $00, $81, $74, $1d, $81, $00, $81, $72, $20, $81, $00, $81, $74, $1d, $81, $00, $81
	.byte $72, $20, $81, $00, $81, $74
	.byte $41, $18
	.word @song0ref644
	.byte $74, $1d, $81, $00, $81, $72, $20, $81, $00, $81, $76, $25, $00, $25, $00, $25, $00, $25
@song0ref695:
	.byte $00
@song0ref696:
	.byte $79, $90, $1e, $8d, $76, $80
@song0ref702:
	.byte $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $16
	.word @song0ref696
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $16
	.word @song0ref696
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $16
	.word @song0ref696
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $16
	.word @song0ref696
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $16
	.word @song0ref696
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $16
	.word @song0ref696
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $24, $00, $24, $00, $24, $00, $24
	.byte $41, $17
	.word @song0ref695
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $41, $14
	.word @song0ref702
	.byte $ff, $44, $00
@song0ch4:
	.byte $af, $ff
@song0ref894:
	.byte $14, $85, $00, $85, $16, $85, $14, $85, $00, $85, $14, $85, $16, $85, $00, $85, $14, $85, $00, $85, $16, $85, $00, $85
	.byte $14, $85, $00, $85, $16, $81, $16, $81, $16, $81, $16, $81
	.byte $41, $24
	.word @song0ref894
	.byte $41, $24
	.word @song0ref894
	.byte $41, $24
	.word @song0ref894
	.byte $41, $24
	.word @song0ref894
	.byte $41, $24
	.word @song0ref894
	.byte $41, $24
	.word @song0ref894
	.byte $41, $24
	.word @song0ref894
	.byte $41, $1d
	.word @song0ref894
	.byte $85, $16, $81, $16, $81
	.byte $41, $16
	.word @song0ref894
	.byte $14, $85, $16, $85, $14, $85, $16, $85, $16, $81, $16, $81
	.byte $41, $1d
	.word @song0ref894
	.byte $85, $16, $81, $16, $81
	.byte $41, $16
	.word @song0ref894
	.byte $14, $85, $16, $85, $14, $85, $16, $81, $16, $81, $16, $81, $16, $81
	.byte $41, $1d
	.word @song0ref894
	.byte $85, $16, $85
	.byte $41, $24
	.word @song0ref894
	.byte $41, $1d
	.word @song0ref894
	.byte $85, $16, $85
	.byte $41, $24
	.word @song0ref894
	.byte $41, $1d
	.word @song0ref894
	.byte $85, $16, $81, $16, $81
	.byte $41, $16
	.word @song0ref894
	.byte $14, $85, $16, $85, $14, $85, $16, $85, $16, $81, $16, $81, $00, $fd, $44, $00
@song1ch0:
	.byte $46, $06, $53, $4f, $00
@song1ref6:
	.byte $86
@song1ref7:
	.byte $25, $81, $2c, $81, $25, $81, $2c, $81, $25, $81, $2c, $81, $25, $81, $2c, $81, $20, $81, $27, $81, $20, $81, $27, $81
	.byte $20, $81, $27, $81, $20, $81, $27, $81, $4f, $01, $22, $81, $29, $81, $22, $81, $29, $81, $22, $81, $29, $81, $22, $81
	.byte $29, $81, $1e, $81, $25, $81, $1e, $81, $25, $81, $1e, $81, $25, $81, $1e, $81, $25, $81, $4f, $02
	.byte $41, $40
	.word @song1ref7
@song1ref78:
	.byte $4f, $01, $25, $00
@song1ref82:
	.byte $2c, $75, $25, $7f, $25, $75, $2c, $7f, $2c, $75, $25, $7f, $25, $75, $2c, $7f, $2c, $75, $25, $7f, $25, $75, $2c, $7f
	.byte $2c, $75, $25, $7f, $20, $75, $2c, $7f, $27, $75, $20, $7f, $20, $75, $27, $7f, $27, $75, $20, $7f, $20, $75, $27, $7f
	.byte $27, $75, $20, $7f, $20, $75, $27, $7f, $27, $75, $20, $7f, $22, $75, $27, $7f, $29, $75, $22, $7f, $22, $75, $29, $7f
	.byte $29, $75, $22, $7f, $22, $75, $29, $7f, $29, $75, $22, $7f, $22, $75, $29, $7f, $29, $75, $22, $7f, $1e, $75, $29, $7f
	.byte $25, $75, $1e, $7f, $1e, $75, $25, $7f, $25, $75, $1e, $7f, $1e, $75, $25, $7f, $25, $75, $1e, $7f, $1e, $75, $25, $7f
	.byte $25, $75, $1e, $7f, $4f, $01, $25, $75, $25, $7f
	.byte $41, $3e
	.word @song1ref82
	.byte $45, $9d, $7f
	.byte $41, $42
	.word @song1ref78
	.byte $7f
	.byte $41, $40
	.word @song1ref82
	.byte $7f
	.byte $41, $40
	.word @song1ref82
	.byte $7f
	.byte $41, $3e
	.word @song1ref82
	.byte $45, $fd, $ff, $76, $4f, $03, $a4
@song1ref240:
	.byte $31, $83, $31, $83, $31, $83, $31, $83, $31, $83, $31, $83, $30, $83, $30, $83, $30, $83, $30, $83, $30, $81, $31, $77
	.byte $83, $31, $83, $31, $83, $31, $83, $31, $83, $31, $81, $78, $81, $33, $83, $33, $83, $33, $83, $33, $83, $33, $81, $79
	.byte $31, $83, $31, $83, $31, $81, $7a, $81, $31, $83, $7b, $31, $83, $31, $83, $30, $81, $7c, $81, $30, $83, $30, $83, $30
	.byte $7d, $83, $30, $81, $31
@song1ref317:
	.byte $83, $31, $83, $31, $83, $31, $83, $31, $83, $31, $83, $33, $83, $33, $83, $33, $83, $35, $7e, $83, $35, $81, $7f, $4f
	.byte $03
	.byte $41, $17
	.word @song1ref240
	.byte $41, $11
	.word @song1ref317
	.byte $33, $83, $33, $81
	.byte $41, $17
	.word @song1ref240
	.byte $41, $12
	.word @song1ref317
	.byte $83, $35, $81, $45, $87, $44, $00
@song1ch1:
	.byte $78, $53, $4f, $03
	.byte $41, $14
	.word @song1ref6
	.byte $4f, $01, $20, $81, $27, $81, $20, $81, $27, $71, $20, $78, $20, $71, $27, $78, $27, $71, $20, $78, $22, $71, $27, $78
	.byte $29, $71, $22, $78, $22, $71, $29, $76, $29, $71, $22, $76, $22, $71, $29, $76, $29, $71, $22, $76, $22, $71, $8a, $29
	.byte $76, $86, $29, $71, $8a, $22, $76, $4f, $03, $86, $1e, $71, $8a, $29, $76, $86, $25, $71, $8a, $1e, $76, $86, $1e, $71
	.byte $8a, $25, $76, $86, $25, $71, $8a, $1e, $76, $86, $1e, $71, $8a, $25, $76, $86, $25, $71, $8a, $1e, $76, $86, $1e, $71
	.byte $8a, $25, $76, $86, $25, $71, $8a, $1e, $76, $86, $25, $71, $a0, $1e, $76, $86, $2c, $71, $8a, $25, $76, $86, $25, $71
	.byte $8a, $2c, $76, $86, $2c, $71, $8a, $25, $76, $86, $25, $71, $8a, $2c, $76, $86, $2c, $71, $8a, $25, $76, $86, $25, $71
	.byte $8a, $2c, $76, $86, $2c, $71, $8a, $25, $76, $4f, $01, $86, $20, $71, $8a, $2c, $76, $86, $27, $71, $8a, $20, $76, $86
	.byte $20, $71, $8a, $27, $76, $86, $27, $71, $8a, $20, $76, $86, $20, $72, $8a, $27, $76, $86, $27, $72, $8a, $20, $76, $86
	.byte $20, $72, $8a, $27, $76, $86, $27, $72, $8a, $20, $76, $86, $22, $72, $8a, $27, $76, $86, $29, $72, $8a, $22, $76, $86
	.byte $22, $72, $8a, $29, $76, $86, $29, $72, $8a, $22, $76, $86, $22, $72, $8a, $29, $76, $86, $29, $72, $8a, $22, $76, $86
	.byte $22, $72, $8a, $29, $76, $86, $29, $72, $8a, $22, $76, $86, $1e, $72, $8a, $29, $76, $86, $25, $72, $8a, $1e, $76, $86
	.byte $1e, $72, $8a, $25, $76, $86, $25, $72, $8a, $1e, $76, $86, $1e, $72, $8a, $25, $76, $86, $25, $72, $8a, $1e, $76, $86
	.byte $1e, $72, $8a, $25, $76, $86, $25, $72, $8a, $1e, $7a, $4b, .lobyte(@env10), .hibyte(@env10), $a8, $19, $9d, $4d, $14
	.byte $9d, $4b, .lobyte(@env46), .hibyte(@env46), $16, $9d, $4b, .lobyte(@env10), .hibyte(@env10), $12, $9d, $4d, $19, $9d
	.byte $4d, $14, $9d, $4b, .lobyte(@env46), .hibyte(@env46), $16, $9d, $4b, .lobyte(@env10), .hibyte(@env10), $12, $9d, $45
	.byte $9d, $7c, $4b, .lobyte(@env23), .hibyte(@env23), $4c, $4f, $03, $88
@song1ref717:
	.byte $25, $81, $25, $81, $25, $81, $25, $25, $25, $25, $83, $25, $81, $25, $25, $83, $24, $83, $24, $83, $24, $24, $83, $24
	.byte $83, $24, $25, $81, $25, $81, $25, $81, $25, $25, $81, $25, $83, $25, $81, $25, $25, $25, $81, $27, $83, $27, $83, $27
	.byte $27, $83, $27, $83, $27, $4f, $03
	.byte $41, $32
	.word @song1ref717
	.byte $29, $29, $81, $29, $4f, $03
	.byte $41, $35
	.word @song1ref717
	.byte $4f, $03
	.byte $41, $32
	.word @song1ref717
	.byte $29, $29, $81, $29, $4f, $03
	.byte $41, $35
	.word @song1ref717
	.byte $4f, $03
	.byte $41, $32
	.word @song1ref717
	.byte $29, $29, $81, $29, $4f, $03
	.byte $41, $35
	.word @song1ref717
	.byte $4f, $03
	.byte $41, $32
	.word @song1ref717
	.byte $29, $29, $81, $29, $4f, $01, $a4
@song1ref824:
	.byte $25, $78, $25, $81, $7c, $25, $78, $25, $81, $7c, $25, $78, $25, $81, $7c, $25, $78, $25, $81, $7c, $25, $78, $25, $81
	.byte $7c, $25, $78, $25, $81, $7c, $24, $78, $24, $81, $7c, $24, $78, $24, $81, $7c, $24, $78, $24, $81, $7c, $24, $78, $24
	.byte $81, $7c, $24, $78, $24, $7c
	.byte $41, $12
	.word @song1ref824
	.byte $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $27, $78, $27
	.byte $7c
	.byte $41, $20
	.word @song1ref824
	.byte $7c
	.byte $41, $12
	.word @song1ref824
	.byte $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $29, $78, $29, $81, $7c, $29, $78, $29
	.byte $45, $87, $44, $00
@song1ch2:
	.byte $ff, $ff, $a0
@song1ref945:
	.byte $19, $9d, $14, $9d, $16, $9d, $12, $9d, $19, $9d, $14, $9d, $16, $9d, $12, $9d, $00, $9d
@song1ref963:
	.byte $19, $81, $25, $19, $83, $25, $19, $83, $25, $19, $83, $25, $19, $14, $81, $20, $14, $83, $20, $14, $83, $20, $14, $83
	.byte $20, $14, $16, $81, $22, $16, $83, $22, $16, $83, $22, $16, $83, $22, $16, $12, $81, $1e, $12, $83, $1e, $12, $83, $1e
	.byte $12, $83, $1e, $12
	.byte $41, $34
	.word @song1ref963
	.byte $41, $34
	.word @song1ref963
	.byte $41, $34
	.word @song1ref963
	.byte $41, $34
	.word @song1ref963
	.byte $41, $34
	.word @song1ref963
	.byte $41, $34
	.word @song1ref963
	.byte $41, $34
	.word @song1ref963
	.byte $41, $11
	.word @song1ref945
	.byte $87, $44, $00
@song1ch3:
	.byte $ff, $ef, $71, $8a, $1f, $72, $81, $73, $81, $74, $81, $75, $81, $76, $81, $77, $81, $78, $81, $79, $90, $1f, $81, $88
	.byte $21, $81, $7f
@song1ref1070:
	.byte $82, $14, $81, $80, $21, $23, $84, $14, $80, $23, $21, $81, $82, $14, $81, $80, $21, $23
@song1ref1088:
	.byte $84, $14, $81, $80, $21, $81, $82, $14, $81, $80, $21, $23, $84, $14, $80, $23, $21, $81, $82, $14, $81, $80, $21, $23
	.byte $84, $14, $81, $80, $21, $81
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $1c
	.word @song1ref1070
	.byte $8f, $71, $a0, $1f, $72, $81, $73, $81, $75, $81, $77, $81, $7a, $81, $7c, $81, $7f, $81
	.byte $41, $14
	.word @song1ref1088
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $41, $20
	.word @song1ref1070
	.byte $82, $14, $81, $80, $21, $23, $84, $14, $80, $23, $21, $81, $82, $14, $81, $80, $21, $23, $90, $1f, $8d, $45, $ed, $ff
	.byte $89, $44, $00
@song1ch4:
	.byte $ff, $ff
@song1ref1223:
	.byte $87, $16, $8d, $16, $8d, $16, $8d, $16, $8d, $16, $8d, $16, $8d, $16, $8d, $16, $85
	.byte $41, $11
	.word @song1ref1223
	.byte $9f
@song1ref1244:
	.byte $14, $81, $06, $81, $16, $81, $06, $85, $06, $81, $16, $81, $06, $81, $14, $81, $05, $81, $16, $81, $05, $85, $05, $81
	.byte $16, $81, $05, $81, $14, $81, $10, $81, $16, $81, $10, $85, $10, $81, $16, $81, $10, $81, $14, $81, $04, $81, $16, $81
	.byte $04, $85, $04, $81, $16, $81, $04, $81
	.byte $41, $38
	.word @song1ref1244
	.byte $41, $38
	.word @song1ref1244
	.byte $41, $38
	.word @song1ref1244
	.byte $41, $38
	.word @song1ref1244
	.byte $41, $38
	.word @song1ref1244
	.byte $41, $38
	.word @song1ref1244
	.byte $41, $38
	.word @song1ref1244
	.byte $00, $fd, $ff, $89, $44, $00
; The DPCM aligner used to be here
@song3ch0:
	.byte $46, $06, $83, $98
@song3ref5:
	.byte $03, $81, $12, $81, $03, $12, $81, $03, $12, $81, $03, $12, $81, $03, $12, $81, $12, $81, $03, $81, $12, $03, $81, $12
	.byte $03, $81, $12, $03, $81, $12, $03, $81
	.byte $41, $20
	.word @song3ref5
@song3ref40:
	.byte $06, $81, $12, $81, $06, $12, $81, $06, $12, $81, $06, $12, $81, $06, $12, $81, $12, $81, $06, $81, $12, $06, $81, $12
	.byte $06, $81, $12, $06, $81, $12, $06, $81
	.byte $41, $20
	.word @song3ref40
	.byte $41, $20
	.word @song3ref5
	.byte $41, $20
	.word @song3ref5
	.byte $41, $20
	.word @song3ref40
@song3ref84:
	.byte $03, $81, $0f, $81, $03, $0f, $81, $03, $0f, $81, $03, $0f, $81, $03, $0f, $81, $0f, $81, $03, $81, $0f, $03, $81, $0f
	.byte $03, $81, $0f, $03, $81, $0f, $03, $81
	.byte $41, $20
	.word @song3ref84
	.byte $41, $20
	.word @song3ref84
	.byte $41, $20
	.word @song3ref84
	.byte $41, $20
	.word @song3ref84
	.byte $9a, $22, $85, $7a, $9c, $50, $0b, $29, $23, $85, $7f, $98, $0f, $81, $03, $81, $0f, $81, $9a, $20, $81, $20, $81, $22
	.byte $81, $88
@song3ref154:
	.byte $1b, $81, $1b, $81, $1b, $81, $1b, $81, $1b, $81, $1b, $81, $9a, $22, $85, $00, $8a, $40, $0a, $01, $03, $00, $06, $08
	.byte $0a, $06, $03, $9a, $20, $81, $20, $81, $22, $81, $98, $1b, $19, $14, $20, $81, $22, $25, $27, $21, $20, $1e, $20, $83
	.byte $22, $81, $7a, $9c, $50, $10, $23, $1d, $85, $7f, $8a, $50, $80, $0b, $17, $81, $0b, $00, $0b, $83, $00, $87, $7a, $9c
	.byte $50, $10, $23, $1d, $85, $50, $f0, $1d, $23, $85, $50, $10, $23, $1d, $85, $7f, $98, $40, $0a, $83, $02, $83, $05, $83
	.byte $08, $83, $0a, $83, $0e, $83, $11, $81, $88, $27, $27, $27, $8a, $27, $81, $1b, $81, $0f, $96, $50, $b3, $16, $5b, $85
	.byte $9a, $22, $85, $7a, $9c, $50, $0b, $29, $23, $85, $7f, $98, $0b, $81, $40, $0b, $81, $0b, $81, $9a, $20, $81, $20, $81
	.byte $22, $81, $88
@song3ref301:
	.byte $17, $81, $17, $81, $17, $81, $17, $81, $17, $81, $17, $81, $98
@song3ref314:
	.byte $1a, $85, $1a, $85, $1a, $85, $1a, $85, $1d, $85, $1d, $85, $1d, $85, $50, $02, $29, $28, $85, $1b, $85, $00, $95, $44
	.byte $00
@song3ch1:
	.byte $83, $9f, $9f, $9f, $9f, $7b, $ac, $19, $85, $00, $95, $9f, $1b, $85, $00, $95, $9f, $1b, $85, $00, $95, $9f, $1b, $85
	.byte $00, $95, $9f, $19, $85, $00, $95, $9f, $1b, $85, $00, $95, $8f, $7f, $a6, $2c, $8d, $2b, $9d, $8f, $2f, $8d, $2e, $9d
	.byte $8f, $2c, $8d, $2b, $9d, $8f, $25, $8d, $27, $9d, $9b, $50, $0a, $3a, $33, $81, $00, $85, $7a, $9c, $50, $0b, $29, $23
	.byte $85, $7f, $98, $0f, $81, $03, $81, $0f, $81, $00, $81, $87, $9e
	.byte $41, $0c
	.word @song3ref154
	.byte $00, $99, $8a, $01, $81, $00, $9d, $9b, $98, $1d, $81, $83, $1e, $81, $7a, $9c, $50, $1d, $2d, $1e, $85, $50, $d1, $1a
	.byte $33, $85, $50, $1d, $2d, $1e, $85, $7f, $86, $0a, $83, $0e, $83, $11, $83, $14, $83, $16, $83, $1a, $83, $1d, $81, $27
	.byte $27, $27, $98, $27, $81, $1b, $81, $0f, $96, $50, $b3, $16, $5b, $85, $00, $85, $7a, $9c, $50, $0b, $29, $23, $85, $7f
	.byte $98, $17, $81, $0b, $81, $17, $81, $00, $81, $87, $9e
	.byte $41, $0c
	.word @song3ref301
	.byte $86
	.byte $41, $10
	.word @song3ref314
	.byte $51, $fb, $00, $27, $81, $27, $81, $27, $81, $27, $81, $00, $8d, $44, $00
@song3ch2:
	.byte $83, $9f, $9f, $8a, $0f
@song3ref539:
	.byte $9d, $9f, $12, $9d, $9f, $14, $9d, $9f, $0f, $9d, $9f, $14
	.byte $41, $0b
	.word @song3ref539
	.byte $0f, $9d, $9f, $0f, $9d, $9f, $0f, $9d, $50, $13, $3e, $36, $50, $13, $3e, $36, $00, $50, $16, $3b, $33, $50, $16, $3b
	.byte $33, $00, $50, $1c, $37, $2f, $50, $1c, $37, $2f, $00, $50, $23, $33, $2b, $50, $23, $33, $2b, $00, $87
@song3ref599:
	.byte $1b, $81, $27, $81, $1b, $81, $27, $81, $1b, $81, $27, $81
	.byte $41, $0c
	.word @song3ref599
	.byte $41, $0c
	.word @song3ref599
	.byte $41, $0c
	.word @song3ref599
	.byte $41, $0c
	.word @song3ref599
	.byte $1b, $81, $27
@song3ref626:
	.byte $81
@song3ref627:
	.byte $17, $81, $23, $81, $17, $81, $23, $81, $17, $81, $23
	.byte $41, $0c
	.word @song3ref626
@song3ref641:
	.byte $81, $17, $81, $23, $81, $17, $81, $23, $81, $16, $83, $1a, $83, $16, $83, $1a, $83, $16, $83, $1a, $83, $16, $81, $00
	.byte $95
	.byte $41, $0b
	.word @song3ref627
	.byte $41, $0c
	.word @song3ref626
	.byte $41, $0a
	.word @song3ref641
@song3ref675:
	.byte $81, $22, $81, $16, $81, $22, $81, $16, $81, $22, $81, $16
	.byte $41, $0c
	.word @song3ref675
	.byte $81, $22, $81, $16, $81, $22, $81, $00, $9d, $44, $00
@song3ch3:
	.byte $83, $9f, $9f, $9f, $9f
@song3ref707:
	.byte $7c, $90, $1e, $81
@song3ref711:
	.byte $79, $8e, $1e, $81, $75, $82, $1c, $79, $8e, $1e, $81, $75, $82, $1c, $79, $8e, $1e, $81, $75, $82, $1c, $79, $8e, $1e
	.byte $81, $75, $82, $1b, $1b, $81, $1c, $1c
	.byte $41, $10
	.word @song3ref711
	.byte $41, $10
	.word @song3ref711
	.byte $41, $0e
	.word @song3ref711
	.byte $41, $12
	.word @song3ref707
	.byte $41, $10
	.word @song3ref711
	.byte $41, $10
	.word @song3ref711
	.byte $41, $0e
	.word @song3ref711
	.byte $41, $12
	.word @song3ref707
	.byte $41, $10
	.word @song3ref711
	.byte $41, $10
	.word @song3ref711
	.byte $41, $0e
	.word @song3ref711
@song3ref776:
	.byte $7c, $90, $1e
@song3ref779:
	.byte $81, $7f, $8e, $1e, $81, $75, $82, $1c, $7f, $8e, $1e, $81, $75, $82, $1c, $7f, $8e, $1e, $81, $75, $82, $1c, $7f, $8e
	.byte $1e, $81, $75, $82, $1b, $1b, $81, $1c
	.byte $41, $0f
	.word @song3ref779
	.byte $41, $11
	.word @song3ref776
	.byte $41, $0f
	.word @song3ref779
	.byte $7f
@song3ref821:
	.byte $2a, $81, $2a, $81, $90, $2d, $81, $82, $2a, $2a, $81, $2a, $2a, $81, $90, $2d, $81, $00, $82, $2a
	.byte $41, $10
	.word @song3ref821
	.byte $41, $10
	.word @song3ref821
	.byte $2a, $81, $00, $99, $79
@song3ref852:
	.byte $22, $83, $00, $90, $24, $83, $00, $82, $22, $83, $00, $90, $24, $83, $00, $82
	.byte $41, $0c
	.word @song3ref852
	.byte $82
	.byte $41, $0c
	.word @song3ref852
	.byte $82
	.byte $41, $0c
	.word @song3ref852
	.byte $82
	.byte $41, $0c
	.word @song3ref852
	.byte $82
	.byte $41, $0c
	.word @song3ref852
	.byte $82
	.byte $41, $0c
	.word @song3ref852
	.byte $82
	.byte $41, $0c
	.word @song3ref852
	.byte $82
	.byte $41, $0c
	.word @song3ref852
	.byte $82
	.byte $41, $0c
	.word @song3ref852
	.byte $82
	.byte $41, $0c
	.word @song3ref852
	.byte $82
	.byte $41, $0c
	.word @song3ref852
	.byte $82, $22, $83, $00, $97, $44, $00
@song3ch4:
	.byte $83, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f
@song3ref936:
	.byte $14, $81, $00, $81, $14, $00, $81, $14, $00, $81, $14, $00, $81, $14, $14, $81
	.byte $41, $10
	.word @song3ref936
	.byte $41, $10
	.word @song3ref936
	.byte $41, $10
	.word @song3ref936
@song3ref961:
	.byte $14, $00, $14, $00, $16, $00, $14, $14, $00, $14, $14, $00, $16, $00, $81, $14
	.byte $41, $10
	.word @song3ref961
	.byte $41, $10
	.word @song3ref961
	.byte $14, $14, $00, $14, $14, $00, $14, $14, $00, $14, $14, $00, $14, $00, $14, $00
@song3ref999:
	.byte $14, $81, $12, $81, $16, $81, $12, $81, $14, $81, $12, $81, $16, $81, $12, $81
	.byte $41, $10
	.word @song3ref999
	.byte $41, $10
	.word @song3ref999
	.byte $41, $10
	.word @song3ref999
@song3ref1024:
	.byte $14, $81, $0c, $81, $16, $81, $0c, $81, $14, $81, $0c, $81, $16, $81, $0c, $81
	.byte $41, $10
	.word @song3ref1024
@song3ref1043:
	.byte $14, $81, $10, $81, $16, $81
@song3ref1049:
	.byte $10, $81, $14, $81, $10, $81, $16, $81, $10, $81, $14, $81, $10, $81, $16, $81, $00, $81, $14, $81, $00, $81, $16, $81
	.byte $00, $81
	.byte $41, $10
	.word @song3ref1024
	.byte $41, $10
	.word @song3ref1024
	.byte $41, $16
	.word @song3ref1043
	.byte $41, $0a
	.word @song3ref1049
	.byte $0f, $85, $00, $95, $44, $00
@song4ch0:
	.byte $46, $06, $72, $51, $01, $50, $ae, $25, $9d, $76, $9f, $27, $9d, $99, $29, $83, $9f, $97, $2b, $85, $9f, $9f, $77, $4e
	.byte $00, $96, $1c, $91, $50, $04, $28, $26, $89
@song4ref34:
	.byte $4b, .lobyte(@env40), .hibyte(@env40), $4f, $01, $8a, $15, $81, $4d, $1c, $81, $4d, $1c, $81, $00, $81, $4d, $1c, $81
	.byte $4e, $f5, $4d, $1c, $81, $4e, $00, $4d, $1e, $81, $4d, $1a, $81, $4d, $15, $81, $4d, $1c, $81, $4d, $1c, $81, $00, $81
	.byte $4d, $1c, $81, $4d, $1c, $81, $7b, $4b, .lobyte(@env23), .hibyte(@env23), $4c, $96, $15, $85, $77
	.byte $41, $10
	.word @song4ref34
@song4ref95:
	.byte $78, $4d, $15, $81, $4d, $1c, $81, $4d, $15, $81, $4d, $1c, $81, $4b, .lobyte(@env23), .hibyte(@env23), $4c, $96, $0b
	.byte $81, $09, $81, $09, $85, $77
	.byte $41, $1e
	.word @song4ref34
	.byte $77
	.byte $41, $10
	.word @song4ref34
	.byte $41, $0e
	.word @song4ref95
	.byte $77
	.byte $41, $1e
	.word @song4ref34
	.byte $77
	.byte $41, $10
	.word @song4ref34
	.byte $41, $0e
	.word @song4ref95
	.byte $77
	.byte $41, $1e
	.word @song4ref34
	.byte $77
	.byte $41, $10
	.word @song4ref34
	.byte $41, $0e
	.word @song4ref95
	.byte $77
	.byte $41, $1e
	.word @song4ref34
	.byte $77
	.byte $41, $10
	.word @song4ref34
	.byte $41, $0e
	.word @song4ref95
	.byte $77
	.byte $41, $1e
	.word @song4ref34
	.byte $77
	.byte $41, $10
	.word @song4ref34
	.byte $41, $0e
	.word @song4ref95
	.byte $77
	.byte $41, $1e
	.word @song4ref34
	.byte $77
	.byte $41, $10
	.word @song4ref34
	.byte $41, $0e
	.word @song4ref95
	.byte $77
	.byte $41, $1e
	.word @song4ref34
	.byte $77
	.byte $41, $10
	.word @song4ref34
	.byte $41, $0e
	.word @song4ref95
	.byte $50, $1b, $1f, $0e, $8d, $51, $fc, $00, $8f, $00, $95, $8a, $50, $dd, $0d, $27, $85, $74, $97, $7d, $4b, .lobyte(@env43)
	.byte .hibyte(@env43), $9a, $26, $8d, $7a, $89, $79, $85, $83, $7b, $8b, $8b, $78, $83, $4b, .lobyte(@env11), .hibyte(@env11)
	.byte $22, $87, $79, $85, $7d, $8d, $7c, $81, $8f, $89, $76, $85, $78, $4d, $1f, $81, $7b, $89, $7a, $83, $79, $8d, $7b, $85
	.byte $7a, $8b, $7b, $89, $7d, $83, $4b, .lobyte(@env43), .hibyte(@env43), $28, $7a, $83, $7c, $87, $7a, $85, $7d, $89, $79
	.byte $81, $9f, $4b, .lobyte(@env40), .hibyte(@env40)
@song4ref283:
	.byte $88, $21, $4d, $86, $21, $4d, $88, $1f, $4d, $86, $1f, $4d, $88, $1c, $4d, $86, $1c, $4d, $88, $21, $4d, $86, $21, $4d
	.byte $88, $1f, $4d, $86, $1f, $4d, $88, $1c, $4d, $86, $1c, $4d, $88, $21, $4d, $86, $21, $4d, $88, $1c, $4d, $86, $1c, $4d
	.byte $41, $10
	.word @song4ref283
@song4ref334:
	.byte $4d, $88, $1f, $4d, $86, $1f, $4d, $88, $1d, $4d, $86, $1d, $4d, $88, $1a, $4d, $86, $1a, $4d, $88, $1f, $4d, $86, $1f
	.byte $4d, $88, $1d, $4d, $86, $1d, $4d, $88, $1a, $4d, $86, $1a, $4d, $88, $1f, $4d, $86, $1f, $4d, $88, $1a, $4d, $86, $1a
	.byte $41, $10
	.word @song4ref334
	.byte $00, $9d, $44, $00
@song4ch1:
	.byte $75, $96
@song4ref392:
	.byte $09, $00, $09, $00, $09, $00, $09, $00, $09, $00, $09, $74, $51, $02, $e0, $00, $87
	.byte $41, $0b
	.word @song4ref392
	.byte $7f, $00, $87
	.byte $41, $0b
	.word @song4ref392
@song4ref418:
	.byte $00, $87, $09, $00, $09, $00, $09, $00, $07, $00, $07, $00, $0a, $00, $09, $81, $00, $81
	.byte $41, $0b
	.word @song4ref392
	.byte $00, $87
	.byte $41, $0b
	.word @song4ref392
	.byte $00, $87
	.byte $41, $0b
	.word @song4ref392
	.byte $41, $12
	.word @song4ref418
	.byte $9f
@song4ref453:
	.byte $09, $81, $00, $85, $09, $81, $00, $81, $0c, $81, $0c, $81, $07, $81, $09, $81, $00, $85, $09, $81, $00, $8d
	.byte $41, $16
	.word @song4ref453
	.byte $41, $16
	.word @song4ref453
	.byte $41, $16
	.word @song4ref453
	.byte $41, $16
	.word @song4ref453
	.byte $41, $16
	.word @song4ref453
	.byte $78, $4b, .lobyte(@env40), .hibyte(@env40), $b0
@song4ref495:
	.byte $21, $81, $4d, $50, $fa, $2f, $30, $4d, $24, $4d, $21, $4d, $50, $07, $2d, $2c, $4d, $15, $81, $4d, $21, $81, $4d, $50
	.byte $ed, $2d, $30, $4d, $24, $4b, .lobyte(@env23), .hibyte(@env23), $4c, $50, $fc, $38, $39, $2d, $4b, .lobyte(@env40)
	.byte .hibyte(@env40), $28, $81, $4d, $21, $81, $4d, $50, $fa, $2f, $30, $4d, $24, $4d, $50, $fc, $38, $39, $4d, $2d, $4d
	.byte $21, $81, $4d, $24, $81, $4d, $21, $81, $4d, $21, $81, $4d, $50, $08, $2d, $2b, $81, $4d
	.byte $41, $10
	.word @song4ref495
@song4ref577:
	.byte $4d, $24, $81, $4d, $50, $fb, $33, $34, $4d, $28, $4d, $28, $81, $4d, $50, $03, $34, $33, $81, $4d, $21, $81, $4d, $2d
	.byte $81, $4d, $26, $81, $4d, $32, $81, $4d
	.byte $41, $20
	.word @song4ref495
	.byte $4d
	.byte $41, $10
	.word @song4ref495
	.byte $41, $10
	.word @song4ref577
	.byte $4d
	.byte $41, $20
	.word @song4ref495
	.byte $4d
	.byte $41, $10
	.word @song4ref495
	.byte $41, $10
	.word @song4ref577
	.byte $4d
	.byte $41, $20
	.word @song4ref495
	.byte $4d
	.byte $41, $10
	.word @song4ref495
	.byte $41, $10
	.word @song4ref577
	.byte $4d
	.byte $41, $20
	.word @song4ref495
	.byte $4d
	.byte $41, $10
	.word @song4ref495
	.byte $41, $10
	.word @song4ref577
	.byte $00, $9d, $9f, $97, $76, $4b, .lobyte(@env23), .hibyte(@env23), $4c, $96
@song4ref662:
	.byte $0e, $9d, $9f, $0a, $9d, $9f, $07, $9d, $9f, $10, $9d, $9f, $75, $4e, $ff, $4b, .lobyte(@env40), .hibyte(@env40), $4f
	.byte $02
	.byte $41, $10
	.word @song4ref283
	.byte $4e, $ff, $4d, $4f, $02
	.byte $41, $10
	.word @song4ref283
	.byte $41, $10
	.word @song4ref334
	.byte $41, $10
	.word @song4ref334
	.byte $00, $9d, $44, $00
@song4ch2:
	.byte $8a, $09, $9d, $9f, $9f, $07, $9d, $09, $9d, $9f, $9f, $00, $9d, $10, $9d, $15, $9d, $00, $9d, $15, $9d, $00, $9d, $15
	.byte $9d, $00, $9d, $15, $9d, $00
@song4ref734:
	.byte $9d, $49, .lobyte(@env33), .hibyte(@env33), $28, $9d, $8a, $29, $9d, $2b, $9d, $2d, $9d, $49, .lobyte(@env33), .hibyte(@env33)
	.byte $28, $9d, $8a, $29, $9d, $2b, $9d, $2d
	.byte $41, $10
	.word @song4ref734
	.byte $41, $10
	.word @song4ref734
	.byte $9d, $00, $9d, $9f, $97
	.byte $41, $0c
	.word @song4ref662
	.byte $15, $9d, $9f, $13, $9d, $9f, $00, $9d, $44, $00
@song4ch3:
	.byte $72, $51, $03, $d0
@song4ref787:
	.byte $84, $16, $85, $94, $1c, $81, $00, $81, $84, $16, $85, $94, $1c, $81, $00, $81, $7f
	.byte $41, $0c
	.word @song4ref787
	.byte $41, $0c
	.word @song4ref787
	.byte $41, $0c
	.word @song4ref787
@song4ref813:
	.byte $84
@song4ref814:
	.byte $16, $00, $16, $00, $94, $1c, $81, $84, $16, $00, $16, $00, $94, $1c, $81, $84, $16, $00, $83
	.byte $41, $0f
	.word @song4ref814
	.byte $41, $0f
	.word @song4ref814
	.byte $41, $0f
	.word @song4ref814
	.byte $90, $1d, $8d, $00, $81, $8a, $50, $06, $20, $29, $89
@song4ref853:
	.byte $84, $16, $00, $80, $1f, $00, $82, $1f, $81, $80, $1f, $00, $1f, $00, $84, $16, $00, $82, $1f, $81, $80, $1f, $00
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $10
	.word @song4ref853
	.byte $41, $0f
	.word @song4ref813
	.byte $41, $0f
	.word @song4ref814
	.byte $41, $0f
	.word @song4ref814
	.byte $41, $0e
	.word @song4ref814
	.byte $94, $1c, $81, $51, $f4, $00, $90, $50, $f3, $2e, $20, $85, $00, $95, $8f, $71, $51, $02, $90, $8a, $50, $03, $20, $2c
	.byte $8d, $95, $7e, $81, $72, $a0, $20, $9d, $9f, $9f, $9f, $9f, $9f, $9f, $7f, $84, $16, $81, $72, $a0, $20, $89, $7f, $84
	.byte $16, $81, $94, $1b, $81, $84, $16, $81, $00, $81
@song4ref1027:
	.byte $16, $81, $00, $89, $82, $20, $81, $00, $89, $84, $16, $81, $00, $89, $82, $20, $81, $84, $16, $81, $00, $85
	.byte $41, $12
	.word @song4ref1027
	.byte $77, $51, $fd, $00, $8a, $50, $fc, $2d, $26, $8d, $7f, $00, $8d, $44, $00
@song4ch4:
	.byte $14, $00, $83, $16, $00, $83, $14, $00, $83, $16, $00, $83
@song4ref1080:
	.byte $14, $85, $16, $81, $00, $81, $14, $85, $16, $81, $00, $81
	.byte $41, $0c
	.word @song4ref1080
	.byte $41, $0c
	.word @song4ref1080
@song4ref1098:
	.byte $14, $81, $14, $81, $16, $81, $14, $81, $14, $81, $16, $81, $14, $81, $00, $81
	.byte $41, $10
	.word @song4ref1098
	.byte $41, $10
	.word @song4ref1098
	.byte $41, $10
	.word @song4ref1098
	.byte $09, $9d
@song4ref1125:
	.byte $14, $0b, $00, $81, $16, $00, $0b, $81, $14, $00, $11, $81, $16, $11, $0a, $81, $14, $0a, $00, $81, $16, $00, $0a, $81
	.byte $14, $00, $83, $16, $0d, $83
	.byte $41, $1c
	.word @song4ref1125
	.byte $0b, $83
	.byte $41, $1e
	.word @song4ref1125
	.byte $41, $1c
	.word @song4ref1125
	.byte $0b, $83
	.byte $41, $1e
	.word @song4ref1125
	.byte $41, $1c
	.word @song4ref1125
	.byte $0b, $83
	.byte $41, $1e
	.word @song4ref1125
	.byte $41, $1c
	.word @song4ref1125
	.byte $0b, $83
	.byte $41, $1e
	.word @song4ref1125
	.byte $41, $1c
	.word @song4ref1125
	.byte $0b, $83
	.byte $41, $1e
	.word @song4ref1125
	.byte $41, $1c
	.word @song4ref1125
	.byte $0b, $83
	.byte $41, $1e
	.word @song4ref1125
	.byte $41, $1c
	.word @song4ref1125
	.byte $0b, $83
	.byte $41, $1e
	.word @song4ref1125
	.byte $41, $1c
	.word @song4ref1125
	.byte $0b, $83, $00, $9d, $9f, $97, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $14, $00, $8b, $14, $00, $16, $81, $14, $00, $83, $14
	.byte $81, $00, $81, $0b, $81, $00, $81, $16, $81, $00, $81, $0b, $81, $00, $81, $14, $81, $00, $81, $0b, $81, $00, $81, $16
	.byte $81, $14, $81, $0b
@song4ref1266:
	.byte $81, $00, $81, $14, $81, $00, $81, $0a, $81, $00, $81, $16, $81, $00, $81, $0a
	.byte $41, $0d
	.word @song4ref1266
	.byte $14, $81, $0a, $81, $00, $81, $15, $9d, $44, $00
@song5ch0:
	.byte $46, $06
@song5ch0loop:
	.byte $79, $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $02, $9e
@song5ref12:
	.byte $19, $19, $25, $0d, $20, $81, $19, $1f, $81, $1e, $81, $1c, $81, $19, $1c, $1e, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $4f, $02, $17, $17, $25, $0b, $20, $81, $19, $1f, $81, $1e, $81, $1c, $81, $19, $1c, $1e, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $4f, $02, $16, $16, $25, $0a, $20, $81, $19, $1f, $81, $1e, $81, $1c, $81, $19, $1c, $1e, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $4f, $02, $15, $15, $25, $09, $20, $81, $19, $1f, $81, $1e, $81, $1c, $81, $19
	.byte $1c, $1e, $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $02
	.byte $41, $40
	.word @song5ref12
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $02
	.byte $41, $40
	.word @song5ref12
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $02
	.byte $41, $30
	.word @song5ref12
	.byte $49, .lobyte(@env5), .hibyte(@env5), $4f, $02, $9a, $09, $8b, $43, $0b, $8b, $45, $81, $42
	.word @song5ch0loop
@song5ch1:
@song5ch1loop:
	.byte $7a, $49, .lobyte(@env7), .hibyte(@env7), $4f, $01, $a8
@song5ref145:
	.byte $0d, $97, $45, $83, $a8, $0b, $97, $45, $83, $0a, $97, $45, $83, $09, $8b, $45, $0b, $8b, $45, $49, .lobyte(@env7)
	.byte .hibyte(@env7), $4f, $01
	.byte $41, $12
	.word @song5ref145
	.byte $49, .lobyte(@env7), .hibyte(@env7), $4f, $01
	.byte $41, $12
	.word @song5ref145
	.byte $49, .lobyte(@env7), .hibyte(@env7), $4f, $01, $0d, $99, $45, $81, $a8, $0b, $99, $45, $81, $0a, $99, $45, $81, $49
	.byte .lobyte(@env16), .hibyte(@env16), $4f, $03, $9a, $09, $8b, $43, $0b, $8b, $45, $81, $42
	.word @song5ch1loop
@song5ch2:
@song5ch2loop:
	.byte $b2
@song5ref216:
	.byte $19, $19, $25, $19, $19, $00, $25, $31, $00, $8d, $17, $17, $23, $17, $17, $00, $23, $2f, $00, $8d, $16, $16, $22, $16
	.byte $16, $00, $22, $2e, $00, $16, $22, $16, $00, $85, $15, $15, $21, $15, $15, $00, $23, $2f, $00, $17, $23, $17, $00, $81
	.byte $23, $00
	.byte $41, $32
	.word @song5ref216
	.byte $41, $32
	.word @song5ref216
	.byte $41, $21
	.word @song5ref216
	.byte $a5, $42
	.word @song5ch2loop
@song5ch3:
@song5ch3loop:
	.byte $7c, $80
@song5ref282:
	.byte $20, $81, $21, $81, $7a, $1e, $7c, $21, $7a, $23, $21, $81, $7c, $21, $81, $7a, $1f, $7c, $21, $81, $78, $21, $7a, $21
	.byte $23, $81, $7c, $21, $81, $7a, $1e, $7c, $21, $7a, $1c, $1e, $81, $7c, $1d, $81, $7a, $1f, $21, $81, $7c, $1e, $78, $23
	.byte $7c
	.byte $41, $20
	.word @song5ref282
	.byte $7c
	.byte $41, $20
	.word @song5ref282
	.byte $7c
	.byte $41, $20
	.word @song5ref282
	.byte $7c
	.byte $41, $20
	.word @song5ref282
	.byte $7c
	.byte $41, $20
	.word @song5ref282
	.byte $7c
	.byte $41, $20
	.word @song5ref282
	.byte $7c
	.byte $41, $14
	.word @song5ref282
	.byte $7a, $23, $89, $78, $b4, $23, $89, $42
	.word @song5ch3loop
@song5ch4:
@song5ch4loop:
@song5ref369:
	.byte $52, $41
@song5ref371:
	.byte $14, $85, $16, $81, $14, $83, $14, $14, $81, $16, $85, $14, $81, $14, $81, $16, $81, $14, $16, $81, $14, $14, $81, $16
	.byte $16, $16, $16
	.byte $41, $1b
	.word @song5ref371
	.byte $41, $1b
	.word @song5ref369
	.byte $41, $1b
	.word @song5ref371
	.byte $41, $1b
	.word @song5ref369
	.byte $41, $1b
	.word @song5ref371
	.byte $41, $1b
	.word @song5ref369
	.byte $14, $85, $16, $83, $14, $81, $14, $14, $81, $16, $85, $14, $81, $14, $85, $14, $85, $14, $81, $14, $85, $42
	.word @song5ch4loop
@song6ch0:
	.byte $46, $06, $8f, $4f, $02, $9e, $1c, $81, $19, $1c, $23, $25, $20
@song6ref14:
	.byte $85, $10, $83, $10, $83, $17, $81, $14, $17, $23, $25, $1c
@song6ref26:
	.byte $85, $0b, $83, $0b, $83, $19, $81, $15, $19, $23, $25, $21
@song6ref38:
	.byte $85, $0d, $83, $0d, $83, $1b, $81, $17, $1b, $23, $25, $1e, $85, $0f, $83, $0f, $83, $1c, $81, $19, $1c, $23, $25, $28
	.byte $41, $0b
	.word @song6ref14
	.byte $23
	.byte $41, $0b
	.word @song6ref26
	.byte $2a
	.byte $41, $0b
	.word @song6ref38
	.byte $20, $85, $0f, $83, $0f, $83, $00, $8d
@song6ref81:
	.byte $1c, $81, $19, $1c, $23, $25, $20, $87, $28, $83, $27, $81, $17, $81, $14, $17, $23, $25, $1c, $87, $27, $83, $23, $81
	.byte $19, $81, $15, $19, $23, $25, $21, $87, $25, $83, $27
@song6ref116:
	.byte $81, $1b, $81, $17, $1b, $23, $25, $1e, $87, $23, $83, $20
@song6ref128:
	.byte $81, $1c, $81, $19, $1c, $23, $25, $28, $87, $27, $83, $28, $81, $17, $81, $14, $17, $23, $25, $23, $87, $23, $83, $25
@song6ref152:
	.byte $81, $19, $81, $15, $19, $23, $25, $2c, $87, $28, $83, $2a, $81, $1b, $81, $17, $1b, $23, $25, $2a, $87, $28, $83, $27
	.byte $81
	.byte $41, $16
	.word @song6ref81
	.byte $28, $81, $19, $81, $15, $19, $23, $25, $21, $87, $2a, $83, $28
	.byte $41, $0b
	.word @song6ref116
	.byte $25
	.byte $41, $13
	.word @song6ref128
	.byte $2a, $87, $28, $83, $2a
	.byte $41, $13
	.word @song6ref152
	.byte $20, $87, $20, $83, $1e, $81, $78, $20, $85, $1c, $85, $1b, $81, $19, $85, $17, $1b, $20, $85, $1e, $81, $1c, $85, $20
	.byte $85, $25, $27, $28, $89, $27, $89, $25, $81, $23, $21, $20, $89, $21, $20, $1e, $85, $1c, $85, $20, $85, $1c, $81, $19
	.byte $81, $17, $81, $19, $85, $17, $81, $14, $85, $1c, $81, $12, $14, $12, $85, $1b, $81, $0b, $81, $0d, $8d, $0d, $85, $0d
	.byte $10, $0d, $10, $12, $89, $10, $81, $12, $81, $10, $14, $83, $12, $81, $1c, $81, $19, $1c, $83, $1b, $81, $19, $81, $1b
	.byte $20, $83, $1b, $81, $1c, $91, $20, $1e, $83, $1c, $81, $21, $83, $21, $83, $20, $81, $1e, $81, $20, $1e, $83, $1c, $81
	.byte $1e, $9d, $1c, $81, $19, $1c, $83, $1e, $81, $1c, $81, $1b, $1c, $83, $1b, $81, $1c, $91, $1c, $20, $83, $21, $81, $23
	.byte $83, $23, $83, $21, $81, $23, $81, $21, $20, $83, $1e, $81, $20, $9d, $00, $8d, $44, $00
@song6ch1:
	.byte $8f, $4f, $02, $9e, $20, $81, $00, $99, $23, $81, $00, $99, $1c, $81, $00, $99, $1e, $81, $00, $99, $4f, $02, $20, $81
	.byte $00, $99, $74, $23, $81, $00, $99, $1c, $81, $00, $99, $71, $4f, $00, $8a, $50, $f5, $21, $60, $85, $72, $87, $73, $87
	.byte $74, $87, $00, $8d, $7b, $4f, $02, $00, $81, $9e, $0d, $81
@song6ref431:
	.byte $00, $81, $0d, $81, $00, $81, $0d, $81, $00, $81
@song6ref441:
	.byte $0d, $81, $00, $81, $10, $81, $00, $81, $10, $81, $00, $81, $10, $81, $00, $81, $10, $81, $00, $81, $09, $81, $00, $81
	.byte $09, $81, $00, $81, $09, $81, $00, $81, $09, $81, $00, $81, $0b, $81, $00, $81, $0b, $81, $00, $81, $0b, $81, $00, $81
	.byte $0b, $81, $4f, $02
	.byte $41, $0e
	.word @song6ref431
	.byte $41, $32
	.word @song6ref441
	.byte $4f, $02
	.byte $41, $0e
	.word @song6ref431
	.byte $41, $32
	.word @song6ref441
	.byte $4f, $02
	.byte $41, $0e
	.word @song6ref431
	.byte $41, $32
	.word @song6ref441
	.byte $00, $81, $aa
@song6ref518:
	.byte $19, $00, $8b, $19, $00, $83, $19, $00, $83, $1c, $00, $8b, $1c, $00, $83, $1c, $00, $83, $15, $00, $8b, $15, $00, $83
	.byte $15, $00, $83, $17, $00, $8b, $17, $00, $83, $17, $00, $00, $81
	.byte $41, $25
	.word @song6ref518
	.byte $41, $25
	.word @song6ref518
	.byte $41, $23
	.word @song6ref518
	.byte $8f, $44, $00
@song6ch2:
@song6ref568:
	.byte $8f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $8f
@song6ref578:
	.byte $92, $0d, $0d, $19, $00, $0d, $00, $19, $00, $88, $3d, $92, $0d, $19, $00, $88, $3d, $00, $3b, $00, $92, $10, $10, $1c
	.byte $00, $10, $00, $1c, $00, $88, $3b, $92, $10, $1c, $00, $88, $3b, $00, $38, $00, $92, $09, $09, $15, $00, $09, $00, $15
	.byte $00, $88, $3d, $92, $09, $15, $00, $88, $3d, $00, $3b, $00, $92, $0b, $0b, $17, $00, $0b, $00, $17, $00, $88, $3b, $92
	.byte $0b, $17, $00, $88, $3b, $00, $3d, $00
	.byte $41, $40
	.word @song6ref578
	.byte $41, $40
	.word @song6ref578
	.byte $41, $40
	.word @song6ref578
	.byte $92
@song6ref668:
	.byte $0d, $0d, $19, $00, $0d, $00, $19, $00, $0d, $0d, $19, $00, $0d, $00, $19, $00, $10, $10, $1c, $00, $10, $00, $1c, $00
	.byte $10, $10, $1c, $00, $10, $00, $1c, $00, $09, $09, $15, $00, $09, $00, $15, $00, $09, $09, $15, $00, $09, $00, $15, $00
	.byte $0b, $0b, $17, $00, $0b, $00, $17, $00, $0b, $0b, $17, $00, $0b, $00, $17, $00
	.byte $41, $40
	.word @song6ref668
	.byte $41, $40
	.word @song6ref668
	.byte $41, $40
	.word @song6ref668
	.byte $8f, $44, $00
@song6ch3:
	.byte $8f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $8f, $80, $21, $21, $21, $21, $21, $21, $21, $21, $00, $8d
@song6ref765:
	.byte $90, $21, $7d, $81, $7b, $81, $79, $81, $7a
@song6ref774:
	.byte $51, $fd, $60, $8c, $1e, $45, $00, $81
@song6ref782:
	.byte $7f, $51, $fd, $a0, $84, $1b, $45, $00, $81, $51, $fd, $60, $8c, $1e, $45, $00, $81, $7f, $51, $fd, $a0, $84, $1b, $45
	.byte $00, $81
	.byte $41, $10
	.word @song6ref774
	.byte $41, $10
	.word @song6ref774
@song6ref814:
	.byte $51, $fd, $60, $8c, $1e, $45, $00, $81, $7f, $51, $fd, $a0, $84, $1b, $45, $00, $81, $8c, $1e, $45, $51, $e8, $00, $1e
	.byte $7a, $51, $e8, $00, $1e
	.byte $41, $0c
	.word @song6ref782
	.byte $41, $10
	.word @song6ref774
	.byte $41, $10
	.word @song6ref774
	.byte $41, $0c
	.word @song6ref774
	.byte $7f, $51, $fa, $a0, $84, $1b, $45, $8c, $1e, $45, $1e, $45, $51, $e8, $00, $1e, $7a, $51, $e8, $00, $1e, $7f
	.byte $41, $14
	.word @song6ref765
	.byte $41, $10
	.word @song6ref774
	.byte $41, $10
	.word @song6ref774
	.byte $41, $0c
	.word @song6ref814
	.byte $41, $0c
	.word @song6ref782
	.byte $41, $10
	.word @song6ref774
	.byte $41, $10
	.word @song6ref774
	.byte $41, $0c
	.word @song6ref774
	.byte $7f, $80, $21, $21, $21, $21, $21, $21, $21, $21
	.byte $41, $14
	.word @song6ref765
	.byte $41, $10
	.word @song6ref774
	.byte $41, $10
	.word @song6ref774
	.byte $41, $10
	.word @song6ref774
	.byte $41, $10
	.word @song6ref774
	.byte $41, $10
	.word @song6ref774
	.byte $41, $10
	.word @song6ref774
	.byte $41, $0c
	.word @song6ref774
	.byte $7f
	.byte $41, $14
	.word @song6ref765
	.byte $41, $10
	.word @song6ref774
	.byte $41, $10
	.word @song6ref774
	.byte $41, $10
	.word @song6ref774
	.byte $41, $10
	.word @song6ref774
	.byte $41, $10
	.word @song6ref774
	.byte $41, $10
	.word @song6ref774
	.byte $41, $0c
	.word @song6ref774
	.byte $7f, $90, $21, $7d, $81, $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $44, $00
@song6ch4:
	.byte $41, $0a
	.word @song6ref568
	.byte $83, $03
@song6ref985:
	.byte $00, $83, $03, $00, $83, $03, $00, $83
@song6ref993:
	.byte $03, $00, $83, $09, $00, $83, $09, $00, $83, $09, $00, $83, $09, $00, $85, $00, $85, $00, $85, $00, $85, $00, $83, $08
	.byte $00, $83, $08, $00, $83, $08, $00, $83, $08
	.byte $41, $0b
	.word @song6ref985
	.byte $41, $21
	.word @song6ref993
	.byte $41, $0b
	.word @song6ref985
	.byte $41, $21
	.word @song6ref993
	.byte $41, $0b
	.word @song6ref985
	.byte $41, $21
	.word @song6ref993
	.byte $41, $0b
	.word @song6ref985
	.byte $41, $21
	.word @song6ref993
	.byte $41, $0b
	.word @song6ref985
	.byte $41, $21
	.word @song6ref993
	.byte $41, $0b
	.word @song6ref985
	.byte $41, $21
	.word @song6ref993
	.byte $41, $0b
	.word @song6ref985
	.byte $41, $21
	.word @song6ref993
	.byte $00, $8f, $44, $00
