#define song_crackdown 0
#define song_driving_by_night 1
#define song_freedom_dive 2
#define song_infernoplex_full 3
#define song_pyrophoric 4
#define song_lost 5
#define song_subtle_oddities 6
#define song_atthespeedoflightfull 7
#define song_ultimatedestruction 8
#define song_eon 9
#define song_ninox 10
#define song_chaozfantasy 11
#define song_whats_a_future_funk 12
#define song_practice 13
#define song_haunted_woods 14
#define song_clutterfunk_2 15
#define song_magic_touch 16
#define song_endgame 17
#define song_menu_theme_22 18
#define song_idols 19
#define song_death_moon 20
#define song_atthespeedoflight2 21
#define song_ludicrous_speed 22
#define song_clubstep 23
#define song_atthespeedoflight 24
#define song_stalemate 25
#define song_cycles 26
#define song_just_right 27
#define song_against_the_odds_redux 28
#define song_speed_racer 29
#define song_stereo_madness 30
#define song_scheming_weasel 31
#define song_stereo_madness_2 32
#define song_atthespeedoflight3 33
#define song_windfall 34
#define song_cant_let_go 35
#define song_problematic 36
#define song_midnight 37
#define song_max 38