#define song_subtle_oddities 0
#define song_dance_of_the_violins 1
#define song_infinite_power 2
#define song_whats_a_future_funk 3
#define song_factory_time 4
#define song_magic_touch 5
#define song_check_out 6
#define song_menu_theme_22 7
#define song_cryogenic 8
#define song_meowstuff 9
#define song_endgame 10
#define song_clutterfunk_2 11
#define song_death_moon 12
#define song_cycles 13
#define song_practice 14
#define song_fantasy 15
#define song_pursuit 16
#define song_hell 17
#define song_fire_aura 18
#define song_infiltration 19
#define song_clubstep 20
#define song_stereo_madness_2 21
#define song_chaoz_fantasy_extended 22
#define song_power_trip 23
#define song_xenogenesis 24
#define song_meltdown 25
#define song_kesobomb 26
#define song_glitch_gremlin 27
#define song_holography 28
#define song_scheming_weasel 29
#define song_problematic 30
#define song_ninox 31
#define song_speed_racer 32
#define song_pyrophoric 33
#define song_tiny_tunes 34
#define song_driving_by_night 35
#define song_max 36