; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Famidash music:
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_NOISE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1
; FAMISTUDIO_USE_ARPEGGIO = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_famidash_music11:=music_data_famidash_music11

music_data_famidash_music11:
	.byte 5
	.word @instruments
	.word @samples-5
; 00 : Dance of the violins
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 266,221
; 01 : Meowstuff
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word 307,256
; 02 : Ninox
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word 251,209
; 03 : Dry Out
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word 296,247
; The DPCM aligner used to be here
; 05 : ultimatedestruction
	.word @song5ch0
	.word @song5ch1
	.word @song5ch2
	.word @song5ch3
	.word @song5ch4
	.word 286,238

.export music_data_famidash_music11
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env18,@env7,@env26,@env0 ; 00 : rel hats
	.word @env19,@env25,@env2,@env0 ; 01 : snare
	.word @env10,@env34,@env26,@env0 ; 02 : kick
	.word @env8,@env7,@env33,@env0 ; 03 : hat
	.word @env3,@env22,@env28,@env0 ; 04 : sample
	.word @env24,@env27,@env26,@env0 ; 05 : clap
	.word @env35,@env7,@env2,@env0 ; 06 : cymbal
	.word @env20,@env22,@env26,@env0 ; 07 : triangle pluck 3
	.word @env43,@env22,@env26,@env0 ; 08 : triangle pluck 2
	.word @env39,@env22,@env26,@env0 ; 09 : blank instant decay
	.word @env23,@env22,@env26,@env0 ; 0a : infernoplex_piano
	.word @env17,@env22,@env26,@env0 ; 0b : blank
	.word @env30,@env22,@env26,@env0 ; 0c : quiet bass
	.word @env16,@env22,@env6,@env0 ; 0d : hex guitar 1
	.word @env31,@env22,@env26,@env32 ; 0e : jaezu lead
	.word @env16,@env22,@env26,@env13 ; 0f : I don't know what to name this
	.word @env24,@env22,@env26,@env0 ; 10 : clap no app
	.word @env21,@env22,@env26,@env0 ; 11 : blank string
	.word @env1,@env22,@env26,@env0 ; 12 : echo
	.word @env15,@env22,@env5,@env0 ; 13 : endgame lead
	.word @env40,@env22,@env26,@env0 ; 14 : blank slower string
	.word @env38,@env22,@env26,@env0 ; 15 : menu acc
	.word @env42,@env22,@env29,@env0 ; 16 : death moon lead
	.word @env17,@env22,@env4,@env0 ; 17 : electroman lead
	.word @env9,@env22,@env26,@env0 ; 18 : clutterfunk sax

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cb,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$13
@env2:
	.byte $c1,$c0,$00,$01
@env3:
	.byte $00,$c9,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$00,$08
@env4:
	.byte $c2,$c1,$03,$c0,$02,$c0,$00,$01
@env5:
	.byte $c2,$c2,$c0,$00,$00
@env6:
	.byte $c3,$c2,$c1,$c2,$c2,$c1,$00,$02
@env7:
	.byte $bd,$c0,$00,$01
@env8:
	.byte $00,$c8,$c4,$c2,$c0,$00,$04
@env9:
	.byte $05,$ce,$cf,$00,$02,$cc,$c8,$c5,$c2,$c0,$00,$09
@env10:
	.byte $00,$cd,$c9,$c5,$c2,$c1,$c0,$00,$06
@env11:
	.byte $c0,$c4,$c7,$00,$00
@env12:
	.byte $c0,$c4,$c0,$00,$00
@env13:
	.byte $00,$c3,$cb,$cf,$d5,$c0,$c3,$ca,$cd,$d4,$c0,$c4,$c8,$cf,$d6,$dd,$e3,$e6,$e7,$e8,$ea,$eb,$ed,$ee,$f0,$f2,$f6,$fa,$fd,$ff,$00,$1d
@env14:
	.byte $c0,$c7,$c0,$00,$00
@env15:
	.byte $00,$cf,$cd,$cb,$c7,$c7,$ca,$00,$06
@env16:
	.byte $00,$cf,$7f,$00,$02
@env17:
	.byte $04,$cf,$00,$01,$ca,$c6,$c4,$c2,$c0,$00,$08
@env18:
	.byte $00,$c8,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$0d
@env19:
	.byte $00,$cd,$cb,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env20:
	.byte $00,$cf,$02,$c0,$00,$03
@env21:
	.byte $08,$c5,$c6,$c7,$08,$c6,$00,$05,$c6,$c6,$c5,$02,$c4,$02,$c3,$02,$c2,$02,$c1,$c1,$c0,$00,$14
@env22:
	.byte $c0,$7f,$00,$01
@env23:
	.byte $00,$ce,$02,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$c9,$c9,$c8,$c7,$c6,$c5,$c3,$00,$10
@env24:
	.byte $00,$cf,$ca,$cc,$ca,$c9,$c8,$c6,$c5,$c4,$c2,$c1,$c0,$00,$0c
@env25:
	.byte $c6,$cc,$00,$01
@env26:
	.byte $7f,$00,$00
@env27:
	.byte $bc,$c1,$c0,$00,$02
@env28:
	.byte $c2,$7f,$00,$00
@env29:
	.byte $c1,$7f,$00,$00
@env30:
	.byte $00,$c9,$c7,$c5,$00,$03
@env31:
	.byte $0d,$c6,$c8,$ca,$cc,$03,$cb,$03,$ca,$03,$c9,$00,$0a,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$1c
@env32:
	.byte $00,$c0,$07,$c0,$c1,$c2,$c3,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$00,$03
@env33:
	.byte $c0,$c1,$00,$00
@env34:
	.byte $c9,$cf,$00,$01
@env35:
	.byte $18,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c7,$c6,$02,$c5,$c5,$c4,$02,$c3,$03,$c2,$c2,$00,$15,$c2,$c2,$c1,$03,$c0,$00,$1c
@env36:
	.byte $00,$c0,$bf,$be,$bd,$bd,$be,$bf,$c1,$c2,$c3,$c3,$c2,$c1,$00,$01
@env37:
	.byte $c0,$c3,$c7,$00,$00
@env38:
	.byte $00,$c8,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$06,$c1,$07,$c0,$00,$10
@env39:
	.byte $00,$cf,$cf,$cb,$c8,$c5,$c3,$c2,$c1,$c0,$00,$09
@env40:
	.byte $0c,$c2,$c3,$c4,$c5,$c6,$c6,$c7,$04,$c6,$00,$09,$c6,$c6,$c5,$02,$c4,$02,$c3,$02,$c2,$02,$c1,$c1,$c0,$00,$18
@env41:
	.byte $c0,$c5,$c9,$00,$00
@env42:
	.byte $00,$cf,$ca,$c9,$c8,$c7,$c6,$c6,$c5,$00,$08
@env43:
	.byte $00,$cf,$cf,$c0,$00,$03
@env44:
	.byte $c0,$c5,$c0,$00,$00

@samples:
	.byte $11+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 00 fdbass A# (Pitch:15)
	.byte $23+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$40,$00 ; 01 fdbass B (Pitch:13)
	.byte $23+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$00 ; 02 fdbass B (Pitch:15)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0c,$40,$00 ; 03 fdbass C (Pitch:12)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 04 fdbass C (Pitch:15)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$07,$40,$00 ; 05 fdbass C# (Pitch:7)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$08,$40,$00 ; 06 fdbass C# (Pitch:8)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$09,$40,$00 ; 07 fdbass C# (Pitch:9)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0a,$40,$00 ; 08 fdbass C# (Pitch:10)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0b,$40,$00 ; 09 fdbass C# (Pitch:11)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0d,$40,$00 ; 0a fdbass C# (Pitch:13)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 0b fdbass C# (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$07,$40,$00 ; 0c fdbass D (Pitch:7)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$08,$40,$00 ; 0d fdbass D (Pitch:8)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0a,$40,$00 ; 0e fdbass D (Pitch:10)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0c,$40,$00 ; 0f fdbass D (Pitch:12)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0f,$40,$00 ; 10 fdbass D (Pitch:15)
	.byte $6b+.lobyte(FAMISTUDIO_DPCM_PTR),$2b,$0e,$40,$00 ; 11 fdkick (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$57,$0f,$40,$01 ; 12 run (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$41,$0f,$34,$00 ; 13 snare (Pitch:15)

@song0ch0:
	.byte $46, $06, $4b, .lobyte(@env37), .hibyte(@env37), $8a
@song0ref7:
	.byte $1b, $81, $00, $81, $4d, $1b, $81, $00, $4b, .lobyte(@env11), .hibyte(@env11), $17, $81, $00, $4d, $17, $81, $4d, $17
	.byte $81, $00, $81, $4b, .lobyte(@env41), .hibyte(@env41), $19, $81, $00, $81, $4d, $19, $81, $00, $4b, .lobyte(@env14)
	.byte .hibyte(@env14), $19, $81, $00, $4d, $19, $81, $4b, .lobyte(@env12), .hibyte(@env12), $19, $81, $4b, .lobyte(@env44)
	.byte .hibyte(@env44), $19, $81, $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref7
	.byte $00, $9d, $44, $00
@song0ch1:
@song0ref196:
	.byte $75, $4b, .lobyte(@env37), .hibyte(@env37), $a6
@song0ref201:
	.byte $0f, $81, $00, $81, $4d, $0f, $81, $00, $4b, .lobyte(@env11), .hibyte(@env11), $0b, $81, $00, $4d, $0b, $81, $4d, $0b
	.byte $81, $00, $81, $4b, .lobyte(@env41), .hibyte(@env41), $0d, $81, $00, $81, $4d, $0d, $81, $00, $4b, .lobyte(@env14)
	.byte .hibyte(@env14), $0d, $81, $00, $4d, $0d, $81, $4b, .lobyte(@env12), .hibyte(@env12), $0d, $81, $4b, .lobyte(@env44)
	.byte .hibyte(@env44), $0d, $81, $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref201
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref201
@song0ref265:
	.byte $79, $49, .lobyte(@env0), .hibyte(@env0), $4a, $4b, .lobyte(@env22), .hibyte(@env22), $4c
@song0ref274:
	.byte $4f, $00, $9c, $50, $f6, $33, $36, $2a, $49, .lobyte(@env36), .hibyte(@env36), $89, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $9c, $27, $81, $49, .lobyte(@env36), .hibyte(@env36), $81, $49, .lobyte(@env36), .hibyte(@env36), $8b, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $9c, $25, $81, $49, .lobyte(@env36), .hibyte(@env36), $83, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $9c, $2a, $49, .lobyte(@env36), .hibyte(@env36), $83, $9c, $29, $8f, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $4f, $00, $50, $f6, $33, $36, $2a, $49, .lobyte(@env36), .hibyte(@env36), $89, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $9c, $27, $81, $49, .lobyte(@env36), .hibyte(@env36), $81, $49, .lobyte(@env36), .hibyte(@env36), $8b, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $9c, $25, $49, .lobyte(@env36), .hibyte(@env36), $85, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $9c, $1e, $49, .lobyte(@env36), .hibyte(@env36), $83, $49, .lobyte(@env0), .hibyte(@env0), $4a, $9c, $20, $81, $49
	.byte .lobyte(@env36), .hibyte(@env36), $8d, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $41, $17
	.word @song0ref274
@song0ref393:
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $9c, $2a, $49, .lobyte(@env36), .hibyte(@env36), $83, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $9c, $2c, $81, $49, .lobyte(@env36), .hibyte(@env36), $8d, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $9c, $22, $81, $1b, $81, $22, $81, $1b, $22, $49, .lobyte(@env36), .hibyte(@env36), $1e, $81, $9c, $27, $81, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $25, $81, $23, $81, $25, $81, $22, $81, $1e, $81
@song0ref449:
	.byte $1d, $49, .lobyte(@env36), .hibyte(@env36), $81, $4f, $01, $83, $4f, $00, $9c, $19, $81, $1d, $81, $1e
@song0ref465:
	.byte $81, $49, .lobyte(@env0), .hibyte(@env0), $4a, $22, $81, $1b, $81, $22, $81, $1b, $22, $49, .lobyte(@env36), .hibyte(@env36)
	.byte $1e, $81, $9c, $27, $81, $49, .lobyte(@env0), .hibyte(@env0), $4a, $25, $81, $23, $81, $25, $81, $22, $81, $1e, $81
	.byte $20, $49, .lobyte(@env36), .hibyte(@env36), $4f, $01, $83, $4f, $00, $81, $9c, $2a, $85, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $29
	.byte $41, $17
	.word @song0ref465
	.byte $41, $25
	.word @song0ref449
	.byte $81
	.byte $41, $20
	.word @song0ref196
	.byte $4b, .lobyte(@env37), .hibyte(@env37)
	.byte $41, $20
	.word @song0ref201
	.byte $41, $17
	.word @song0ref265
	.byte $41, $40
	.word @song0ref393
	.byte $41, $17
	.word @song0ref465
	.byte $41, $25
	.word @song0ref449
	.byte $41, $17
	.word @song0ref465
	.byte $41, $25
	.word @song0ref449
	.byte $41, $17
	.word @song0ref465
	.byte $41, $25
	.word @song0ref449
	.byte $81, $00, $9d, $44, $00
@song0ch2:
	.byte $96
@song0ref565:
	.byte $0f, $8b, $0b, $8f, $12, $8b, $0d, $8f, $0f, $8b, $0b, $8f, $12, $8b, $0d, $8f, $0f, $8b, $0b, $8f, $12, $8b, $0d, $8f
	.byte $41, $18
	.word @song0ref565
	.byte $41, $18
	.word @song0ref565
	.byte $41, $18
	.word @song0ref565
	.byte $41, $18
	.word @song0ref565
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $9c, $2e, $81, $27, $00, $2e, $00, $27, $2e, $49, .lobyte(@env36), .hibyte(@env36)
	.byte $2a, $00, $9c, $33, $81, $49, .lobyte(@env0), .hibyte(@env0), $4a, $31, $81, $2f, $81, $31, $00, $2e, $00, $2a, $00
@song0ref636:
	.byte $29, $49, .lobyte(@env36), .hibyte(@env36), $83, $00, $9c, $25, $00, $29, $00, $2a
@song0ref648:
	.byte $00, $49, .lobyte(@env0), .hibyte(@env0), $4a, $2e, $81, $27, $00, $2e, $00, $27, $2e, $49, .lobyte(@env36), .hibyte(@env36)
	.byte $2a, $00, $9c, $33, $81, $49, .lobyte(@env0), .hibyte(@env0), $4a, $31, $81, $2f, $81, $31, $00, $2e, $00, $2a, $00
	.byte $2c, $49, .lobyte(@env36), .hibyte(@env36), $00, $83, $9c, $36, $85, $49, .lobyte(@env0), .hibyte(@env0), $4a, $35
	.byte $41, $17
	.word @song0ref648
	.byte $41, $25
	.word @song0ref636
	.byte $00
@song0ref704:
	.byte $36, $81, $27, $81, $36, $81, $27, $36, $27, $81, $36, $81, $35, $81, $33, $81, $31, $81, $2e, $81, $31, $48, $02, $81
	.byte $31, $83, $00, $29, $81, $2c, $81, $2e, $81, $36, $81, $27, $81, $36, $81, $27, $36, $27, $81, $36, $81, $35, $81, $33
	.byte $81, $38, $81, $36, $81, $33, $81, $31, $85, $3a, $85, $38, $81
	.byte $41, $3b
	.word @song0ref704
	.byte $00, $9d, $44, $00
@song0ch3:
@song0ref773:
	.byte $8c, $2e, $85
@song0ref776:
	.byte $8a, $3a, $81, $80, $30, $81, $84, $25, $00, $80, $30, $81, $8a, $3a, $81, $80, $30, $81, $84, $25, $00, $80, $30, $81
	.byte $8a, $3a, $81, $80, $30, $81, $84, $25, $00, $80, $30, $81
	.byte $41, $18
	.word @song0ref776
	.byte $41, $18
	.word @song0ref776
	.byte $8a, $3a, $81, $80, $30, $81, $84, $25, $00, $80, $30, $81, $8a, $3a, $81, $80, $30, $81, $84, $25, $00, $80, $30, $81
	.byte $8a, $3a, $81, $80, $30, $81
	.byte $41, $1a
	.word @song0ref773
	.byte $41, $18
	.word @song0ref776
	.byte $41, $18
	.word @song0ref776
	.byte $41, $18
	.word @song0ref776
	.byte $41, $18
	.word @song0ref776
	.byte $8a, $3a, $81, $80, $30, $81, $8c, $2e, $8d, $77, $8f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $2e, $8d, $8f, $9f, $9f, $9f
	.byte $2e, $8d, $8f, $9f, $72, $51, $01, $f0, $82, $20, $21, $20, $21, $20, $21, $20, $21, $20, $21, $20, $21, $20, $21, $20
	.byte $21, $20, $21, $20, $21, $20, $21, $20, $21, $20, $21, $20, $21, $20, $21, $20, $21
	.byte $41, $1a
	.word @song0ref773
	.byte $41, $18
	.word @song0ref776
	.byte $41, $18
	.word @song0ref776
	.byte $41, $18
	.word @song0ref776
	.byte $41, $18
	.word @song0ref776
	.byte $8a, $3a, $81, $80, $30, $81
	.byte $41, $1a
	.word @song0ref773
	.byte $41, $18
	.word @song0ref776
	.byte $41, $18
	.word @song0ref776
	.byte $41, $18
	.word @song0ref776
	.byte $8a, $3a, $81, $80, $30, $81, $84, $25, $00, $80, $30, $81, $8a, $3a, $81, $80, $30, $81, $8c, $31, $85, $80, $31, $83
	.byte $31, $83, $31, $81, $31, $81, $31, $81, $8c, $2e, $9d, $44, $00
@song0ch4:
@song0ref999:
	.byte $12, $00, $10, $81, $14, $00, $10, $0a, $12, $00, $0a, $81, $14, $00, $0a, $81, $12, $00, $0b, $81, $14, $00, $0b, $04
	.byte $12, $00, $04, $81, $14, $00, $04, $81
	.byte $41, $20
	.word @song0ref999
	.byte $41, $20
	.word @song0ref999
	.byte $41, $20
	.word @song0ref999
	.byte $41, $20
	.word @song0ref999
	.byte $41, $20
	.word @song0ref999
	.byte $41, $20
	.word @song0ref999
@song0ref1049:
	.byte $10, $81, $00, $81, $10, $81, $00, $0a, $81, $00, $0a, $81, $0a, $81, $00, $81, $0b, $81, $00, $81, $0b, $81, $00, $04
	.byte $81, $00, $04, $81, $0a, $81, $04, $81
	.byte $41, $20
	.word @song0ref1049
	.byte $41, $20
	.word @song0ref1049
	.byte $41, $20
	.word @song0ref1049
	.byte $41, $20
	.word @song0ref1049
	.byte $41, $20
	.word @song0ref1049
	.byte $41, $20
	.word @song0ref1049
	.byte $41, $20
	.word @song0ref1049
	.byte $41, $20
	.word @song0ref999
	.byte $41, $20
	.word @song0ref999
	.byte $41, $20
	.word @song0ref999
	.byte $41, $20
	.word @song0ref999
	.byte $41, $20
	.word @song0ref999
	.byte $41, $20
	.word @song0ref999
	.byte $41, $20
	.word @song0ref999
	.byte $12, $00, $10, $81, $14, $00, $10, $0a, $12, $00, $0a, $81, $14, $00, $0a, $81, $14, $00, $0b, $81, $14, $00, $0b, $14
	.byte $00, $81, $04, $81, $14, $00, $04, $81, $00, $9d, $44, $00
@song1ch0:
	.byte $46, $03, $9c, $2b, $85, $2c, $85, $2e, $85, $45, $85, $27, $85, $45, $85, $2c, $85, $45, $85, $00, $ed, $a4
@song1ref23:
	.byte $2c, $85, $38, $89, $38, $89, $36, $89, $36, $89, $36, $8d, $35, $89, $35, $89, $34, $89, $34, $89, $36, $85, $2c, $85
	.byte $38, $89, $38, $89, $36, $89, $36, $89, $36, $85, $36, $89, $36, $89, $38, $a5
	.byte $41, $27
	.word @song1ref23
	.byte $8d, $79, $9c, $27, $85, $2e, $85, $2b, $85, $2c, $85, $2e, $85, $30, $85, $31, $85, $33, $85, $45, $85, $2c, $85, $45
	.byte $85, $29, $85, $45, $85, $2b, $85, $2c, $85, $2b, $85, $2e, $85, $27, $85, $45, $85, $24, $85, $27, $85, $2c, $85, $2e
	.byte $85, $30, $85, $45, $85, $2c, $85, $45, $85, $29, $85, $45, $85, $2b, $85, $2c, $85, $2e, $85, $33, $85, $27, $85, $45
	.byte $85, $2c, $85, $28, $85, $27, $85, $25, $85, $24, $85, $27, $85, $2c, $85, $2e, $85, $30, $85, $45, $85, $30, $85, $2e
	.byte $85, $2c, $85, $45, $85, $27, $85, $25, $85, $24, $85, $27, $85, $2c, $85, $27, $85, $2b, $85, $29, $85, $27, $85, $30
	.byte $85, $2e, $85, $2c, $85
@song1ref191:
	.byte $2e, $85, $30, $85, $33, $85, $30, $85, $2e, $85, $30, $85, $2c, $85, $45, $85, $00, $ed, $ff, $ff, $ff, $7f, $a4, $38
	.byte $85, $38, $89, $38, $89, $3c, $89, $3c, $89, $3c, $85, $3d, $85, $3d, $89, $3d, $89, $3f, $89, $3f, $89, $79, $9c
@song1ref238:
	.byte $2c, $81, $2e, $81, $30, $85, $2c, $85, $27, $85, $45, $85, $00, $85, $25, $85, $24, $85, $25, $85, $27, $85, $2c, $85
	.byte $20, $85, $45, $85, $00, $95, $20, $81, $22, $81, $24, $85, $20, $85, $27, $85, $45, $85, $00, $85, $27, $85, $27, $85
	.byte $25, $85, $27, $85, $45, $85, $00, $a5
	.byte $41, $18
	.word @song1ref238
	.byte $41, $14
	.word @song1ref191
	.byte $44, $00
@song1ch1:
	.byte $79, $9c, $1d, $85, $45, $85, $1b, $8d, $45, $8d, $20, $8d, $45, $8d, $00, $dd, $a4
@song1ref320:
	.byte $27, $85, $30, $89, $30, $89, $2e, $89, $2e, $89, $2e, $8d, $2c, $89, $2c, $89, $2e, $89, $2e, $89, $30, $85, $27, $85
	.byte $30, $89, $30, $89, $2e, $89, $2e, $89, $2e, $85, $2e, $89, $2e, $89, $30, $a5
	.byte $41, $28
	.word @song1ref320
	.byte $7f
	.byte $41, $14
	.word @song1ref23
	.byte $34, $85
	.byte $41, $14
	.word @song1ref23
	.byte $34, $85
	.byte $41, $14
	.word @song1ref23
	.byte $34, $85
	.byte $41, $14
	.word @song1ref23
	.byte $34, $85, $00, $fd, $ff, $ff, $ff, $78, $4f, $01, $a8, $24, $9d, $22, $9d, $25, $9d, $24, $9d, $24, $9d, $22, $9d, $25
	.byte $9d, $27, $9d, $4f, $01, $24, $9d, $22, $9d, $25, $9d, $24, $9d, $24, $9d, $22, $9d, $25, $9d, $27, $9d, $77, $8f, $76
	.byte $8f, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $70, $8f, $00, $fd, $ff, $44, $00
@song1ch2:
	.byte $af
@song1ref450:
	.byte $96
@song1ref451:
	.byte $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85
	.byte $14, $85, $20, $85, $14, $85, $20, $85
@song1ref483:
	.byte $14, $85, $20, $83, $00, $81, $20, $83, $00, $81, $23, $85, $00, $81
@song1ref497:
	.byte $20, $85, $1e, $85, $20, $85
@song1ref503:
	.byte $19, $85, $00, $81, $19, $85, $00, $81, $1b, $85, $00, $81, $1b, $85, $00, $81, $a0, $1b, $85, $1b, $85, $96, $14, $85
	.byte $20, $83, $00, $81, $20, $83, $00, $81, $23, $85, $00, $81, $25, $85, $23, $85, $20, $85, $1e, $85, $00, $81, $1e, $85
	.byte $00, $81, $20, $85, $00, $9d
	.byte $41, $48
	.word @song1ref483
	.byte $41, $3c
	.word @song1ref483
	.byte $41, $22
	.word @song1ref503
	.byte $41, $2e
	.word @song1ref497
	.byte $41, $14
	.word @song1ref503
	.byte $00, $fd, $ff, $ff, $bf
	.byte $41, $20
	.word @song1ref450
	.byte $19, $85, $25, $85, $19, $85, $25, $85, $1b, $85, $27, $85
@song1ref592:
	.byte $1b, $85, $27
@song1ref595:
	.byte $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $19, $85, $25, $85, $19, $85, $25
	.byte $85, $1b, $85, $27, $85, $23, $85, $22
	.byte $41, $1d
	.word @song1ref595
	.byte $41, $23
	.word @song1ref592
	.byte $85, $00, $fd, $ff
	.byte $41, $20
	.word @song1ref451
	.byte $44, $00
@song1ch3:
	.byte $af, $74, $82
@song1ref646:
	.byte $1d, $81, $00, $81, $72, $20, $81, $00, $81, $74, $1d, $81, $00, $81, $72, $20, $81, $00, $81, $74, $1d, $81, $00, $81
	.byte $72, $20, $81, $00, $81, $74
	.byte $41, $18
	.word @song1ref646
	.byte $74, $1d, $81, $00, $81, $72, $20, $81, $00, $81, $76, $25, $00, $25, $00, $25, $00, $25
@song1ref697:
	.byte $00
@song1ref698:
	.byte $79, $8c, $1e, $8d, $76, $86
@song1ref704:
	.byte $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $16
	.word @song1ref698
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $16
	.word @song1ref698
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $16
	.word @song1ref698
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $16
	.word @song1ref698
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $16
	.word @song1ref698
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $16
	.word @song1ref698
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $24, $00, $24, $00, $24, $00, $24
	.byte $41, $17
	.word @song1ref697
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $41, $14
	.word @song1ref704
	.byte $ff, $44, $00
@song1ch4:
	.byte $af, $ff
@song1ref896:
	.byte $12, $85, $00, $85, $14, $85, $12, $85, $00, $85, $12, $85, $14, $85, $00, $85, $12, $85, $00, $85, $14, $85, $00, $85
	.byte $12, $85, $00, $85, $14, $81, $14, $81, $14, $81, $14, $81
	.byte $41, $24
	.word @song1ref896
	.byte $41, $24
	.word @song1ref896
	.byte $41, $24
	.word @song1ref896
	.byte $41, $24
	.word @song1ref896
	.byte $41, $24
	.word @song1ref896
	.byte $41, $24
	.word @song1ref896
	.byte $41, $24
	.word @song1ref896
	.byte $41, $1d
	.word @song1ref896
	.byte $85, $14, $81, $14, $81
	.byte $41, $16
	.word @song1ref896
	.byte $12, $85, $14, $85, $12, $85, $14, $85, $14, $81, $14, $81
	.byte $41, $1d
	.word @song1ref896
	.byte $85, $14, $81, $14, $81
	.byte $41, $16
	.word @song1ref896
	.byte $12, $85, $14, $85, $12, $85, $14, $81, $14, $81, $14, $81, $14, $81
	.byte $41, $1d
	.word @song1ref896
	.byte $85, $14, $85
	.byte $41, $24
	.word @song1ref896
	.byte $41, $1d
	.word @song1ref896
	.byte $85, $14, $85
	.byte $41, $24
	.word @song1ref896
	.byte $41, $1d
	.word @song1ref896
	.byte $85, $14, $81, $14, $81
	.byte $41, $16
	.word @song1ref896
	.byte $12, $85, $14, $85, $12, $85, $14, $85, $14, $81, $14, $81, $00, $fd, $44, $00
@song2ch0:
	.byte $46, $06, $83, $94
@song2ref5:
	.byte $03, $81, $12, $81, $03, $12, $81, $03, $12, $81, $03, $12, $81, $03, $12, $81, $12, $81, $03, $81, $12, $03, $81, $12
	.byte $03, $81, $12, $03, $81, $12, $03, $81
	.byte $41, $20
	.word @song2ref5
@song2ref40:
	.byte $06, $81, $12, $81, $06, $12, $81, $06, $12, $81, $06, $12, $81, $06, $12, $81, $12, $81, $06, $81, $12, $06, $81, $12
	.byte $06, $81, $12, $06, $81, $12, $06, $81
	.byte $41, $20
	.word @song2ref40
	.byte $41, $20
	.word @song2ref5
	.byte $41, $20
	.word @song2ref5
	.byte $41, $20
	.word @song2ref40
@song2ref84:
	.byte $03, $81, $0f, $81, $03, $0f, $81, $03, $0f, $81, $03, $0f, $81, $03, $0f, $81, $0f, $81, $03, $81, $0f, $03, $81, $0f
	.byte $03, $81, $0f, $03, $81, $0f, $03, $81
	.byte $41, $20
	.word @song2ref84
	.byte $41, $20
	.word @song2ref84
	.byte $41, $20
	.word @song2ref84
	.byte $41, $20
	.word @song2ref84
	.byte $a2, $22, $85, $7a, $9e, $50, $0b, $29, $23, $85, $7f, $94, $0f, $81, $03, $81, $0f, $81, $a2, $20, $81, $20, $81, $22
	.byte $81, $92
@song2ref154:
	.byte $1b, $81, $1b, $81, $1b, $81, $1b, $81, $1b, $81, $1b, $81, $a2, $22, $85, $00, $96, $40, $0a, $01, $03, $00, $06, $08
	.byte $0a, $06, $03, $a2, $20, $81, $20, $81, $22, $81, $94, $1b, $19, $14, $20, $81, $22, $25, $27, $21, $20, $1e, $20, $83
	.byte $22, $81, $7a, $9e, $50, $10, $23, $1d, $85, $7f, $96, $50, $80, $0b, $17, $81, $0b, $00, $0b, $83, $00, $87, $7a, $9e
	.byte $50, $10, $23, $1d, $85, $50, $f0, $1d, $23, $85, $50, $10, $23, $1d, $85, $7f, $94, $40, $0a, $83, $02, $83, $05, $83
	.byte $08, $83, $0a, $83, $0e, $83, $11, $81, $92, $27, $27, $27, $96, $27, $81, $1b, $81, $0f, $a6, $50, $b3, $16, $5b, $85
	.byte $a2, $22, $85, $7a, $9e, $50, $0b, $29, $23, $85, $7f, $94, $0b, $81, $40, $0b, $81, $0b, $81, $a2, $20, $81, $20, $81
	.byte $22, $81, $92
@song2ref301:
	.byte $17, $81, $17, $81, $17, $81, $17, $81, $17, $81, $17, $81, $94
@song2ref314:
	.byte $1a, $85, $1a, $85, $1a, $85, $1a, $85, $1d, $85, $1d, $85, $1d, $85, $50, $02, $29, $28, $85, $1b, $85, $00, $95, $44
	.byte $00
@song2ch1:
	.byte $83, $9f, $9f, $9f, $9f, $7b, $ac, $19, $85, $00, $95, $9f, $1b, $85, $00, $95, $9f, $1b, $85, $00, $95, $9f, $1b, $85
	.byte $00, $95, $9f, $19, $85, $00, $95, $9f, $1b, $85, $00, $95, $8f, $7f, $a8, $2c, $8d, $2b, $9d, $8f, $2f, $8d, $2e, $9d
	.byte $8f, $2c, $8d, $2b, $9d, $8f, $25, $8d, $27, $9d, $9b, $50, $0a, $3a, $33, $81, $00, $85, $7a, $9e, $50, $0b, $29, $23
	.byte $85, $7f, $94, $0f, $81, $03, $81, $0f, $81, $00, $81, $87, $aa
	.byte $41, $0c
	.word @song2ref154
	.byte $00, $99, $96, $01, $81, $00, $9d, $9b, $94, $1d, $81, $83, $1e, $81, $7a, $9e, $50, $1d, $2d, $1e, $85, $50, $d1, $1a
	.byte $33, $85, $50, $1d, $2d, $1e, $85, $7f, $a4, $0a, $83, $0e, $83, $11, $83, $14, $83, $16, $83, $1a, $83, $1d, $81, $27
	.byte $27, $27, $94, $27, $81, $1b, $81, $0f, $a6, $50, $b3, $16, $5b, $85, $00, $85, $7a, $9e, $50, $0b, $29, $23, $85, $7f
	.byte $94, $17, $81, $0b, $81, $17, $81, $00, $81, $87, $aa
	.byte $41, $0c
	.word @song2ref301
	.byte $a4
	.byte $41, $10
	.word @song2ref314
	.byte $51, $fb, $00, $27, $81, $27, $81, $27, $81, $27, $81, $00, $8d, $44, $00
@song2ch2:
	.byte $83, $9f, $9f, $96, $0f
@song2ref539:
	.byte $9d, $9f, $12, $9d, $9f, $14, $9d, $9f, $0f, $9d, $9f, $14
	.byte $41, $0b
	.word @song2ref539
	.byte $0f, $9d, $9f, $0f, $9d, $9f, $0f, $9d, $50, $13, $3e, $36, $50, $13, $3e, $36, $00, $50, $16, $3b, $33, $50, $16, $3b
	.byte $33, $00, $50, $1c, $37, $2f, $50, $1c, $37, $2f, $00, $50, $23, $33, $2b, $50, $23, $33, $2b, $00, $87
@song2ref599:
	.byte $1b, $81, $27, $81, $1b, $81, $27, $81, $1b, $81, $27, $81
	.byte $41, $0c
	.word @song2ref599
	.byte $41, $0c
	.word @song2ref599
	.byte $41, $0c
	.word @song2ref599
	.byte $41, $0c
	.word @song2ref599
	.byte $1b, $81, $27
@song2ref626:
	.byte $81
@song2ref627:
	.byte $17, $81, $23, $81, $17, $81, $23, $81, $17, $81, $23
	.byte $41, $0c
	.word @song2ref626
@song2ref641:
	.byte $81, $17, $81, $23, $81, $17, $81, $23, $81, $16, $83, $1a, $83, $16, $83, $1a, $83, $16, $83, $1a, $83, $16, $81, $00
	.byte $95
	.byte $41, $0b
	.word @song2ref627
	.byte $41, $0c
	.word @song2ref626
	.byte $41, $0a
	.word @song2ref641
@song2ref675:
	.byte $81, $22, $81, $16, $81, $22, $81, $16, $81, $22, $81, $16
	.byte $41, $0c
	.word @song2ref675
	.byte $81, $22, $81, $16, $81, $22, $81, $00, $9d, $44, $00
@song2ch3:
	.byte $83, $9f, $9f, $9f, $9f
@song2ref707:
	.byte $7c, $8c, $1e, $81
@song2ref711:
	.byte $79, $88, $1e, $81, $75, $82, $1c, $79, $88, $1e, $81, $75, $82, $1c, $79, $88, $1e, $81, $75, $82, $1c, $79, $88, $1e
	.byte $81, $75, $82, $1b, $1b, $81, $1c, $1c
	.byte $41, $10
	.word @song2ref711
	.byte $41, $10
	.word @song2ref711
	.byte $41, $0e
	.word @song2ref711
	.byte $41, $12
	.word @song2ref707
	.byte $41, $10
	.word @song2ref711
	.byte $41, $10
	.word @song2ref711
	.byte $41, $0e
	.word @song2ref711
	.byte $41, $12
	.word @song2ref707
	.byte $41, $10
	.word @song2ref711
	.byte $41, $10
	.word @song2ref711
	.byte $41, $0e
	.word @song2ref711
@song2ref776:
	.byte $7c, $8c, $1e
@song2ref779:
	.byte $81, $7f, $88, $1e, $81, $75, $82, $1c, $7f, $88, $1e, $81, $75, $82, $1c, $7f, $88, $1e, $81, $75, $82, $1c, $7f, $88
	.byte $1e, $81, $75, $82, $1b, $1b, $81, $1c
	.byte $41, $0f
	.word @song2ref779
	.byte $41, $11
	.word @song2ref776
	.byte $41, $0f
	.word @song2ref779
	.byte $7f
@song2ref821:
	.byte $2a, $81, $2a, $81, $8c, $2d, $81, $82, $2a, $2a, $81, $2a, $2a, $81, $8c, $2d, $81, $00, $82, $2a
	.byte $41, $10
	.word @song2ref821
	.byte $41, $10
	.word @song2ref821
	.byte $2a, $81, $00, $99, $79
@song2ref852:
	.byte $22, $83, $00, $8c, $24, $83, $00, $82, $22, $83, $00, $8c, $24, $83, $00, $82
	.byte $41, $0c
	.word @song2ref852
	.byte $82
	.byte $41, $0c
	.word @song2ref852
	.byte $82
	.byte $41, $0c
	.word @song2ref852
	.byte $82
	.byte $41, $0c
	.word @song2ref852
	.byte $82
	.byte $41, $0c
	.word @song2ref852
	.byte $82
	.byte $41, $0c
	.word @song2ref852
	.byte $82
	.byte $41, $0c
	.word @song2ref852
	.byte $82
	.byte $41, $0c
	.word @song2ref852
	.byte $82
	.byte $41, $0c
	.word @song2ref852
	.byte $82
	.byte $41, $0c
	.word @song2ref852
	.byte $82
	.byte $41, $0c
	.word @song2ref852
	.byte $82, $22, $83, $00, $97, $44, $00
@song2ch4:
	.byte $83, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f
@song2ref936:
	.byte $12, $81, $00, $81, $12, $00, $81, $12, $00, $81, $12, $00, $81, $12, $12, $81
	.byte $41, $10
	.word @song2ref936
	.byte $41, $10
	.word @song2ref936
	.byte $41, $10
	.word @song2ref936
@song2ref961:
	.byte $12, $00, $12, $00, $14, $00, $12, $12, $00, $12, $12, $00, $14, $00, $81, $12
	.byte $41, $10
	.word @song2ref961
	.byte $41, $10
	.word @song2ref961
	.byte $12, $12, $00, $12, $12, $00, $12, $12, $00, $12, $12, $00, $12, $00, $12, $00
@song2ref999:
	.byte $12, $81, $10, $81, $14, $81, $10, $81, $12, $81, $10, $81, $14, $81, $10, $81
	.byte $41, $10
	.word @song2ref999
	.byte $41, $10
	.word @song2ref999
	.byte $41, $10
	.word @song2ref999
@song2ref1024:
	.byte $12, $81, $0a, $81, $14, $81, $0a, $81, $12, $81, $0a, $81, $14, $81, $0a, $81
	.byte $41, $10
	.word @song2ref1024
@song2ref1043:
	.byte $12, $81, $0f, $81, $14, $81
@song2ref1049:
	.byte $0f, $81, $12, $81, $0f, $81, $14, $81, $0f, $81, $12, $81, $0f, $81, $14, $81, $00, $81, $12, $81, $00, $81, $14, $81
	.byte $00, $81
	.byte $41, $10
	.word @song2ref1024
	.byte $41, $10
	.word @song2ref1024
	.byte $41, $16
	.word @song2ref1043
	.byte $41, $0a
	.word @song2ref1049
	.byte $0d, $85, $00, $95, $44, $00
@song3ch0:
	.byte $46, $06, $7c, $4f, $02, $92
@song3ref7:
	.byte $12, $12, $1e, $1e, $1c, $1c, $19, $19, $83, $15, $15, $14, $14, $10, $10, $12, $12, $81, $1c, $1c, $81, $19, $19, $83
	.byte $0d, $0d, $10, $10, $14, $14, $12, $12, $1c, $1c, $1e, $1e, $19, $19, $83, $14, $14, $15, $15, $17, $17, $1c, $1c, $81
	.byte $1e, $1e, $81, $19, $19, $83, $1e, $1e, $15, $15, $14, $14, $4f, $02
	.byte $41, $3c
	.word @song3ref7
	.byte $4f, $02
	.byte $41, $3c
	.word @song3ref7
	.byte $4f, $02
	.byte $41, $3c
	.word @song3ref7
	.byte $9f, $00, $83, $73
@song3ref86:
	.byte $9a
@song3ref87:
	.byte $06, $81, $00, $81, $06, $81, $00, $81, $06, $81, $50, $80, $12, $1e, $43, $12, $00, $81, $12, $81, $04, $81, $00, $81
	.byte $04, $81, $00, $81, $04, $81, $50, $80, $10, $1c, $43, $10, $00, $81, $10, $81, $01, $81, $00, $81, $01, $81, $00, $81
	.byte $01, $81, $50, $80, $0d, $19, $43, $0d, $00, $81, $0d, $81, $04, $81, $00, $81, $04, $81, $00, $81, $09, $81, $00, $81
	.byte $08, $81, $04, $81
	.byte $41, $3b
	.word @song3ref87
@song3ref166:
	.byte $83, $7b, $4f, $02, $92, $12, $12, $1e, $1e, $1c, $1c, $19, $19, $73, $00, $83, $9a, $06, $81, $50, $80, $12, $1e, $43
	.byte $12, $00, $7b, $92, $12, $12, $00, $1c, $1c, $00, $19, $19, $73, $00, $83, $9a, $04, $81, $50, $80, $10, $1c, $43, $10
	.byte $00, $7b, $92, $12, $12, $1c, $1c, $1e, $1e, $19, $19, $73, $00, $83, $9a, $01, $81, $50, $80, $0d, $19, $43, $0d, $00
	.byte $7b, $92, $1c, $1c, $00, $1e, $1e, $00, $19, $19, $73, $00, $83, $9a, $09, $81, $00
	.byte $41, $3b
	.word @song3ref166
	.byte $83, $76, $4f, $00, $92
@song3ref263:
	.byte $12, $12, $1e, $1e, $1c, $1c, $19, $19, $00, $8d, $12, $12, $00, $1c, $1c, $00, $19, $19, $00, $8d, $12, $12, $1c, $1c
	.byte $1e, $1e, $19, $19, $00, $8d, $1c, $1c, $00, $1e, $1e, $00, $19, $19, $00, $8d, $4f, $00
	.byte $41, $28
	.word @song3ref263
	.byte $7b, $4f, $02
@song3ref311:
	.byte $12, $12, $1e, $1e, $1c, $1c, $19, $19, $74, $94, $1e, $81, $28, $81, $21, $81, $20, $81, $7b, $92, $12, $12, $00, $1c
	.byte $1c, $00, $19, $19, $74, $94, $25, $85, $19, $81, $1c, $81, $7b, $92, $12, $12, $1c, $1c, $1e, $1e, $19, $19, $74, $94
	.byte $19, $81, $1c, $81, $20, $81, $21, $81, $7b, $92, $1c, $1c, $00, $1e, $1e, $00, $19, $19, $74, $94, $25, $81, $2a, $85
	.byte $21, $81, $7b, $4f, $02, $92
	.byte $41, $3c
	.word @song3ref311
	.byte $20, $81, $1e, $89, $44, $00
@song3ch1:
	.byte $98
@song3ref400:
	.byte $06, $9d, $04, $9d, $01, $9d, $04, $9d, $06, $9d, $04, $9d, $01, $9d, $04, $9d
	.byte $41, $10
	.word @song3ref400
	.byte $00, $85, $70, $51, $07, $f0, $ae, $06, $89, $51, $fc, $60, $8b, $7b
	.byte $41, $40
	.word @song3ref86
	.byte $41, $40
	.word @song3ref87
	.byte $41, $40
	.word @song3ref87
	.byte $41, $40
	.word @song3ref87
	.byte $7a, $4f, $00, $b0
@song3ref449:
	.byte $12, $81, $4f, $00, $83, $4f, $01, $83, $4f, $00, $83, $4f, $00, $1c, $81, $4f, $00, $15, $81, $4f, $01, $14, $81, $4f
	.byte $00, $10, $81, $4f, $00, $12, $81, $4f, $00, $83, $4f, $01, $83, $4f, $00, $19, $81, $4f, $00, $83, $4f, $00, $0d, $81
	.byte $4f, $01, $10, $81, $4f, $00, $14, $81, $4f, $00, $12, $81, $4f, $00, $83, $4f, $01, $83, $4f, $00, $0d, $81, $4f, $00
	.byte $10, $81, $4f, $00, $14, $81, $4f, $01, $15, $81, $4f, $00, $17, $81, $4f, $00, $12, $81, $4f, $00, $83, $4f, $01, $83
	.byte $4f, $00, $19, $81, $4f, $00, $1e, $81, $4f, $00, $83, $4f, $01, $15, $81, $4f, $00, $14, $81, $4f, $00
	.byte $41, $35
	.word @song3ref449
	.byte $7c, $4f, $02, $94
@song3ref573:
	.byte $1e, $89, $1e, $81, $28, $81, $21, $81, $20, $81, $1c, $81, $1e, $89, $25, $85, $19, $81, $1c, $81, $20, $81, $1e, $89
	.byte $19, $81, $1c, $81, $20, $81, $21, $81, $23, $81, $1e, $89, $25, $81, $2a, $85, $21, $81, $20, $81, $4f, $02
	.byte $41, $2c
	.word @song3ref573
	.byte $1e, $89, $00, $81, $44, $00
@song3ch2:
	.byte $98
@song3ref630:
	.byte $12, $9d, $10, $9d, $0d, $9d, $10, $9d, $12, $9d, $10, $9d, $0d, $9d, $10, $9d
	.byte $41, $10
	.word @song3ref630
	.byte $00, $9d
@song3ref651:
	.byte $12, $8d, $00, $8d, $10, $8d, $00, $8d, $0d, $8d, $00, $8d, $10, $8d, $00, $8d
	.byte $41, $10
	.word @song3ref651
	.byte $8e
@song3ref671:
	.byte $2a, $90, $2a, $8e, $36, $90, $36, $8e, $34, $90, $34, $8e, $31, $90, $31, $00, $8d, $8e, $2a, $90, $2a, $98, $10, $8e
	.byte $34, $90, $34, $98, $10, $8e, $31, $90, $31, $00, $8d, $8e, $2a, $90, $2a, $8e, $34, $90, $34, $8e, $36, $90, $36, $8e
	.byte $31, $90, $31, $00, $8d, $8e, $34, $34, $98, $10, $8e, $36, $36, $98, $10, $8e, $31, $31, $00, $8d
	.byte $41, $28
	.word @song3ref671
	.byte $98
	.byte $41, $10
	.word @song3ref651
	.byte $41, $10
	.word @song3ref651
	.byte $41, $10
	.word @song3ref651
	.byte $41, $10
	.word @song3ref651
	.byte $8f, $44, $00
@song3ch3:
	.byte $96, $10, $81, $50, $ff, $1c, $18, $7c, $85, $79, $83, $77, $87, $75, $85, $74, $85, $72, $83, $71, $87, $7f, $00, $cd
	.byte $bf, $71, $51, $01, $d0, $50, $02, $14, $1f, $bb, $7f, $81, $8c, $1d, $85, $84
@song3ref799:
	.byte $14, $00, $83, $14, $00, $83, $14, $00, $83, $14, $00, $83, $14, $00, $83
	.byte $41, $0f
	.word @song3ref799
	.byte $41, $0f
	.word @song3ref799
@song3ref820:
	.byte $8c, $1d, $85, $84
@song3ref824:
	.byte $14, $00, $14, $00, $14, $00, $14, $00, $14, $00, $14, $00, $14, $00
	.byte $41, $0e
	.word @song3ref824
	.byte $41, $10
	.word @song3ref820
	.byte $14, $00, $14, $00, $14, $00, $14, $14, $14, $14, $14, $14, $14, $14, $8c, $1d, $8d, $00, $8d
@song3ref863:
	.byte $1d, $85, $00, $81
@song3ref867:
	.byte $80, $20, $81, $82, $14, $81, $00, $85, $80, $20, $20, $84, $14, $00, $80, $20, $84, $14, $00, $80, $20, $82, $14, $81
	.byte $00, $85, $84, $14, $00, $83, $14, $00, $87
	.byte $41, $18
	.word @song3ref867
	.byte $41, $18
	.word @song3ref867
	.byte $41, $18
	.word @song3ref867
	.byte $41, $18
	.word @song3ref867
	.byte $41, $18
	.word @song3ref867
	.byte $41, $18
	.word @song3ref867
	.byte $41, $15
	.word @song3ref867
	.byte $8c
	.byte $41, $1c
	.word @song3ref863
	.byte $41, $18
	.word @song3ref867
	.byte $41, $18
	.word @song3ref867
	.byte $41, $15
	.word @song3ref867
	.byte $8c
	.byte $41, $1c
	.word @song3ref863
	.byte $41, $18
	.word @song3ref867
	.byte $41, $18
	.word @song3ref867
	.byte $41, $15
	.word @song3ref867
	.byte $8f, $44, $00
@song3ch4:
	.byte $ff, $ff, $12, $00, $0b, $81, $12, $00, $0b, $81, $12, $00, $0b, $81, $12, $00, $0b
@song3ref968:
	.byte $81, $12, $00, $02, $81, $12, $00, $02, $81, $12, $00, $02, $81, $12, $00, $02, $81, $12, $00, $04, $81, $12, $00, $04
	.byte $81, $12, $00, $04, $81, $12, $00, $04
	.byte $41, $12
	.word @song3ref968
	.byte $0b, $12, $0b, $12, $0b, $12, $0b, $12, $0b, $12, $0b, $12, $0b, $12, $0b, $12, $02, $12, $02, $12, $02, $12, $02, $12
	.byte $02, $12, $02, $12, $02, $12, $02, $12, $04, $12, $04, $12, $04, $12, $04, $12, $04, $12, $04, $12, $04, $12, $04, $12
	.byte $02, $12, $02, $12, $02, $12, $02, $12, $12, $12, $12, $12, $12, $12, $12, $95, $00, $83, $00, $81
@song3ref1071:
	.byte $12, $81, $0b, $81, $0b, $81, $0b, $81, $14, $85, $00, $85, $12, $81, $02, $12, $02, $81, $14, $02, $00, $85, $12, $85
	.byte $12, $81, $04, $81, $04, $81, $04, $81, $14, $85, $00, $85, $12, $81, $02, $12, $02, $81, $14, $81, $02, $00, $83, $12
	.byte $85
	.byte $41, $31
	.word @song3ref1071
	.byte $41, $31
	.word @song3ref1071
	.byte $41, $31
	.word @song3ref1071
	.byte $41, $31
	.word @song3ref1071
	.byte $41, $31
	.word @song3ref1071
	.byte $41, $31
	.word @song3ref1071
	.byte $41, $31
	.word @song3ref1071
	.byte $00, $8d, $44, $00
; The DPCM aligner used to be here
@song5ch0:
	.byte $46, $03, $79, $92
@song5ref5:
	.byte $10, $81, $13, $81, $15, $81, $18, $89, $18, $85, $17, $81, $17, $81, $17, $81, $17, $89, $17, $85, $10, $81, $13, $81
	.byte $15, $81, $18, $89, $17, $85, $17, $89, $17, $81, $17, $85, $1d, $81, $1d, $81, $1d, $89, $1c, $89, $1c, $85, $1c, $89
	.byte $15, $89, $15, $85, $13, $89, $13, $89, $15, $85, $17, $85, $18, $85, $17, $85, $18, $85
	.byte $41, $42
	.word @song5ref5
	.byte $41, $42
	.word @song5ref5
	.byte $41, $42
	.word @song5ref5
	.byte $41, $42
	.word @song5ref5
	.byte $00, $bd
@song5ref85:
	.byte $1c, $89, $1c, $89, $17, $85, $18, $89, $18, $89, $1f, $85, $1c, $89, $1c, $89, $17, $85, $18, $89, $18, $89, $1c, $81
	.byte $1f, $81, $21, $89, $21, $89, $1f, $85, $18, $89, $18, $89, $17, $81, $18, $81, $21, $89, $21, $89, $1f, $85, $18, $89
	.byte $18, $89, $18, $81, $1c, $81, $1d, $89, $1d, $89, $1c, $85, $15, $89, $15, $89, $1c, $85, $1d, $89, $1d, $89, $1c, $85
	.byte $21, $89, $21, $89, $1c, $85, $15, $89, $15, $89, $13, $85, $15, $89, $15, $89, $13, $85, $17, $89, $17, $89, $15, $85
	.byte $17, $85, $24, $81, $23, $85, $21, $81, $20, $83, $4f, $03, $81
	.byte $41, $6b
	.word @song5ref85
	.byte $00, $44, $00
@song5ch1:
	.byte $bf, $bf, $bf, $bf, $4f, $03, $98
@song5ref208:
	.byte $05, $81, $05, $81, $05, $81, $05, $81, $05, $81, $05, $81, $05, $81, $05, $81
	.byte $41, $10
	.word @song5ref208
@song5ref227:
	.byte $07, $81, $07, $81, $07, $81, $07, $81, $07, $81, $07, $81, $07, $81, $07, $81
	.byte $41, $10
	.word @song5ref227
@song5ref246:
	.byte $09, $81, $09, $81, $09, $81, $09, $81, $09, $81, $09, $81, $09, $81, $09, $81
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $4f, $03
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref227
	.byte $41, $10
	.word @song5ref227
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $4f, $03
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref227
	.byte $41, $10
	.word @song5ref227
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $4f, $03
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref227
	.byte $41, $10
	.word @song5ref227
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $00, $bd
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref208
@song5ref375:
	.byte $02, $81, $02, $81, $02, $81, $02, $81, $02, $81, $02, $81, $02, $81, $02, $81
	.byte $41, $10
	.word @song5ref375
	.byte $41, $10
	.word @song5ref375
	.byte $41, $10
	.word @song5ref375
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref208
@song5ref406:
	.byte $04, $81, $04, $81, $04, $81, $04, $81, $04, $81, $04, $81, $04, $81, $04, $81
	.byte $41, $10
	.word @song5ref406
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref375
	.byte $41, $10
	.word @song5ref375
	.byte $41, $10
	.word @song5ref375
	.byte $41, $10
	.word @song5ref375
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref208
	.byte $41, $10
	.word @song5ref406
	.byte $41, $10
	.word @song5ref406
	.byte $00, $44, $00
@song5ch2:
@song5ref477:
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $41, $10
	.word @song5ref477
	.byte $bf, $bf, $bf, $bf, $bf, $81, $44, $00
@song5ch3:
	.byte $41, $10
	.word @song5ref477
	.byte $bf, $bf, $bf, $bf, $bf
@song5ref513:
	.byte $84, $14, $81, $86, $22, $81, $20, $81, $22, $81, $82, $14, $81, $86, $22, $81, $20, $81, $22, $81
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
@song5ref539:
	.byte $84, $14, $81, $86, $22, $81, $82, $14, $81, $86, $22, $81, $82, $14, $81, $86, $22, $81, $82, $14, $81, $14, $81
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref539
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref539
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref539
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref539
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref539
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref539
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref513
	.byte $41, $10
	.word @song5ref539
	.byte $00, $44, $00
@song5ch4:
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
@song5ref658:
	.byte $0e, $81, $0e, $81, $0e, $81, $0e, $81, $0e, $81, $0e, $81, $0e, $81, $0e, $81
	.byte $41, $10
	.word @song5ref658
@song5ref677:
	.byte $08, $81, $08, $81, $08, $81, $08, $81, $08, $81, $08, $81, $08, $81, $08, $81
	.byte $41, $10
	.word @song5ref677
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
	.byte $41, $10
	.word @song5ref246
@song5ref708:
	.byte $12, $0e, $0e, $81, $0e, $81, $0e, $81, $12, $0e, $0e, $81, $0e, $81, $0e, $81
	.byte $41, $10
	.word @song5ref708
@song5ref727:
	.byte $12, $08, $08, $81, $08, $81, $08, $81, $12, $08, $08, $81, $08, $81, $08, $81
	.byte $41, $10
	.word @song5ref727
@song5ref746:
	.byte $12, $09, $09, $81, $09, $81, $09, $81, $12, $09, $09, $81, $09, $81, $09, $81
	.byte $41, $10
	.word @song5ref746
	.byte $41, $10
	.word @song5ref746
	.byte $41, $10
	.word @song5ref746
	.byte $41, $10
	.word @song5ref708
	.byte $41, $10
	.word @song5ref708
	.byte $41, $10
	.word @song5ref727
	.byte $41, $10
	.word @song5ref727
@song5ref783:
	.byte $12, $09, $12, $09, $12, $09, $12, $12, $12, $09, $12, $09, $12, $09, $12, $12
	.byte $41, $10
	.word @song5ref783
@song5ref802:
	.byte $14, $14, $14, $14, $14, $14, $14, $14, $14, $14, $14, $14, $14, $14, $14, $14
	.byte $41, $10
	.word @song5ref802
	.byte $00, $bd
@song5ref823:
	.byte $12, $81, $09, $81, $09, $81, $09, $81, $14, $81, $09, $81, $09, $81, $09, $81
	.byte $41, $10
	.word @song5ref823
	.byte $41, $10
	.word @song5ref823
@song5ref845:
	.byte $12, $81, $09, $81, $14, $81, $09, $81, $14, $81, $09
@song5ref856:
	.byte $81, $14, $81, $14
@song5ref860:
	.byte $81, $12, $81, $0e, $81, $0e, $81, $0e, $81, $14, $81, $0e, $81, $0e, $81, $0e
	.byte $41, $10
	.word @song5ref860
	.byte $41, $10
	.word @song5ref860
@song5ref882:
	.byte $81, $12, $81, $0e, $81, $14, $81, $0e, $81, $14, $81, $0e, $81, $14, $81, $14
@song5ref898:
	.byte $81, $12, $81, $06, $81, $06, $81, $06, $81, $14, $81, $06, $81, $06, $81, $06
	.byte $41, $10
	.word @song5ref898
	.byte $41, $10
	.word @song5ref898
	.byte $81, $12, $81, $06, $81, $14, $81, $06, $81, $14, $81, $06
	.byte $41, $14
	.word @song5ref856
	.byte $41, $10
	.word @song5ref860
@song5ref938:
	.byte $81, $12, $81, $07, $81, $07, $81, $07, $81, $14, $81, $07, $81, $07, $81, $07, $81, $12, $81, $07, $81, $14, $81, $07
	.byte $81, $14, $81, $07, $81, $14, $81, $14, $81
	.byte $41, $10
	.word @song5ref823
	.byte $41, $10
	.word @song5ref823
	.byte $41, $10
	.word @song5ref823
	.byte $41, $1f
	.word @song5ref845
	.byte $41, $10
	.word @song5ref860
	.byte $41, $10
	.word @song5ref860
	.byte $41, $20
	.word @song5ref882
	.byte $41, $10
	.word @song5ref898
	.byte $41, $10
	.word @song5ref898
	.byte $81, $12, $81, $06, $81, $14, $81, $06, $81, $14, $81, $06
	.byte $41, $14
	.word @song5ref856
	.byte $41, $10
	.word @song5ref860
	.byte $41, $21
	.word @song5ref938
	.byte $81, $44, $00
