#define song_subtle_oddities 0
#define song_whats_a_future_funk 1
#define song_meowstuff 2
#define song_practice 3
#define song_magic_touch 4
#define song_power_trip 5
#define song_factory_time 6
#define song_infiltration 7
#define song_fire_aura 8
#define song_cryogenic 9
#define song_check_out 10
#define song_tiny_tunes 11
#define song_clubstep 12
#define song_clutterfunk_2 13
#define song_fantasy 14
#define song_endgame 15
#define song_slash_inferno 16
#define song_menu_theme_22 17
#define song_hell 18
#define song_driving_by_night 19
#define song_infinite_power 20
#define song_death_moon 21
#define song_chaoz_fantasy_extended 22
#define song_glitch_gremlin 23
#define song_xenogenesis 24
#define song_meltdown 25
#define song_against_the_odds_redux 26
#define song_kesobomb 27
#define song_scheming_weasel 28
#define song_stereo_madness_2 29
#define song_pyrophoric_legacy_remix 30
#define song_dance_of_the_violins 31
#define song_problematic 32
#define song_ninox 33
#define song_speed_racer 34
#define song_max 35