#define song_clutterfunk 0
#define song_dash 1
#define song_polargeist 2
#define song_infernoplex 3
#define song_hexagon_force 4
#define song_fingerdash 5
#define song_toe_2 6
#define song_geometrical_dominator 7
#define song_time_machine 8
#define song_electrodynamix 9
#define song_the_challenge 10
#define song_endgame 11
#define song_cycles 12
#define song_atthespeedoflight2 13
#define song_electroman_adventures 14
#define song_just_right 15
#define song_practice 16
#define song_clubstep 17
#define song_deadlocked 18
#define song_rainbow_tylenol 19
#define song_blast_processing 20
#define song_menu_theme 21
#define song_atthespeedoflight 22
#define song_haunted_woods 23
#define song_back_on_track 24
#define song_base_after_base 25
#define song_stalemate_greif_cut 26
#define song_against_the_odds_redux 27
#define song_stereo_madness 28
#define song_xstep 29
#define song_theory_of_everything 30
#define song_midnight 31
#define song_ground_to_space 32
#define song_retray 33
#define song_dry_out 34
#define song_cant_let_go 35
#define song_jumper 36
#define song_scheming_weasel 37
#define song_problematic 38
#define song_max 39