#define song_scheming_weasel 0
#define song_practice 1
#define song_retray_madness 2
#define song_back_on_retray 3
#define song_polartray 4
#define song_ground_to_retray 5
#define song_menu_theme 6
#define song_retray 7
#define song_desert_city 8
#define song_the_challenge 9
#define song_youve_been_trolled 10
#define song_max 11