#define song_atthespeedoflight 0
#define song_clutterfunk 1
#define song_time_machine 2
#define song_practice 3
#define song_polargeist 4
#define song_dash 5
#define song_infernoplex 6
#define song_fingerdash 7
#define song_atthespeedoflight2 8
#define song_toe_2 9
#define song_electroman_adventures 10
#define song_geometrical_dominator 11
#define song_menu_theme 12
#define song_rainbow_tylenol 13
#define song_electrodynamix 14
#define song_theory_of_everything 15
#define song_hexagon_force 16
#define song_the_challenge 17
#define song_haunted_woods 18
#define song_base_after_base 19
#define song_blast_processing 20
#define song_just_right 21
#define song_back_on_track 22
#define song_cant_let_go 23
#define song_clubstep 24
#define song_extraordinary_excitement 25
#define song_ground_to_space 26
#define song_cycles 27
#define song_deadlocked 28
#define song_midnight 29
#define song_stereo_madness 30
#define song_dry_out 31
#define song_xstep 32
#define song_casual_game_music_09 33
#define song_retray 34
#define song_jumper 35
#define song_desert_city 36
#define song_scheming_weasel 37
#define song_max 38