#define song_clutterfunk 0
#define song_midnight 1
#define song_cycles 2
#define song_practice 3
#define song_polargeist 4
#define song_atthespeedoflight 5
#define song_clubstep 6
#define song_fingerdash 7
#define song_back_on_track 8
#define song_toe_2 9
#define song_blast_processing 10
#define song_geometrical_dominator 11
#define song_base_after_base 12
#define song_electrodynamix 13
#define song_hexagon_force 14
#define song_deadlocked 15
#define song_time_machine 16
#define song_infernoplex 17
#define song_menu_theme 18
#define song_theory_of_everything 19
#define song_atthespeedoflight2 20
#define song_electroman_adventures 21
#define song_dash 22
#define song_cant_let_go 23
#define song_haunted_woods 24
#define song_rainbow_tylenol 25
#define song_extraordinary_excitement 26
#define song_stalemate_greif_cut 27
#define song_just_right 28
#define song_the_challenge 29
#define song_stereo_madness 30
#define song_dry_out 31
#define song_xstep 32
#define song_ground_to_space 33
#define song_scheming_weasel 34
#define song_retray 35
#define song_jumper 36
#define song_max 37