#define song_dry_out 0
#define song_didnt_realize_it_credits_mix_wip_in_game 1
#define song_clutterfunk 2
#define song_blast_processing 3
#define song_deadlocked 4
#define song_practice 5
#define song_polargeist 6
#define song_infernoplex 7
#define song_theory_of_everything 8
#define song_fingerdash 9
#define song_time_machine 10
#define song_geometrical_dominator 11
#define song_toe_2 12
#define song_haunted_woods 13
#define song_electrodynamix 14
#define song_rainbow_tylenol 15
#define song_electroman_adventures 16
#define song_hexagon_force 17
#define song_menu_theme_22 18
#define song_menu_theme 19
#define song_back_on_track 20
#define song_base_after_base 21
#define song_clubstep 22
#define song_jumper 23
#define song_cycles 24
#define song_ground_to_space_gda 25
#define song_just_right 26
#define song_stereo_madness 27
#define song_xstep 28
#define song_dash 29
#define song_extraordinary_excitement 30
#define song_stalemate_greif_cut 31
#define song_scheming_weasel 32
#define song_cant_let_go 33
#define song_ground_to_space 34
#define song_midnight 35
#define song_the_challenge 36
#define song_retray 37
#define song_rustic_runes 38
#define song_max 39