#define song_scheming_weasel 0
#define song_stay_inside_me 1
#define song_time_machine 2
#define song_insert_cash_fd2_version 3
#define song_super_underground_64 4
#define song_desert_city 5
#define song_golden_haze 6
#define song_menu_theme 7
#define song_stereo_madness 8
#define song_jumper 9
#define song_max 10