; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Famidash music:
; FAMISTUDIO_EXP_EPSM = 1
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1
; FAMISTUDIO_USE_ARPEGGIO = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1
; FAMISTUDIO_USE_DELTA_COUNTER = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_famidash_music8:=music_data_famidash_music8

music_data_famidash_music8:
	.byte 3
	.word @instruments
	.word @instruments_exp
	.word @samples-5
; 00 : Electroman Adventures
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song0ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song0ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song0ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song0ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song0ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song0ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song0ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song0ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song0ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song0ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song0ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song0ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song0ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song0ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song0ch19
	.endif
	.word 348,290
; 01 : Hexagon Force
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song1ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song1ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song1ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song1ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song1ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song1ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song1ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song1ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song1ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song1ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song1ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song1ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song1ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song1ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song1ch19
	.endif
	.word 333,278
; 03 : Menu Theme (2.2)
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song3ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song3ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song3ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song3ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song3ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song3ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song3ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song3ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song3ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song3ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song3ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song3ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song3ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song3ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song3ch19
	.endif
	.word 262,218

.export music_data_famidash_music8
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env24,@env8,@env36,@env0 ; 00 : rel hats
	.word @env12,@env45,@env36,@env0 ; 01 : kick
	.word @env21,@env30,@env36,@env0 ; 02 : blank
	.word @env11,@env8,@env36,@env0 ; 03 : hat
	.word @env25,@env35,@env2,@env0 ; 04 : snare
	.word @env43,@env9,@env36,@env0 ; 05 : tight triangle snare
	.word @env43,@env4,@env36,@env0 ; 06 : tight triangle kick
	.word @env3,@env30,@env38,@env0 ; 07 : sample
	.word @env34,@env37,@env36,@env0 ; 08 : clap
	.word @env27,@env30,@env36,@env0 ; 09 : loud blank string
	.word @env47,@env8,@env2,@env0 ; 0a : cymbal
	.word @env16,@env30,@env36,@env18 ; 0b : tom
	.word @env21,@env30,@env5,@env0 ; 0c : electroman lead
	.word @env16,@env30,@env23,@env0 ; 0d : hex guitar 2
	.word @env29,@env30,@env36,@env0 ; 0e : blank string
	.word @env16,@env30,@env36,@env0 ; 0f : DMC: drums + bass
	.word @env16,@env30,@env7,@env0 ; 10 : hex guitar 1
	.word @env1,@env30,@env36,@env0 ; 11 : echo
	.word @env33,@env19,@env36,@env0 ; 12 : octave jumping echo
	.word @env48,@env30,@env36,@env0 ; 13 : piano
	.word @env41,@env30,@env36,@env42 ; 14 : jaezu lead
	.word @env3,@env30,@env36,@env20 ; 15 : triangle drums
	.word @env31,@env30,@env36,@env0 ; 16 : infernoplex_piano
	.word @env53,@env30,@env36,@env0 ; 17 : menu acc
	.word @env50,@env30,@env39,@env0 ; 18 : shift string
	.word @env26,@env30,@env36,@env0 ; 19 : triangle pluck 3

@instruments_exp:


@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cb,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$13
@env2:
	.byte $c1,$c0,$00,$01
@env3:
	.byte $00,$c9,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$00,$08
@env4:
	.byte $da,$d0,$ce,$c4,$00,$03
@env5:
	.byte $c2,$c1,$03,$c0,$02,$c0,$00,$01
@env6:
	.byte $00,$c0,$bd,$bb,$ba,$ba,$bc,$bf,$c1,$c4,$c6,$c6,$c5,$c3,$00,$01
@env7:
	.byte $c3,$c2,$c1,$c2,$c2,$c1,$00,$02
@env8:
	.byte $bd,$c0,$00,$01
@env9:
	.byte $e3,$e2,$e1,$e0,$00,$03
@env10:
	.byte $00,$c0,$b9,$b5,$b6,$bc,$c4,$ca,$cb,$c7,$00,$01
@env11:
	.byte $00,$c8,$c4,$c2,$c0,$00,$04
@env12:
	.byte $00,$cd,$c9,$c5,$c2,$c1,$c0,$00,$06
@env13:
	.byte $c0,$c4,$c4,$00,$00
@env14:
	.byte $00,$c0,$c0,$bf,$03,$c0,$c0,$c1,$03,$c0,$00,$01
@env15:
	.byte $c0,$c4,$cc,$00,$00
@env16:
	.byte $00,$cf,$7f,$00,$02
@env17:
	.byte $00,$c0,$02,$bf,$05,$be,$0e,$bf,$05,$c0,$04,$c1,$05,$c2,$0e,$c1,$05,$c0,$c0,$00,$01
@env18:
	.byte $80,$c0,$d5,$00,$02
@env19:
	.byte $b4,$c0,$cc,$d8,$00,$00
@env20:
	.byte $80,$bf,$f1,$00,$02
@env21:
	.byte $04,$cf,$00,$01,$ca,$c6,$c4,$c2,$c0,$00,$08
@env22:
	.byte $00,$c0,$bf,$be,$bf,$c0,$c1,$c2,$c1,$00,$01
@env23:
	.byte $c3,$c2,$c1,$c3,$00,$03
@env24:
	.byte $00,$c8,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$0d
@env25:
	.byte $00,$cd,$cb,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env26:
	.byte $00,$cf,$02,$c0,$00,$03
@env27:
	.byte $0b,$c6,$c8,$ca,$cb,$cc,$05,$cb,$cb,$00,$08,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c3,$c2,$c1,$c0,$00,$1b
@env28:
	.byte $00,$c0,$bf,$bf,$be,$02,$bf,$bf,$c0,$c1,$c1,$c2,$02,$c1,$c1,$00,$01
@env29:
	.byte $08,$c5,$c6,$c7,$08,$c6,$00,$05,$c6,$c6,$c5,$02,$c4,$02,$c3,$02,$c2,$02,$c1,$c1,$c0,$00,$14
@env30:
	.byte $c0,$7f,$00,$01
@env31:
	.byte $00,$ce,$02,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$c9,$c9,$c8,$c7,$c6,$c5,$c3,$00,$10
@env32:
	.byte $c0,$cc,$cc,$00,$00
@env33:
	.byte $00,$cb,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$c2,$c2,$c1,$05,$c0,$00,$0f
@env34:
	.byte $00,$cf,$ca,$cc,$ca,$c9,$c8,$c6,$c5,$c4,$c2,$c1,$c0,$00,$0c
@env35:
	.byte $c6,$cc,$00,$01
@env36:
	.byte $7f,$00,$00
@env37:
	.byte $bc,$c1,$c0,$00,$02
@env38:
	.byte $c2,$7f,$00,$00
@env39:
	.byte $c1,$c2,$c1,$c0,$00,$00
@env40:
	.byte $00,$c0,$be,$bd,$be,$c0,$c2,$c3,$c2,$00,$01
@env41:
	.byte $0d,$c6,$c8,$ca,$cc,$03,$cb,$03,$ca,$03,$c9,$00,$0a,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$1c
@env42:
	.byte $00,$c0,$07,$c0,$c1,$c2,$c3,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$00,$03
@env43:
	.byte $00,$cf,$03,$c0,$00,$03
@env44:
	.byte $c0,$c0,$cc,$00,$00
@env45:
	.byte $c9,$cf,$00,$01
@env46:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env47:
	.byte $18,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c7,$c6,$02,$c5,$c5,$c4,$02,$c3,$03,$c2,$c2,$00,$15,$c2,$c2,$c1,$03,$c0,$00,$1c
@env48:
	.byte $00,$cf,$ce,$ce,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$c9,$c9,$c8,$c7,$c6,$c5,$c3,$00,$11
@env49:
	.byte $c0,$c3,$cc,$00,$00
@env50:
	.byte $08,$c4,$c5,$c6,$08,$c5,$00,$05,$c5,$04,$c4,$07,$c3,$05,$c2,$02,$c1,$02,$c0,$00,$12
@env51:
	.byte $c0,$c0,$cc,$cc,$c7,$c7,$00,$00
@env52:
	.byte $00,$c0,$bf,$be,$02,$bf,$c0,$c0,$c1,$c2,$02,$c1,$00,$01
@env53:
	.byte $00,$c8,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$06,$c1,$07,$c0,$00,$10
@env54:
	.byte $00,$c0,$bb,$ba,$bd,$c3,$c6,$c5,$00,$01
@env55:
	.byte $c0,$c5,$c5,$00,$00

@samples:
	.byte $4a+.lobyte(FAMISTUDIO_DPCM_PTR),$cc,$0f,$40,$04 ; 00 12 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e2,$0f,$40,$08 ; 01 34 (Pitch:15)
	.byte $51+.lobyte(FAMISTUDIO_DPCM_PTR),$b7,$0f,$40,$0a ; 02 56 (Pitch:15)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$cf,$0f,$40,$0b ; 03 78 (Pitch:15)
	.byte $39+.lobyte(FAMISTUDIO_DPCM_PTR),$98,$0f,$40,$08 ; 04 9 (Pitch:15)
	.byte $4b+.lobyte(FAMISTUDIO_DPCM_PTR),$d1,$0f,$40,$01 ; 05 andexcitement (Pitch:15)
	.byte $71+.lobyte(FAMISTUDIO_DPCM_PTR),$2c,$0c,$40,$06 ; 06 b (Pitch:12)
	.byte $60+.lobyte(FAMISTUDIO_DPCM_PTR),$76,$0c,$40,$08 ; 07 b 1 (Pitch:12)
	.byte $46+.lobyte(FAMISTUDIO_DPCM_PTR),$2e,$0f,$40,$0b ; 08 blastprocess sna (Pitch:15)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$a7,$4f,$40,$02 ; 09 Choir Ahh A (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$4f,$40,$07 ; 0a Choir Ahh B (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$4f,$40,$07 ; 0b Choir Ahh C (Pitch:15)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$4d,$40,$06 ; 0c Choir Ahh C# (Pitch:13)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4c,$40,$09 ; 0d Choir Ahh D (Pitch:12)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4e,$40,$09 ; 0e Choir Ahh D (Pitch:14)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4f,$40,$09 ; 0f Choir Ahh D (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4f,$40,$05 ; 10 Choir Ahh E (Pitch:15)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4f,$40,$04 ; 11 Choir Ahh G (Pitch:15)
	.byte $4c+.lobyte(FAMISTUDIO_DPCM_PTR),$75,$0f,$40,$03 ; 12 dash (Pitch:15)
	.byte $63+.lobyte(FAMISTUDIO_DPCM_PTR),$4e,$0e,$40,$05 ; 13 Dry Out Freeze (Pitch:14)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$01 ; 14 EON_AH (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0d,$40,$0b ; 15 fdbass A# (Pitch:13)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0f,$40,$0b ; 16 fdbass A# (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$09,$40,$00 ; 17 fdbass B (Pitch:9)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0a,$40,$00 ; 18 fdbass B (Pitch:10)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0c,$40,$00 ; 19 fdbass B (Pitch:12)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0d,$40,$00 ; 1a fdbass B (Pitch:13)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0e,$40,$00 ; 1b fdbass B (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0f,$40,$00 ; 1c fdbass B (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$03,$40,$04 ; 1d fdbass C (Pitch:3)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$04,$40,$04 ; 1e fdbass C (Pitch:4)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$05,$40,$04 ; 1f fdbass C (Pitch:5)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$06,$40,$04 ; 20 fdbass C (Pitch:6)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$07,$40,$04 ; 21 fdbass C (Pitch:7)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$08,$40,$04 ; 22 fdbass C (Pitch:8)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$09,$40,$04 ; 23 fdbass C (Pitch:9)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0a,$40,$04 ; 24 fdbass C (Pitch:10)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0b,$40,$04 ; 25 fdbass C (Pitch:11)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0c,$40,$04 ; 26 fdbass C (Pitch:12)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0d,$40,$04 ; 27 fdbass C (Pitch:13)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0e,$40,$04 ; 28 fdbass C (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0f,$40,$04 ; 29 fdbass C (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$05,$40,$06 ; 2a fdbass C# (Pitch:5)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$07,$40,$06 ; 2b fdbass C# (Pitch:7)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$08,$40,$06 ; 2c fdbass C# (Pitch:8)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0a,$40,$06 ; 2d fdbass C# (Pitch:10)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0b,$40,$06 ; 2e fdbass C# (Pitch:11)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0c,$40,$06 ; 2f fdbass C# (Pitch:12)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0d,$40,$06 ; 30 fdbass C# (Pitch:13)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0e,$40,$06 ; 31 fdbass C# (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$48,$0f,$40,$06 ; 32 fdbass C# (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0e,$40,$09 ; 33 fdbass D (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$09 ; 34 fdbass D (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$2c,$0e,$40,$01 ; 35 fdkick (Pitch:14)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$d3,$0f,$40,$02 ; 36 foralotoffun (Pitch:15)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$ae,$0f,$40,$03 ; 37 geometry (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$99,$0f,$40,$00 ; 38 getready (Pitch:15)
	.byte $52+.lobyte(FAMISTUDIO_DPCM_PTR),$7c,$0f,$40,$06 ; 39 go (Pitch:15)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$78,$0f,$40,$00 ; 3a hi (Pitch:15)
	.byte $6a+.lobyte(FAMISTUDIO_DPCM_PTR),$4e,$0f,$40,$03 ; 3b Human_Beat_Box (Pitch:15)
	.byte $0d+.lobyte(FAMISTUDIO_DPCM_PTR),$35,$0f,$40,$0a ; 3c is a (Pitch:15)
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$69,$0f,$40,$0a ; 3d machine (Pitch:15)
	.byte $38+.lobyte(FAMISTUDIO_DPCM_PTR),$ab,$0f,$40,$05 ; 3e one (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$42,$0f,$34,$02 ; 3f snare (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$33,$0f,$40,$0a ; 40 this (Pitch:15)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$69,$0f,$40,$0a ; 41 three (Pitch:15)
	.byte $11+.lobyte(FAMISTUDIO_DPCM_PTR),$32,$0f,$40,$02 ; 42 time (Pitch:15)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$68,$0f,$40,$00 ; 43 two (Pitch:15)
	.byte $4a+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0e,$40,$00 ; 44 voc1 (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$0e,$40,$03 ; 45 voc2 (Pitch:14)
	.byte $05+.lobyte(FAMISTUDIO_DPCM_PTR),$1e,$0e,$40,$03 ; 46 voc3 (Pitch:14)
	.byte $0d+.lobyte(FAMISTUDIO_DPCM_PTR),$4b,$0e,$40,$03 ; 47 voc4 (Pitch:14)
	.byte $4a+.lobyte(FAMISTUDIO_DPCM_PTR),$c2,$0f,$40,$09 ; 48 youwin (Pitch:15)

@song0ch0:
	.byte $46, $03, $77, $98, $21, $8d, $43, $50, $39, $2d, $21, $85, $43, $15, $85, $4f, $02, $9e, $10, $85, $00, $85, $10, $83
	.byte $00, $10, $85, $00, $8d, $0c, $85, $00, $85, $10, $85, $00, $85, $10
@song0ref39:
	.byte $85, $00, $85, $10, $85, $00, $85, $10, $85, $00, $85, $10, $85, $00, $85, $10, $83, $00, $10, $85, $00, $85, $09, $85
	.byte $10, $85, $00, $85, $10, $85, $00, $85, $11
	.byte $41, $16
	.word @song0ref39
	.byte $15, $85, $0c, $85, $00, $85, $13, $85, $00, $85, $13
	.byte $41, $21
	.word @song0ref39
	.byte $85, $00, $85, $4f, $00, $98, $21, $8d, $43, $50, $3c, $2d, $23, $83, $00, $84, $21, $81, $00, $81, $24, $85, $21, $85
	.byte $1f, $81, $00, $81, $21, $85, $00, $8d, $23, $24, $83, $00, $85, $1f, $85, $00, $85, $24, $85, $00
@song0ref133:
	.byte $85
@song0ref134:
	.byte $21, $85, $00, $8d, $21, $81, $00, $81, $24, $85, $21, $85, $1f, $81, $00, $81, $21, $85, $00, $85, $21, $81, $00, $81
	.byte $24, $81, $00, $81, $21, $81, $00, $81, $1c, $81, $00, $81, $22, $85, $00, $85, $1f
	.byte $41, $14
	.word @song0ref133
	.byte $8d, $1c, $81, $00, $81, $1c, $81, $00, $81, $1c, $81, $00, $81, $1f, $81, $00, $81, $1f, $81, $00, $81, $1f, $81, $00
	.byte $81, $9e
	.byte $41, $20
	.word @song0ref134
	.byte $24, $81, $00, $81, $26, $81, $00, $81, $21, $81, $00, $81, $1f, $81, $00, $81, $98, $1c, $81, $00, $81, $1c, $81, $00
	.byte $81, $23, $85, $24, $85, $24, $85, $23, $85, $21, $85, $1c, $85, $00, $85, $1c, $85, $24, $85, $21, $85, $50, $fe, $2e
	.byte $2f, $89, $43, $23, $89, $21, $81, $23, $81, $24, $85, $21, $81, $23, $81, $24, $85, $21, $81, $23, $81, $26, $85, $23
	.byte $81, $24, $81, $26, $85, $24, $81, $26, $81, $28, $85, $24, $81, $23, $81, $24, $81, $00, $81, $24, $81, $21, $81, $23
	.byte $85, $24, $81, $23, $81, $24, $81, $00, $81, $23, $85
@song0ref314:
	.byte $21, $89, $00, $81
@song0ref318:
	.byte $23, $85, $24, $85, $24, $85, $23, $85, $21, $85, $1d, $8d, $00, $85, $23, $85, $24, $85, $24, $85, $23, $85, $21, $85
	.byte $1f, $85, $87, $00, $85, $23, $85, $24, $85, $24, $85, $23, $85, $21, $85, $26, $8d, $24, $85, $23, $85, $24, $8d, $23
	.byte $85, $1f, $85, $21, $85, $87, $00, $85
	.byte $41, $32
	.word @song0ref318
	.byte $8d
	.byte $41, $39
	.word @song0ref314
	.byte $41, $36
	.word @song0ref314
	.byte $8d
	.byte $41, $39
	.word @song0ref314
	.byte $41, $36
	.word @song0ref314
	.byte $8d, $7f
@song0ref393:
	.byte $4f, $01, $8e
@song0ref396:
	.byte $21, $85, $92, $28, $81, $00, $81, $8e, $23, $85, $92, $28, $81, $00, $81, $8e, $24, $85, $92, $28, $81, $00, $81, $8e
	.byte $21, $85, $1d, $8d, $92, $24, $81, $00, $81, $29, $81, $00, $81, $24, $81, $00, $89, $24, $81, $00, $81, $29, $81, $00
	.byte $81, $24, $81, $00, $81, $8e, $24, $85, $92, $2b, $81, $00, $81, $8e, $23, $85, $92, $2b, $81, $00, $81, $8e, $24, $85
	.byte $23, $85, $21, $85, $26, $8d, $92, $26, $81, $00, $81, $2b, $81, $00, $81, $26, $81, $00, $81, $8e, $24, $85, $92, $26
	.byte $81, $00, $81, $2b, $81, $00, $81, $26, $81, $00, $81
	.byte $41, $41
	.word @song0ref393
	.byte $85, $4b, .lobyte(@env55), .hibyte(@env55), $30, $83, $45, $87, $4b, .lobyte(@env13), .hibyte(@env13), $30, $83, $45
	.byte $87, $7a, $4b, .lobyte(@env30), .hibyte(@env30), $4c, $a0, $13, $8d, $4f, $03, $8f, $15, $85, $18, $85, $17, $85, $17
	.byte $85, $18, $85, $15, $85, $15, $85, $50, $f9, $27, $28, $83, $43, $1c, $87, $43, $1c, $85, $18, $85, $1a, $85, $1c, $85
	.byte $18, $85, $1a, $85, $18, $85, $21, $85, $1c, $85, $1a, $85, $21, $85, $1c, $85, $1a, $85, $1c, $85, $50, $f9, $2c, $2d
	.byte $81, $43, $21, $81, $49, .lobyte(@env52), .hibyte(@env52), $87, $a0, $21, $85, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $21, $85, $1f, $85, $24, $85, $23, $85, $21, $85, $1f, $85, $21, $8d, $23, $8d, $50, $f4, $2f, $30, $43, $24, $83
	.byte $21, $8d, $26, $85, $49, .lobyte(@env52), .hibyte(@env52), $87, $49, .lobyte(@env0), .hibyte(@env0), $4a, $a0, $24
	.byte $85, $23, $85, $24, $85, $26, $85, $24, $85, $26, $85, $28, $85, $2d, $8d, $49, .lobyte(@env28), .hibyte(@env28), $87
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $43, $50, $0e, $39, $37, $43, $2b, $83, $43, $50, $f2, $37, $39, $43, $2d
	.byte $83, $49, .lobyte(@env14), .hibyte(@env14), $8f, $49, .lobyte(@env0), .hibyte(@env0), $4a, $43, $50, $0e, $39, $37
	.byte $43, $2b, $83, $43, $50, $f2, $37, $39, $43, $2d, $83, $43, $50, $0e, $39, $37, $43, $2b, $83, $43, $50, $f2, $37, $39
	.byte $43, $2d, $83, $43, $50, $0e, $39, $37, $43, $2b, $83, $43, $50, $f2, $37, $39, $43, $2d, $9b
@song0ref734:
	.byte $4f, $02, $84, $21, $85, $76, $9a, $15, $85, $73, $15, $85, $7a, $84, $21, $85, $73, $9a, $15, $85, $76, $15, $85, $73
	.byte $15, $85, $76, $15, $85, $7a, $84, $21, $85, $76, $9a, $15, $85, $73, $15, $85, $7a, $84, $21, $85, $73, $9a, $15, $85
	.byte $76, $15, $85, $73, $15, $85, $76, $15, $85, $7a
	.byte $41, $16
	.word @song0ref734
	.byte $76, $15, $85, $7a, $84, $24, $85, $23, $85, $24, $85, $23, $85, $7f, $4f, $02, $a0, $21, $85, $7a, $87, $76, $87, $79
	.byte $84, $21, $85, $73, $9a, $15, $85, $74, $15, $85, $72, $15, $85, $74, $15, $85, $78, $84, $21, $85, $74, $9a, $15, $85
	.byte $71, $15, $85, $77, $84, $21, $85, $71, $9a, $15, $85, $73, $15, $85, $71, $15, $85, $73, $15, $85, $76, $4f, $02, $84
	.byte $21, $85, $71, $9a, $15, $85, $73, $15, $85, $75, $84, $21, $85, $71, $9a, $15, $85, $72, $15, $85, $71, $15, $85, $72
	.byte $15, $85, $74, $84, $21, $85, $72, $9a, $15, $85, $71, $15, $85, $00, $85, $73, $84, $24, $85, $23, $85, $24, $85, $23
	.byte $85, $44, $00
@song0ch1:
	.byte $77, $4f, $02, $9e
@song0ref923:
	.byte $15, $85, $00, $85, $15, $85, $00, $85, $18, $85, $00, $85, $18, $85, $15, $85, $00
@song0ref940:
	.byte $85, $15, $85, $10, $85, $00, $85, $13, $85, $00, $85, $13
@song0ref952:
	.byte $85, $00, $85, $15, $85, $00, $85, $15, $85, $00, $85, $18, $85, $00, $85, $18, $85, $15, $85, $00, $8d, $15, $85, $00
	.byte $85, $13, $85, $00, $85, $14
	.byte $41, $15
	.word @song0ref952
	.byte $10, $85, $00, $85, $17, $85, $00, $85, $17
	.byte $41, $1e
	.word @song0ref952
	.byte $85, $00, $85, $4f, $02
	.byte $41, $3b
	.word @song0ref923
	.byte $41, $14
	.word @song0ref952
	.byte $41, $2a
	.word @song0ref940
	.byte $85, $00, $85, $ff, $ff, $b7, $98, $21, $8d, $00, $ad, $1c, $85, $87, $00, $ad, $1f, $8d, $00, $b5, $b7, $21, $8d, $00
	.byte $ad, $1c, $85, $87, $00, $ad, $1f, $8d, $00, $b5, $7f, $8e
@song0ref1047:
	.byte $21, $85, $00, $85, $21, $85, $00, $85, $21, $85, $00, $85, $2d, $85, $77, $98, $21, $8d, $7f, $00, $85, $8e, $24, $85
	.byte $00, $85, $24, $85, $00, $85, $24, $85, $77, $98, $1c, $85, $7f, $8e, $24, $85, $00, $85, $23, $85, $00, $85, $24, $85
	.byte $23, $85, $21, $85, $77, $98, $1f, $8d, $7f, $00, $85, $8e, $23, $85, $00, $85, $24, $85, $00, $85, $23, $85, $00, $85
	.byte $41, $3c
	.word @song0ref1047
	.byte $41, $3c
	.word @song0ref1047
	.byte $41, $3c
	.word @song0ref1047
	.byte $77, $98, $21, $8d, $43, $50, $39, $2d, $21, $85, $43, $15, $85, $7f, $8e
@song0ref1143:
	.byte $1c, $85, $00, $85, $1c, $85, $1d, $8d, $00, $85, $1d, $85, $00, $85, $1d, $85, $00, $85, $1d, $85, $00, $85, $1f, $85
	.byte $00, $85, $1f, $85, $00, $85, $1f, $85, $1f, $85, $1f, $85, $1f, $8d, $00, $85, $1f, $85, $00, $85, $21, $85, $00, $85
	.byte $1f, $85, $00, $85, $1c, $85, $00, $85, $1c, $85, $00, $85
	.byte $41, $34
	.word @song0ref1143
	.byte $4f, $01
	.byte $41, $5c
	.word @song0ref396
	.byte $41, $42
	.word @song0ref393
	.byte $00, $85, $23, $85, $00, $85, $24, $85, $00, $85, $23, $85, $00, $85, $7a, $4f, $02, $84
@song0ref1232:
	.byte $1c, $85, $00, $8d, $1c, $85, $00, $9d, $1c, $85, $00, $8d, $1c, $85, $00, $9d, $1c, $85, $00, $8d, $1c, $85, $00, $9d
	.byte $1c, $85, $00, $95, $1c, $85, $1c, $85, $1c, $85, $1c, $85, $51, $ff, $30, $4f, $02
	.byte $41, $24
	.word @song0ref1232
	.byte $44, $00
@song0ch2:
	.byte $ff, $ff, $ff, $ff, $9e
@song0ref1284:
	.byte $1c, $85, $00, $85, $1c, $85, $00, $85, $1c, $85, $00, $85, $1c, $83, $00, $1c, $85, $00, $8d, $18, $85, $00, $85, $1c
	.byte $85, $00, $85, $1c, $85, $00, $85
	.byte $41, $1f
	.word @song0ref1284
	.byte $41, $1f
	.word @song0ref1284
	.byte $41, $1f
	.word @song0ref1284
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song0ref1330:
	.byte $8e
@song0ref1331:
	.byte $28, $85, $00, $85, $28, $85, $00, $85, $28, $85, $00, $85, $34, $85, $29, $8d, $00, $85, $29, $85, $00, $85, $29, $85
	.byte $00, $85, $29, $85, $00, $85, $2b, $85, $00, $85, $2b, $85, $00, $85, $2b, $85, $2b, $85, $2b, $85, $32, $8d, $00, $85
	.byte $2b, $85, $00, $85, $2d, $85, $00, $85, $2b, $85, $00, $85
	.byte $41, $3c
	.word @song0ref1331
	.byte $41, $3c
	.word @song0ref1331
	.byte $41, $3c
	.word @song0ref1331
	.byte $41, $1e
	.word @song0ref1331
	.byte $84, $24, $85, $00, $85, $23, $85, $00, $85, $24, $85, $23, $85, $1f, $85, $26, $8d, $00, $85, $23, $85, $00, $85, $24
	.byte $85, $00, $85, $23, $85, $00, $85
	.byte $41, $1e
	.word @song0ref1330
@song0ref1437:
	.byte $84, $24, $85, $00, $85, $23, $85, $00, $85, $24, $85, $23, $85, $1f, $85, $26, $8d, $00, $85, $1f, $85, $00, $85, $21
	.byte $85, $00, $85, $1f, $85, $00, $85
	.byte $41, $1e
	.word @song0ref1330
	.byte $41, $1e
	.word @song0ref1437
	.byte $41, $1e
	.word @song0ref1330
	.byte $41, $1e
	.word @song0ref1437
	.byte $ff, $ff, $ff, $ff, $44, $00
@song0ch3:
@song0ref1487:
	.byte $82, $14, $85, $80, $21, $85
@song0ref1493:
	.byte $86, $1d, $85, $80, $21, $85, $82, $14, $85, $80, $21, $85, $86, $1d, $85, $80, $21, $85, $82, $14, $85, $80, $21, $85
	.byte $86, $1d, $85, $80, $21, $85
	.byte $41, $18
	.word @song0ref1487
	.byte $41, $18
	.word @song0ref1487
	.byte $41, $18
	.word @song0ref1487
	.byte $41, $18
	.word @song0ref1487
	.byte $41, $18
	.word @song0ref1487
	.byte $41, $18
	.word @song0ref1487
	.byte $41, $18
	.word @song0ref1487
	.byte $41, $18
	.word @song0ref1487
	.byte $41, $18
	.word @song0ref1487
	.byte $82, $14, $85, $80, $21, $85, $86, $1d, $85, $80, $21, $85, $82, $14, $85, $80, $21, $85, $86, $1d, $85, $80, $21, $85
	.byte $ac, $21, $8d
	.byte $41, $14
	.word @song0ref1493
	.byte $41, $18
	.word @song0ref1487
	.byte $41, $18
	.word @song0ref1487
	.byte $41, $18
	.word @song0ref1487
	.byte $41, $18
	.word @song0ref1487
	.byte $41, $18
	.word @song0ref1487
	.byte $41, $18
	.word @song0ref1487
	.byte $86, $1d, $85, $80, $21, $85, $86, $1d, $85, $80, $21, $85, $94, $20, $8d, $7c, $88, $14, $85, $86, $21, $85, $21, $85
	.byte $21, $85, $88, $14, $85, $86, $21, $85, $7f
@song0ref1631:
	.byte $82, $1f, $85, $80, $21, $85, $88, $14, $85, $80, $21, $85, $82, $1f, $85, $80, $21, $85, $88, $14, $85, $80, $21, $85
	.byte $82, $1f, $85, $80, $21, $85, $88, $14, $85, $80, $21, $85
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $41, $18
	.word @song0ref1631
	.byte $82, $1f, $85, $80, $21, $85, $88, $14, $85, $80, $21, $85, $82, $1f, $85, $80, $21, $85, $88, $14, $85, $80, $21, $85
	.byte $94, $19, $8d, $86, $1e, $85, $1e, $85, $1e, $85, $1e, $85, $1e, $85, $1e, $85, $94, $20, $8d
@song0ref1767:
	.byte $88, $14, $85, $86, $21, $85
@song0ref1773:
	.byte $82, $14, $85, $86, $21, $85, $88, $14, $85, $86, $21, $85, $82, $14, $85, $86, $21, $85, $88, $14, $85, $86, $21, $85
	.byte $82, $14, $85, $86, $21, $85
	.byte $41, $18
	.word @song0ref1767
	.byte $88, $14, $85, $86, $21, $85, $82, $14, $85, $86, $21, $85, $88, $14, $85, $86, $21, $85, $51, $ff, $00
	.byte $41, $14
	.word @song0ref1773
	.byte $41, $18
	.word @song0ref1767
	.byte $41, $14
	.word @song0ref1767
	.byte $44, $00
@song0ch4:
@song0ref1839:
	.byte $36, $85, $2e, $81, $00, $81, $40, $4c, $85, $2e, $81, $00, $81, $36, $85, $1a, $81, $00, $81, $40, $4c, $85, $2e, $81
	.byte $00, $81, $36, $85, $2e, $81, $00, $81, $40, $4c, $85, $2d, $81, $00, $81, $36, $85, $19, $81, $00, $81, $40, $4c, $85
	.byte $19, $81, $00, $81
	.byte $41, $2c
	.word @song0ref1839
	.byte $25, $81, $00, $81
	.byte $41, $30
	.word @song0ref1839
	.byte $41, $2c
	.word @song0ref1839
	.byte $25, $81, $00, $81
	.byte $41, $30
	.word @song0ref1839
	.byte $41, $2c
	.word @song0ref1839
	.byte $25, $81, $00, $81
	.byte $41, $30
	.word @song0ref1839
	.byte $41, $2c
	.word @song0ref1839
	.byte $25, $81, $00
@song0ref1927:
	.byte $81, $36, $85, $2e, $48, $01, $81, $2e, $48, $01, $81, $40, $4c, $85, $2e, $48, $01, $81, $2e, $48, $01, $81, $36, $85
	.byte $2e, $48, $01, $81, $2e, $48, $01, $81, $40, $4c, $85, $2e, $48, $01, $81, $2e
@song0ref1967:
	.byte $48, $01, $81, $36, $85, $1a, $48, $01, $81, $1a, $48, $01, $81, $40, $4c, $85, $1a, $48, $01, $81, $1a, $48, $01, $81
	.byte $36, $85, $1a, $48, $01, $81, $1a, $48, $01, $81, $40, $4c, $85, $1a, $48, $01, $81, $1a, $48, $01, $81, $36, $85, $30
	.byte $48, $01, $81, $30, $48, $01, $81, $40, $4c, $85, $30, $48, $01, $81, $30, $48, $01, $81, $36, $85, $30, $48, $01, $81
	.byte $30, $48, $01, $81, $40, $4c, $85, $30, $48, $01, $81, $30, $48, $01, $81, $36, $85, $1b, $48, $01, $81, $1b, $48, $01
	.byte $81, $40, $4c, $85, $1b, $48, $01, $81, $1b, $48, $01, $81, $36, $85, $1b, $48, $01, $81, $1b, $48, $01, $81, $40, $4c
	.byte $85, $1b, $48, $01, $81, $1b, $48, $01
	.byte $41, $1b
	.word @song0ref1927
@song0ref2098:
	.byte $28, $48, $01, $81, $28, $48, $01, $81, $40, $4c, $85, $28, $48, $01, $81, $28, $48, $01, $81, $36, $85, $28, $48, $01
	.byte $81, $28, $48, $01, $81, $40, $4c, $85, $28, $48, $01, $81, $28
	.byte $41, $1b
	.word @song0ref1967
@song0ref2138:
	.byte $1c, $48, $01, $81, $1c, $48, $01, $81, $40, $4c, $85, $1c, $48, $01, $81, $1c, $48, $01, $81, $36, $85, $30, $48, $01
	.byte $81, $30, $48, $01, $81, $40, $4c, $85, $30, $48, $01, $81, $30, $48, $01
	.byte $41, $1b
	.word @song0ref1927
	.byte $41, $15
	.word @song0ref2098
	.byte $41, $1b
	.word @song0ref1967
@song0ref2186:
	.byte $1c, $48, $01, $81, $1c, $48, $01, $81, $00, $85, $1c, $48, $01, $81, $1c, $48, $01, $81, $00, $85, $30, $48, $01, $81
	.byte $30, $48, $01, $81, $00, $85, $30, $48, $01, $81, $30, $48, $01
	.byte $41, $1b
	.word @song0ref1927
	.byte $41, $15
	.word @song0ref2098
	.byte $41, $1b
	.word @song0ref1967
	.byte $41, $15
	.word @song0ref2138
	.byte $48, $01
	.byte $41, $1b
	.word @song0ref1927
	.byte $41, $15
	.word @song0ref2098
	.byte $41, $1b
	.word @song0ref1967
	.byte $41, $15
	.word @song0ref2138
	.byte $48, $01
	.byte $41, $1b
	.word @song0ref1927
	.byte $41, $15
	.word @song0ref2098
	.byte $41, $1b
	.word @song0ref1967
	.byte $41, $15
	.word @song0ref2138
	.byte $48, $01
	.byte $41, $1b
	.word @song0ref1927
	.byte $41, $15
	.word @song0ref2098
	.byte $41, $1b
	.word @song0ref1967
	.byte $41, $15
	.word @song0ref2138
	.byte $48, $01
	.byte $41, $1b
	.word @song0ref1927
	.byte $41, $15
	.word @song0ref2098
	.byte $41, $1b
	.word @song0ref1967
	.byte $41, $15
	.word @song0ref2138
	.byte $48, $01
	.byte $41, $1b
	.word @song0ref1927
	.byte $41, $15
	.word @song0ref2098
	.byte $41, $1b
	.word @song0ref1967
	.byte $41, $15
	.word @song0ref2138
	.byte $48, $01
	.byte $41, $1b
	.word @song0ref1927
	.byte $41, $15
	.word @song0ref2098
	.byte $41, $1b
	.word @song0ref1967
	.byte $41, $15
	.word @song0ref2138
	.byte $48, $01
	.byte $41, $1b
	.word @song0ref1927
	.byte $41, $15
	.word @song0ref2098
	.byte $41, $1b
	.word @song0ref1967
	.byte $41, $15
	.word @song0ref2186
	.byte $48, $01
@song0ref2335:
	.byte $81, $36, $85, $2e, $81, $2e, $81, $2e, $81, $00, $81, $2e, $81, $2e, $81, $36, $85, $2e, $81, $2e, $81, $2e, $81, $00
	.byte $81, $2e, $81, $2e
	.byte $41, $1c
	.word @song0ref2335
	.byte $41, $1c
	.word @song0ref2335
	.byte $41, $1c
	.word @song0ref2335
	.byte $41, $1c
	.word @song0ref2335
	.byte $41, $1c
	.word @song0ref2335
	.byte $81, $36, $85, $2e, $81, $00, $81, $2e, $81, $00, $81, $2e, $81, $00, $81, $36, $85, $2e, $81, $00, $81, $2e, $81, $00
	.byte $81, $2e, $81, $00, $81, $36, $85, $2e, $81, $00, $89, $2e, $81, $00, $81, $36, $85, $2e, $81, $00, $89, $2e, $81, $00
	.byte $81, $44, $00
@song0ch19:
@song0ch18:
@song0ch17:
@song0ch16:
@song0ch15:
@song0ch14:
@song0ch13:
@song0ch12:
@song0ch11:
@song0ch10:
@song0ch9:
@song0ch8:
@song0ch7:
@song0ch6:
@song0ch5:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $44, $00
@song1ch0:
	.byte $46, $06, $71, $9c, $20, $72, $81, $73, $bb, $71, $1c, $75, $81, $78, $9b, $79, $1e, $7a, $81, $7b, $81, $7c, $81, $7d
	.byte $81, $7e, $81, $7f, $93, $20, $bd, $1c, $9d, $1e, $8b, $78, $81, $71, $81, $81, $73, $4f, $00, $84, $1b, $51, $06, $70
	.byte $81, $1e, $81, $20
@song1ref53:
	.byte $81, $78, $23, $85, $22, $72, $81, $71, $83, $78, $20, $81, $1e, $72, $81, $74, $1b, $72, $81, $78, $20, $89, $72, $85
	.byte $71, $81, $78, $27, $89, $72, $83, $78, $23, $85, $22, $72, $81, $71, $81, $72, $81, $78, $20, $81, $1e, $72, $81, $74
	.byte $1b, $72, $81, $78, $20, $85, $27, $81, $20, $81, $25, $72, $83, $71, $81, $78, $23, $72, $81, $78, $22, $83, $72
	.byte $41, $2c
	.word @song1ref53
	.byte $72, $81, $78, $23, $83, $72, $81, $78, $22, $72, $81, $78, $23, $81, $72, $83, $78, $27, $81, $72, $83, $78, $20, $85
	.byte $72, $83, $78, $22, $72, $81, $78, $23, $81, $22, $81, $1e, $72, $81, $78, $22, $83, $72, $81, $78, $23, $85, $22, $83
	.byte $72, $81, $78, $20, $72, $81, $78, $1e, $72, $83, $71, $81, $78, $20, $83, $72, $81, $78, $22, $81, $23
@song1ref196:
	.byte $81, $25, $81, $27, $81, $2a, $81, $2c, $81, $2f, $81, $2c, $85, $51, $fd, $30, $8d, $77, $51, $fd, $30, $4f, $00, $9c
	.byte $17, $81, $19, $83, $72, $51, $fd, $10, $81, $77, $51, $fd, $40, $1b, $85, $51, $fe, $00, $8b, $87
@song1ref240:
	.byte $77, $20, $85, $1e, $81, $1b, $81, $19, $85, $1b, $85, $17, $81, $16, $85, $17, $81, $16, $85, $17, $87, $85, $14, $83
	.byte $74, $81, $77, $14, $85, $17, $81, $19, $83, $81, $74, $1b, $85, $51, $fe, $00, $8b, $87, $77, $20, $85, $23, $81, $22
	.byte $81, $20, $83, $74, $81, $77, $1e, $85, $1b, $81, $19, $83, $74, $81, $77, $1b, $81, $17, $83, $74, $81, $77, $16, $85
	.byte $12, $85, $76, $14, $83, $74, $81, $76, $14, $85, $17, $81, $19, $83, $77, $81, $1b, $85, $51, $fd, $00, $93
	.byte $41, $32
	.word @song1ref240
	.byte $74, $4f, $02, $25, $51, $06, $a0, $81, $49, .lobyte(@env22), .hibyte(@env22), $81, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $81, $76, $51, $06, $e0, $9c, $27, $81, $49, .lobyte(@env40), .hibyte(@env40), $83, $78, $51, $06, $f0, $9c, $2a
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $81, $49, .lobyte(@env46), .hibyte(@env46), $81, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $81, $79, $4e, $00, $4f, $00, $84, $20, $81, $14, $81, $20, $81, $14, $81, $1e, $81, $23, $81, $27, $81, $29, $81
	.byte $49, .lobyte(@env22), .hibyte(@env22), $83, $49, .lobyte(@env0), .hibyte(@env0), $4a, $84, $2c, $81, $20, $81, $2a
	.byte $81, $49, .lobyte(@env46), .hibyte(@env46), $83, $49, .lobyte(@env0), .hibyte(@env0), $4a, $84, $27, $81, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $2a, $85, $2c, $81, $49, .lobyte(@env54), .hibyte(@env54), $8b, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $84, $27, $81, $2a, $81, $2c, $81, $2e, $81, $2f, $81, $2e, $81, $2f, $81, $31, $85, $27, $81, $2e, $85, $2c, $85
	.byte $2c, $85, $2c, $81, $2e, $81, $2f, $81, $31, $81, $49, .lobyte(@env22), .hibyte(@env22), $83, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $84, $2f, $81, $2e, $81, $2f, $81, $49, .lobyte(@env46), .hibyte(@env46), $83, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $84, $2e, $81, $49, .lobyte(@env0), .hibyte(@env0), $4a, $2a, $85, $2c, $81, $49, .lobyte(@env54), .hibyte(@env54)
	.byte $8f, $49, .lobyte(@env0), .hibyte(@env0), $4a, $84, $27, $81, $2a, $81, $27, $81, $20, $81, $1e, $81, $1b, $81, $1d
	.byte $85, $1b, $81, $17, $85, $7f, $4f, $01, $9c
@song1ref547:
	.byte $20, $81, $1b, $81, $20, $81, $1e, $85, $1b, $81, $1e, $81, $1d, $85, $1b, $81, $1d, $81, $1e, $85, $1b, $81, $1d, $81
	.byte $1e, $81
	.byte $41, $08
	.word @song1ref547
	.byte $1e, $85, $20, $95, $43, $50, $22, $2c, $24, $81, $78, $84, $1d, $1e, $1b, $17, $20, $81, $22, $81, $23, $81, $22, $81
	.byte $23, $81, $25, $81, $23, $81, $25, $81, $27
	.byte $41, $08
	.word @song1ref196
	.byte $89, $43, $50, $21, $38, $2b, $81, $23, $00, $23, $81, $20, $81, $25, $81, $71, $83, $78, $25, $81, $71, $83, $78, $1e
	.byte $81, $72, $83, $78, $1e, $81, $73, $83, $78, $1e, $81, $20, $89, $74, $83, $00, $81, $4e, $fe, $81, $77, $4f, $03, $9c
@song1ref660:
	.byte $08, $83, $72, $81, $77, $08, $85, $0b, $81, $0d, $83, $72, $81, $77, $0f, $85, $51, $fd, $00, $93, $77
@song1ref681:
	.byte $14, $85, $12, $81, $0f, $81, $0d, $85, $0f, $85, $0b, $81, $0a, $85, $0b, $81, $0a, $85, $0b, $87, $83, $4e, $fe, $81
	.byte $4f, $00
	.byte $41, $0f
	.word @song1ref660
@song1ref710:
	.byte $17, $81, $16, $81, $14, $85, $12, $85, $0f, $81, $0d, $83, $7c, $4f, $00, $19, $85, $1b, $85, $1e, $85, $2c, $51, $fd
	.byte $10, $9d, $44, $00
@song1ch1:
	.byte $b3, $70, $51, $01, $f0, $a2
@song1ref745:
	.byte $20, $81, $1e, $81, $20, $85, $20, $81, $1e, $81, $20, $85
	.byte $41, $0c
	.word @song1ref745
	.byte $20, $81, $1e, $81, $20, $81, $83, $4b, .lobyte(@env44), .hibyte(@env44)
@song1ref770:
	.byte $20, $81, $4d, $1e, $81, $4d, $20, $85, $4d, $20, $81, $4d, $1e, $81, $4d, $20, $85, $4d
	.byte $41, $0c
	.word @song1ref770
	.byte $4d
	.byte $41, $0c
	.word @song1ref770
	.byte $4d
	.byte $41, $0b
	.word @song1ref770
	.byte $81, $83, $4d
	.byte $41, $0c
	.word @song1ref770
	.byte $4d
	.byte $41, $0c
	.word @song1ref770
	.byte $4d
	.byte $41, $0c
	.word @song1ref770
	.byte $4d
	.byte $41, $0b
	.word @song1ref770
	.byte $81, $83, $4d
	.byte $41, $0c
	.word @song1ref770
	.byte $4d
	.byte $41, $0c
	.word @song1ref770
	.byte $4d
	.byte $41, $0c
	.word @song1ref770
	.byte $4d
	.byte $41, $0b
	.word @song1ref770
	.byte $81, $83, $4d
	.byte $41, $0a
	.word @song1ref770
	.byte $4d, $23, $85, $4d
	.byte $41, $0c
	.word @song1ref770
	.byte $4b, .lobyte(@env30), .hibyte(@env30), $4c, $a4
	.byte $41, $0c
	.word @song1ref745
	.byte $2c, $81, $2a, $81, $2c, $85, $2c, $81, $2a, $81, $2c, $81, $4f, $01, $9c
@song1ref871:
	.byte $14, $81, $45, $75, $81, $7f, $14, $81, $45, $81, $17, $45, $19, $81, $45, $77, $81, $7f, $50, $ed, $25, $27, $43, $1b
	.byte $83, $51, $fd, $80, $8b, $45, $85, $7f, $20, $81, $45, $81, $1e, $45, $1b, $45, $19, $45, $83, $1b, $45, $83, $17, $45
	.byte $16, $45, $83, $17, $45, $16, $81, $45, $81, $17, $81, $45, $81, $19, $81, $45, $81
	.byte $41, $0b
	.word @song1ref871
	.byte $45, $81, $77, $81, $7f, $1b, $85, $51, $fd, $80, $8b, $45, $85, $7f, $20, $81, $45, $81, $23, $45, $22, $45, $20, $81
	.byte $45, $77, $81, $7f, $1e, $45, $83, $1b, $45, $19, $81, $45, $77, $81, $7f, $1b, $45, $17, $81, $45, $77, $81, $7f, $16
	.byte $81, $45, $81, $12, $81, $45, $4f, $00, $81, $7c, $4b, .lobyte(@env44), .hibyte(@env44)
@song1ref1000:
	.byte $14, $83, $75, $81, $7c, $4d, $14, $85, $4d, $17, $81, $4d, $19, $83, $77, $81, $7c, $4d, $1b, $85, $51, $fd, $50, $93
	.byte $7c, $4d, $20, $85, $4d, $1e, $81, $4d, $1b, $81, $4d, $19, $85, $4d, $1b, $85, $4d, $17, $81, $4d, $16, $85, $4d, $17
	.byte $81, $4d, $16, $85, $4d, $17, $85, $4d, $19, $85, $4d
	.byte $41, $0f
	.word @song1ref1000
	.byte $4d, $23, $81, $4d, $22, $81, $4d, $20, $83, $77, $81, $7c, $4d, $1e, $85, $4d, $1b, $81, $4d, $19, $83, $77, $81, $7c
	.byte $4d, $1b, $81, $4d, $17, $83, $77, $81, $7c, $4d, $16, $85, $7f, $4d, $12, $85, $78, $4e, $ff, $4f, $03, $00, $81, $4b
	.byte .lobyte(@env30), .hibyte(@env30), $4c, $a6, $0f, $81, $1b, $81, $0f, $81, $1b, $81, $20, $81, $23, $81, $25, $81, $49
	.byte .lobyte(@env22), .hibyte(@env22), $83, $49, .lobyte(@env0), .hibyte(@env0), $4a, $a6, $27, $81, $20, $81, $27, $81
	.byte $49, .lobyte(@env46), .hibyte(@env46), $83, $49, .lobyte(@env0), .hibyte(@env0), $4a, $a6, $27, $81, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $2a, $85, $27, $81, $49, .lobyte(@env54), .hibyte(@env54), $8b, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $a6, $27, $81, $2a, $81, $2c, $81, $2a, $81, $2c, $81, $2a, $81, $2c, $81, $2c, $85, $27, $81, $2a, $85, $2c, $81
	.byte $20, $81, $2c, $81, $23, $81, $27, $81, $2a, $81, $2c, $81, $2c, $81, $49, .lobyte(@env22), .hibyte(@env22), $83, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $a6, $2c, $81, $2a, $81, $2c, $81, $49, .lobyte(@env46), .hibyte(@env46), $83
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $a6, $2a, $81, $49, .lobyte(@env0), .hibyte(@env0), $4a, $27, $85, $27, $81
	.byte $49, .lobyte(@env54), .hibyte(@env54), $8f, $49, .lobyte(@env0), .hibyte(@env0), $4a, $a6, $1b, $81, $1e, $81, $1b
	.byte $81, $14, $81, $12, $81, $0f, $81, $11, $85, $0f, $81, $0b, $83, $4f, $00, $81, $7f, $4e, $00, $4b, .lobyte(@env32)
	.byte .hibyte(@env32), $9c
@song1ref1278:
	.byte $2c, $81, $4d, $27, $81, $4d, $2c, $81, $4b, .lobyte(@env15), .hibyte(@env15), $2a, $85, $4b, .lobyte(@env32), .hibyte(@env32)
	.byte $27, $81, $4d, $2a, $81, $4b, .lobyte(@env49), .hibyte(@env49), $29, $85, $4b, .lobyte(@env32), .hibyte(@env32), $27
	.byte $81, $4d, $29, $81, $4b, .lobyte(@env15), .hibyte(@env15), $2a, $85, $4b, .lobyte(@env32), .hibyte(@env32), $27, $81
	.byte $4d, $29, $81, $4d, $2a, $81, $4d
	.byte $41, $08
	.word @song1ref1278
	.byte $4d, $2a, $85, $4b, .lobyte(@env51), .hibyte(@env51), $2c, $95, $43, $50, $21, $38, $2b, $81, $78, $4d, $84, $1d, $4d
	.byte $1e, $4d, $1b, $4d, $17, $4d, $14, $81, $4d, $16, $81, $4d, $17, $81, $4d, $16, $81, $4d, $17, $81, $4d, $19, $81, $4d
	.byte $17, $81, $4d, $19, $81, $4d, $1b, $81, $4d, $19, $81, $4d, $1b, $81, $4d, $1e, $81, $4d, $20, $89, $43, $50, $22, $2c
	.byte $24, $81, $4d, $17, $00, $4d, $17, $81, $4d, $14, $81, $4d, $19, $81, $71, $83, $78, $4d, $19, $81, $71, $83, $78, $4d
	.byte $12, $81, $72, $83, $78, $4d, $12, $81, $73, $83, $78, $4d, $12, $81, $4d, $14, $89, $74, $83, $7c, $4b, .lobyte(@env30)
	.byte .hibyte(@env30), $4c, $4f, $03, $a8
@song1ref1450:
	.byte $08, $83, $74, $81, $7c, $08, $85, $0b, $81, $0d, $83, $76, $81, $7c, $0f, $85, $51, $fe, $80, $93, $7c
	.byte $41, $13
	.word @song1ref681
	.byte $85, $0d, $85
	.byte $41, $0d
	.word @song1ref1450
	.byte $7c, $14, $85
	.byte $41, $0b
	.word @song1ref710
	.byte $85, $0f, $81, $4f, $01, $25, $85, $27, $85, $2a, $85, $20, $7f, $51, $fc, $00, $95, $87, $44, $00
@song1ch2:
	.byte $aa, $50, $21, $31, $21, $85, $00, $b5, $9e, $1c, $81, $00, $81, $1c, $83, $00, $83, $1c, $00, $1c
@song1ref1527:
	.byte $81, $1e, $81, $00, $81, $1e, $00, $1e
@song1ref1535:
	.byte $83, $00, $83, $20, $81, $1e, $81, $20, $00, $20, $81, $00, $81, $20
	.byte $41, $08
	.word @song1ref1535
	.byte $81, $00, $81, $20, $00, $20, $83, $00, $83, $20, $81, $00, $81, $20, $81, $84, $1c, $81, $00, $81, $1c, $81, $00, $85
	.byte $1c, $81, $00
	.byte $41, $09
	.word @song1ref1527
	.byte $43, $1e, $00, $8d
@song1ref1586:
	.byte $48, $03, $8c, $01, $84, $14, $81, $00, $14, $00, $87, $14, $00, $12, $00, $14, $81, $48, $03, $8c, $01, $00, $84, $14
	.byte $00, $14, $8b, $00, $14, $81, $00, $81, $48, $03, $8c, $01, $84, $10, $81, $00, $10, $83, $00, $83, $10, $00, $10, $00
	.byte $10, $00, $48, $03, $8c, $01, $00, $84, $12, $00, $12, $85, $00, $81, $12, $00, $12, $00, $83
	.byte $41, $33
	.word @song1ref1586
	.byte $14, $85, $48, $0a, $96, $2c, $00, $84, $17, $85, $48, $0a, $96, $2c, $00, $84, $17, $81, $10, $81, $10, $85, $48, $07
	.byte $96, $38, $00, $48, $08, $31, $00, $48, $09, $2c, $00, $48, $0a, $27, $00, $48, $04, $8c, $01, $84, $12
@song1ref1701:
	.byte $83, $48, $04, $8c, $01, $84, $10
@song1ref1708:
	.byte $83, $48, $04, $8a, $01, $84, $10, $48, $04, $8c, $01, $84, $10, $83, $48, $04, $8a, $01, $84, $10, $48, $04, $8c, $01
	.byte $84, $10, $81, $10, $48, $04, $8c, $01, $00, $84, $12, $81, $48, $04, $8a, $01, $84, $12, $48, $04, $8c, $01, $84, $12
	.byte $83, $48, $04, $8a, $01, $96, $36, $48, $04, $8c, $01, $96, $31, $2e, $27
@song1ref1771:
	.byte $8c, $01, $84, $14
@song1ref1775:
	.byte $14, $81, $8a, $01, $84, $14, $8b, $8a, $01, $84, $14, $14, $81, $00, $81
	.byte $41, $0b
	.word @song1ref1775
@song1ref1793:
	.byte $10, $81, $8a, $01, $84, $10, $8b, $8a, $01, $84, $10, $10, $81, $00, $81, $12, $81, $8a, $01, $84, $12, $87, $8a, $01
	.byte $84, $12, $83, $48, $01, $8a, $01, $84, $12
	.byte $41, $0d
	.word @song1ref1771
	.byte $41, $0b
	.word @song1ref1775
	.byte $41, $15
	.word @song1ref1793
	.byte $00
@song1ref1836:
	.byte $14, $14, $81
@song1ref1839:
	.byte $8a, $03, $84, $14
@song1ref1843:
	.byte $48, $08, $96, $20, $00, $48, $08, $1b, $00, $48, $08, $16, $00, $48, $04, $8a, $03, $00, $84, $14, $81, $00, $81, $14
	.byte $81, $48, $04
	.byte $41, $0e
	.word @song1ref1839
	.byte $10, $81, $48, $04, $8a, $03, $84, $10
	.byte $41, $08
	.word @song1ref1843
@song1ref1884:
	.byte $84, $10, $81, $00, $81, $12, $81, $48, $04, $8a, $03, $84, $12, $48, $08, $96, $20, $00, $48, $08, $1b, $00, $48, $04
	.byte $8a, $03, $00, $84, $12, $81, $48, $04, $8a, $03, $00, $00, $84
	.byte $41, $13
	.word @song1ref1836
	.byte $48, $04
	.byte $41, $0e
	.word @song1ref1839
	.byte $10, $81, $48, $04, $8a, $03, $84, $10
	.byte $41, $08
	.word @song1ref1843
	.byte $41, $12
	.word @song1ref1884
@song1ref1943:
	.byte $48, $04, $8c, $01, $84, $14, $83, $48, $04, $8a, $03, $84, $14, $48, $04, $8c, $01, $84, $14, $83, $48, $04, $8c, $01
	.byte $84, $14, $48, $04, $8a, $03, $84, $14, $17, $81, $48, $04, $8c, $01, $84, $17, $83, $48, $04, $8a, $03, $84, $17, $48
	.byte $04, $8c, $01, $84, $16, $83, $48, $04, $8c, $01, $84, $16, $48, $04, $8a, $03, $84, $16, $83
	.byte $41, $0c
	.word @song1ref1943
@song1ref2013:
	.byte $19, $81, $48, $04, $8c, $01, $84, $19, $83, $48, $04, $8a, $03, $84, $19, $48, $04, $8c, $01, $84, $17, $83, $48, $04
	.byte $8c, $01, $84, $17, $48, $04, $8a, $03, $84, $17, $83
	.byte $41, $1b
	.word @song1ref1943
	.byte $41, $0c
	.word @song1ref1943
	.byte $1b, $81, $48, $04, $8c, $01, $84, $20, $1e, $81, $48, $04, $8a, $03, $84, $1b, $48, $04, $8c, $01, $84, $1d, $83, $48
	.byte $04, $8c, $01, $84, $1b, $48, $04, $8a, $03, $84, $17
@song1ref2089:
	.byte $83
@song1ref2090:
	.byte $48, $04, $8c, $01, $84, $14, $83, $48, $04, $8a, $03, $84, $14, $48, $04, $8c, $01, $84, $17, $83, $48, $04, $8c, $01
	.byte $84, $17, $48, $04, $8a, $03, $84, $17
	.byte $41, $0f
	.word @song1ref2013
	.byte $41, $0c
	.word @song1ref2090
	.byte $41, $08
	.word @song1ref2013
	.byte $84, $19, $83, $48, $04, $8c, $01, $84, $19, $48, $04, $8a, $03, $84, $19
	.byte $41, $0d
	.word @song1ref1701
	.byte $41, $0a
	.word @song1ref1708
	.byte $83, $48, $04, $8a, $01, $84, $10
	.byte $41, $0d
	.word @song1ref2089
	.byte $41, $08
	.word @song1ref2013
	.byte $84, $19, $96, $2c, $84, $14, $96, $27, $84, $14, $96, $22, $84, $14, $96, $1d, $11, $8c, $01, $00, $fb, $01, $00, $e3
	.byte $8a, $01, $81, $01, $01, $01, $81, $01, $81, $01, $81, $01, $81, $8c, $01, $00, $9b, $44, $00
@song1ch3:
	.byte $76, $51, $fa, $00, $94, $1d, $83, $81, $78, $51, $f7, $20, $90, $1d, $81, $74, $51, $fa, $00, $86, $22, $81, $87, $78
	.byte $51, $f7, $20, $90, $1d, $81, $74, $51, $fa, $00, $86, $22, $81, $87, $79, $51, $f9, $00, $90, $1d, $85, $83, $74, $51
	.byte $fa, $00, $86, $22, $81, $79, $51, $f7, $30, $90, $1d, $81, $74, $51, $fa, $00, $86, $22, $81, $87, $7a, $51, $f7, $40
	.byte $90, $1d, $81, $51, $fa, $00, $86, $21, $81, $87, $7a, $51, $f7, $40, $90, $1d, $81, $51, $fa, $00, $86, $21, $81, $87
	.byte $7b, $51, $f7, $50, $90, $1d, $81, $71, $51, $fd, $00, $86, $21, $85, $74, $51, $fa, $00, $21, $81, $7b, $51, $f7, $50
	.byte $90, $1d, $81, $7a, $51, $f8, $00, $86, $21, $81, $83, $83, $7c, $51, $f7, $60, $90, $1d, $81, $51, $fa, $00, $86, $22
	.byte $83, $85, $7c, $51, $f7, $60, $90, $1d, $81, $51, $fa, $00, $86, $22, $83, $85, $7c, $51, $f9, $00, $90, $1d, $87, $81
	.byte $77, $51, $f7, $10, $86, $22, $81, $7c, $51, $f7, $60, $90, $1d, $81, $77, $51, $f9, $00, $86, $22, $83, $85, $7c, $51
	.byte $f7, $60, $90, $1d, $81, $78, $51, $f8, $00, $86, $22, $83, $85, $7c, $51, $f7, $60, $90, $1d, $81, $78, $51, $f8, $00
	.byte $86, $22, $83, $85, $7c, $51, $f9, $00, $90, $1d, $87, $81, $78, $51, $f7, $20, $86, $22, $81, $7c, $51, $f7, $60
@song1ref2448:
	.byte $90, $1d, $81, $71, $51, $0e, $a0, $84, $21, $81, $7c, $94, $20, $85
@song1ref2462:
	.byte $7d, $90, $1d, $81, $78, $86, $22, $89
@song1ref2470:
	.byte $7d, $90, $1d, $81, $78, $86, $22, $89, $7d, $90, $1d, $89, $78, $86, $22, $81
	.byte $41, $09
	.word @song1ref2462
	.byte $81, $78, $86, $22, $89, $7d, $90, $1d, $89, $78, $86, $22, $81, $7d
	.byte $41, $12
	.word @song1ref2448
	.byte $41, $09
	.word @song1ref2462
	.byte $81, $78, $86, $22, $89, $7d, $90, $1d, $89, $78, $86, $22, $81, $7d, $90, $1d, $81, $71, $51, $0e, $a0, $84, $21, $81
	.byte $7f, $94, $20, $85, $7d, $90, $1d, $81, $7f, $94, $20, $85, $86, $1e, $81
	.byte $41, $08
	.word @song1ref2470
	.byte $7f, $94, $20, $85, $20, $85, $88, $21, $81, $78, $86, $22, $85, $7f, $88, $21, $85, $78, $86, $22, $89, $7f, $88, $21
	.byte $85, $71, $51, $03, $30, $84, $21, $81, $7f, $88, $21, $81, $17, $17, $7a, $51, $e5, $10, $84, $1e, $7f, $51, $e5, $60
	.byte $20
@song1ref2600:
	.byte $7f
@song1ref2601:
	.byte $94, $1f, $85
@song1ref2604:
	.byte $88, $23, $81, $82, $22, $81, $21, $81, $20, $81, $88, $23, $81, $86, $1f, $81, $82, $21, $81, $86, $1f, $81
	.byte $41, $10
	.word @song1ref2604
	.byte $41, $10
	.word @song1ref2604
@song1ref2632:
	.byte $88, $23, $81, $82, $22, $81, $21, $81, $88, $23, $81, $86, $1f, $81, $88, $23, $81
	.byte $41, $12
	.word @song1ref2601
	.byte $41, $10
	.word @song1ref2604
	.byte $41, $10
	.word @song1ref2604
	.byte $41, $0c
	.word @song1ref2632
	.byte $41, $12
	.word @song1ref2601
	.byte $41, $10
	.word @song1ref2604
	.byte $41, $10
	.word @song1ref2604
	.byte $41, $0c
	.word @song1ref2632
	.byte $41, $12
	.word @song1ref2601
	.byte $41, $10
	.word @song1ref2604
	.byte $41, $10
	.word @song1ref2604
	.byte $41, $0c
	.word @song1ref2632
	.byte $41, $12
	.word @song1ref2601
	.byte $41, $10
	.word @song1ref2604
	.byte $41, $10
	.word @song1ref2604
	.byte $41, $09
	.word @song1ref2604
	.byte $71, $51, $0c, $d0, $84, $21, $83
	.byte $41, $12
	.word @song1ref2600
	.byte $41, $10
	.word @song1ref2604
	.byte $41, $10
	.word @song1ref2604
	.byte $41, $09
	.word @song1ref2604
	.byte $71, $51, $0c, $d0, $84, $21, $83
	.byte $41, $12
	.word @song1ref2600
	.byte $41, $10
	.word @song1ref2604
	.byte $41, $10
	.word @song1ref2604
	.byte $41, $09
	.word @song1ref2604
	.byte $71, $51, $0c, $d0, $84, $21, $83, $7f
@song1ref2743:
	.byte $94, $20, $85, $88, $21, $81, $94, $20, $85, $88, $21, $81
	.byte $41, $08
	.word @song1ref2743
	.byte $94, $20, $85, $88, $21, $85, $82, $21, $83
@song1ref2767:
	.byte $21, $88, $23, $81, $82, $22, $81, $21, $81, $21, $81, $88, $23, $81, $82, $21, $81, $21, $81, $86, $1f, $82
	.byte $41, $09
	.word @song1ref2767
	.byte $71, $51, $0b, $f0, $84, $21, $85, $51, $fe, $00, $94, $1f, $a9, $d3, $e7, $7c, $82, $14, $81, $14, $14, $14, $81, $14
	.byte $81, $14, $81, $14, $71, $51, $20, $c0, $84, $21, $7f, $51, $fd, $00, $94, $1f, $9d, $44, $00
@song1ch4:
	.byte $ff, $bf, $1b, $85, $1b, $89, $1b, $85, $31, $85, $31, $81, $31, $95
@song1ref2850:
	.byte $25, $85, $25, $89, $25, $81, $24, $81, $25, $85, $25, $81, $25, $8d, $25
@song1ref2865:
	.byte $85, $2d, $85, $2d, $89, $2d, $81, $2d, $81, $2d, $85, $24, $81, $24, $89, $24, $81, $24, $85
	.byte $41, $22
	.word @song1ref2850
	.byte $25, $85, $25, $81, $2f, $85, $2f, $85, $2d, $81, $2d, $85, $2d, $81, $2d, $81, $24, $81, $24, $81, $24
	.byte $41, $12
	.word @song1ref2865
	.byte $81, $24
@song1ref2913:
	.byte $81, $36, $81, $25, $81, $40, $4c, $81, $25, $85, $25, $81, $40, $4c, $81, $25
	.byte $41, $0e
	.word @song1ref2913
@song1ref2932:
	.byte $81, $36, $81, $2d, $81, $40, $4c, $81, $2d, $85, $2d, $81, $40, $4c, $81, $2d, $81, $36, $81, $24, $81, $40, $4c, $81
	.byte $24, $85, $40, $4c, $81, $24, $81, $40, $4c
	.byte $41, $0e
	.word @song1ref2913
	.byte $41, $0e
	.word @song1ref2913
	.byte $41, $1c
	.word @song1ref2932
	.byte $41, $0e
	.word @song1ref2913
	.byte $41, $0e
	.word @song1ref2913
	.byte $41, $1c
	.word @song1ref2932
	.byte $41, $0e
	.word @song1ref2913
	.byte $41, $0e
	.word @song1ref2913
	.byte $41, $1c
	.word @song1ref2932
@song1ref2992:
	.byte $81, $36, $81
@song1ref2995:
	.byte $25, $81, $40, $4c, $81, $36, $81, $25
@song1ref3003:
	.byte $81, $36, $81, $40, $4c, $81, $2f, $81, $36, $81, $2f, $81, $40, $4c, $81, $36, $81, $26, $81, $36, $81, $40, $4c, $81
	.byte $26
	.byte $41, $0f
	.word @song1ref2992
@song1ref3031:
	.byte $27, $81, $36, $81, $27, $81, $40, $4c, $81, $36, $81, $2f
	.byte $41, $09
	.word @song1ref3003
	.byte $41, $1d
	.word @song1ref2995
	.byte $41, $0f
	.word @song1ref2992
	.byte $16, $81, $36, $81, $24, $81, $40, $4c, $81, $18, $85, $23, $81, $40, $4c, $81, $2b
	.byte $41, $09
	.word @song1ref2992
	.byte $2f, $81, $36, $81, $40, $4c, $81
	.byte $41, $0b
	.word @song1ref3031
	.byte $41, $09
	.word @song1ref3003
	.byte $25, $81
@song1ref3087:
	.byte $40, $4c, $81, $36, $81, $2f, $81, $36, $81, $40, $4c, $81
	.byte $41, $08
	.word @song1ref3031
	.byte $27, $85, $27, $81, $40, $4c, $81, $27
@song1ref3110:
	.byte $81, $36, $81, $2d, $81, $40, $4c, $81, $36, $81, $2d, $81, $40, $4c
	.byte $41, $0c
	.word @song1ref3110
	.byte $41, $08
	.word @song1ref2932
	.byte $81, $36, $81, $25, $36
	.byte $41, $0a
	.word @song1ref3087
	.byte $36, $81, $36, $81, $27, $36, $40, $4c, $81, $27, $81, $36, $81, $36, $81, $36, $81, $36, $36
	.byte $41, $22
	.word @song1ref2850
	.byte $41, $22
	.word @song1ref2850
	.byte $40, $4c, $9d, $44, $00
@song1ch19:
@song1ch18:
@song1ch17:
@song1ch16:
@song1ch15:
@song1ch14:
@song1ch13:
@song1ch12:
@song1ch11:
@song1ch10:
@song1ch9:
@song1ch8:
@song1ch7:
@song1ch6:
@song1ch5:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $9f, $44, $00
@song2ch0:
	.byte $46, $01
@song2ch0loop:
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $42
	.word @song2ch0loop
@song2ch19:
@song2ch18:
@song2ch17:
@song2ch16:
@song2ch15:
@song2ch14:
@song2ch13:
@song2ch12:
@song2ch11:
@song2ch10:
@song2ch9:
@song2ch8:
@song2ch7:
@song2ch6:
@song2ch5:
@song2ch3:
@song2ch2:
@song2ch1:
@song2ch1loop:
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $42
	.word @song2ch1loop
@song2ch4:
@song2ch4loop:
	.byte $3b, $3c, $89, $3a, $40, $55, $05, $04, $03, $02, $01, $06, $37, $39, $1e, $81, $1f, $81, $20, $2b, $21, $22, $2c, $23
	.byte $2d, $18, $24, $19, $25, $2e, $26, $2f, $1a, $27, $30, $16, $1b, $28, $31, $1c, $29, $32, $34, $17, $1d, $2a, $33, $35
	.byte $09, $36, $40, $4c, $40, $4d, $3d, $40, $4f, $3e, $3f, $40, $50, $40, $4e, $40, $51, $40, $52, $40, $53, $40, $54, $14
	.byte $38, $13, $07, $08, $0e, $0d, $0f, $0b, $0c, $10, $11, $12, $0a, $15, $00, $9d, $9f, $42
	.word @song2ch4loop
@song3ch0:
	.byte $46, $06
@song3ch0loop:
	.byte $79, $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $02, $ae
@song3ref12:
	.byte $19, $19, $25, $0d, $20, $81, $19, $1f, $81, $1e, $81, $1c, $81, $19, $1c, $1e, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $4f, $02, $17, $17, $25, $0b, $20, $81, $19, $1f, $81, $1e, $81, $1c, $81, $19, $1c, $1e, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $4f, $02, $16, $16, $25, $0a, $20, $81, $19, $1f, $81, $1e, $81, $1c, $81, $19, $1c, $1e, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $4f, $02, $15, $15, $25, $09, $20, $81, $19, $1f, $81, $1e, $81, $1c, $81, $19
	.byte $1c, $1e, $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $02
	.byte $41, $40
	.word @song3ref12
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $02
	.byte $41, $40
	.word @song3ref12
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $02
	.byte $41, $30
	.word @song3ref12
	.byte $49, .lobyte(@env6), .hibyte(@env6), $4f, $02, $9c, $09, $8b, $43, $0b, $8b, $45, $81, $42
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
	.byte $7a, $49, .lobyte(@env10), .hibyte(@env10), $4f, $01, $b0
@song3ref145:
	.byte $0d, $97, $45, $83, $b0, $0b, $97, $45, $83, $0a, $97, $45, $83, $09, $8b, $45, $0b, $8b, $45, $49, .lobyte(@env10)
	.byte .hibyte(@env10), $4f, $01
	.byte $41, $12
	.word @song3ref145
	.byte $49, .lobyte(@env10), .hibyte(@env10), $4f, $01
	.byte $41, $12
	.word @song3ref145
	.byte $49, .lobyte(@env10), .hibyte(@env10), $4f, $01, $0d, $99, $45, $81, $b0, $0b, $99, $45, $81, $0a, $99, $45, $81, $49
	.byte .lobyte(@env17), .hibyte(@env17), $4f, $03, $9c, $09, $8b, $43, $0b, $8b, $45, $81, $42
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
	.byte $b2
@song3ref216:
	.byte $19, $19, $25, $3d, $19, $00, $25, $31, $00, $8d, $17, $17, $23, $3d, $17, $00, $23, $2f, $00, $8d, $16, $16, $22, $3d
	.byte $16, $00, $22, $2e, $00, $16, $22, $16, $00, $85, $15, $15, $21, $3d, $15, $00, $23, $2f, $00, $17, $23, $17, $00, $81
	.byte $23, $00
	.byte $41, $32
	.word @song3ref216
	.byte $41, $32
	.word @song3ref216
	.byte $41, $21
	.word @song3ref216
	.byte $a5, $42
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
	.byte $7c, $86
@song3ref282:
	.byte $20, $81, $21, $81, $7a, $1e, $7c, $21, $7a, $23, $21, $81, $7c, $21, $81, $7a, $1f, $7c, $21, $81, $78, $21, $7a, $21
	.byte $23, $81, $7c, $21, $81, $7a, $1e, $7c, $21, $7a, $1c, $1e, $81, $7c, $1d, $81, $7a, $1f, $21, $81, $7c, $1e, $78, $23
	.byte $7c
	.byte $41, $20
	.word @song3ref282
	.byte $7c
	.byte $41, $20
	.word @song3ref282
	.byte $7c
	.byte $41, $20
	.word @song3ref282
	.byte $7c
	.byte $41, $20
	.word @song3ref282
	.byte $7c
	.byte $41, $20
	.word @song3ref282
	.byte $7c
	.byte $41, $20
	.word @song3ref282
	.byte $7c
	.byte $41, $14
	.word @song3ref282
	.byte $7a, $23, $89, $78, $80, $23, $89, $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
@song3ref369:
	.byte $52, $41
@song3ref371:
	.byte $36, $85, $40, $4c, $81, $36, $83, $36, $36, $81, $40, $4c, $85, $36, $81, $36, $81, $40, $4c, $81, $36, $40, $4c, $81
	.byte $36, $36, $81, $40, $4c, $40, $4c, $40, $4c, $40, $4c
	.byte $41, $1b
	.word @song3ref371
	.byte $41, $1b
	.word @song3ref369
	.byte $41, $1b
	.word @song3ref371
	.byte $41, $1b
	.word @song3ref369
	.byte $41, $1b
	.word @song3ref371
	.byte $41, $1b
	.word @song3ref369
	.byte $36, $85, $40, $4c, $83, $36, $81, $36, $36, $81, $40, $4c, $85, $36, $81, $36, $85, $36, $85, $36, $81, $36, $85, $42
	.word @song3ch4loop
@song3ch19:
@song3ch18:
@song3ch17:
@song3ch16:
@song3ch15:
@song3ch14:
@song3ch13:
@song3ch12:
@song3ch11:
@song3ch10:
@song3ch9:
@song3ch8:
@song3ch7:
@song3ch6:
@song3ch5:
@song3ch5loop:
	.byte $ff, $ff, $ff, $ff, $42
	.word @song3ch5loop
