#define song_electroman_adventures 0
#define song_select_payment_type 1
#define song_jumper 2
#define song_stay_inside_me 3
#define song_super_underground_64 4
#define song_ground_to_space 5
#define song_insert_cash_fd2_version 6
#define song_menu_theme 7
#define song_pyrophoric_ginished 8
#define song_desert_city 9
#define song_golden_haze 10
#define song_scheming_weasel 11
#define song_stereo_madness 12
#define song_time_machine 13
#define song_max 14