
// Exported by export_levels.py

#define EASY 0
#define NORMAL 1
#define HARD 2
#define HARDER 3
#define INSANE 4
#define DEMON 5
#define AUTO 6

const uint8_t difficulty_list[] = {
	EASY,	// stereomadness
	EASY,	// backontrack
	NORMAL,	// polargeist
	NORMAL,	// dryout
	HARD,	// baseafterbase
	HARD,	// cantletgo
	HARDER,	// jumper
	HARDER,	// timemachine
	HARDER,	// cycles
	INSANE,	// xstep
	INSANE,	// clutterfunk
	INSANE,	// theoryofeverything
	INSANE,	// electroman
	DEMON,	// clubstep
	INSANE,	// electrodynamix
	INSANE,	// hexagonforce
	HARDER,	// blastprocessing
	DEMON,	// toe2
	HARDER,	// geometricaldominator
	DEMON,	// deadlocked
	INSANE,	// fingerdash
	INSANE,	// dash
	EASY,	// retray
	NORMAL,	// thechallenge
	NORMAL,	// dorabaebasic4
	HARD,	// dreamer
	HARD,	// groundtospace
	HARDER,	// kappaclysm
	HARDER,	// sunshine
	HARDER,	// revolution
	INSANE,	// lostinthewoods
	INSANE,	// bloodbathbutno
	INSANE,	// rainbowtylenol
	INSANE,	// aprettyeasylevel
	DEMON,	// thelightningroad
	DEMON,	// nightmare
	DEMON,	// demonpark
	DEMON,	// decode
	DEMON,	// dearnostalgists
	DEMON,	// problematic
	DEMON,	// firetemple
	DEMON,	// foresttemple
	DEMON,	// luckydraw
};

const uint8_t stars_list[] = {
	1,	// stereomadness
	2,	// backontrack
	3,	// polargeist
	4,	// dryout
	5,	// baseafterbase
	6,	// cantletgo
	7,	// jumper
	8,	// timemachine
	9,	// cycles
	10,	// xstep
	11,	// clutterfunk
	12,	// theoryofeverything
	10,	// electroman
	14,	// clubstep
	12,	// electrodynamix
	12,	// hexagonforce
	10,	// blastprocessing
	14,	// toe2
	10,	// geometricaldominator
	15,	// deadlocked
	12,	// fingerdash
	12,	// dash
	2,	// retray
	3,	// thechallenge
	3,	// dorabaebasic4
	4,	// dreamer
	5,	// groundtospace
	6,	// kappaclysm
	7,	// sunshine
	7,	// revolution
	8,	// lostinthewoods
	8,	// bloodbathbutno
	8,	// rainbowtylenol
	9,	// aprettyeasylevel
	10,	// thelightningroad
	10,	// nightmare
	10,	// demonpark
	10,	// decode
	10,	// dearnostalgists
	10,	// problematic
	10,	// firetemple
	10,	// foresttemple
	10,	// luckydraw
};
