
// Exported by export_levels.py

const uint8_t difficulty_list[] = {
	EASY,	// stereomadness
	EASY,	// backontrack
	NORMAL,	// polargeist
	NORMAL,	// dryout
	HARD,	// baseafterbase
	HARD,	// cantletgo
	HARDER,	// jumper
	HARDER,	// timemachine
	HARDER,	// cycles
	INSANE,	// xstep
	INSANE,	// clutterfunk
	INSANE,	// theoryofeverything
	INSANE,	// electroman
	DEMON,	// clubstep
	INSANE,	// electrodynamix
	INSANE,	// hexagonforce
	HARDER,	// blastprocessing
	DEMON,	// toe2
	HARDER,	// geometricaldominator
	DEMON,	// deadlocked
	INSANE,	// fingerdash
	INSANE,	// dash
	EASY,	// retray
	NORMAL,	// leveleasy
	NORMAL,	// thechallenge
	NORMAL,	// dorabaebasic4
	NORMAL,	// dorabaebasic6
	HARD,	// dreamer
	HARD,	// groundtospace
	HARD,	// subzero
	HARDER,	// kappaclysm
	HARDER,	// sunshine
	HARDER,	// revolution
	HARDER,	// funnygameholiday
	INSANE,	// lostinthewoods
	INSANE,	// bloodbathbutno
	INSANE,	// rainbowtylenol
	INSANE,	// greif
	INSANE,	// aprettyeasylevel
	INSANE,	// extraordinaryexcitement
	DEMON,	// thelightningroad
	DEMON,	// nightmare
	DEMON,	// demonpark
	DEMON,	// firetemple
	DEMON,	// foresttemple
};

const uint8_t stars_list[] = {
	1,	// stereomadness
	2,	// backontrack
	3,	// polargeist
	4,	// dryout
	5,	// baseafterbase
	6,	// cantletgo
	7,	// jumper
	8,	// timemachine
	9,	// cycles
	10,	// xstep
	11,	// clutterfunk
	12,	// theoryofeverything
	10,	// electroman
	14,	// clubstep
	12,	// electrodynamix
	12,	// hexagonforce
	10,	// blastprocessing
	14,	// toe2
	10,	// geometricaldominator
	15,	// deadlocked
	12,	// fingerdash
	12,	// dash
	2,	// retray
	3,	// leveleasy
	3,	// thechallenge
	3,	// dorabaebasic4
	3,	// dorabaebasic6
	4,	// dreamer
	5,	// groundtospace
	5,	// subzero
	6,	// kappaclysm
	7,	// sunshine
	7,	// revolution
	7,	// funnygameholiday
	8,	// lostinthewoods
	8,	// bloodbathbutno
	8,	// rainbowtylenol
	8,	// greif
	9,	// aprettyeasylevel
	9,	// extraordinaryexcitement
	10,	// thelightningroad
	10,	// nightmare
	10,	// demonpark
	10,	// firetemple
	10,	// foresttemple
};
