
// Exported by export_levels.py

const uint8_t DECOTYPE[] = {
	DECO1,	// stereomadness
	DECO1,	// backontrack
	DECO1,	// polargeist
	DECO1,	// dryout
	DECO1,	// baseafterbase
	DECO1,	// cantletgo
	DECO1,	// jumper
	DECO1,	// timemachine
	DECO1,	// cycles
	DECOCLOUD,	// xstep
	DECOCLOUD,	// clutterfunk
	DECOCLOUD,	// theoryofeverything
	DECOCLOUD,	// electroman
	DECO1,	// clubstep
	DECO1,	// electrodynamix
	DECO1,	// hexagonforce
	DECO1,	// blastprocessing
	DECO1,	// toe2
	DECO1,	// geometricaldominator
	EXTRASPRITES1,	// deadlocked
	EXTRASPRITES1,	// fingerdash
	EXTRASPRITES1,	// dash
	DECO1,	// retray
	EXTRASPRITES1,	// thechallenge
	DECO1,	// dreamer
	DECO1,	// groundtospace
	DECOCLOUD,	// kappaclysm
	DECO1,	// sunshine
	DECO1,	// revolution
	DECO1,	// lostinthewoods
	DECO1,	// bloodbathbutno
	EXTRASPRITES1,	// rainbowtylenol
	DECO1,	// aprettyeasylevel
	DECO1,	// thelightningroad
	DECOCLOUD,	// nightmare
	DECO1,	// demonpark
	DECO1,	// deathmoon
	DECOCLOUD,	// decode
	EXTRASPRITES1,	// dearnostalgists
	DECO1,	// problematic
	DECO1,	// firetemple
	DECO1,	// foresttemple
	DECOCLOUD,	// luckydraw
};

const uint8_t spike_set[] = {
	SPIKESA,	// stereomadness
	SPIKESA,	// backontrack
	SPIKESA,	// polargeist
	SPIKESA,	// dryout
	SPIKESA,	// baseafterbase
	SPIKESA,	// cantletgo
	SPIKESA,	// jumper
	SPIKESA,	// timemachine
	SPIKESA,	// cycles
	SPIKESB,	// xstep
	SPIKESB,	// clutterfunk
	SPIKESB,	// theoryofeverything
	SPIKESB,	// electroman
	SPIKESA,	// clubstep
	SPIKESA,	// electrodynamix
	SPIKESB,	// hexagonforce
	SPIKESB,	// blastprocessing
	SPIKESA,	// toe2
	SPIKESC,	// geometricaldominator
	SPIKESA,	// deadlocked
	SPIKESC,	// fingerdash
	SPIKESA,	// dash
	SPIKESA,	// retray
	SPIKESA,	// thechallenge
	SPIKESA,	// dreamer
	SPIKESA,	// groundtospace
	SPIKESC,	// kappaclysm
	SPIKESA,	// sunshine
	SPIKESA,	// revolution
	SPIKESA,	// lostinthewoods
	SPIKESA,	// bloodbathbutno
	SPIKESA,	// rainbowtylenol
	SPIKESC,	// aprettyeasylevel
	SPIKESC,	// thelightningroad
	SPIKESB,	// nightmare
	SPIKESC,	// demonpark
	SPIKESB,	// deathmoon
	SPIKESB,	// decode
	SPIKESC,	// dearnostalgists
	SPIKESB,	// problematic
	SPIKESB,	// firetemple
	SPIKESB,	// foresttemple
	SPIKESB,	// luckydraw
};


const uint8_t block_set[] = {
	BLOCKSA,	// stereomadness
	BLOCKSA,	// backontrack
	BLOCKSA,	// polargeist
	BLOCKSA,	// dryout
	BLOCKSA,	// baseafterbase
	BLOCKSA,	// cantletgo
	BLOCKSA,	// jumper
	BLOCKSA,	// timemachine
	BLOCKSA,	// cycles
	BLOCKSC,	// xstep
	BLOCKSD,	// clutterfunk
	BLOCKSB,	// theoryofeverything
	BLOCKSB,	// electroman
	BLOCKSB,	// clubstep
	BLOCKSB,	// electrodynamix
	BLOCKSB,	// hexagonforce
	BLOCKSB,	// blastprocessing
	BLOCKSB,	// toe2
	BLOCKSB,	// geometricaldominator
	BLOCKSB,	// deadlocked
	BLOCKSB,	// fingerdash
	BLOCKSB,	// dash
	BLOCKSB,	// retray
	BLOCKSB,	// thechallenge
	BLOCKSB,	// dreamer
	BLOCKSB,	// groundtospace
	BLOCKSB,	// kappaclysm
	BLOCKSB,	// sunshine
	BLOCKSB,	// revolution
	BLOCKSB,	// lostinthewoods
	BLOCKSB,	// bloodbathbutno
	BLOCKSA,	// rainbowtylenol
	BLOCKSC,	// aprettyeasylevel
	BLOCKSA,	// thelightningroad
	BLOCKSC,	// nightmare
	BLOCKSA,	// demonpark
	BLOCKSB,	// deathmoon
	BLOCKSB,	// decode
	BLOCKSA,	// dearnostalgists
	BLOCKSB,	// problematic
	BLOCKSB,	// firetemple
	BLOCKSB,	// foresttemple
	BLOCKSB,	// luckydraw
};

const uint8_t saw_set[] = {
	SAWBLADESA,	// stereomadness
	SAWBLADESA,	// backontrack
	SAWBLADESA,	// polargeist
	SAWBLADESA,	// dryout
	SAWBLADESA,	// baseafterbase
	SAWBLADESA,	// cantletgo
	SAWBLADESA,	// jumper
	SAWBLADESA,	// timemachine
	SAWBLADESA,	// cycles
	SAWBLADESA,	// xstep
	SAWBLADESA,	// clutterfunk
	SAWBLADESA,	// theoryofeverything
	SAWBLADESA,	// electroman
	SAWBLADESA,	// clubstep
	SAWBLADESA,	// electrodynamix
	SAWBLADESA,	// hexagonforce
	SAWBLADESA,	// blastprocessing
	SAWBLADESA,	// toe2
	SAWBLADESA,	// geometricaldominator
	SAWBLADESA,	// deadlocked
	SAWBLADESA,	// fingerdash
	SAWBLADESA,	// dash
	SAWBLADESA,	// retray
	SAWBLADESA,	// thechallenge
	SAWBLADESA,	// dreamer
	SAWBLADESA,	// groundtospace
	SAWBLADESA,	// kappaclysm
	SAWBLADESA,	// sunshine
	SAWBLADESA,	// revolution
	SAWBLADESA,	// lostinthewoods
	SAWBLADESA,	// bloodbathbutno
	SAWBLADESA,	// rainbowtylenol
	SAWBLADESA,	// aprettyeasylevel
	SAWBLADESA,	// thelightningroad
	SAWBLADESA,	// nightmare
	SAWBLADESA,	// demonpark
	SAWBLADESA,	// deathmoon
	SAWBLADESA,	// decode
	SAWBLADESA,	// dearnostalgists
	SAWBLADESA,	// problematic
	SAWBLADESA,	// firetemple
	SAWBLADESA,	// foresttemple
	LETTERBANK,	// luckydraw
};


#define EASY 0
#define NORMAL 1
#define HARD 2
#define HARDER 3
#define INSANE 4
#define DEMON 5
#define AUTO 6

const uint8_t difficulty_list[] = {
	EASY,	// stereomadness
	EASY,	// backontrack
	NORMAL,	// polargeist
	NORMAL,	// dryout
	HARD,	// baseafterbase
	HARD,	// cantletgo
	HARDER,	// jumper
	HARDER,	// timemachine
	HARDER,	// cycles
	INSANE,	// xstep
	INSANE,	// clutterfunk
	INSANE,	// theoryofeverything
	INSANE,	// electroman
	DEMON,	// clubstep
	INSANE,	// electrodynamix
	INSANE,	// hexagonforce
	HARDER,	// blastprocessing
	DEMON,	// toe2
	HARDER,	// geometricaldominator
	DEMON,	// deadlocked
	INSANE,	// fingerdash
	INSANE,	// dash
	EASY,	// retray
	NORMAL,	// thechallenge
	HARD,	// dreamer
	HARD,	// groundtospace
	HARDER,	// kappaclysm
	HARDER,	// sunshine
	HARDER,	// revolution
	INSANE,	// lostinthewoods
	INSANE,	// bloodbathbutno
	INSANE,	// rainbowtylenol
	INSANE,	// aprettyeasylevel
	DEMON,	// thelightningroad
	DEMON,	// nightmare
	DEMON,	// demonpark
	DEMON,	// deathmoon
	DEMON,	// decode
	DEMON,	// dearnostalgists
	DEMON,	// problematic
	DEMON,	// firetemple
	DEMON,	// foresttemple
	DEMON,	// luckydraw
};

const uint8_t stars_list[] = {
	1,	// stereomadness
	2,	// backontrack
	3,	// polargeist
	4,	// dryout
	5,	// baseafterbase
	6,	// cantletgo
	7,	// jumper
	8,	// timemachine
	9,	// cycles
	10,	// xstep
	11,	// clutterfunk
	12,	// theoryofeverything
	10,	// electroman
	14,	// clubstep
	12,	// electrodynamix
	12,	// hexagonforce
	10,	// blastprocessing
	14,	// toe2
	10,	// geometricaldominator
	15,	// deadlocked
	12,	// fingerdash
	12,	// dash
	2,	// retray
	3,	// thechallenge
	4,	// dreamer
	5,	// groundtospace
	6,	// kappaclysm
	7,	// sunshine
	7,	// revolution
	8,	// lostinthewoods
	8,	// bloodbathbutno
	8,	// rainbowtylenol
	9,	// aprettyeasylevel
	10,	// thelightningroad
	10,	// nightmare
	10,	// demonpark
	10,	// deathmoon
	10,	// decode
	10,	// dearnostalgists
	10,	// problematic
	10,	// firetemple
	10,	// foresttemple
	10,	// luckydraw
};
