#define song_atthespeedoflightfull 0
#define song_kratos 1
#define song_practice 2
#define song_jawbreaker 3
#define song_thermodynamix_acheron 4
#define song_pyrophoric_xl 5
#define song_toe_2 6
#define song_cryogenic 7
#define song_haunted_woods 8
#define song_clutterfunk_2 9
#define song_fracture_wcropolix 10
#define song_endgame 11
#define song_time_machine 12
#define song_slash_inferno 13
#define song_explorers 14
#define song_final_battle 15
#define song_supernova 16
#define song_careless 17
#define song_slow_down 18
#define song_clubstep 19
#define song_golden_haze_not_retray 20
#define song_infinite_power 21
#define song_windfall 22
#define song_flow 23
#define song_menu_theme_human_capturing_mix 24
#define song_lost 25
#define song_speed_racer 26
#define song_scheming_weasel 27
#define song_max 28