name: Cache CC65
description: Caches CC65 and builds it from source if missing
inputs:
  cc65Ref:
    description: "CC65 Git Ref (used to checkout a fixed version)"
    required: false
    default: "master"
  cc65Path:
    description: "CC65 path to cache"
    required: false
    default: ${{ github.workspace }}/opt/cc65
runs:
  using: "composite"
  steps:
      # Cache CC65
      - uses: actions/cache@v4
        id: cache_cc65
        with:
          path: ${{ inputs.cc65Path }}
          key: ${{ runner.os }}-cc65-${{ inputs.cc65Ref }}-${{ hashFiles('.github/actions/cache_cc65/*') }}
      # Checkout CC65
      - uses: actions/checkout@v4
        if: steps.cache_cc65.outputs.cache-hit != 'true'
        with:
          repository: cc65/cc65
          ref: ${{ inputs.cc65Ref }}
          path: './cc65'
      # Build CC65
      - if: steps.cache_cc65.outputs.cache-hit != 'true'
        run: |
          cd cc65
          PREFIX=${{ inputs.cc65Path }} make
          PREFIX=${{ inputs.cc65Path }} make install
        shell: bash
