
// Exported by export_levels.py

const uint8_t difficulty_list[] = {
	EASY,	// stereomadness
	EASY,	// backontrack
	NORMAL,	// polargeist
	NORMAL,	// dryout
	HARD,	// baseafterbase
	HARD,	// cantletgo
	HARDER,	// jumper
	HARDER,	// timemachine
	HARDER,	// cycles
	INSANE,	// xstep
	INSANE,	// clutterfunk
	INSANE,	// theoryofeverything
	INSANE,	// electroman
	DEMON,	// clubstep
	INSANE,	// electrodynamix
	INSANE,	// hexagonforce
	HARDER,	// blastprocessing
	DEMON,	// toe2
	HARDER,	// geometricaldominator
	DEMON,	// deadlocked
	INSANE,	// fingerdash
	INSANE,	// dash
	EASY,	// retray
	EASY,	// sonar
	EASY,	// darkparadise
	NORMAL,	// leveleasy
	NORMAL,	// thechallenge
	NORMAL,	// dorabaebasic4
	NORMAL,	// ninox
	NORMAL,	// dorabaebasic6
	HARD,	// dreamer
	HARD,	// lookatthislevel
	HARD,	// groundtospace
	HARD,	// subzero
	HARD,	// moonlight
	HARD,	// fofii_fofii_fofii
	HARDER,	// pyrophoric
	HARDER,	// cryogenic
	HARDER,	// oceane
	HARDER,	// generationretro
	HARDER,	// scarletsurge
	HARDER,	// tinytunes
	HARDER,	// kappaclysm
	HARDER,	// sunshine
	HARDER,	// revolution
	HARDER,	// funnygameholiday
	HARDER,	// fireaura
	HARDER,	// rainbowdust
	HARDER,	// factorytime
	HARDER,	// thesteamworks
	INSANE,	// lostinthewoods
	INSANE,	// bloodbathbutno
	INSANE,	// rainbowtylenol
	INSANE,	// greif
	INSANE,	// dorabaebasic10
	INSANE,	// subtleoddities
	INSANE,	// powertrip
	INSANE,	// danceofviolins
	INSANE,	// aprettyeasylevel
	INSANE,	// highlife
	INSANE,	// extraordinaryexcitement
	DEMON,	// thelightningroad
	DEMON,	// nightmare
	DEMON,	// demonpark
	DEMON,	// supercycles
	DEMON,	// xx
	DEMON,	// problematic
	DEMON,	// infinitecircles
	DEMON,	// sonicblaster
	DEMON,	// decode
	DEMON,	// deathmoon
	DEMON,	// dearnostalgists
	DEMON,	// clutterfunk2
	DEMON,	// motion
	DEMON,	// speedracer
	DEMON,	// endorphinrush
	DEMON,	// everymadness
	DEMON,	// skeletalshenanigans
	DEMON,	// hell
	DEMON,	// invisiblelight
	DEMON,	// firetemple
	DEMON,	// pgclubstep
	DEMON,	// deadlyclubstep
	DEMON,	// thermodynamix
	DEMON,	// foresttemple
	DEMON,	// ninecircles
	DEMON,	// fairydust
	DEMON,	// futurefunk
	DEMON,	// stalemate
	DEMON,	// eighto
	DEMON,	// hi
	DEMON,	// eon
	DEMON,	// windylandscape
	DEMON,	// sonicwave
	DEMON,	// bloodbath
	DEMON,	// cataclysm
	DEMON,	// aftermath
	DEMON,	// silentclubstep
	DEMON,	// kratos
	DEMON,	// aftercatabath
	DEMON,	// slaughterhouse
	DEMON,	// everyend
	DEMON,	// luckydraw
};

const uint8_t stars_list[] = {
	1,	// stereomadness
	2,	// backontrack
	3,	// polargeist
	4,	// dryout
	5,	// baseafterbase
	6,	// cantletgo
	7,	// jumper
	8,	// timemachine
	9,	// cycles
	10,	// xstep
	11,	// clutterfunk
	12,	// theoryofeverything
	10,	// electroman
	14,	// clubstep
	12,	// electrodynamix
	12,	// hexagonforce
	10,	// blastprocessing
	14,	// toe2
	10,	// geometricaldominator
	15,	// deadlocked
	12,	// fingerdash
	12,	// dash
	2,	// retray
	2,	// sonar
	2,	// darkparadise
	3,	// leveleasy
	3,	// thechallenge
	3,	// dorabaebasic4
	3,	// ninox
	3,	// dorabaebasic6
	4,	// dreamer
	4,	// lookatthislevel
	5,	// groundtospace
	5,	// subzero
	5,	// moonlight
	5,	// fofii_fofii_fofii
	6,	// pyrophoric
	6,	// cryogenic
	6,	// oceane
	6,	// generationretro
	6,	// scarletsurge
	6,	// tinytunes
	6,	// kappaclysm
	7,	// sunshine
	7,	// revolution
	7,	// funnygameholiday
	7,	// fireaura
	7,	// rainbowdust
	7,	// factorytime
	7,	// thesteamworks
	8,	// lostinthewoods
	8,	// bloodbathbutno
	8,	// rainbowtylenol
	8,	// greif
	8,	// dorabaebasic10
	8,	// subtleoddities
	8,	// powertrip
	8,	// danceofviolins
	9,	// aprettyeasylevel
	9,	// highlife
	9,	// extraordinaryexcitement
	10,	// thelightningroad
	10,	// nightmare
	10,	// demonpark
	10,	// supercycles
	10,	// xx
	10,	// problematic
	10,	// infinitecircles
	10,	// sonicblaster
	10,	// decode
	10,	// deathmoon
	10,	// dearnostalgists
	10,	// clutterfunk2
	10,	// motion
	10,	// speedracer
	10,	// endorphinrush
	10,	// everymadness
	10,	// skeletalshenanigans
	10,	// hell
	10,	// invisiblelight
	10,	// firetemple
	10,	// pgclubstep
	10,	// deadlyclubstep
	10,	// thermodynamix
	10,	// foresttemple
	10,	// ninecircles
	10,	// fairydust
	10,	// futurefunk
	10,	// stalemate
	10,	// eighto
	10,	// hi
	10,	// eon
	10,	// windylandscape
	10,	// sonicwave
	10,	// bloodbath
	10,	// cataclysm
	10,	// aftermath
	10,	// silentclubstep
	10,	// kratos
	10,	// aftercatabath
	10,	// slaughterhouse
	10,	// everyend
	10,	// luckydraw
};
