#define song_golden_haze 0
#define song_pyrophoric_sniper_and_crafty_edition 1
#define song_electroman_adventures 2
#define song_stalemate 3
#define song_super_underground_64 4
#define song_lost_xva_remix_slaughterhouse 5
#define song_stay_inside_me 6
#define song_ground_to_space 7
#define song_jumper 8
#define song_insert_cash_fd2_version 9
#define song_select_payment_type 10
#define song_stereo_madness 11
#define song_desert_city 12
#define song_every_end 13
#define song_menu_theme 14
#define song_scheming_weasel 15
#define song_time_machine 16
#define song_max 17