#define song_electroman_adventures 0
#define song_lost_xva_remix_slaughterhouse 1
#define song_select_payment_type 2
#define song_stay_inside_me 3
#define song_every_end 4
#define song_ground_to_space 5
#define song_jumper 6
#define song_insert_cash_fd2_version 7
#define song_pyrophoric_ginished 8
#define song_stereo_madness 9
#define song_time_machine 10
#define song_desert_city 11
#define song_golden_haze 12
#define song_menu_theme 13
#define song_scheming_weasel 14
#define song_stalemate 15
#define song_super_underground_64 16
#define song_max 17