#define song_atthespeedoflightfull 0
#define song_menu_theme_human_capturing_mix 1
#define song_clubstep 2
#define song_practice 3
#define song_cryogenic 4
#define song_time_machine 5
#define song_endgame 6
#define song_haunted_woods 7
#define song_jawbreaker 8
#define song_golden_haze_not_retray 9
#define song_lost 10
#define song_supernova 11
#define song_windfall 12
#define song_flow 13
#define song_scheming_weasel 14
#define song_kratos 15
#define song_slow_down 16
#define song_max 17