#define song_atthespeedoflightfull 0
#define song_windfall 1
#define song_menu_theme_human_capturing_mix 2
#define song_clubstep 3
#define song_scheming_weasel 4
#define song_practice 5
#define song_lost 6
#define song_kratos 7
#define song_max 8