#define song_crackdown 0
#define song_menu_theme_human_capturing_mix 1
#define song_nine_circles 2
#define song_every_end_pt2 3
#define song_blacklight 4
#define song_eon 5
#define song_every_end_pt1 6
#define song_stalemate 7
#define song_try_this 8
#define song_practice 9
#define song_death_moon 10
#define song_thermodynamix 11
#define song_atthespeedoflight 12
#define song_atthespeedoflight2 13
#define song_every_madness 14
#define song_pursuit 15
#define song_sonic_blaster 16
#define song_endorphins 17
#define song_hell 18
#define song_clubstep 19
#define song_atthespeedoflight3 20
#define song_eighto 21
#define song_holography 22
#define song_miami_hotline_vol_3 23
#define song_fairydust 24
#define song_problematic 25
#define song_scheming_weasel 26
#define song_max 27