#define song_nine_circles 0
#define song_subtle_oddities 1
#define song_the_challenge 2
#define song_clutterfunk 3
#define song_kesobomb 4
#define song_thermodynamix 5
#define song_tiny_tunes 6
#define song_pursuit 7
#define song_polargeist 8
#define song_fantasy 9
#define song_fingerdash 10
#define song_toe_2 11
#define song_deadlocked 12
#define song_geometrical_dominator 13
#define song_haunted_woods 14
#define song_theory_of_everything 15
#define song_electrodynamix 16
#define song_hexagon_force 17
#define song_infernoplex 18
#define song_time_machine 19
#define song_magic_touch 20
#define song_factory_time 21
#define song_endgame 22
#define song_clutterfunk_2 23
#define song_check_out 24
#define song_atthespeedoflight2 25
#define song_pyrophoric 26
#define song_practice 27
#define song_death_moon 28
#define song_electroman_adventures 29
#define song_menu_theme 30
#define song_retray 31
#define song_dash 32
#define song_rainbow_tylenol 33
#define song_every_madness 34
#define song_blast_processing 35
#define song_glitch_gremlin 36
#define song_atthespeedoflight 37
#define song_stalemate 38
#define song_sonic_blaster 39
#define song_back_on_track 40
#define song_clubstep 41
#define song_hell 42
#define song_fire_aura 43
#define song_infiltration 44
#define song_base_after_base 45
#define song_endorphins 46
#define song_just_right 47
#define song_power_trip 48
#define song_driving_by_night 49
#define song_infinite_power 50
#define song_xenogenesis 51
#define song_miami_hotline_vol_3 52
#define song_blacklight 53
#define song_cycles 54
#define song_problematic 55
#define song_chaoz_fantasy_extended 56
#define song_meltdown 57
#define song_extraordinary_excitement 58
#define song_midnight 59
#define song_against_the_odds_redux 60
#define song_stereo_madness 61
#define song_stereo_madness_2 62
#define song_stalemate_greif_cut 63
#define song_holography 64
#define song_cant_let_go 65
#define song_xstep 66
#define song_ground_to_space 67
#define song_dance_of_the_violins 68
#define song_fairydust 69
#define song_meowstuff 70
#define song_dry_out 71
#define song_jumper 72
#define song_ninox 73
#define song_speed_racer 74
#define song_scheming_weasel 75
#define song_max 76