#define song_nine_circles 0
#define song_driving_by_night 1
#define song_subtle_oddities 2
#define song_clutterfunk 3
#define song_xenogenesis 4
#define song_thermodynamix 5
#define song_sonic_blaster 6
#define song_fantasy 7
#define song_polargeist 8
#define song_deadlocked 9
#define song_fingerdash 10
#define song_pursuit 11
#define song_toe_2 12
#define song_geometrical_dominator 13
#define song_dash 14
#define song_electrodynamix 15
#define song_practice 16
#define song_hexagon_force 17
#define song_infernoplex 18
#define song_time_machine 19
#define song_magic_touch 20
#define song_factory_time 21
#define song_endgame 22
#define song_clutterfunk_2 23
#define song_check_out 24
#define song_electroman_adventures 25
#define song_atthespeedoflight2 26
#define song_the_challenge 27
#define song_death_moon 28
#define song_retray 29
#define song_rainbow_tylenol 30
#define song_every_madness 31
#define song_cycles 32
#define song_haunted_woods 33
#define song_clubstep 34
#define song_atthespeedoflight 35
#define song_hell 36
#define song_fire_aura 37
#define song_back_on_track 38
#define song_blast_processing 39
#define song_infiltration 40
#define song_base_after_base 41
#define song_stalemate 42
#define song_endorphins 43
#define song_menu_theme 44
#define song_just_right 45
#define song_power_trip 46
#define song_infinite_power 47
#define song_chaoz_fantasy_extended 48
#define song_pyrophoric 49
#define song_miami_hotline_vol_3 50
#define song_blacklight 51
#define song_ninox 52
#define song_kesobomb 53
#define song_glitch_gremlin 54
#define song_meltdown 55
#define song_extraordinary_excitement 56
#define song_stalemate_greif_cut 57
#define song_against_the_odds_redux 58
#define song_stereo_madness 59
#define song_xstep 60
#define song_stereo_madness_2 61
#define song_holography 62
#define song_cant_let_go 63
#define song_theory_of_everything 64
#define song_midnight 65
#define song_ground_to_space 66
#define song_dance_of_the_violins 67
#define song_meowstuff 68
#define song_dry_out 69
#define song_speed_racer 70
#define song_tiny_tunes 71
#define song_fairydust 72
#define song_jumper 73
#define song_scheming_weasel 74
#define song_problematic 75
#define song_max 76