#define song_pyrophoric 0
#define song_subtle_oddities 1
#define song_theory_of_everything 2
#define song_whats_a_future_funk 3
#define song_infinite_power 4
#define song_clutterfunk 5
#define song_polargeist 6
#define song_rainbow_tylenol 7
#define song_fingerdash 8
#define song_practice 9
#define song_toe_2 10
#define song_atthespeedoflight2 11
#define song_electroman_adventures 12
#define song_geometrical_dominator 13
#define song_endgame 14
#define song_electrodynamix 15
#define song_hexagon_force 16
#define song_infernoplex 17
#define song_clutterfunk_2 18
#define song_magic_touch 19
#define song_factory_time 20
#define song_time_machine 21
#define song_death_moon 22
#define song_check_out 23
#define song_fantasy 24
#define song_dash 25
#define song_ground_to_space 26
#define song_pursuit 27
#define song_deadlocked 28
#define song_holography 29
#define song_atthespeedoflight 30
#define song_haunted_woods 31
#define song_just_right 32
#define song_clubstep 33
#define song_blast_processing 34
#define song_hell 35
#define song_fire_aura 36
#define song_infiltration 37
#define song_back_on_track 38
#define song_endorphins 39
#define song_base_after_base 40
#define song_menu_theme 41
#define song_power_trip 42
#define song_ninox 43
#define song_chaoz_fantasy_extended 44
#define song_glitch_gremlin 45
#define song_xenogenesis 46
#define song_meltdown 47
#define song_stereo_madness 48
#define song_cycles 49
#define song_kesobomb 50
#define song_extraordinary_excitement 51
#define song_stereo_madness_2 52
#define song_stalemate_greif_cut 53
#define song_against_the_odds_redux 54
#define song_jumper 55
#define song_xstep 56
#define song_midnight 57
#define song_dance_of_the_violins 58
#define song_tiny_tunes 59
#define song_meowstuff 60
#define song_dry_out 61
#define song_scheming_weasel 62
#define song_problematic 63
#define song_speed_racer 64
#define song_driving_by_night 65
#define song_retray 66
#define song_cant_let_go 67
#define song_the_challenge 68
#define song_max 69