song_stereo_madness_foreverbound = 0
song_back_on_track_djvi = 1
song_polargeist_step = 2
song_dry_out_djvi = 3
song_base_after_base_djvi = 4
song_cant_let_go = 5
song_jumper = 6
song_time_machine = 7
song_cycles = 8
song_xstep = 9
song_clutterfunk = 10
song_theory_of_everything = 11
song_electroman_adventures = 12
song_clubstep_ = 13
song_electrodynamix = 14
song_hexagon_force_waterflame = 15
song_blast_processing_waterflame = 16
song_theory_2 = 17
song_geometrical_dominator_waterflame = 18
song_deadlocked_f-777 = 19
song_fingerdash_mdk = 20
song_dash_mdk = 21
song_practice_ocularnebula = 22
song_at_the_speed_of_light = 23
song_geometry_dash_menu_theme = 24
song_max = 25

.if SONG_STRINGS
song_strings:
.asciiz "Stereo Madness (ForeverBound)"
.asciiz "Back on Track (DJVI)"
.asciiz "Polargeist (Step)"
.asciiz "Dry Out (DJVI)"
.asciiz "Base after Base (DJVI)"
.asciiz "Can't Let Go"
.asciiz "Jumper"
.asciiz "Time Machine"
.asciiz "Cycles"
.asciiz "xStep"
.asciiz "Clutterfunk"
.asciiz "Theory of Everything"
.asciiz "Electroman Adventures"
.asciiz "Clubstep "
.asciiz "Electrodynamix"
.asciiz "Hexagon Force (Waterflame)"
.asciiz "Blast Processing (Waterflame)"
.asciiz "Theory 2"
.asciiz "Geometrical Dominator (Waterflame)"
.asciiz "Deadlocked (F-777)"
.asciiz "Fingerdash (MDK)"
.asciiz "Dash (MDK)"
.asciiz "Practice (OcularNebula)"
.asciiz "At the Speed of Light"
.asciiz "Geometry Dash Menu Theme"
.endif
