; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Project uses delayed notes or cuts, you must set FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1.
; Project uses release notes, you must set FAMISTUDIO_USE_RELEASE_NOTES = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Volume slides are used, you must set FAMISTUDIO_USE_VOLUME_SLIDES = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Slide notes are used on the noise channel, you must set FAMISTUDIO_USE_NOISE_SLIDE_NOTES = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Arpeggios are used, you must set FAMISTUDIO_USE_ARPEGGIO = 1.
; Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_famidash_music27=music_data_famidash_music27
.endif

music_data_famidash_music27:
	.byte 5
	.word @instruments
	.word @samples-5
; 00 : Menu Theme B Sides
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 264,220
; The DPCM aligner used to be here
; 02 : against the odds redux
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word 307,256
; 03 : Can't Electroman
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word 348,290
; 04 : Dry Out Full
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.word 296,247
; 05 : Power Trip
	.word @song5ch0
	.word @song5ch1
	.word @song5ch2
	.word @song5ch3
	.word @song5ch4
	.word 174,145

.export music_data_famidash_music27
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env23,@env8,@env31,@env0 ; 00 : rel hats
	.word @env10,@env38,@env31,@env0 ; 01 : kick
	.word @env9,@env8,@env37,@env0 ; 02 : hat
	.word @env24,@env29,@env3,@env0 ; 03 : snare
	.word @env34,@env25,@env31,@env0 ; 04 : Instrument 5
	.word @env39,@env8,@env3,@env0 ; 05 : cymbal
	.word @env1,@env25,@env31,@env0 ; 06 : echo
	.word @env35,@env25,@env31,@env0 ; 07 : triangle pluck 4
	.word @env28,@env25,@env31,@env0 ; 08 : triangle pluck
	.word @env20,@env25,@env31,@env0 ; 09 : blank
	.word @env4,@env25,@env32,@env0 ; 0a : sample
	.word @env43,@env25,@env31,@env0 ; 0b : blank instant decay
	.word @env15,@env25,@env31,@env13 ; 0c : I don't know what to name this
	.word @env15,@env25,@env31,@env0 ; 0d : DMC: drums + bass
	.word @env20,@env25,@env5,@env0 ; 0e : electroman lead
	.word @env15,@env25,@env6,@env0 ; 0f : hex guitar 1
	.word @env15,@env25,@env22,@env0 ; 10 : hex guitar 2
	.word @env27,@env25,@env31,@env0 ; 11 : infernoplex_piano
	.word @env33,@env25,@env31,@env0 ; 12 : quiet bass
	.word @env4,@env25,@env31,@env19 ; 13 : triangle drums
	.word @env15,@env25,@env31,@env18 ; 14 : tom
	.word @env21,@env25,@env30,@env16 ; 15 : Kap lead
	.word @env33,@env41,@env32,@env0 ; 16 : octave arp

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cb,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$13
@env2:
	.byte $00,$c0,$ba,$b7,$ba,$c0,$c6,$c9,$c6,$00,$01
@env3:
	.byte $c1,$c0,$00,$01
@env4:
	.byte $00,$c9,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$00,$08
@env5:
	.byte $c2,$c1,$03,$c0,$02,$c0,$00,$01
@env6:
	.byte $c3,$c2,$c1,$c2,$c2,$c1,$00,$02
@env7:
	.byte $00,$c0,$be,$bd,$bd,$be,$bf,$c1,$c2,$c3,$c3,$c2,$00,$01
@env8:
	.byte $bd,$c0,$00,$01
@env9:
	.byte $00,$c8,$c4,$c2,$c0,$00,$04
@env10:
	.byte $00,$cd,$c9,$c5,$c2,$c1,$c0,$00,$06
@env11:
	.byte $00,$c0,$bf,$03,$c0,$c0,$c1,$02,$c1,$00,$01
@env12:
	.byte $c0,$c4,$cc,$00,$00
@env13:
	.byte $00,$c3,$cb,$cf,$d5,$c0,$c3,$ca,$cd,$d4,$c0,$c4,$c8,$cf,$d6,$dd,$e3,$e6,$e7,$e8,$ea,$eb,$ed,$ee,$f0,$f2,$f6,$fa,$fd,$ff,$00,$1d
@env14:
	.byte $00,$c0,$ba,$b6,$b5,$b8,$bd,$c3,$c8,$cb,$ca,$c6,$00,$01
@env15:
	.byte $00,$cf,$7f,$00,$02
@env16:
	.byte $00,$c0,$03,$c0,$c0,$c1,$c0,$02,$bf,$c0,$c0,$c0,$00,$03
@env17:
	.byte $00,$c0,$bd,$bc,$be,$c2,$c4,$c3,$00,$01
@env18:
	.byte $80,$c0,$d5,$00,$02
@env19:
	.byte $80,$bf,$f1,$00,$02
@env20:
	.byte $04,$cf,$00,$01,$ca,$c6,$c4,$c2,$c0,$00,$08
@env21:
	.byte $00,$ca,$7f,$00,$02
@env22:
	.byte $c3,$c2,$c1,$c3,$00,$03
@env23:
	.byte $00,$c8,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$0d
@env24:
	.byte $00,$cd,$cb,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env25:
	.byte $c0,$7f,$00,$01
@env26:
	.byte $00,$c0,$bb,$bb,$c0,$c5,$c5,$00,$01
@env27:
	.byte $00,$ce,$02,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$c9,$c9,$c8,$c7,$c6,$c5,$c3,$00,$10
@env28:
	.byte $00,$cf,$c0,$00,$02
@env29:
	.byte $c6,$cc,$00,$01
@env30:
	.byte $c0,$c1,$c2,$00,$02
@env31:
	.byte $7f,$00,$00
@env32:
	.byte $c2,$7f,$00,$00
@env33:
	.byte $00,$c9,$c7,$c5,$00,$03
@env34:
	.byte $06,$cc,$cc,$cc,$00,$03,$cb,$c8,$c6,$c4,$c2,$c0,$00,$0b
@env35:
	.byte $00,$cf,$03,$c0,$00,$03
@env36:
	.byte $c0,$c0,$cc,$00,$00
@env37:
	.byte $c0,$c1,$00,$00
@env38:
	.byte $c9,$cf,$00,$01
@env39:
	.byte $18,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c7,$c6,$02,$c5,$c5,$c4,$02,$c3,$03,$c2,$c2,$00,$15,$c2,$c2,$c1,$03,$c0,$00,$1c
@env40:
	.byte $c0,$c3,$cc,$00,$00
@env41:
	.byte $c0,$c0,$cc,$cc,$00,$00
@env42:
	.byte $00,$c0,$bb,$ba,$bd,$c3,$c6,$c5,$00,$01
@env43:
	.byte $00,$cf,$cf,$cb,$c8,$c5,$c3,$c2,$c1,$c0,$00,$09

@samples:
	.byte $2a+.lobyte(FAMISTUDIO_DPCM_PTR),$a8,$0b,$40,$02 ; 00 BSV (Pitch:11)
	.byte $54+.lobyte(FAMISTUDIO_DPCM_PTR),$7f,$0c,$40,$02 ; 01 BSV_1 (Pitch:12)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$a7,$4f,$40,$03 ; 02 Choir Ahh A (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$4f,$40,$04 ; 03 Choir Ahh B (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$4f,$40,$04 ; 04 Choir Ahh C (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$4d,$40,$05 ; 05 Choir Ahh C# (Pitch:13)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4c,$40,$05 ; 06 Choir Ahh D (Pitch:12)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4e,$40,$05 ; 07 Choir Ahh D (Pitch:14)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4f,$40,$05 ; 08 Choir Ahh D (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4f,$40,$06 ; 09 Choir Ahh E (Pitch:15)
	.byte $38+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4f,$40,$06 ; 0a Choir Ahh G (Pitch:15)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$01 ; 0b demon level (Pitch:15)
	.byte $2a+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$03 ; 0c EON_AH (Pitch:15)
	.byte $11+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 0d fdbass A# (Pitch:15)
	.byte $23+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$40,$00 ; 0e fdbass B (Pitch:13)
	.byte $23+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$00 ; 0f fdbass B (Pitch:15)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0a,$40,$00 ; 10 fdbass C (Pitch:10)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0c,$40,$00 ; 11 fdbass C (Pitch:12)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0d,$40,$00 ; 12 fdbass C (Pitch:13)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0e,$40,$00 ; 13 fdbass C (Pitch:14)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 14 fdbass C (Pitch:15)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$09,$40,$00 ; 15 fdbass C# (Pitch:9)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0b,$40,$00 ; 16 fdbass C# (Pitch:11)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0d,$40,$00 ; 17 fdbass C# (Pitch:13)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 18 fdbass C# (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0a,$40,$00 ; 19 fdbass D (Pitch:10)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0b,$40,$00 ; 1a fdbass D (Pitch:11)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0c,$40,$00 ; 1b fdbass D (Pitch:12)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0d,$40,$00 ; 1c fdbass D (Pitch:13)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0e,$40,$00 ; 1d fdbass D (Pitch:14)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0f,$40,$00 ; 1e fdbass D (Pitch:15)
	.byte $6b+.lobyte(FAMISTUDIO_DPCM_PTR),$2b,$0e,$40,$00 ; 1f fdkick (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$38,$0f,$40,$01 ; 20 is a (Pitch:15)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$6d,$0f,$40,$02 ; 21 machine (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e0,$0e,$40,$07 ; 22 MUSIC_PCM_DS-geo (Pitch:14)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$08 ; 23 one (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$41,$0f,$34,$00 ; 24 snare (Pitch:15)
	.byte $0f+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0f,$40,$01 ; 25 this (Pitch:15)
	.byte $38+.lobyte(FAMISTUDIO_DPCM_PTR),$e7,$0f,$40,$07 ; 26 three (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$37,$0f,$40,$02 ; 27 time (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$d6,$0f,$40,$08 ; 28 two (Pitch:15)

@song0ch0:
	.byte $46, $06, $85, $8c
@song0ref5:
	.byte $31, $9d, $31, $9d, $31, $9d, $31, $97, $85, $31, $9d, $31, $9d, $31, $9d, $31, $97, $85
	.byte $41, $0e
	.word @song0ref5
	.byte $b7, $44, $00
@song0ch1:
	.byte $ac
@song0ref31:
	.byte $0d, $9d, $0b, $9d, $0a, $9d, $09, $8b, $0b, $8f
	.byte $41, $0a
	.word @song0ref31
	.byte $41, $0a
	.word @song0ref31
	.byte $41, $0a
	.word @song0ref31
	.byte $44, $00
@song0ch2:
	.byte $8e
@song0ref54:
	.byte $25, $25
@song0ref56:
	.byte $31, $90, $31, $8e, $2c, $90, $2c, $81, $8e, $2b, $90, $2b, $8e, $2a, $90, $2a, $8e, $28, $90, $28, $8e, $25, $28, $2a
	.byte $23, $23
	.byte $41, $0e
	.word @song0ref56
	.byte $22, $22
	.byte $41, $0e
	.word @song0ref56
	.byte $21, $21
	.byte $41, $0e
	.word @song0ref56
	.byte $41, $12
	.word @song0ref54
	.byte $41, $0e
	.word @song0ref56
	.byte $22, $22
	.byte $41, $0e
	.word @song0ref56
	.byte $21, $21
	.byte $41, $0e
	.word @song0ref56
	.byte $41, $12
	.word @song0ref54
	.byte $41, $0e
	.word @song0ref56
	.byte $22, $22
	.byte $41, $0e
	.word @song0ref56
	.byte $21, $21
	.byte $41, $0e
	.word @song0ref56
	.byte $41, $12
	.word @song0ref54
	.byte $41, $0e
	.word @song0ref56
	.byte $22, $22
	.byte $41, $0e
	.word @song0ref56
	.byte $9f, $44, $00
@song0ch3:
@song0ref142:
	.byte $82, $14, $84, $23, $21, $23, $86, $14, $84, $23, $21, $82, $14, $84, $1f, $82, $14, $14, $84, $23, $86, $14, $84, $23
	.byte $21, $23, $82, $14, $84, $23, $82, $14, $84, $23, $86, $14, $84, $23, $82, $14, $86, $14, $84, $1f, $82, $14, $14, $84
	.byte $23, $86, $14, $16, $16, $16
	.byte $41, $20
	.word @song0ref142
	.byte $41, $20
	.word @song0ref142
	.byte $41, $20
	.word @song0ref142
	.byte $41, $20
	.word @song0ref142
	.byte $41, $20
	.word @song0ref142
	.byte $41, $20
	.word @song0ref142
	.byte $41, $11
	.word @song0ref142
	.byte $81, $14, $85, $14, $81, $14, $85, $80, $20, $81, $20, $81, $44, $00
@song0ch4:
@song0ref232:
	.byte $20, $85, $25, $83, $20, $81, $20, $20, $81, $25, $85, $20, $81, $20, $81, $25, $81, $20, $25, $81, $20, $20, $81, $25
	.byte $25, $25, $25
	.byte $41, $1b
	.word @song0ref232
	.byte $41, $1b
	.word @song0ref232
	.byte $41, $1b
	.word @song0ref232
	.byte $41, $1b
	.word @song0ref232
	.byte $41, $1b
	.word @song0ref232
	.byte $41, $1b
	.word @song0ref232
	.byte $41, $0e
	.word @song0ref232
	.byte $85, $20, $81, $20, $85, $20, $81, $20, $81, $44, $00
; The DPCM aligner used to be here
@song2ch0:
	.byte $46, $09
@song2ref3:
	.byte $79
@song2ref4:
	.byte $49, .lobyte(@env11), .hibyte(@env11), $4f, $02, $88, $24, $45, $88, $24, $1f, $22, $23, $81, $24, $45, $24, $45, $1b
	.byte $1d, $1b, $45, $50, $f6, $29, $2b, $1f, $49, .lobyte(@env42), .hibyte(@env42), $89, $00, $81, $73
@song2ref38:
	.byte $49, .lobyte(@env11), .hibyte(@env11), $4b, .lobyte(@env40), .hibyte(@env40), $4f, $00, $24, $4d, $88, $24, $4f, $01
	.byte $00, $4d, $24, $00, $4b, .lobyte(@env12), .hibyte(@env12), $4f, $02, $22, $00, $4d, $4f, $00, $22, $79, $4b, .lobyte(@env40)
	.byte .hibyte(@env40), $4f, $02, $24, $4b, .lobyte(@env25), .hibyte(@env25), $4c, $1f, $22, $1f, $24, $26, $45, $24, $27
	.byte $26, $45, $22, $45, $1f, $22, $49, .lobyte(@env26), .hibyte(@env26), $24, $81, $49, .lobyte(@env11), .hibyte(@env11)
	.byte $a2, $1f, $a2, $22, $1f, $24, $27, $45, $49, .lobyte(@env26), .hibyte(@env26), $26, $81, $49, .lobyte(@env11), .hibyte(@env11)
	.byte $22, $45, $a2, $1f, $26, $22, $45, $24
	.byte $41, $0b
	.word @song2ref4
@song2ref127:
	.byte $1d, $22, $1f, $00, $50, $f9, $2e, $30, $24, $49, .lobyte(@env42), .hibyte(@env42), $89, $00, $81, $75
	.byte $41, $1f
	.word @song2ref38
@song2ref146:
	.byte $49, .lobyte(@env26), .hibyte(@env26), $29, $81, $49, .lobyte(@env11), .hibyte(@env11), $22, $45, $a2, $1f, $26, $22
	.byte $45, $24, $45, $81, $9e, $24, $22, $24, $81, $26, $27, $00
@song2ref172:
	.byte $27, $00, $22, $24
@song2ref176:
	.byte $22, $1d, $1f, $00, $81, $24, $22, $24, $81, $26, $27, $00, $26, $22, $24, $20
	.byte $41, $0c
	.word @song2ref176
	.byte $41, $14
	.word @song2ref172
	.byte $41, $0c
	.word @song2ref176
	.byte $41, $14
	.word @song2ref172
	.byte $22, $1d, $1f, $00, $81, $24, $22, $24, $00, $20, $45, $50, $f8, $2c, $2e, $22, $83, $4f, $01, $50, $04, $2e, $2b, $83
	.byte $00, $7f, $a0
@song2ref231:
	.byte $18, $18, $1b, $18, $1f, $18, $1b, $18, $18, $1a, $1b, $49, .lobyte(@env14), .hibyte(@env14), $1d, $81, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $a0, $1b, $1a, $18
	.byte $41, $0b
	.word @song2ref231
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $1a, $81, $18, $49, .lobyte(@env0), .hibyte(@env0), $4a, $1a, $18
	.byte $41, $10
	.word @song2ref231
	.byte $41, $0b
	.word @song2ref231
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $1a, $81, $18, $49, .lobyte(@env0), .hibyte(@env0), $4a, $1a, $18
	.byte $41, $10
	.word @song2ref231
	.byte $41, $0b
	.word @song2ref231
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $1a, $81, $18, $49, .lobyte(@env0), .hibyte(@env0), $4a, $1a, $18
	.byte $41, $10
	.word @song2ref231
	.byte $41, $0b
	.word @song2ref231
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $1a, $81, $18, $49, .lobyte(@env0), .hibyte(@env0), $4a, $1a, $18
	.byte $41, $3c
	.word @song2ref3
	.byte $41, $0b
	.word @song2ref4
	.byte $41, $09
	.word @song2ref127
	.byte $75
	.byte $41, $1f
	.word @song2ref38
	.byte $41, $09
	.word @song2ref146
	.byte $44, $00
@song2ch1:
@song2ref347:
	.byte $7c, $49, .lobyte(@env7), .hibyte(@env7)
@song2ref351:
	.byte $4f, $01, $9e, $18, $00, $9e, $18, $13, $16, $17, $00, $18, $00, $18, $00, $0f, $11, $0f, $00, $50, $ed, $1d, $1f, $88
	.byte $13, $49, .lobyte(@env17), .hibyte(@env17), $89, $00, $81, $75, $49, .lobyte(@env7), .hibyte(@env7), $4b, .lobyte(@env40)
	.byte .hibyte(@env40), $4f, $00, $9e, $18, $4d, $4f, $02, $9e, $18, $00, $4d, $18, $4f, $01, $00, $4b, .lobyte(@env12), .hibyte(@env12)
	.byte $16, $00, $4d, $4f, $00, $16, $49, .lobyte(@env7), .hibyte(@env7), $4b, .lobyte(@env40), .hibyte(@env40), $4f, $01
	.byte $18, $4b, .lobyte(@env25), .hibyte(@env25), $4c, $9e, $13, $7c, $16, $13, $18, $1a, $00, $18, $1b, $1a, $00, $16, $00
	.byte $13, $16, $49, .lobyte(@env2), .hibyte(@env2), $18, $88, $18, $49, .lobyte(@env0), .hibyte(@env0), $4a, $a0, $13, $16
	.byte $13, $18, $1b, $00, $49, .lobyte(@env2), .hibyte(@env2), $1a, $a0, $1a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $16
	.byte $00, $13, $1a, $16, $00, $18, $49, .lobyte(@env11), .hibyte(@env11)
	.byte $41, $0b
	.word @song2ref351
@song2ref482:
	.byte $11, $16, $13, $00, $50, $f2, $22, $24, $88, $18, $49, .lobyte(@env42), .hibyte(@env42), $89, $00, $81, $78, $49, .lobyte(@env11)
	.byte .hibyte(@env11), $4b, .lobyte(@env40), .hibyte(@env40), $4f, $02, $18, $4d, $88, $18, $4f, $03, $00, $4d, $18, $00
	.byte $4b, .lobyte(@env12), .hibyte(@env12), $4f, $01, $16, $00, $4d, $4f, $00, $16, $7c, $4b, .lobyte(@env40), .hibyte(@env40)
	.byte $4f, $01, $18, $4b, .lobyte(@env25), .hibyte(@env25), $4c, $13, $16, $13, $18, $1a, $45, $18, $1b, $1a, $45, $16, $45
	.byte $13, $16, $49, .lobyte(@env26), .hibyte(@env26), $18, $81, $49, .lobyte(@env11), .hibyte(@env11), $a0, $13, $a0, $16
	.byte $13, $18, $1b, $45, $49, .lobyte(@env26), .hibyte(@env26), $1d, $81, $49, .lobyte(@env11), .hibyte(@env11), $16, $45
	.byte $a0, $13, $1a, $16, $45, $18, $45, $81, $4f, $01, $aa, $18, $16, $18, $81, $1a, $1b, $00
@song2ref597:
	.byte $1b, $00, $16, $18
@song2ref601:
	.byte $16, $11, $13, $00, $81, $18, $16, $18, $81, $1a, $1b, $00, $1a, $16, $18, $14
	.byte $41, $0c
	.word @song2ref601
	.byte $41, $14
	.word @song2ref597
	.byte $41, $0c
	.word @song2ref601
	.byte $41, $14
	.word @song2ref597
	.byte $16, $11, $13, $00, $81, $18, $16, $18, $00, $14, $45, $50, $f0, $20, $22, $16, $81, $4e, $06, $81, $4e, $00, $81, $7f
	.byte $88, $13, $16, $1a, $00, $bd, $bf, $a0
@song2ref661:
	.byte $24, $24, $27, $24, $2b, $24, $27, $24, $24, $26, $27, $29, $81, $27, $26, $24
	.byte $41, $0b
	.word @song2ref661
	.byte $26, $81, $24, $26, $24
	.byte $41, $10
	.word @song2ref661
	.byte $41, $0b
	.word @song2ref661
	.byte $26, $81, $24, $26, $24
	.byte $41, $3c
	.word @song2ref347
	.byte $49, .lobyte(@env11), .hibyte(@env11)
	.byte $41, $0b
	.word @song2ref351
	.byte $41, $31
	.word @song2ref482
	.byte $44, $00
@song2ch2:
@song2ref711:
	.byte $a6, $19, $81, $88, $18, $83, $1f, $83, $1d, $83, $1b, $85, $1f, $8f, $18, $83, $1b, $81, $98, $3d, $81, $88, $1f, $83
@song2ref735:
	.byte $18, $83, $1b, $83, $1a, $83, $1d, $83, $1a, $85, $20, $83, $98, $3d, $81, $00, $88, $1b, $83, $18, $83, $1f, $81, $00
	.byte $81
	.byte $41, $17
	.word @song2ref735
	.byte $41, $15
	.word @song2ref735
@song2ref766:
	.byte $24, $83, $2b, $83, $24, $81, $27, $83, $2e, $83, $2b, $00, $2b, $83, $30, $83, $2b, $81, $30, $83, $2e, $81, $98, $3d
	.byte $81, $88, $24
	.byte $41, $19
	.word @song2ref766
	.byte $33, $83, $30, $83, $2c, $81, $2e, $83, $29, $83, $2e, $81, $30, $83, $2e, $83, $00, $32, $81, $30, $83, $2e, $81, $2b
	.byte $81, $2c, $83, $30, $81, $98, $3d, $81, $88, $2c, $2e, $81, $00, $89
@song2ref834:
	.byte $18, $8d, $11, $83, $16, $83, $11, $81, $18, $8d, $11, $83, $16, $81, $98, $3d, $81, $88, $11
	.byte $41, $11
	.word @song2ref834
	.byte $41, $11
	.word @song2ref834
	.byte $41, $11
	.word @song2ref834
	.byte $41, $2b
	.word @song2ref711
	.byte $41, $17
	.word @song2ref735
	.byte $41, $15
	.word @song2ref735
	.byte $44, $00
@song2ch3:
@song2ref874:
	.byte $7c, $48, $05, $88, $40, $02, $80, $40, $09, $8a
@song2ref884:
	.byte $40, $08, $48, $05, $88, $40, $02, $75, $80, $40, $09, $7c, $48, $05, $88, $40, $02, $8a, $40, $08, $75, $80, $40, $09
	.byte $7c, $48, $05, $88, $40, $02, $80, $40, $09, $8a, $40, $08, $48, $05, $88, $40, $02, $75, $80, $40, $09, $7c, $48, $05
	.byte $88, $40, $02, $8a, $40, $08, $75, $80, $40, $09
	.byte $41, $10
	.word @song2ref874
	.byte $41, $10
	.word @song2ref874
	.byte $41, $10
	.word @song2ref874
	.byte $41, $10
	.word @song2ref874
	.byte $41, $10
	.word @song2ref874
	.byte $41, $10
	.word @song2ref874
	.byte $41, $10
	.word @song2ref874
	.byte $7f, $8a, $40, $08, $85
@song2ref968:
	.byte $7c, $48, $05, $88, $40, $02
@song2ref974:
	.byte $48, $05, $40, $02, $8a, $40, $08, $75, $80, $40, $09, $7c, $48, $05, $88, $40, $02, $48, $05, $40, $02, $8a, $40, $08
	.byte $75, $80, $40, $09, $48, $05, $88, $40, $02, $7c, $48, $05, $40, $02, $8a, $40, $08, $75, $80, $40, $09, $7c, $48, $05
	.byte $88, $40, $02, $48, $05, $40, $02, $8a, $40, $08, $75, $80, $40, $09, $48, $05, $88, $40, $02, $7c
	.byte $41, $0f
	.word @song2ref974
	.byte $41, $11
	.word @song2ref968
	.byte $7c
	.byte $41, $0f
	.word @song2ref974
	.byte $41, $11
	.word @song2ref968
	.byte $7c
	.byte $41, $0f
	.word @song2ref974
	.byte $7c, $48, $05, $88, $40, $02, $48, $05, $40, $02, $8a, $40, $08, $7f, $81, $40, $09, $89, $00, $81, $7c, $48, $05, $88
	.byte $40, $02, $48, $05, $40, $02, $8a, $40, $08, $75, $80, $40, $09
	.byte $41, $11
	.word @song2ref968
	.byte $7c
	.byte $41, $0b
	.word @song2ref974
@song2ref1103:
	.byte $7c, $48, $05, $8a, $40, $09, $48, $05, $40, $09, $7f, $40, $08, $75, $80, $40, $09, $7c, $48, $05, $8a, $40, $09, $48
	.byte $05, $40, $09, $7f, $40, $08, $75, $80, $40, $09, $7c, $48, $05, $8a, $40, $09, $48, $05, $40, $09, $7f, $40, $08, $75
	.byte $80, $40, $09
	.byte $41, $0c
	.word @song2ref1103
	.byte $41, $0c
	.word @song2ref1103
	.byte $41, $0c
	.word @song2ref1103
	.byte $41, $0c
	.word @song2ref1103
	.byte $41, $0c
	.word @song2ref1103
	.byte $41, $0c
	.word @song2ref1103
	.byte $41, $0c
	.word @song2ref1103
	.byte $7f, $8a, $40, $0a, $81, $7c
	.byte $41, $0e
	.word @song2ref884
	.byte $41, $10
	.word @song2ref874
	.byte $41, $10
	.word @song2ref874
	.byte $41, $10
	.word @song2ref874
	.byte $41, $10
	.word @song2ref874
	.byte $41, $10
	.word @song2ref874
	.byte $41, $10
	.word @song2ref874
	.byte $41, $10
	.word @song2ref874
	.byte $44, $00
@song2ch4:
@song2ref1208:
	.byte $20, $48, $06, $10, $25, $48, $05, $10, $20, $48, $05, $10, $25, $48, $05, $10, $20, $48, $05, $1c, $25, $48, $05, $1c
	.byte $20, $48, $05, $1c, $25, $48, $05, $1c, $20, $48, $06, $1d, $25, $48, $04, $1d, $20, $48, $04, $1d, $25, $48, $04, $1d
	.byte $20, $48, $03, $10, $25, $48, $05, $10, $20, $48, $05, $1e, $25, $48, $05, $1e, $48, $06, $10, $48, $06, $10, $48, $06
	.byte $25, $10, $20, $48, $06, $10, $25, $48, $06, $10, $20, $48, $05, $1f, $25, $48, $06, $1e, $20, $48, $06, $1d, $25, $48
	.byte $07, $1e, $20, $48, $06, $10, $25, $48, $06, $10, $20, $48, $06, $10, $25, $48, $05, $10, $20, $48, $07, $1d, $25, $48
	.byte $05, $1d, $20, $48, $05, $1e, $25, $48, $06, $1e
	.byte $41, $40
	.word @song2ref1208
	.byte $41, $09
	.word @song2ref1208
@song2ref1344:
	.byte $48, $05, $10, $25, $48, $05, $10, $20, $48, $05, $1c, $25, $48, $05, $1d, $20, $48, $06, $10, $25, $48, $04, $10, $20
	.byte $48, $04, $10, $25, $48, $04, $10, $20, $48, $03, $1e, $25, $48, $05, $10, $20, $48, $05, $1e, $25, $48, $05, $10
	.byte $41, $09
	.word @song2ref1208
	.byte $41, $17
	.word @song2ref1344
	.byte $41, $09
	.word @song2ref1208
	.byte $41, $17
	.word @song2ref1344
	.byte $41, $09
	.word @song2ref1208
	.byte $00, $8b
	.byte $41, $09
	.word @song2ref1208
	.byte $41, $17
	.word @song2ref1344
	.byte $41, $09
	.word @song2ref1208
@song2ref1417:
	.byte $48, $05, $10, $25, $48, $05, $10, $20, $48, $05, $1c, $25, $48, $05, $13, $20, $48, $06, $13, $25, $48, $04, $13, $20
	.byte $48, $04, $13, $25, $48, $04, $13, $20, $48, $03, $13, $25, $48, $05, $13, $20, $48, $05, $13, $25, $48, $05, $13
	.byte $41, $09
	.word @song2ref1208
	.byte $41, $17
	.word @song2ref1344
	.byte $41, $09
	.word @song2ref1208
	.byte $41, $17
	.word @song2ref1417
	.byte $41, $40
	.word @song2ref1208
	.byte $41, $40
	.word @song2ref1208
	.byte $44, $00
@song3ch0:
	.byte $46, $06, $77, $4e, $00, $4f, $02, $9c, $1d, $85, $43, $50, $48, $29, $1d, $81, $43, $11, $81, $9a
@song3ref21:
	.byte $0d, $81, $00, $81, $0d, $81, $00, $81, $0d, $81, $0a, $81, $00, $81, $0a, $81, $00, $8d, $0a, $81, $00, $81, $0a, $81
	.byte $00, $81, $0d, $81, $00, $81, $0d, $81, $00, $81, $0d, $81, $0a, $81, $00, $81, $0a, $81, $00, $85, $0f, $81, $0f, $81
	.byte $0d, $81, $00, $81, $0d, $81, $00, $81
	.byte $41, $30
	.word @song3ref21
	.byte $4e, $00, $4f, $02, $9c, $1d, $85, $43, $50, $48, $29, $1d, $81, $4f, $00, $9a, $20, $00, $22, $00, $20, $00, $22, $00
	.byte $24, $00, $83, $1b, $00, $83, $1b, $00, $83, $20, $00, $22, $00, $24, $00, $24, $00, $83, $25, $00, $83, $1d, $00, $20
	.byte $00, $22, $00, $24, $00, $22, $00, $20, $00, $1f, $00, $20, $00, $83, $19, $00, $20, $00, $1f, $00, $1d, $00, $87, $20
	.byte $00, $22, $00, $20, $00, $22, $00, $24, $00, $87, $1b, $00, $1b, $00, $1d, $00, $1d, $00, $1f, $00, $1f, $00, $1d, $00
	.byte $87, $20, $00, $22, $00, $20, $00, $22, $00, $24, $00, $83, $19, $00, $20, $00, $1f, $00, $20, $00, $22, $00, $20, $00
	.byte $1f, $00, $9f, $9c
@song3ref204:
	.byte $1d, $81, $1d, $81, $1d, $81, $1d, $81, $1d, $81, $1d, $81, $20, $85, $1b, $85, $00, $81, $1b, $85, $00, $81, $22, $85
	.byte $19, $81, $19, $81, $19, $81, $19, $81, $19, $81, $19, $81, $19, $81, $19, $81, $1b, $85, $00, $81, $1b, $85, $00, $81
	.byte $20, $85
	.byte $41, $32
	.word @song3ref204
	.byte $41, $32
	.word @song3ref204
	.byte $41, $2c
	.word @song3ref204
	.byte $50, $af, $27, $33, $43, $27, $83, $00, $81, $20, $85
	.byte $41, $32
	.word @song3ref204
	.byte $41, $32
	.word @song3ref204
	.byte $7f, $4f, $01, $94
@song3ref284:
	.byte $1d, $81, $8c, $29, $00, $94, $1d, $81, $8c, $29, $00, $94, $1d, $81, $8c, $29, $00, $94, $20, $81, $8c, $2c, $00, $94
	.byte $20, $81, $1b, $81, $8c, $27, $00, $94, $1b, $81, $8c, $27, $00, $94, $19, $81, $16, $81, $19, $81, $19, $81, $8c, $25
	.byte $00, $94, $19, $81, $8c, $25, $00, $94, $1d, $81, $8c, $29, $00, $94, $1d, $81, $8c, $29, $00, $94, $1d, $81, $1b, $81
	.byte $8c, $27, $00, $94, $1b, $81, $8c, $27, $00, $94, $19, $81, $20, $81, $1f, $81, $4f, $01
	.byte $41, $40
	.word @song3ref284
	.byte $4f, $01
	.byte $41, $40
	.word @song3ref284
	.byte $4f, $01
	.byte $41, $40
	.word @song3ref284
	.byte $00, $85, $44, $00
@song3ch1:
	.byte $77, $4f, $02, $9a
@song3ref396:
	.byte $11, $81, $00, $81, $11, $81, $00, $81, $14, $81, $00, $81, $14, $81, $00, $81, $14, $81, $0f, $81, $00, $81, $0f, $81
	.byte $00, $81, $0d, $81, $0a, $81, $0d, $48, $04, $81, $0d, $81, $00, $81, $0d, $81, $00, $81, $11, $81, $00, $81, $11, $81
	.byte $00, $81, $11, $81, $0f, $81, $00, $81, $0f, $81, $00, $85, $14, $81, $13, $81, $4f, $02
	.byte $41, $3e
	.word @song3ref396
	.byte $4f, $02
	.byte $41, $3e
	.word @song3ref396
	.byte $4f, $02
	.byte $41, $3e
	.word @song3ref396
	.byte $a4, $05, $85, $00, $95, $9f, $9c, $16, $85, $00, $8d, $19, $85, $00, $9d, $16, $85, $00, $95, $9f, $16, $85, $00, $8d
	.byte $19, $85, $00, $9d, $16, $85, $00, $95, $9f, $16, $85, $00, $8d, $19, $85, $00, $9d, $16, $85, $00, $95, $9f, $16, $85
	.byte $00, $8d, $19, $85, $00, $bd, $9a
@song3ref530:
	.byte $11, $81, $00, $81, $11, $81, $00, $81, $11, $81, $00, $81, $11, $81, $14, $81, $9c, $16, $85, $9a, $0f, $81, $00, $81
	.byte $0f, $81, $00, $81, $9c, $19, $85, $9a, $14, $81, $00, $81, $11, $81, $00, $81, $14, $81, $00, $81, $14, $81, $00, $81
	.byte $9c, $16, $85, $00, $81, $9a, $16, $81, $00, $81, $14, $81, $13, $81, $0f, $81
	.byte $41, $3a
	.word @song3ref530
	.byte $7f, $94
@song3ref599:
	.byte $14, $81, $00, $81, $14, $81, $00, $81, $14, $81, $00, $81, $19, $81, $00, $81, $19, $81, $16, $81, $00, $81, $16, $81
	.byte $00, $81, $11, $81, $0f, $81, $11, $81, $11, $81, $00, $81, $11, $81, $00, $81, $16, $81, $00, $81, $16, $81, $00, $81
	.byte $16, $81, $14, $81, $00, $81, $14, $81, $00, $8d
	.byte $41, $38
	.word @song3ref599
	.byte $7a, $9e, $11, $85, $13, $85, $14, $81, $14, $81, $1b, $81, $14, $81, $1d, $81, $14, $81, $14, $81, $50, $fb, $28, $29
	.byte $81, $43, $1d, $81, $14, $81, $16, $81, $14, $81, $19, $81, $16, $81, $13, $81, $14, $81, $20, $81, $1f, $81, $1d, $81
	.byte $20, $81, $1f, $81, $1d, $81, $1d, $81, $50, $fc, $2b, $2c, $81, $43, $20, $81, $20, $81, $20, $81, $1d, $81, $25, $81
	.byte $24, $81, $22, $81, $20, $81, $22, $85, $24, $85, $25, $81, $20, $85, $27, $85, $24, $81, $24, $81, $25, $81, $29, $81
	.byte $27, $81, $25, $81, $20, $81, $2e, $89, $43, $50, $0a, $3a, $37, $43, $2b, $43, $50, $f6, $37, $3a, $43, $2e, $87, $43
	.byte $50, $0a, $3a, $37, $43, $2b, $43, $50, $f6, $37, $3a, $43, $2e, $43, $50, $0a, $3a, $37, $43, $2b, $43, $50, $f6, $37
	.byte $3a, $43, $2e, $43, $50, $0a, $3a, $37, $43, $2b, $43, $50, $f6, $37, $3a, $43, $2e, $8b, $77, $4f, $02, $9a, $11, $81
	.byte $00, $81, $44, $00
@song3ch2:
	.byte $ff, $ff, $9a
@song3ref836:
	.byte $19, $81, $00, $81, $19, $81, $00, $81, $19, $81, $00, $81, $19, $81, $00, $81, $19, $81, $16, $81, $00, $81, $16, $81
	.byte $00, $8d, $16, $81, $00, $81, $16, $81, $00, $81, $19, $81, $00, $81, $19, $81, $00, $81, $19, $81, $16, $81, $00, $81
	.byte $16, $81, $00, $85, $1b, $81, $1b, $81
	.byte $41, $38
	.word @song3ref836
	.byte $00, $9d, $ff, $ff, $ff, $ff
@song3ref901:
	.byte $20, $81, $00, $81, $20, $81, $00, $81, $20, $81, $00, $81, $20, $81, $29, $85, $00, $81, $20, $81, $00, $81, $20, $81
	.byte $00, $81, $1f, $81, $1d, $85, $00, $81, $19, $81, $00, $81, $1d, $81, $00, $81, $1d, $81, $00, $81, $1d, $81, $1b, $81
	.byte $00, $81, $1b, $81, $00, $81, $19, $81, $20, $81, $1f, $81
	.byte $41, $3c
	.word @song3ref901
	.byte $00, $fd, $ff, $ff, $ff, $11, $85, $44, $00
@song3ch3:
@song3ref974:
	.byte $82, $14, $81, $80, $21, $81, $84, $1d, $81, $80, $21, $81, $82, $14, $81, $80, $21, $81, $84, $1d, $81, $80, $21, $81
	.byte $82, $14, $81, $80, $21, $81, $84, $1d, $81, $80, $21, $81, $82, $14, $81, $80, $21, $81, $84, $1d, $81, $80, $21, $81
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $82, $14, $81, $80, $21, $81, $84, $1d, $81, $80, $21, $81, $82, $14, $81, $80, $21, $81, $84, $1d, $81, $80, $21, $81
	.byte $8a, $20, $85, $7c
@song3ref1092:
	.byte $86, $14, $81, $84, $21, $81, $21, $81, $21, $81, $86, $14, $81, $84, $21, $81, $21, $81, $21, $81, $86, $14, $81, $84
	.byte $21, $81, $21, $81, $21, $81, $86, $14, $81, $84, $21, $81
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $41, $20
	.word @song3ref974
	.byte $8a, $20, $85
	.byte $41, $1c
	.word @song3ref1092
	.byte $82, $14, $81, $80, $21, $81, $44, $00
@song3ch4:
@song3ref1176:
	.byte $20, $81, $13, $00, $25, $81, $13, $00, $20, $81, $14, $00, $25, $81, $14, $00, $20, $81, $1c, $00, $25, $81, $1c, $00
	.byte $20, $81, $1c, $00, $25, $81, $1c, $00, $20, $81, $12, $00, $25, $81, $12, $00, $20, $81, $12, $00, $25, $81, $12, $00
	.byte $20, $81, $1c, $00, $25, $81, $1c, $00, $20, $81, $1c, $00, $25, $81, $1c, $00
	.byte $41, $40
	.word @song3ref1176
	.byte $41, $40
	.word @song3ref1176
	.byte $41, $40
	.word @song3ref1176
	.byte $25, $81, $20, $81, $20, $81, $25, $81, $20, $81, $20, $81, $25, $25, $25, $25
@song3ref1265:
	.byte $20, $81, $13, $13, $25, $81, $13, $13, $20, $81, $13, $13, $25, $81, $14, $14, $20, $81, $1c, $1c, $25, $81, $1c, $1c
	.byte $20, $81, $1c, $1c, $25, $81, $1c, $1c, $20, $81, $12, $12, $25, $81, $12, $12, $20, $81, $12, $12, $25, $81, $12, $12
	.byte $20, $81, $1c, $1c, $25, $81, $1c, $1c, $20, $81, $1c, $1c, $25, $81, $1c, $1c
	.byte $41, $40
	.word @song3ref1265
	.byte $41, $40
	.word @song3ref1265
	.byte $41, $24
	.word @song3ref1265
	.byte $00, $81, $12, $12, $00, $81, $12, $12, $00, $81, $12, $12, $00, $81, $1c, $1c, $00, $81, $1c, $1c, $00, $81, $1f, $1f
	.byte $00, $81, $14, $14
	.byte $41, $40
	.word @song3ref1265
	.byte $41, $40
	.word @song3ref1265
	.byte $41, $40
	.word @song3ref1265
	.byte $41, $40
	.word @song3ref1265
	.byte $41, $40
	.word @song3ref1265
	.byte $41, $40
	.word @song3ref1265
	.byte $00, $85, $44, $00
@song4ch0:
	.byte $46, $06, $4f, $02, $8c
@song4ref6:
	.byte $12, $12, $1e, $1e, $1c, $1c, $19, $19, $83, $15, $15, $14, $14, $10, $10, $12, $12, $81, $1c, $1c, $81, $19, $19, $83
	.byte $0d, $0d, $10, $10, $14, $14, $12, $12, $1c, $1c, $1e, $1e, $19, $19, $83, $14, $14, $15, $15, $17, $17, $1c, $1c, $81
	.byte $1e, $1e, $81, $19, $19, $83, $1e, $1e, $15, $15, $14, $14, $4f, $02
	.byte $41, $3c
	.word @song4ref6
	.byte $4f, $02
	.byte $41, $3c
	.word @song4ref6
	.byte $4f, $02
	.byte $41, $3c
	.word @song4ref6
	.byte $12, $12, $9b, $00, $83
@song4ref86:
	.byte $73, $92, $50, $7f, $1e, $12
@song4ref92:
	.byte $43, $06, $71, $83, $73, $06, $43, $06, $71, $83, $73, $06, $43, $06, $50, $80, $12, $1e, $43, $12, $71, $83, $73, $12
	.byte $43, $12, $50, $7f, $1e, $10, $81, $71, $43, $04, $81, $73, $04, $43, $04, $71, $83, $73, $04, $43, $04, $50, $80, $10
	.byte $1c, $43, $10, $71, $83, $73, $10, $43, $10, $50, $7f, $1c, $0d, $81, $71, $43, $01, $81, $73, $01, $43, $01, $71, $83
	.byte $73, $01, $43, $01, $50, $80, $0d, $19, $81, $71, $43, $0d, $81, $73, $0d, $43, $0d, $50, $7f, $19, $10, $43, $04, $71
	.byte $83, $73, $04, $43, $04, $71, $83, $73, $50, $80, $10, $15, $43, $09, $71, $83, $73, $50, $17, $15, $14, $43, $08, $83
	.byte $50, $33, $14, $12
	.byte $41, $33
	.word @song4ref92
@song4ref219:
	.byte $7f, $8c, $12, $12, $1e, $1e, $1c, $1c, $19, $19, $73, $92, $06, $71, $83, $73, $06, $81, $12, $81, $71, $81, $7f, $8c
	.byte $12, $12, $73, $92, $12, $7f, $8c, $1c, $1c, $71, $81, $7f, $19, $19, $73, $92, $04, $71, $83, $73, $04, $81, $10, $81
	.byte $71, $81, $7f, $8c, $12, $12, $1c, $1c, $1e, $1e, $19, $19, $73, $92, $01, $71, $83, $73, $01, $81, $0d, $81, $71, $81
	.byte $7f, $8c, $1c, $1c, $73, $92, $0d, $7f, $8c, $1e, $1e, $71, $81, $7f, $19, $19, $73, $92, $04, $71, $83, $73, $09, $81
	.byte $71, $83, $73, $08
	.byte $41, $3b
	.word @song4ref219
@song4ref322:
	.byte $77
@song4ref323:
	.byte $4f, $00
@song4ref325:
	.byte $12, $81, $4f, $01, $83, $4f, $02, $83, $4f, $01, $83, $4f, $00, $15, $81, $4f, $01, $14, $81, $4f, $02, $96, $10, $81
	.byte $4f, $01, $92, $14, $81, $4f, $00, $12, $81, $4f, $01, $83, $4f, $02, $83, $4f, $01, $19, $81, $4f, $00, $83, $4f, $01
	.byte $0d, $81, $4f, $02, $96, $10, $81, $4f, $01, $92, $14, $81, $4f, $00, $12, $81, $4f, $01, $83, $4f, $02, $83, $4f, $01
	.byte $0d, $81, $4f, $00, $10, $81, $4f, $01, $12, $81, $4f, $02, $96, $15, $81, $4f, $01, $92, $17, $81, $4f, $00, $12, $81
	.byte $4f, $01, $83, $4f, $02, $83, $4f, $01, $19, $81, $4f, $00, $1e, $81, $4f, $01, $83, $4f, $02, $96, $15, $81, $4f, $01
	.byte $92, $14, $81
	.byte $41, $35
	.word @song4ref323
@song4ref451:
	.byte $7f, $4f, $02, $8c
@song4ref455:
	.byte $12, $12, $1e, $1e, $1c, $1c, $19, $19, $85, $77, $21, $81, $20, $81, $1c, $7f, $12, $12, $81, $1c, $1c, $81, $19, $19
	.byte $81, $77, $25, $85, $19, $81, $1c, $7f, $12, $12, $1c, $1c, $1e, $1e, $19, $19, $81, $77, $19, $81, $1c, $81, $1e, $81
	.byte $21, $7f, $1c, $1c, $81, $1e, $1e, $81, $19, $19, $81, $77, $25, $81, $2a, $85, $21, $7f, $4f, $02
	.byte $41, $3a
	.word @song4ref455
	.byte $4f, $00, $92
	.byte $41, $35
	.word @song4ref325
	.byte $41, $35
	.word @song4ref323
	.byte $41, $3a
	.word @song4ref451
	.byte $7f, $4f, $02
	.byte $41, $3a
	.word @song4ref455
	.byte $85
	.byte $41, $37
	.word @song4ref86
	.byte $41, $33
	.word @song4ref92
	.byte $41, $3b
	.word @song4ref219
	.byte $41, $3b
	.word @song4ref219
	.byte $41, $35
	.word @song4ref322
	.byte $41, $35
	.word @song4ref323
	.byte $41, $3a
	.word @song4ref451
	.byte $7f, $4f, $02
	.byte $41, $3a
	.word @song4ref455
	.byte $87, $44, $00
@song4ch1:
	.byte $7c, $a4
@song4ref578:
	.byte $06, $9d, $04, $9d, $01, $9d, $04, $9d, $06, $9d, $04, $9d, $01, $9d, $04, $9d
	.byte $41, $10
	.word @song4ref578
	.byte $06, $8d, $00, $8d, $78, $92, $06, $81
@song4ref605:
	.byte $73, $83, $78, $06, $43, $06, $73, $83, $78, $06, $43, $06, $50, $80, $12, $1e, $43, $12, $73, $83, $78, $12, $43, $12
	.byte $50, $7f, $1e, $10, $81, $73, $43, $04, $81, $78, $04, $43, $04, $73, $83, $78, $04, $43, $04, $50, $80, $10, $1c, $43
	.byte $10, $73, $83, $78, $10, $43, $10, $50, $7f, $1c, $0d, $81, $73, $43, $01, $81, $78, $01, $43, $01, $73, $83, $78, $01
	.byte $43, $01, $50, $80, $0d, $19, $81, $73, $43, $0d, $81, $78, $0d, $43, $0d, $50, $7f, $19, $10, $43, $04, $73, $83, $78
	.byte $04, $43, $04, $73, $83, $78, $50, $80, $10, $15, $43, $09, $73, $83, $78, $50, $17, $15, $14, $43, $08, $50, $6b, $14
	.byte $10, $43, $04, $50, $c7, $10, $12, $43, $06
	.byte $41, $37
	.word @song4ref605
	.byte $41, $37
	.word @song4ref605
	.byte $41, $37
	.word @song4ref605
	.byte $41, $37
	.word @song4ref605
	.byte $41, $35
	.word @song4ref605
@song4ref749:
	.byte $7f, $4f, $02, $8c
@song4ref753:
	.byte $1e, $8d, $21, $81, $20, $81, $1c, $81, $20, $81, $1e, $89, $25, $85, $19, $81, $1c, $81, $20, $81, $1e, $89, $19, $81
	.byte $1c, $81, $1e, $81, $21, $81, $23, $81, $1e, $89, $25, $81, $2a, $85, $21, $81, $20, $81, $4f, $02
	.byte $41, $2a
	.word @song4ref753
	.byte $78, $92, $50, $c7, $10, $12, $43, $06
	.byte $41, $37
	.word @song4ref605
	.byte $41, $35
	.word @song4ref605
	.byte $41, $2a
	.word @song4ref749
	.byte $4f, $02
	.byte $41, $2a
	.word @song4ref753
	.byte $78, $92, $06, $73, $81
@song4ref827:
	.byte $78, $06, $73, $81, $78, $06, $73, $81, $78, $06, $73, $81, $00, $81, $7f, $51, $e1, $30, $50, $80, $12, $1e, $7f, $51
	.byte $e1, $30, $43, $12, $78, $81, $73, $12, $78, $12, $73, $81, $78, $50, $7f, $1e, $10, $73, $81, $78, $43, $04, $73, $81
	.byte $78, $04, $73, $81, $78, $43, $04, $73, $81, $00, $81, $7f, $51, $e1, $30, $50, $80, $10, $1c, $7f, $51, $e1, $30, $43
	.byte $10, $78, $81, $73, $81, $78, $10, $73, $43, $10, $78, $50, $7f, $1c, $0d, $73, $81, $78, $43, $01, $73, $81, $78, $01
	.byte $73, $81, $78, $43, $01, $73, $81, $00, $81, $7f, $51, $e1, $30, $50, $80, $0d, $19, $7f, $51, $e1, $30, $81, $78, $43
	.byte $0d, $73, $81, $78, $0d, $73, $43, $0d, $78, $50, $7f, $19, $10, $73, $43, $04, $78, $81, $73, $81, $78, $04, $73, $43
	.byte $04, $78, $00, $73, $81, $78, $50, $80, $10, $15, $73, $43, $09, $78, $81, $73, $81, $78, $50, $17, $15, $14, $73, $43
	.byte $08, $78, $50, $6b, $14, $10, $73, $43, $04, $78, $50, $c7, $10, $12, $73, $06
	.byte $41, $40
	.word @song4ref827
	.byte $41, $40
	.word @song4ref827
	.byte $41, $3f
	.word @song4ref827
	.byte $43, $06
	.byte $41, $37
	.word @song4ref605
	.byte $41, $35
	.word @song4ref605
	.byte $41, $2a
	.word @song4ref749
	.byte $4f, $02
	.byte $41, $2a
	.word @song4ref753
	.byte $1e, $85, $44, $00
@song4ch2:
	.byte $ff, $ff, $ff, $ff, $9f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $92
@song4ref1055:
	.byte $12, $9d, $10, $9d, $0d, $9d, $10, $9d, $12, $9d, $10, $9d, $0d, $9d, $10, $9d
	.byte $41, $10
	.word @song4ref1055
	.byte $41, $10
	.word @song4ref1055
	.byte $41, $10
	.word @song4ref1055
	.byte $41, $10
	.word @song4ref1055
	.byte $00, $fd, $ff, $87, $44, $00
@song4ch3:
	.byte $ff, $ff
@song4ref1092:
	.byte $82, $14, $81, $80, $1f, $84, $21, $82, $14, $81, $84, $1f, $81, $82, $14, $81, $80, $1f, $84, $21, $82, $14, $81, $84
	.byte $1f, $81
	.byte $41, $10
	.word @song4ref1092
	.byte $41, $10
	.word @song4ref1092
	.byte $41, $10
	.word @song4ref1092
	.byte $82
@song4ref1128:
	.byte $14, $81, $14, $81, $14, $81, $14, $81, $14, $81, $14, $81, $14, $81, $14, $81
	.byte $41, $10
	.word @song4ref1128
	.byte $41, $10
	.word @song4ref1128
	.byte $41, $10
	.word @song4ref1128
	.byte $8f, $71, $9a, $20, $81, $72, $81, $73, $81, $74, $81, $76, $81, $78, $81, $7c, $81, $7f
@song4ref1171:
	.byte $82
@song4ref1172:
	.byte $14, $89, $14, $81, $86, $14, $8d, $82, $14, $83, $14, $83, $14, $81, $86, $14, $8d, $82, $14, $89, $14, $81, $86, $14
	.byte $8d, $82, $14, $83, $14, $83, $14, $81, $86, $14, $8d
	.byte $41, $1c
	.word @song4ref1171
	.byte $41, $1c
	.word @song4ref1171
	.byte $41, $1c
	.word @song4ref1171
	.byte $41, $1c
	.word @song4ref1171
	.byte $41, $1c
	.word @song4ref1171
@song4ref1222:
	.byte $82, $14, $89, $14, $81, $86, $14, $8d, $82, $14, $83, $14, $83, $86, $14, $91, $82, $14, $89, $14, $81, $86, $14, $8d
	.byte $82, $14, $83, $14, $83, $86, $14, $91
	.byte $41, $18
	.word @song4ref1222
	.byte $41, $1c
	.word @song4ref1171
	.byte $41, $1c
	.word @song4ref1171
	.byte $82, $14, $89, $00, $f1, $ff
	.byte $41, $1c
	.word @song4ref1172
	.byte $41, $1c
	.word @song4ref1171
	.byte $41, $1c
	.word @song4ref1171
	.byte $41, $1c
	.word @song4ref1171
	.byte $41, $1c
	.word @song4ref1171
	.byte $41, $1c
	.word @song4ref1171
	.byte $41, $18
	.word @song4ref1222
	.byte $41, $18
	.word @song4ref1222
	.byte $87, $44, $00
@song4ch4:
	.byte $ff, $ff
@song4ref1299:
	.byte $20, $85, $20, $85, $20, $85, $20, $85, $20, $85, $20, $85, $20, $85, $20, $85
	.byte $41, $10
	.word @song4ref1299
@song4ref1318:
	.byte $20, $81, $20, $81, $20, $81, $20, $81, $20, $81, $20, $81, $20, $81, $20, $81
	.byte $41, $10
	.word @song4ref1318
	.byte $41, $10
	.word @song4ref1318
	.byte $41, $10
	.word @song4ref1318
	.byte $9f
@song4ref1344:
	.byte $20, $89, $20, $81, $25, $8d, $20, $83, $20, $83, $20, $81, $25, $8d, $20, $89, $20, $81, $25, $8d, $20, $83, $20, $83
	.byte $20, $81, $25, $8d
	.byte $41, $1c
	.word @song4ref1344
	.byte $41, $1c
	.word @song4ref1344
	.byte $41, $1c
	.word @song4ref1344
	.byte $41, $1c
	.word @song4ref1344
	.byte $41, $1c
	.word @song4ref1344
@song4ref1387:
	.byte $20, $89, $20, $81, $25, $8d, $20, $83, $20, $83, $25, $91, $20, $89, $20, $81, $25, $8d, $20, $83, $20, $83, $25, $91
	.byte $41, $18
	.word @song4ref1387
	.byte $41, $1c
	.word @song4ref1344
	.byte $41, $1c
	.word @song4ref1344
	.byte $20, $89, $00, $f1, $ff
	.byte $41, $1c
	.word @song4ref1344
	.byte $41, $1c
	.word @song4ref1344
	.byte $41, $1c
	.word @song4ref1344
	.byte $41, $1c
	.word @song4ref1344
	.byte $41, $1c
	.word @song4ref1344
	.byte $41, $1c
	.word @song4ref1344
	.byte $41, $18
	.word @song4ref1387
	.byte $41, $18
	.word @song4ref1387
	.byte $87, $44, $00
@song5ch0:
	.byte $46, $03, $97, $77, $4b, .lobyte(@env36), .hibyte(@env36), $4f, $01, $92, $08, $8d, $00, $ad, $8f, $71, $51, $01, $40
	.byte $4b, .lobyte(@env25), .hibyte(@env25), $4c, $0b, $ab, $81, $77, $4b, .lobyte(@env36), .hibyte(@env36), $4f, $01, $08
	.byte $8d, $00, $ad, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $7a
@song5ref49:
	.byte $4d
@song5ref50:
	.byte $4f, $00, $08, $87, $00, $4d, $08, $87, $00, $4d, $07, $81, $43, $08, $83, $00, $4d, $48, $03, $08, $4d, $48, $03, $08
	.byte $4d, $0a, $81, $4d, $0b, $81, $4d, $0d, $81, $4d, $0b, $81, $4d, $0a, $81, $4d, $0b, $81, $4d, $08, $87, $00, $4d, $08
	.byte $87, $00, $4d, $08, $87, $00, $4d, $48, $03, $08, $4d, $48, $03, $08, $4d, $0f, $81, $4d, $10, $81, $4d, $12, $81, $4d
	.byte $10, $81, $4d, $0f, $81, $4d, $10, $81
	.byte $41, $24
	.word @song5ref49
	.byte $4d, $0d, $81, $4d, $0f, $81, $4d, $10, $81, $4d, $0f, $81, $4d, $10, $81, $4d, $0f, $81, $00, $85, $4b, .lobyte(@env25)
	.byte .hibyte(@env25), $4c, $4f, $02
@song5ref159:
	.byte $27, $81, $00, $81, $25, $81, $27, $81, $00, $81, $28, $81, $00, $81, $28, $81, $00, $81, $28, $81, $27, $81, $28, $81
	.byte $24, $85
@song5ref185:
	.byte $25, $81, $00, $85, $25, $81, $00, $81, $24, $81, $00, $81, $21, $81, $00, $81, $21, $81, $00, $81, $24, $81, $21, $81
	.byte $1e, $81, $20
@song5ref212:
	.byte $85
@song5ref213:
	.byte $4f, $01
@song5ref215:
	.byte $20, $81, $00, $85, $20, $81, $00, $81, $48, $03, $20, $48, $03, $20, $27, $81, $20, $81, $00, $81, $48, $03, $20, $48
	.byte $03, $20, $25, $81, $27, $81, $28, $81, $27, $81, $28, $81, $27, $81
	.byte $41, $12
	.word @song5ref215
@song5ref256:
	.byte $27, $81, $28, $81, $2a, $81, $28, $81, $27, $81, $28, $81
	.byte $41, $1e
	.word @song5ref213
@song5ref271:
	.byte $25, $81, $00, $85, $25, $81, $00, $81, $25, $81, $27, $81, $24, $81, $00, $81, $24, $81, $00, $81, $24, $81, $25, $81
	.byte $27, $81, $20, $85, $4b, .lobyte(@env36), .hibyte(@env36)
	.byte $41, $19
	.word @song5ref50
	.byte $4d, $12, $4d, $0f, $4d, $0c, $4d, $0a, $4d, $08, $4d, $06, $4d, $0c, $4d, $0a, $4d, $08, $4d, $05, $4d, $03, $4d, $40
	.byte $0c, $4d, $08, $4d, $06, $4d, $03, $4d, $40, $0a, $4b, .lobyte(@env25), .hibyte(@env25), $4c, $4f, $01
@song5ref345:
	.byte $24, $48, $03, $81, $48, $03, $24, $48, $03, $25, $24, $81, $43, $25, $48, $03, $81, $28, $48, $03, $81, $27, $48, $03
	.byte $81, $1f, $81, $20, $81, $4b, .lobyte(@env36), .hibyte(@env36)
	.byte $41, $19
	.word @song5ref50
	.byte $00, $85, $4b, .lobyte(@env25), .hibyte(@env25), $4c, $4f, $01
@song5ref388:
	.byte $25, $83, $00, $25, $81, $24, $81, $00, $81, $27, $81
@song5ref399:
	.byte $00, $81, $25, $81, $00, $81, $24, $48, $03, $81, $24, $81, $25, $81, $1f
	.byte $41, $1f
	.word @song5ref212
	.byte $41, $12
	.word @song5ref215
	.byte $41, $0c
	.word @song5ref256
	.byte $41, $1e
	.word @song5ref213
	.byte $41, $1c
	.word @song5ref271
	.byte $14, $8d, $00, $ad, $44, $00
@song5ch1:
	.byte $97, $bf, $bf, $bf, $bf, $bf, $bf, $96
@song5ref444:
	.byte $14, $81, $00, $81, $78, $8a, $08, $81, $7f, $96
@song5ref454:
	.byte $14, $81, $00, $81, $14, $14, $1b, $81, $14, $81, $00, $81, $14, $14, $19, $81, $1b, $81, $1c, $81, $1b, $81, $1c, $81
	.byte $1b, $81, $14, $81, $00, $85
	.byte $41, $0e
	.word @song5ref454
@song5ref487:
	.byte $1b, $81, $1c, $81, $1e, $81, $1c, $81, $1b, $81, $1c, $81
	.byte $41, $20
	.word @song5ref444
@song5ref502:
	.byte $19, $81, $00, $81, $78, $8a, $0d, $81, $7f, $96, $19, $81, $00, $81, $1b, $81, $19, $81, $18, $81, $00, $81, $18, $81
	.byte $00, $81, $18, $81, $19, $81, $1b, $81, $14, $85
	.byte $41, $24
	.word @song5ref444
	.byte $41, $0e
	.word @song5ref454
	.byte $41, $0c
	.word @song5ref487
	.byte $41, $20
	.word @song5ref444
	.byte $41, $1e
	.word @song5ref502
	.byte $00, $bd, $bf, $bf, $bf, $87, $7a, $4e, $fe, $4f, $02, $92
	.byte $41, $18
	.word @song5ref159
	.byte $4f, $01, $24, $85, $4f, $00
	.byte $41, $1c
	.word @song5ref185
	.byte $4f, $02
	.byte $41, $1e
	.word @song5ref215
	.byte $41, $12
	.word @song5ref215
	.byte $41, $0c
	.word @song5ref256
	.byte $4f, $02
	.byte $41, $1e
	.word @song5ref215
	.byte $41, $1c
	.word @song5ref271
	.byte $00, $bd, $9f, $4f, $00
	.byte $41, $0d
	.word @song5ref345
	.byte $48, $03, $81, $20, $48, $03, $81, $00, $bd, $87
	.byte $41, $0b
	.word @song5ref388
	.byte $4f, $01
	.byte $41, $0d
	.word @song5ref399
	.byte $85, $4f, $02
	.byte $41, $1e
	.word @song5ref215
	.byte $41, $12
	.word @song5ref215
	.byte $41, $0c
	.word @song5ref256
	.byte $4f, $02
	.byte $41, $1e
	.word @song5ref215
	.byte $41, $1c
	.word @song5ref271
	.byte $14, $8d, $00, $ad, $44, $00
@song5ch2:
	.byte $97, $bf, $bf, $bf, $71, $51, $01, $40, $83, $92
@song5ref657:
	.byte $50, $4d, $17, $14, $50, $51, $16, $13, $50, $38, $15, $13, $50, $35, $16, $14, $50, $4d, $17, $14, $50, $49, $18, $15
	.byte $50, $45, $19, $16, $50, $41, $1a, $17, $50, $3d, $1b, $18, $50, $3a, $1c, $19, $50, $37, $1d, $1a, $50, $34, $1e, $1b
	.byte $50, $31, $1f, $1c, $50, $2e, $20, $1d, $50, $2c, $21, $1e, $50, $1b, $22, $20, $50, $19, $23, $21, $50, $18, $24, $22
	.byte $50, $17, $25, $23, $50, $15, $26, $24, $50, $14, $27, $25, $50, $13, $28, $26, $50, $12, $29, $27, $50, $11, $2a, $28
	.byte $50, $10, $2b, $29, $50, $0f, $2c, $2a, $50, $0f, $2d, $2b, $50, $0e, $2e, $2c, $50, $0d, $2f, $2d, $50, $0c, $30, $2e
	.byte $00, $bd, $bf, $bf, $bf, $bf, $71, $51, $01, $40, $83
	.byte $41, $1e
	.word @song5ref657
	.byte $8e
@song5ref792:
	.byte $14, $00, $87, $14, $00, $83, $14, $14, $1b, $00, $14, $00, $83, $14, $14, $19, $00, $1b, $00, $1c, $00, $1b, $00, $1c
	.byte $00, $1b, $00
	.byte $41, $0f
	.word @song5ref792
	.byte $1b, $00, $1c, $00, $1e, $00, $1c, $00, $1b, $00, $1c, $00
	.byte $41, $1b
	.word @song5ref792
	.byte $19, $00, $87, $19, $00, $83, $1b, $00, $19, $00, $18, $00, $83, $18, $00, $83, $18, $00, $19, $00, $1b, $00, $14, $00
	.byte $83
@song5ref862:
	.byte $92
@song5ref863:
	.byte $14, $48, $02, $81, $48, $02, $14, $48, $02, $14, $48, $02, $14, $00, $14, $48, $02, $81, $48, $02, $14, $48, $02, $14
	.byte $48, $02, $14, $00, $14, $83, $00, $83, $48, $02, $14, $48, $02, $14, $16, $48, $02, $81, $17, $48, $02, $81, $19, $48
	.byte $02, $81, $17, $48, $02, $81, $16, $48, $02, $81, $17, $48, $02, $81
	.byte $41, $12
	.word @song5ref863
@song5ref928:
	.byte $1b, $48, $02, $81, $1c, $48, $02, $81, $1e, $48, $02, $81, $1c, $48, $02, $81, $1b, $48, $02, $81, $1c, $48, $02, $81
	.byte $41, $1e
	.word @song5ref863
	.byte $41, $12
	.word @song5ref863
@song5ref958:
	.byte $19, $48, $02, $81, $1b, $48, $02, $81, $1c, $48, $02, $81, $1b, $48, $02, $81, $1c, $48, $02, $81, $1b, $48, $02, $81
	.byte $a8, $25, $89, $00, $b1, $bf
	.byte $41, $1e
	.word @song5ref862
	.byte $41, $12
	.word @song5ref863
	.byte $41, $0c
	.word @song5ref928
	.byte $41, $1e
	.word @song5ref863
	.byte $41, $12
	.word @song5ref863
	.byte $41, $0c
	.word @song5ref958
	.byte $41, $1e
	.word @song5ref863
	.byte $41, $12
	.word @song5ref863
	.byte $41, $0c
	.word @song5ref928
	.byte $41, $1e
	.word @song5ref863
	.byte $a8, $25, $89, $00, $b1
	.byte $41, $1e
	.word @song5ref862
	.byte $41, $12
	.word @song5ref863
	.byte $41, $0c
	.word @song5ref928
	.byte $41, $1e
	.word @song5ref863
	.byte $41, $12
	.word @song5ref863
	.byte $41, $0c
	.word @song5ref958
	.byte $00, $bd, $44, $00
@song5ch3:
	.byte $70, $51, $04, $f0, $92, $50, $05, $10, $1f, $95
@song5ref1056:
	.byte $8a, $40, $0a, $89, $00, $81
@song5ref1062:
	.byte $80, $01, $00, $8c, $01, $01, $80, $01, $00, $8c, $01, $01, $80, $01, $00, $8c, $01, $01
	.byte $41, $0c
	.word @song5ref1062
	.byte $41, $0c
	.word @song5ref1062
	.byte $80, $01, $00, $8c, $01, $01, $80, $01, $01, $01, $01, $86, $01, $00, $80, $01, $01, $01, $86, $01, $80, $01, $01, $01
	.byte $86, $01, $80, $01, $01
	.byte $41, $10
	.word @song5ref1056
	.byte $41, $0c
	.word @song5ref1062
	.byte $41, $0c
	.word @song5ref1062
	.byte $41, $0c
	.word @song5ref1062
	.byte $80, $01, $00, $8c, $01, $01, $80, $01, $00, $8c, $01, $01, $86
@song5ref1140:
	.byte $03, $81, $00, $85, $03, $81, $00, $85, $03, $81, $00, $81, $80, $03, $81, $86, $03, $81, $03, $81, $80, $03, $03, $86
	.byte $03, $03, $03, $03, $03, $03, $03, $03, $03, $81, $00, $81, $80, $03, $81, $86, $03, $81, $00, $80, $03, $86, $03, $81
	.byte $03, $81, $00, $80, $03, $03, $81, $86, $03, $81, $80, $03, $81, $86, $03, $81, $01, $47, $02, $01, $47, $05, $01, $81
	.byte $47, $00, $01, $47, $03, $01, $47, $06, $01, $81
	.byte $41, $3c
	.word @song5ref1140
	.byte $41, $3c
	.word @song5ref1140
	.byte $8a, $40, $0a, $9d, $45, $95, $86, $03, $81, $03, $81, $03, $81, $00, $b1, $03, $81, $00, $81, $03, $81, $00, $b9, $70
	.byte $51, $02, $f0, $92, $50, $02, $10, $1f, $bd
@song5ref1261:
	.byte $82, $14, $00, $80, $20, $82, $14
@song5ref1268:
	.byte $86, $14, $81, $82, $14, $80, $20, $21, $20, $82, $14, $80, $20, $86, $14, $81, $82, $14, $80, $20
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $8a, $40, $0a, $85, $45, $85, $00, $9d, $71, $51, $04, $90, $92, $40, $0a, $8d, $7f, $8a, $40, $0a, $85, $45, $85, $00
	.byte $9d, $71, $51, $04, $90, $92, $40, $0a, $8d, $7f
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
@song5ref1364:
	.byte $82, $14, $00, $80, $20, $82, $14, $86, $14, $81, $82, $14, $80, $20, $71, $51, $05, $c0, $92, $01, $8d, $7f, $8a, $40
	.byte $0a, $85
	.byte $41, $0c
	.word @song5ref1268
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $8a, $40, $0a, $89, $45, $81, $00, $9d, $86, $14, $81, $00, $81, $14, $81, $00, $81, $8a, $40, $0a, $85
	.byte $41, $0c
	.word @song5ref1268
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $10
	.word @song5ref1261
	.byte $41, $0b
	.word @song5ref1364
	.byte $8d, $45, $85, $00, $a5, $44, $00
@song5ch4:
	.byte $97, $11, $bd, $00, $9d, $20, $20, $20, $20, $25, $81, $20, $20, $20, $25, $20, $20, $20, $25, $20, $20, $11, $bd, $00
	.byte $bd, $25, $89, $25, $89, $25, $89, $25, $81, $25, $85, $25, $25, $25, $25, $25, $25, $25, $25, $25, $89, $25, $85, $25
	.byte $81, $25, $89, $25, $85, $25, $81, $25, $47, $02, $25, $47, $05, $25, $81, $47, $00, $25, $47, $03, $25, $47, $06
@song5ref1532:
	.byte $25, $81
@song5ref1534:
	.byte $25, $81, $11, $81, $11, $81, $25, $81, $11, $81, $11, $81, $25, $81, $11, $81, $11, $81, $25, $81, $25, $81, $11, $81
	.byte $25, $25, $25, $25, $25, $25, $25, $25
	.byte $41, $0a
	.word @song5ref1534
	.byte $41, $0c
	.word @song5ref1532
@song5ref1572:
	.byte $25, $81, $25, $47, $02, $25, $47, $05, $25, $11, $47, $00, $25, $47, $03, $25, $47, $06, $25, $11
	.byte $41, $20
	.word @song5ref1534
	.byte $41, $0a
	.word @song5ref1534
	.byte $41, $0c
	.word @song5ref1532
	.byte $41, $0a
	.word @song5ref1572
	.byte $00, $b5, $25, $81, $25, $81, $25, $95, $00, $9d, $25, $85, $25, $9d, $00, $9d
@song5ref1620:
	.byte $00, $a9, $20, $20, $25, $81, $20, $81, $25, $81, $20
@song5ref1631:
	.byte $81
@song5ref1632:
	.byte $11, $89, $11, $89, $16, $81, $11, $85, $11, $11, $1a, $81, $17, $81, $12, $81, $17, $81, $1a, $81, $17, $81, $11, $89
	.byte $11, $89, $11, $89, $11, $11, $1c, $81, $0f, $81, $18, $81, $0f, $81, $1c, $81, $0f
	.byte $41, $1f
	.word @song5ref1631
@song5ref1676:
	.byte $12, $81, $1c, $81, $0f, $81, $1c, $81, $0f, $81, $1c, $81, $00, $bd, $bf
	.byte $41, $29
	.word @song5ref1632
	.byte $41, $1f
	.word @song5ref1631
	.byte $41, $0c
	.word @song5ref1676
	.byte $41, $16
	.word @song5ref1632
	.byte $18, $89, $1b, $89, $11, $89, $11, $11
	.byte $41, $0c
	.word @song5ref1676
	.byte $41, $16
	.word @song5ref1632
	.byte $41, $35
	.word @song5ref1620
	.byte $41, $1f
	.word @song5ref1631
	.byte $41, $0e
	.word @song5ref1676
	.byte $44, $00
