song_stereo_madness_foreverbound = 0
song_back_on_track_djvi = 1
song_polargeist_step = 2
song_dry_out_djvi = 3
song_cant_let_go = 4
song_jumper = 5
song_cycles = 6
song_clutterfunk = 7
song_blast_processing_waterflame = 8
song_deadlocked_f-777 = 9
song_practice_ocularnebula = 10
song_geometry_dash_menu_theme = 11
song_max = 12

.if SONG_STRINGS
song_strings:
.asciiz "Stereo Madness (ForeverBound)"
.asciiz "Back on Track (DJVI)"
.asciiz "Polargeist (Step)"
.asciiz "Dry Out (DJVI)"
.asciiz "Can't Let Go"
.asciiz "Jumper"
.asciiz "Cycles"
.asciiz "Clutterfunk"
.asciiz "Blast Processing (Waterflame)"
.asciiz "Deadlocked (F-777)"
.asciiz "Practice (OcularNebula)"
.asciiz "Geometry Dash Menu Theme"
.endif
