#define song_menu_theme_b_sides 0
#define song_crackdown 1
#define song_fingerbang 2
#define song_freedom_dive 3
#define song_pyrophoric 4
#define song_infernoplex_full 5
#define song_ultimatedestruction 6
#define song_dash_full 7
#define song_ground_to_space 8
#define song_subtle_oddities 9
#define song_ssendam_oerets 10
#define song_atthespeedoflightfull 11
#define song_the_seven_seas 12
#define song_against_the_odds_redux 13
#define song_time_machine_full 14
#define song_eon 15
#define song_windfall 16
#define song_mayhem 17
#define song_whats_a_future_funk 18
#define song_clutterfunk 19
#define song_megalovania 20
#define song_deadlocked 21
#define song_atthespeedoflight2 22
#define song_practice 23
#define song_endgame 24
#define song_time_machine 25
#define song_just_right_full 26
#define song_idols 27
#define song_isolation 28
#define song_polargeist 29
#define song_clutterfunk_2 30
#define song_fingerdash 31
#define song_cant_let_go_remix 32
#define song_beep_beep 33
#define song_chaoz_airflow 34
#define song_geometrical_dominator 35
#define song_hsad 36
#define song_electrodynamix 37
#define song_dash 38
#define song_back_on_track_full 39
#define song_magic_touch 40
#define song_toe_2 41
#define song_eighto 42
#define song_hexagon_force 43
#define song_clubstep_full 44
#define song_infernoplex 45
#define song_mayhem_short 46
#define song_stalemate_full 47
#define song_electroman_adventures 48
#define song_dry_out_full 49
#define song_rainbow_tylenol 50
#define song_chaozfantasy 51
#define song_death_moon 52
#define song_jack_russel 53
#define song_atthespeedoflight 54
#define song_haunted_woods 55
#define song_sonic_blaster 56
#define song_blast_processing 57
#define song_clubstep 58
#define song_thoughts 59
#define song_machina_gdw_cut 60
#define song_back_on_track 61
#define song_cant_let_go 62
#define song_base_after_base 63
#define song_stalemate 64
#define song_candyland 65
#define song_glitch_gremlin 66
#define song_just_right 67
#define song_power_trip 68
#define song_cycles 69
#define song_ground_to_krusty_krab 70
#define song_kesobomb 71
#define song_stereo_madness_2 72
#define song_atthespeedoflight3 73
#define song_cant_electroman 74
#define song_glint 75
#define song_hell 76
#define song_xo 77
#define song_stereo_madness 78
#define song_xstep 79
#define song_jumper_full 80
#define song_kratos 81
#define song_midnight 82
#define song_jumper 83
#define song_theory_of_everything 84
#define song_chaoz_impact 85
#define song_lost 86
#define song_ninox 87
#define song_repmuj 88
#define song_dry_out 89
#define song_flow 90
#define song_ludicrous_speed 91
#define song_metamorphosis 92
#define song_problematic 93
#define song_scheming_weasel 94
#define song_menu_theme 95
#define song_the_challenge 96
#define song_driving_by_night 97
#define song_retray 98
#define song_round_1_gdw_cut 99
#define song_space_pirates_gdw_cut 100
#define song_youve_been_trolled 101
#define song_beast_mode_gdw_cut 102
#define song_years_gdw_cut 103
#define song_payload_gdw_cut 104
#define song_emeht_unem 105
#define song_max 106