#define song_crackdown 0
#define song_clutterfunk 1
#define song_atthespeedoflight 2
#define song_practice 3
#define song_atthespeedoflight2 4
#define song_eon 5
#define song_infernoplex 6
#define song_polargeist 7
#define song_time_machine 8
#define song_endgame 9
#define song_electrodynamix 10
#define song_death_moon 11
#define song_hexagon_force 12
#define song_menu_theme 13
#define song_cant_let_go 14
#define song_electroman_adventures 15
#define song_toe_2 16
#define song_back_on_track 17
#define song_clubstep 18
#define song_haunted_woods 19
#define song_base_after_base 20
#define song_jumper 21
#define song_blast_processing 22
#define song_stalemate 23
#define song_stereo_madness_2 24
#define song_cycles 25
#define song_the_challenge 26
#define song_chaozfantasy 27
#define song_just_right 28
#define song_stereo_madness 29
#define song_dry_out 30
#define song_xstep 31
#define song_theory_of_everything 32
#define song_midnight 33
#define song_retray 34
#define song_scheming_weasel 35
#define song_problematic 36
#define song_max 37