sfx_explode_11 = 0
sfx_playsound_01 = 1
sfx_quitsound_01 = 2
sfx_achievement_01 = 3
sfx_endstart_02 = 4
sfx_highscoreget02 = 5
sfx_chestclick = 6
sfx_chestland = 7
sfx_chestopen01 = 8
sfx_reward01 = 9
sfx_gold01 = 10
sfx_gold02 = 11
sfx_secretkey = 12
sfx_max = 13

.if SFX_STRINGS
sfx_strings:
.asciiz "explode_11"
.asciiz "playSound_01"
.asciiz "quitSound_01"
.asciiz "achievement_01"
.asciiz "endStart_02"
.asciiz "highscoreGet02"
.asciiz "chestClick"
.asciiz "chestLand"
.asciiz "chestOpen01"
.asciiz "reward01"
.asciiz "gold01"
.asciiz "gold02"
.asciiz "secretKey"
.endif
