#define song_okiba_crackdown 0
#define song_fingerbang 1
#define song_nine_circles 2
#define song_atthespeedoflightfull 3
#define song_thermodynamix_full 4
#define song_every_end_pt2 5
#define song_infernoplex_full 6
#define song_dash_full 7
#define song_menu_theme 8
#define song_the_angel 9
#define song_lost 10
#define song_time_machine_full 11
#define song_clutterfunk 12
#define song_miami_hotline_vol_3 13
#define song_endorphins 14
#define song_future_funk_pt1 15
#define song_accelerate 16
#define song_apoplexy 17
#define song_clubstep 18
#define song_every_end_pt1 19
#define song_2nes 20
#define song_practice 21
#define song_just_right_full 22
#define song_supernova 23
#define song_polargeist 24
#define song_press_start 25
#define song_theory_of_everything 26
#define song_toe_2 27
#define song_electroman_adventures 28
#define song_geometrical_dominator 29
#define song_fingerdash 30
#define song_shiawase_vip 31
#define song_animation_warrior_theme 32
#define song_electrodynamix 33
#define song_back_on_track_full 34
#define song_slash_inferno 35
#define song_free_mind 36
#define song_future_funk_pt2 37
#define song_eighto_full 38
#define song_endgame 39
#define song_bit_of_a_vibe 40
#define song_magic_touch 41
#define song_hexagon_force 42
#define song_beep_beep 43
#define song_factory_time 44
#define song_idols 45
#define song_astronomical_expedition 46
#define song_isolation 47
#define song_clutterfunk_2 48
#define song_cryogenic 49
#define song_bad_apple 50
#define song_check_out 51
#define song_explorers 52
#define song_death_moon 53
#define song_youve_been_trolled 54
#define song_blast_processing 55
#define song_ludicrous_speed 56
#define song_rainbow_tylenol 57
#define song_fantasy 58
#define song_megalovania 59
#define song_the_seven_seas 60
#define song_haunted_woods 61
#define song_pursuit 62
#define song_stereo_madness_2 63
#define song_every_madness 64
#define song_final_battle 65
#define song_meltdown 66
#define song_raining_tacos 67
#define song_sonic_blaster 68
#define song_stalemate 69
#define song_golden_haze_full 70
#define song_snow 71
#define song_tiny_tunes 72
#define song_base_after_base 73
#define song_fire_aura 74
#define song_infiltration 75
#define song_airborne_robots 76
#define song_mayhem_re_nes 77
#define song_power_trip 78
#define song_dry_out_full 79
#define song_ultimatedestruction 80
#define song_xenogenesis 81
#define song_deadlocked 82
#define song_the_challenge 83
#define song_chaozfantasy 84
#define song_infinite_power 85
#define song_cycles 86
#define song_blacklight 87
#define song_chaoz_impact 88
#define song_glitch_gremlin 89
#define song_against_the_odds_redux 90
#define song_dance_of_the_violins 91
#define song_kesobomb 92
#define song_subtle_oddities 93
#define song_extraordinary_excitement 94
#define song_ground_to_space 95
#define song_holography 96
#define song_windfall 97
#define song_stereo_madness 98
#define song_jawbreaker 99
#define song_pyrophoric_legacy_remix 100
#define song_xo 101
#define song_xstep 102
#define song_candyland 103
#define song_kratos 104
#define song_midnight 105
#define song_fairydust 106
#define song_jumper_full 107
#define song_meowstuff 108
#define song_ninox 109
#define song_select_payment_type 110
#define song_cant_let_go 111
#define song_scheming_weasel 112
#define song_driving_by_night 113
#define song_flow 114
#define song_moon_fries 115
#define song_problematic 116
#define song_max 117