; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Famidash music:
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1
; FAMISTUDIO_USE_ARPEGGIO = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_famidash_music56:=music_data_famidash_music56

music_data_famidash_music56:
	.byte 5
	.word @instruments
	.word @samples-5
; The DPCM aligner used to be here
; 01 : Chaoz Impact
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word 358,298
; 02 : Jumper Full
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word 364,303
; 03 : Meowstuff
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word 307,256
; 04 : Problematic
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.word 262,218
; 05 : repmuJ
	.word @song5ch0
	.word @song5ch1
	.word @song5ch2
	.word @song5ch3
	.word @song5ch4
	.word 366,305

.export music_data_famidash_music56
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env10,@env8,@env31,@env0 ; 00 : hat
	.word @env18,@env21,@env3,@env0 ; 01 : snare
	.word @env17,@env8,@env22,@env0 ; 02 : rel hats
	.word @env36,@env19,@env22,@env0 ; 03 : blank instant decay
	.word @env2,@env19,@env22,@env0 ; 04 : echo
	.word @env11,@env32,@env22,@env0 ; 05 : kick
	.word @env33,@env8,@env3,@env0 ; 06 : cymbal
	.word @env16,@env19,@env22,@env0 ; 07 : blank
	.word @env4,@env19,@env23,@env0 ; 08 : sample
	.word @env16,@env19,@env5,@env0 ; 09 : electroman lead
	.word @env20,@env19,@env22,@env0 ; 0a : clap no app
	.word @env26,@env19,@env22,@env0 ; 0b : Instrument 1
	.word @env27,@env35,@env23,@env0 ; 0c : octave arp
	.word @env17,@env19,@env22,@env0 ; 0d : Instrument 2
	.word @env28,@env19,@env22,@env29 ; 0e : jaezu lead
	.word @env15,@env19,@env22,@env0 ; 0f : DMC: drums + bass
	.word @env14,@env19,@env6,@env0 ; 10 : endgame lead
	.word @env13,@env19,@env22,@env0 ; 11 : 02 but tri
	.word @env34,@env19,@env24,@env0 ; 12 : shift string
	.word @env15,@env19,@env22,@env1 ; 13 : Extreme pitch down
	.word @env27,@env35,@env22,@env0 ; 14 : octave arp [ no duty ]
	.word @env37,@env19,@env22,@env0 ; 15 : blank slower string

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c0,$0f,$c1,$04,$c2,$02,$c3,$04,$c4,$02,$c5,$03,$c6,$04,$c7,$02,$c8,$03,$c9,$05,$ca,$06,$cb,$08,$cc,$03,$ce,$02,$cd,$02,$ce,$cf,$cf,$d0,$03,$d1,$02,$d2,$02,$d3,$02,$d4,$d4,$d5,$02,$d6,$03,$d7,$04,$d8,$d9,$da,$06,$db,$02,$dc,$02,$dd,$02,$de,$03,$df,$02,$e0,$04,$e1,$04,$e2,$05,$e3,$02,$e4,$05,$e5,$04,$e6,$02,$e7,$e7,$e8,$03,$e9,$03,$ea,$05,$eb,$03,$ec,$07,$ed,$03,$ee,$02,$ef,$04,$f0,$04,$f1,$02,$f2,$04,$f3,$f2,$f3,$03,$f4,$03,$f5,$02,$f6,$02,$f7,$02,$f8,$02,$f9,$f9,$fa,$fa,$fb,$fb,$fc,$fd,$fd,$fe,$fe,$ff,$00,$7f
@env2:
	.byte $00,$cb,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$13
@env3:
	.byte $c1,$c0,$00,$01
@env4:
	.byte $00,$c9,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$00,$08
@env5:
	.byte $c2,$c1,$03,$c0,$02,$c0,$00,$01
@env6:
	.byte $c2,$c2,$c0,$00,$00
@env7:
	.byte $c0,$c3,$c8,$cc,$00,$00
@env8:
	.byte $bd,$c0,$00,$01
@env9:
	.byte $c0,$c4,$c9,$cc,$00,$00
@env10:
	.byte $00,$c8,$c4,$c2,$c0,$00,$04
@env11:
	.byte $00,$cd,$c9,$c5,$c2,$c1,$c0,$00,$06
@env12:
	.byte $00,$c0,$bf,$03,$c0,$c0,$c1,$02,$c1,$00,$01
@env13:
	.byte $00,$c4,$02,$c5,$02,$c6,$02,$c0,$c5,$03,$c4,$03,$c0,$00,$0c
@env14:
	.byte $00,$cf,$cd,$cb,$c7,$c7,$ca,$00,$06
@env15:
	.byte $00,$cf,$7f,$00,$02
@env16:
	.byte $04,$cf,$00,$01,$ca,$c6,$c4,$c2,$c0,$00,$08
@env17:
	.byte $00,$c8,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$0d
@env18:
	.byte $00,$cd,$cb,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env19:
	.byte $c0,$7f,$00,$01
@env20:
	.byte $00,$cf,$ca,$cc,$ca,$c9,$c8,$c6,$c5,$c4,$c2,$c1,$c0,$00,$0c
@env21:
	.byte $c6,$cc,$00,$01
@env22:
	.byte $7f,$00,$00
@env23:
	.byte $c2,$7f,$00,$00
@env24:
	.byte $c1,$c2,$c1,$c0,$00,$00
@env25:
	.byte $c0,$c5,$c8,$cc,$00,$00
@env26:
	.byte $00,$c3,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$0d
@env27:
	.byte $00,$c9,$c7,$c5,$00,$03
@env28:
	.byte $0d,$c6,$c8,$ca,$cc,$03,$cb,$03,$ca,$03,$c9,$00,$0a,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$1c
@env29:
	.byte $00,$c0,$07,$c0,$c1,$c2,$c3,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$00,$03
@env30:
	.byte $c0,$c0,$cc,$00,$00
@env31:
	.byte $c0,$c1,$00,$00
@env32:
	.byte $c9,$cf,$00,$01
@env33:
	.byte $18,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c7,$c6,$02,$c5,$c5,$c4,$02,$c3,$03,$c2,$c2,$00,$15,$c2,$c2,$c1,$03,$c0,$00,$1c
@env34:
	.byte $08,$c4,$c5,$c6,$08,$c5,$00,$05,$c5,$04,$c4,$07,$c3,$05,$c2,$02,$c1,$02,$c0,$00,$12
@env35:
	.byte $c0,$c0,$cc,$cc,$00,$00
@env36:
	.byte $00,$cf,$cf,$cb,$c8,$c5,$c3,$c2,$c1,$c0,$00,$09
@env37:
	.byte $0c,$c2,$c3,$c4,$c5,$c6,$c6,$c7,$04,$c6,$00,$09,$c6,$c6,$c5,$02,$c4,$02,$c3,$02,$c2,$02,$c1,$c1,$c0,$00,$18

@samples:
	.byte $2a+.lobyte(FAMISTUDIO_DPCM_PTR),$a8,$0b,$40,$02 ; 00 BSV (Pitch:11)
	.byte $54+.lobyte(FAMISTUDIO_DPCM_PTR),$7f,$0c,$40,$02 ; 01 BSV_1 (Pitch:12)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$a7,$4f,$40,$03 ; 02 Choir Ahh A (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$4f,$40,$09 ; 03 Choir Ahh B (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$4f,$40,$04 ; 04 Choir Ahh C (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$4d,$40,$05 ; 05 Choir Ahh C# (Pitch:13)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4c,$40,$05 ; 06 Choir Ahh D (Pitch:12)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4e,$40,$05 ; 07 Choir Ahh D (Pitch:14)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4f,$40,$05 ; 08 Choir Ahh D (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4f,$40,$06 ; 09 Choir Ahh E (Pitch:15)
	.byte $38+.lobyte(FAMISTUDIO_DPCM_PTR),$de,$4f,$40,$06 ; 0a Choir Ahh G (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$09 ; 0b continue (Pitch:15)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$01 ; 0c demon level (Pitch:15)
	.byte $2a+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$03 ; 0d EON_AH (Pitch:15)
	.byte $11+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 0e fdbass A# (Pitch:15)
	.byte $23+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$00 ; 0f fdbass B (Pitch:15)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$09,$40,$00 ; 10 fdbass C (Pitch:9)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0a,$40,$00 ; 11 fdbass C (Pitch:10)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0c,$40,$00 ; 12 fdbass C (Pitch:12)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0e,$40,$00 ; 13 fdbass C (Pitch:14)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 14 fdbass C (Pitch:15)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$08,$40,$00 ; 15 fdbass C# (Pitch:8)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0a,$40,$00 ; 16 fdbass C# (Pitch:10)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0b,$40,$00 ; 17 fdbass C# (Pitch:11)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0c,$40,$00 ; 18 fdbass C# (Pitch:12)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0d,$40,$00 ; 19 fdbass C# (Pitch:13)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 1a fdbass C# (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0b,$40,$00 ; 1b fdbass D (Pitch:11)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0f,$40,$00 ; 1c fdbass D (Pitch:15)
	.byte $6b+.lobyte(FAMISTUDIO_DPCM_PTR),$2b,$0e,$40,$00 ; 1d fdkick (Pitch:14)
	.byte $5e+.lobyte(FAMISTUDIO_DPCM_PTR),$78,$0f,$40,$01 ; 1e hi (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$38,$0f,$40,$01 ; 1f is a (Pitch:15)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$6d,$0f,$40,$02 ; 20 machine (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e0,$0e,$40,$07 ; 21 MUSIC_PCM_DS-geo (Pitch:14)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$08 ; 22 one (Pitch:15)
	.byte $52+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$40,$04 ; 23 OrchHitA.dmc (Pitch:12)
	.byte $52+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$40,$04 ; 24 OrchHitA.dmc (Pitch:14)
	.byte $52+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$04 ; 25 OrchHitA.dmc (Pitch:15)
	.byte $6a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$40,$03 ; 26 OrchHitF.dmc (Pitch:12)
	.byte $6a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$03 ; 27 OrchHitF.dmc (Pitch:15)
	.byte $64+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$40,$04 ; 28 OrchHitG.dmc (Pitch:12)
	.byte $64+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$40,$04 ; 29 OrchHitG.dmc (Pitch:14)
	.byte $64+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$04 ; 2a OrchHitG.dmc (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$40,$04 ; 2b OrchHitG#.dmc (Pitch:10)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$40,$04 ; 2c OrchHitG#.dmc (Pitch:12)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$40,$04 ; 2d OrchHitG#.dmc (Pitch:13)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$40,$04 ; 2e OrchHitG#.dmc (Pitch:14)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$04 ; 2f OrchHitG#.dmc (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$0a ; 30 PressStart (mp3c (Pitch:15)
	.byte $2f+.lobyte(FAMISTUDIO_DPCM_PTR),$57,$0f,$40,$0b ; 31 run (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$41,$0f,$34,$00 ; 32 snare (Pitch:15)
	.byte $0f+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0f,$40,$01 ; 33 this (Pitch:15)
	.byte $38+.lobyte(FAMISTUDIO_DPCM_PTR),$e7,$0f,$40,$07 ; 34 three (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$37,$0f,$40,$02 ; 35 time (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$d6,$0f,$40,$08 ; 36 two (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$0a ; 37 untitled (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0e,$40,$0b ; 38 voc1 (Pitch:14)
	.byte $0f+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$0e,$40,$0b ; 39 voc2 (Pitch:14)
	.byte $14+.lobyte(FAMISTUDIO_DPCM_PTR),$1e,$0e,$40,$0b ; 3a voc3 (Pitch:14)
	.byte $1c+.lobyte(FAMISTUDIO_DPCM_PTR),$4b,$0e,$40,$0b ; 3b voc4 (Pitch:14)

; The DPCM aligner used to be here
@song1ch0:
	.byte $46, $06
@song1ref3:
	.byte $a8
@song1ref4:
	.byte $12, $85, $00
@song1ref7:
	.byte $85, $12, $85, $19, $81, $18, $81, $00, $81, $15, $81, $00, $81, $0d, $81, $00, $81, $50, $e6, $21, $23, $17, $15, $81
	.byte $00, $81, $12, $85, $00, $85, $10, $81, $00, $85, $12, $81, $00, $81, $19, $81, $00, $81, $19, $81, $15, $81, $15, $81
	.byte $10, $85
	.byte $41, $32
	.word @song1ref4
	.byte $41, $32
	.word @song1ref4
	.byte $41, $32
	.word @song1ref4
	.byte $12, $85, $1e
	.byte $41, $11
	.word @song1ref7
@song1ref72:
	.byte $17, $81, $15, $81, $00, $81, $12, $00, $12, $00, $12, $00, $12, $00, $10, $81, $00, $85, $12, $81, $00, $81, $50, $e9
	.byte $23, $25, $19, $00, $81, $19, $00, $15, $00, $15, $00, $10, $81, $00, $81, $12, $85, $1e
	.byte $41, $11
	.word @song1ref7
	.byte $41, $16
	.word @song1ref72
	.byte $a0
@song1ref121:
	.byte $0e, $81, $00, $85, $0d, $81, $00, $85, $09, $81, $00, $81, $06, $81, $00, $85, $04, $81, $00, $85, $06, $81, $00, $81
	.byte $41, $18
	.word @song1ref121
@song1ref148:
	.byte $12, $81, $00, $85, $0e, $81, $00, $85, $0d, $81, $00, $81, $06, $81, $00, $85, $04, $81, $00, $85, $06, $81, $00, $81
	.byte $41, $18
	.word @song1ref121
	.byte $41, $18
	.word @song1ref148
	.byte $41, $18
	.word @song1ref121
	.byte $41, $18
	.word @song1ref148
	.byte $41, $18
	.word @song1ref121
	.byte $41, $13
	.word @song1ref148
	.byte $81, $06, $81, $00, $85
	.byte $41, $18
	.word @song1ref121
	.byte $41, $13
	.word @song1ref148
	.byte $81, $06, $81, $00, $85
	.byte $41, $16
	.word @song1ref121
	.byte $4f, $02, $a6, $29, $9d, $00, $bd, $44, $00
@song1ch1:
	.byte $bf, $bf, $bf, $bf, $4f, $03
	.byte $41, $23
	.word @song1ref3
	.byte $4f, $00, $81, $00, $81, $19, $81, $00, $81, $19, $81, $15, $81, $15, $81, $10, $85, $4f, $03
	.byte $41, $23
	.word @song1ref4
	.byte $4f, $00, $81, $00, $81, $19, $81, $00, $81, $19, $81, $15, $81, $15, $81, $10, $85, $79, $4e, $01, $4f, $01, $12, $85
	.byte $1e
	.byte $41, $11
	.word @song1ref7
	.byte $41, $24
	.word @song1ref72
	.byte $4e, $01, $4f, $01, $12, $85, $1e
	.byte $41, $11
	.word @song1ref7
	.byte $41, $15
	.word @song1ref72
	.byte $9d, $bf, $bf, $bf, $bf, $4e, $00, $8e, $28, $81, $2a, $81, $49, .lobyte(@env12), .hibyte(@env12), $8f, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $8e, $25, $81, $26, $49, .lobyte(@env12), .hibyte(@env12), $8d, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $8e, $28, $81, $25, $49, .lobyte(@env12), .hibyte(@env12), $85, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e
	.byte $21, $81, $20, $81, $1e, $85, $49, .lobyte(@env12), .hibyte(@env12), $97, $45, $8d, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $00, $8d, $8e, $28, $81, $2a, $49, .lobyte(@env12), .hibyte(@env12), $91, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $8e, $2c, $81, $2d, $49, .lobyte(@env12), .hibyte(@env12), $8d, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e
	.byte $2f, $81, $2c, $49, .lobyte(@env12), .hibyte(@env12), $85, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e, $2d, $81
	.byte $2c, $81, $2a, $49, .lobyte(@env12), .hibyte(@env12), $9d, $45, $8d, $00, $8d, $97, $a0
@song1ref409:
	.byte $1e, $81, $00, $81, $26, $85, $00, $81, $25, $85, $00, $81, $21, $85, $1e, $85, $00, $81, $1c, $85, $00, $81, $1e, $81
	.byte $00, $81, $2a, $85, $00, $81, $26, $85, $00, $81, $25, $85, $1e, $85, $00, $81, $1c, $85, $00, $81
	.byte $41, $19
	.word @song1ref409
	.byte $a1, $bf, $44, $00
@song1ch2:
	.byte $8e
@song1ref462:
	.byte $12, $00, $8b, $12, $00, $83, $19, $00, $18, $00, $83, $15, $00, $83, $0d, $00, $83, $50, $e6, $21, $23, $17, $15, $00
	.byte $83, $12, $00, $8b, $10, $00, $87, $12, $00, $83, $19, $00, $83, $19, $00, $15, $00, $15, $00, $10, $00, $83
	.byte $41, $2b
	.word @song1ref462
	.byte $41, $2b
	.word @song1ref462
	.byte $41, $2b
	.word @song1ref462
	.byte $00, $81, $84
@song1ref520:
	.byte $12, $81, $00, $81, $12, $81, $00, $81, $12, $81, $00, $81, $12, $81, $00, $81, $0e, $81, $00, $81, $0e, $81, $00, $81
	.byte $0d, $81, $00, $81, $0d, $81, $00, $81
	.byte $41, $20
	.word @song1ref520
	.byte $41, $20
	.word @song1ref520
	.byte $41, $20
	.word @song1ref520
	.byte $41, $20
	.word @song1ref520
	.byte $41, $20
	.word @song1ref520
	.byte $41, $20
	.word @song1ref520
	.byte $41, $20
	.word @song1ref520
	.byte $41, $20
	.word @song1ref520
	.byte $41, $20
	.word @song1ref520
	.byte $41, $20
	.word @song1ref520
	.byte $41, $20
	.word @song1ref520
	.byte $41, $20
	.word @song1ref520
	.byte $41, $20
	.word @song1ref520
	.byte $41, $20
	.word @song1ref520
	.byte $12, $81, $00, $81, $12, $81, $00, $81, $12, $81, $00, $81, $12, $81, $a6, $40, $4d, $9d, $00, $bd, $44, $00
@song1ch3:
	.byte $8c, $21, $bd, $bf, $23, $8d, $72
@song1ref624:
	.byte $82
@song1ref625:
	.byte $22, $81
@song1ref627:
	.byte $23, $81, $22, $81, $23, $81, $22, $81, $23, $81, $22, $81, $23, $81, $22, $81, $23, $81, $73
	.byte $41, $14
	.word @song1ref625
	.byte $22, $81, $23, $81, $22, $81, $23, $81, $22, $81, $23, $81, $22, $81, $23, $81, $7f, $8c, $21, $83, $00, $74
	.byte $41, $14
	.word @song1ref624
	.byte $22, $81, $75
	.byte $41, $12
	.word @song1ref627
	.byte $41, $14
	.word @song1ref625
	.byte $7f, $8c, $22, $85, $77, $82, $22, $81, $23, $81, $22, $81, $23, $81, $22, $81, $79
	.byte $41, $12
	.word @song1ref627
	.byte $7c
	.byte $41, $11
	.word @song1ref625
	.byte $7f, $23, $22, $23, $22, $23, $22, $23, $22, $23, $22, $23, $22, $23, $22, $23
@song1ref723:
	.byte $8c
@song1ref724:
	.byte $20, $85
@song1ref726:
	.byte $82, $23, $81, $84, $20, $81, $8a, $16, $81, $84, $20, $20, $82, $23, $81, $84, $20, $81, $8a, $16, $81, $84, $20, $81
	.byte $82, $23, $81, $84, $20, $81, $8a, $16, $81, $84, $20, $20, $82, $23, $81, $84, $20, $81
	.byte $41, $1e
	.word @song1ref723
	.byte $8a, $16, $81, $84, $20, $81
	.byte $41, $1c
	.word @song1ref726
@song1ref780:
	.byte $8a, $16, $81, $84, $20, $81, $82, $23, $81, $84, $20, $81, $8a, $16, $81, $84, $20, $81, $82, $23, $81, $84, $20, $81
	.byte $00, $81, $8c, $1e, $85, $00, $81, $1b, $85, $00, $81, $1d, $81
	.byte $41, $1e
	.word @song1ref724
	.byte $41, $1e
	.word @song1ref723
	.byte $41, $1e
	.word @song1ref723
	.byte $8a, $16, $81, $84, $20, $81
	.byte $41, $1c
	.word @song1ref726
	.byte $41, $1e
	.word @song1ref723
	.byte $8a, $16, $81, $84, $20, $81
	.byte $41, $1c
	.word @song1ref726
	.byte $41, $1e
	.word @song1ref723
	.byte $41, $1c
	.word @song1ref780
	.byte $41, $1e
	.word @song1ref724
	.byte $8a, $16, $81, $84, $20, $81
	.byte $41, $1c
	.word @song1ref726
	.byte $41, $1e
	.word @song1ref723
	.byte $8a, $16, $81, $84, $20, $20, $82, $23, $81, $84, $20, $81, $8a, $16, $81, $84, $20, $20, $82, $23, $81, $84, $20, $81
	.byte $8c, $20, $83, $1e, $83, $20, $83, $20, $83, $1f, $81, $20, $81, $20, $95, $00, $a5, $44, $00
@song1ch4:
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
@song1ref920:
	.byte $00, $81, $1a, $81, $00, $81, $1a, $81, $00, $81, $1a, $81, $00, $81, $1a, $81, $00, $81, $19, $81, $00, $81, $19, $81
	.byte $00, $81, $13, $81, $00, $81, $13, $81
	.byte $41, $20
	.word @song1ref920
	.byte $41, $20
	.word @song1ref920
	.byte $41, $15
	.word @song1ref920
	.byte $85, $13, $81, $00, $85, $17
@song1ref967:
	.byte $81, $00, $81, $11, $81, $00, $85, $16, $81, $00, $81, $11, $81, $00, $85, $19, $81, $00, $85, $13, $81, $00, $85, $17
	.byte $81, $00, $81, $11, $81, $00, $85, $16, $81, $00, $85, $11, $81, $00, $81, $1a, $81, $00, $85, $19, $81, $00, $85, $13
	.byte $41, $30
	.word @song1ref967
	.byte $41, $30
	.word @song1ref967
	.byte $41, $30
	.word @song1ref967
	.byte $41, $30
	.word @song1ref967
	.byte $41, $22
	.word @song1ref967
	.byte $81, $11, $81, $00, $81, $1e, $81, $00, $33, $81, $00, $1e, $81, $00, $33, $81, $00, $1e, $81, $1e, $81, $33, $85, $00
	.byte $b5, $44, $00
@song2ch0:
	.byte $46, $08, $97, $4f, $01, $9a, $2a, $83, $96
@song2ref10:
	.byte $2a, $81, $2a, $26, $81, $2d, $26, $81, $32, $2b, $81, $2d, $2a, $81, $2d, $83, $2a, $2d, $81, $26, $2a, $83, $2a, $81
	.byte $2a, $26, $81, $2d, $32, $81, $2d, $2b, $81, $2a, $28, $83, $26, $87, $4f, $02, $26, $4f, $02, $2a, $83
	.byte $41, $1e
	.word @song2ref10
	.byte $34, $36, $81, $37, $36, $81, $32, $34, $81, $32, $34, $81, $36, $74, $8e, $32, $81, $45, $7f, $96
@song2ref78:
	.byte $36, $81, $36, $37, $81, $37, $36, $81, $36, $32, $81, $32, $36, $81, $36, $37, $81, $37, $39, $81, $39, $32, $81, $32
	.byte $41, $12
	.word @song2ref78
	.byte $30, $81, $31, $32, $81, $32
	.byte $41, $18
	.word @song2ref78
	.byte $41, $12
	.word @song2ref78
	.byte $30, $81, $31, $32, $81, $32
	.byte $41, $18
	.word @song2ref78
	.byte $41, $15
	.word @song2ref78
	.byte $3e, $81, $3e, $3c, $81, $3c, $3b, $81, $3b
@song2ref138:
	.byte $39, $81, $39, $37, $81, $36, $37, $81, $36, $37, $81, $36, $34, $81, $2d, $32, $81, $32, $36, $81, $36, $37, $81, $37
	.byte $41, $0e
	.word @song2ref138
	.byte $32, $7d, $4f, $01, $81, $75, $81, $7f
@song2ref173:
	.byte $2a, $2b, $81, $2a, $2b, $81, $2d, $83, $32, $2d, $81, $2b, $2a, $83, $2b, $81, $2a, $26, $81, $2a, $26, $81
	.byte $41, $0d
	.word @song2ref173
	.byte $81, $2d, $2b, $81, $2a, $2b, $81, $2d, $26, $81
	.byte $41, $16
	.word @song2ref173
	.byte $41, $11
	.word @song2ref173
	.byte $2b, $81, $2d, $26, $81
	.byte $41, $16
	.word @song2ref173
	.byte $41, $11
	.word @song2ref173
	.byte $2b, $81, $2d, $26, $81
	.byte $41, $16
	.word @song2ref173
	.byte $2a, $2b, $81, $2a, $2b, $81, $2d, $83, $32, $36, $81, $37, $36, $81, $32, $34, $81, $32, $34, $81, $36, $88, $32
@song2ref256:
	.byte $00, $98, $1a, $00, $83, $1a, $00, $1a, $00, $81, $1a, $1e, $00, $81, $1e, $00, $1f, $1e, $00, $1e, $00, $81, $1e, $1f
	.byte $00, $81, $1f, $00, $21, $00, $81, $1f, $00, $81, $1f, $21, $00, $81, $21, $00, $26, $25, $00, $21, $00, $81, $21, $88
	.byte $0e
	.byte $41, $27
	.word @song2ref256
	.byte $25, $00, $81, $21, $00, $81, $21, $96
@song2ref316:
	.byte $32, $87, $2b, $83, $2d, $81, $00, $81, $32, $83, $37, $83, $36, $81, $2b, $34, $83
	.byte $41, $0e
	.word @song2ref316
	.byte $37, $39, $83
	.byte $41, $11
	.word @song2ref316
	.byte $41, $0e
	.word @song2ref316
	.byte $37, $39, $83, $4f, $00, $a2
@song2ref351:
	.byte $26, $83, $2b, $83, $2a, $83, $28, $83, $26, $83, $2b, $83, $2a, $83, $28, $83, $26, $83, $2b, $83, $2a, $83, $28, $83
	.byte $2d, $83, $2b, $83, $2a, $83, $25, $83, $4f, $00
	.byte $41, $20
	.word @song2ref351
	.byte $4f, $00
	.byte $41, $20
	.word @song2ref351
	.byte $4f, $00
	.byte $41, $20
	.word @song2ref351
	.byte $9a, $26, $83, $00, $87, $44, $00
@song2ch1:
	.byte $97, $78, $4f, $02, $86
@song2ref411:
	.byte $0e, $74, $15, $78, $1a, $0e, $74, $15, $78, $1a, $0e, $74, $15, $78, $1a, $0e, $74, $15, $78, $1a, $12, $74, $15, $78
	.byte $1e, $12, $74, $15, $78, $1e, $12, $74, $15, $78, $1e, $12, $74, $15, $78, $1e, $13, $74, $17, $78, $1f, $13, $74, $17
	.byte $78, $1f, $13, $74, $17, $78, $1f, $13, $74, $17, $78, $1f, $15, $74, $19, $78, $21, $15, $74, $19, $78, $21, $15, $74
	.byte $19, $78, $21, $15, $74, $19, $78, $21, $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref411
	.byte $41, $0d
	.word @song2ref411
	.byte $74, $1a, $78, $1e, $12, $74, $1a, $78, $1e, $12, $74, $1a, $78, $1e, $12, $74, $1a, $78, $1e, $7a, $a4, $26, $81, $45
	.byte $2b, $81, $45, $2a, $81, $45, $28, $81, $45, $2d, $81, $45, $2b, $81, $45, $2a, $81, $45, $25, $81, $45, $26, $81, $45
	.byte $89, $44, $00
@song2ch2:
	.byte $97, $df, $df, $df, $df, $df, $df, $00, $81, $9e
@song2ref636:
	.byte $1a, $00, $81, $1a, $00, $81, $1a, $00, $81, $1a, $00, $81, $1e, $00, $81, $1e, $00, $81, $1e, $00, $81, $1e, $00, $81
	.byte $1f, $00, $81, $1f, $00, $81, $1f, $00, $81, $1f, $00, $81, $21, $00, $81, $21, $00, $81, $21, $00, $81, $21, $00, $81
	.byte $41, $30
	.word @song2ref636
	.byte $41, $30
	.word @song2ref636
	.byte $41, $2e
	.word @song2ref636
@song2ref693:
	.byte $1a, $81, $00, $8f, $1a, $1e, $81, $00, $8f, $1e, $1f, $81, $00, $8f, $1f, $21, $81, $00, $91
	.byte $41, $13
	.word @song2ref693
	.byte $41, $13
	.word @song2ref693
	.byte $41, $13
	.word @song2ref693
	.byte $41, $13
	.word @song2ref693
	.byte $41, $13
	.word @song2ref693
	.byte $41, $13
	.word @song2ref693
	.byte $41, $13
	.word @song2ref693
	.byte $0e, $83, $00, $87, $44, $00
@song2ch3:
	.byte $97, $7c, $90, $1f, $7a, $83, $74, $81, $71, $81, $70, $d5, $df, $7c, $1f, $7a, $83, $7f
@song2ref758:
	.byte $80
@song2ref759:
	.byte $22, $81, $22, $22, $81, $22, $22, $81, $22, $84, $22, $83, $80, $22, $81, $22, $22, $81, $22, $22, $81, $22, $84, $22
	.byte $83
	.byte $41, $15
	.word @song2ref758
	.byte $81, $80, $22
	.byte $41, $16
	.word @song2ref759
	.byte $41, $11
	.word @song2ref758
	.byte $82, $16, $81, $80, $22
@song2ref801:
	.byte $7c, $90, $1f, $7a, $83, $7f
@song2ref807:
	.byte $82, $14, $81, $80, $22, $22, $81, $22, $82, $14, $81, $80, $22, $84, $22, $81, $80, $22, $82, $14, $81, $80, $22, $22
	.byte $81, $22, $82, $14, $81, $80, $22, $84, $22, $81, $80, $22
	.byte $41, $18
	.word @song2ref807
	.byte $41, $18
	.word @song2ref807
	.byte $41, $15
	.word @song2ref807
	.byte $41, $1a
	.word @song2ref801
	.byte $41, $18
	.word @song2ref807
	.byte $41, $18
	.word @song2ref807
	.byte $41, $15
	.word @song2ref807
	.byte $41, $1a
	.word @song2ref801
	.byte $41, $18
	.word @song2ref807
	.byte $41, $18
	.word @song2ref807
	.byte $41, $15
	.word @song2ref807
	.byte $41, $1a
	.word @song2ref801
	.byte $41, $18
	.word @song2ref807
	.byte $41, $18
	.word @song2ref807
	.byte $41, $15
	.word @song2ref807
	.byte $41, $1a
	.word @song2ref801
	.byte $41, $18
	.word @song2ref807
	.byte $41, $18
	.word @song2ref807
	.byte $41, $15
	.word @song2ref807
	.byte $41, $1a
	.word @song2ref801
	.byte $41, $18
	.word @song2ref807
	.byte $41, $18
	.word @song2ref807
	.byte $41, $15
	.word @song2ref807
	.byte $41, $1a
	.word @song2ref801
	.byte $41, $18
	.word @song2ref807
	.byte $41, $15
	.word @song2ref807
	.byte $78, $22, $81, $22, $7a, $22, $81, $22, $7b, $22, $81, $22, $22, $81, $22, $7c, $22, $81, $22, $7f, $22, $81, $22, $22
	.byte $81, $22, $82, $14, $83, $7c, $90, $1f, $7a, $83, $74, $81, $71, $81, $70, $85, $44, $00
@song2ch4:
	.byte $97, $1e, $dd, $df, $1e, $dd, $d1, $1e, $1e, $83
@song2ref974:
	.byte $33, $83, $1e, $83, $33, $81, $1e, $83, $1e, $33, $83, $1e, $83, $33, $81, $1e, $83, $1e
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $41, $12
	.word @song2ref974
	.byte $33, $ad, $33, $83, $1e, $8d, $44, $00
@song3ch0:
	.byte $46, $03, $9c, $2b, $85, $2c, $85, $2e, $85, $45, $85, $27, $85, $45, $85, $2c, $85, $45, $85, $00, $ed, $88
@song3ref23:
	.byte $2c, $85, $38, $89, $38, $89, $36, $89, $36, $89, $36, $8d, $35, $89, $35, $89, $34, $89, $34, $89, $36, $85, $2c, $85
	.byte $38, $89, $38, $89, $36, $89, $36, $89, $36, $85, $36, $89, $36, $89, $38, $a5
	.byte $41, $27
	.word @song3ref23
	.byte $8d, $79, $9c, $27, $85, $2e, $85, $2b, $85, $2c, $85, $2e, $85, $30, $85, $31, $85, $33, $85, $45, $85, $2c, $85, $45
	.byte $85, $29, $85, $45, $85, $2b, $85, $2c, $85, $2b, $85, $2e, $85, $27, $85, $45, $85, $24, $85, $27, $85, $2c, $85, $2e
	.byte $85, $30, $85, $45, $85, $2c, $85, $45, $85, $29, $85, $45, $85, $2b, $85, $2c, $85, $2e, $85, $33, $85, $27, $85, $45
	.byte $85, $2c, $85, $28, $85, $27, $85, $25, $85, $24, $85, $27, $85, $2c, $85, $2e, $85, $30, $85, $45, $85, $30, $85, $2e
	.byte $85, $2c, $85, $45, $85, $27, $85, $25, $85, $24, $85, $27, $85, $2c, $85, $27, $85, $2b, $85, $29, $85, $27, $85, $30
	.byte $85, $2e, $85, $2c, $85
@song3ref191:
	.byte $2e, $85, $30, $85, $33, $85, $30, $85, $2e, $85, $30, $85, $2c, $85, $45, $85, $00, $ed, $ff, $ff, $ff, $7f, $88, $38
	.byte $85, $38, $89, $38, $89, $3c, $89, $3c, $89, $3c, $85, $3d, $85, $3d, $89, $3d, $89, $3f, $89, $3f, $89, $79, $9c
@song3ref238:
	.byte $2c, $81, $2e, $81, $30, $85, $2c, $85, $27, $85, $45, $85, $00, $85, $25, $85, $24, $85, $25, $85, $27, $85, $2c, $85
	.byte $20, $85, $45, $85, $00, $95, $20, $81, $22, $81, $24, $85, $20, $85, $27, $85, $45, $85, $00, $85, $27, $85, $27, $85
	.byte $25, $85, $27, $85, $45, $85, $00, $a5
	.byte $41, $18
	.word @song3ref238
	.byte $41, $14
	.word @song3ref191
	.byte $44, $00
@song3ch1:
	.byte $79, $9c, $1d, $85, $45, $85, $1b, $8d, $45, $8d, $20, $8d, $45, $8d, $00, $dd, $88
@song3ref320:
	.byte $27, $85, $30, $89, $30, $89, $2e, $89, $2e, $89, $2e, $8d, $2c, $89, $2c, $89, $2e, $89, $2e, $89, $30, $85, $27, $85
	.byte $30, $89, $30, $89, $2e, $89, $2e, $89, $2e, $85, $2e, $89, $2e, $89, $30, $a5
	.byte $41, $28
	.word @song3ref320
	.byte $7f
	.byte $41, $14
	.word @song3ref23
	.byte $34, $85
	.byte $41, $14
	.word @song3ref23
	.byte $34, $85
	.byte $41, $14
	.word @song3ref23
	.byte $34, $85
	.byte $41, $14
	.word @song3ref23
	.byte $34, $85, $00, $fd, $ff, $ff, $ff, $78, $4f, $01, $aa, $24, $9d, $22, $9d, $25, $9d, $24, $9d, $24, $9d, $22, $9d, $25
	.byte $9d, $27, $9d, $4f, $01, $24, $9d, $22, $9d, $25, $9d, $24, $9d, $24, $9d, $22, $9d, $25, $9d, $27, $9d, $77, $8f, $76
	.byte $8f, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $70, $8f, $00, $fd, $ff, $44, $00
@song3ch2:
	.byte $af
@song3ref450:
	.byte $8e
@song3ref451:
	.byte $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85
	.byte $14, $85, $20, $85, $14, $85, $20, $85
@song3ref483:
	.byte $14, $85, $20, $83, $00, $81, $20, $83, $00, $81, $23, $85, $00, $81
@song3ref497:
	.byte $20, $85, $1e, $85, $20, $85
@song3ref503:
	.byte $19, $85, $00, $81, $19, $85, $00, $81, $1b, $85, $00, $81, $1b, $85, $00, $81, $94, $1b, $85, $1b, $85, $8e, $14, $85
	.byte $20, $83, $00, $81, $20, $83, $00, $81, $23, $85, $00, $81, $25, $85, $23, $85, $20, $85, $1e, $85, $00, $81, $1e, $85
	.byte $00, $81, $20, $85, $00, $9d
	.byte $41, $48
	.word @song3ref483
	.byte $41, $3c
	.word @song3ref483
	.byte $41, $22
	.word @song3ref503
	.byte $41, $2e
	.word @song3ref497
	.byte $41, $14
	.word @song3ref503
	.byte $00, $fd, $ff, $ff, $bf
	.byte $41, $20
	.word @song3ref450
	.byte $19, $85, $25, $85, $19, $85, $25, $85, $1b, $85, $27, $85
@song3ref592:
	.byte $1b, $85, $27
@song3ref595:
	.byte $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $14, $85, $20, $85, $19, $85, $25, $85, $19, $85, $25
	.byte $85, $1b, $85, $27, $85, $23, $85, $22
	.byte $41, $1d
	.word @song3ref595
	.byte $41, $23
	.word @song3ref592
	.byte $85, $00, $fd, $ff
	.byte $41, $20
	.word @song3ref451
	.byte $44, $00
@song3ch3:
	.byte $af, $74, $82
@song3ref646:
	.byte $1d, $81, $00, $81, $72, $20, $81, $00, $81, $74, $1d, $81, $00, $81, $72, $20, $81, $00, $81, $74, $1d, $81, $00, $81
	.byte $72, $20, $81, $00, $81, $74
	.byte $41, $18
	.word @song3ref646
	.byte $74, $1d, $81, $00, $81, $72, $20, $81, $00, $81, $76, $25, $00, $25, $00, $25, $00, $25
@song3ref697:
	.byte $00
@song3ref698:
	.byte $79, $8c, $1e, $8d, $76, $80
@song3ref704:
	.byte $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00, $24, $00
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $16
	.word @song3ref698
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $16
	.word @song3ref698
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $16
	.word @song3ref698
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $16
	.word @song3ref698
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $16
	.word @song3ref698
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $16
	.word @song3ref698
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $24, $00, $24, $00, $24, $00, $24
	.byte $41, $17
	.word @song3ref697
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $41, $14
	.word @song3ref704
	.byte $ff, $44, $00
@song3ch4:
	.byte $af, $ff
@song3ref896:
	.byte $1e, $85, $00, $85, $33, $85, $1e, $85, $00, $85, $1e, $85, $33, $85, $00, $85, $1e, $85, $00, $85, $33, $85, $00, $85
	.byte $1e, $85, $00, $85, $33, $81, $33, $81, $33, $81, $33, $81
	.byte $41, $24
	.word @song3ref896
	.byte $41, $24
	.word @song3ref896
	.byte $41, $24
	.word @song3ref896
	.byte $41, $24
	.word @song3ref896
	.byte $41, $24
	.word @song3ref896
	.byte $41, $24
	.word @song3ref896
	.byte $41, $24
	.word @song3ref896
	.byte $41, $1d
	.word @song3ref896
	.byte $85, $33, $81, $33, $81
	.byte $41, $16
	.word @song3ref896
	.byte $1e, $85, $33, $85, $1e, $85, $33, $85, $33, $81, $33, $81
	.byte $41, $1d
	.word @song3ref896
	.byte $85, $33, $81, $33, $81
	.byte $41, $16
	.word @song3ref896
	.byte $1e, $85, $33, $85, $1e, $85, $33, $81, $33, $81, $33, $81, $33, $81
	.byte $41, $1d
	.word @song3ref896
	.byte $85, $33, $85
	.byte $41, $24
	.word @song3ref896
	.byte $41, $1d
	.word @song3ref896
	.byte $85, $33, $85
	.byte $41, $24
	.word @song3ref896
	.byte $41, $1d
	.word @song3ref896
	.byte $85, $33, $81, $33, $81
	.byte $41, $16
	.word @song3ref896
	.byte $1e, $85, $33, $85, $1e, $85, $33, $85, $33, $81, $33, $81, $00, $fd, $44, $00
@song4ch0:
	.byte $46, $06, $74, $4b, .lobyte(@env25), .hibyte(@env25), $8e, $20, $9d, $4b, .lobyte(@env7), .hibyte(@env7), $24, $9d
	.byte $4b, .lobyte(@env9), .hibyte(@env9), $21, $9d, $4b, .lobyte(@env25), .hibyte(@env25), $20, $9d, $4d, $20, $9d, $4b
	.byte .lobyte(@env7), .hibyte(@env7), $24, $9d, $4b, .lobyte(@env9), .hibyte(@env9), $21, $9d, $4b, .lobyte(@env25), .hibyte(@env25)
	.byte $20, $9d
@song4ref43:
	.byte $76, $4b, .lobyte(@env30), .hibyte(@env30), $4f, $00, $0d, $83, $00, $4d, $0d, $83, $00, $4b, .lobyte(@env19), .hibyte(@env19)
	.byte $4c, $92, $14, $79, $19, $00, $1c, $00, $14, $19, $1c, $75, $8e, $50, $2e, $19, $14, $81, $00, $50, $2e, $19, $14, $81
	.byte $00, $50, $2e, $19, $14, $81, $7b, $50, $10, $27, $20
@song4ref94:
	.byte $85, $4b, .lobyte(@env25), .hibyte(@env25), $14, $83, $00, $74, $4b, .lobyte(@env30), .hibyte(@env30), $0d, $83, $00
	.byte $4d, $0d, $83, $00, $4b, .lobyte(@env19), .hibyte(@env19), $4c, $92, $14, $79, $19, $00, $1c, $00, $14, $18, $14, $4b
	.byte .lobyte(@env7), .hibyte(@env7), $8e, $19, $8b, $00, $4d, $18, $8b, $00
	.byte $41, $16
	.word @song4ref43
	.byte $7b, $50, $06, $38, $31
	.byte $41, $18
	.word @song4ref94
	.byte $41, $2f
	.word @song4ref43
	.byte $41, $16
	.word @song4ref43
	.byte $7b, $50, $06, $38, $31
	.byte $41, $18
	.word @song4ref94
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $87, $44, $00
@song4ch1:
@song4ref174:
	.byte $4b, .lobyte(@env30), .hibyte(@env30), $86, $20, $81, $7c, $4b, .lobyte(@env19), .hibyte(@env19), $4c, $88, $20, $00
	.byte $7f, $4b, .lobyte(@env30), .hibyte(@env30), $86, $20, $81, $7c, $4b, .lobyte(@env19), .hibyte(@env19), $4c, $88, $20
	.byte $00, $7f, $4b, .lobyte(@env30), .hibyte(@env30), $86, $25, $81, $7c, $4b, .lobyte(@env19), .hibyte(@env19), $4c, $88
	.byte $25, $00, $7f, $4b, .lobyte(@env30), .hibyte(@env30), $86, $24, $81, $7c, $4b, .lobyte(@env19), .hibyte(@env19), $4c
	.byte $88, $24, $00, $7f, $4b, .lobyte(@env30), .hibyte(@env30), $86, $20, $81, $7c, $4b, .lobyte(@env19), .hibyte(@env19)
	.byte $4c, $88, $20, $00, $7f, $4b, .lobyte(@env30), .hibyte(@env30), $86, $20, $81, $7c, $4b, .lobyte(@env19), .hibyte(@env19)
	.byte $4c, $88, $20, $00, $7f, $4b, .lobyte(@env30), .hibyte(@env30), $86, $24, $81, $7c, $4b, .lobyte(@env19), .hibyte(@env19)
	.byte $4c, $88, $24, $00, $7f, $4b, .lobyte(@env30), .hibyte(@env30), $86, $21, $81, $7c, $4b, .lobyte(@env19), .hibyte(@env19)
	.byte $4c, $88, $21, $00, $7f
	.byte $41, $10
	.word @song4ref174
@song4ref297:
	.byte $7f, $4b, .lobyte(@env30), .hibyte(@env30), $86, $27, $81, $7c, $4b, .lobyte(@env19), .hibyte(@env19), $4c, $88, $27
	.byte $00, $7f, $4b, .lobyte(@env30), .hibyte(@env30), $86, $25, $81, $7c, $4b, .lobyte(@env19), .hibyte(@env19), $4c, $88
	.byte $25, $00, $7f, $4b, .lobyte(@env30), .hibyte(@env30), $86, $24, $81, $7c, $4b, .lobyte(@env19), .hibyte(@env19), $4c
	.byte $88, $24, $00, $7f, $4b, .lobyte(@env30), .hibyte(@env30), $86, $21, $81, $7c, $4b, .lobyte(@env19), .hibyte(@env19)
	.byte $4c, $88, $21, $00, $7f
	.byte $41, $20
	.word @song4ref174
	.byte $7f
	.byte $41, $10
	.word @song4ref174
	.byte $41, $10
	.word @song4ref297
	.byte $4e, $00, $4b, .lobyte(@env9), .hibyte(@env9), $4f, $00, $8e
@song4ref376:
	.byte $1c, $83, $00, $4d, $1c, $83, $00, $4b, .lobyte(@env19), .hibyte(@env19), $4c, $4f, $02, $86, $14, $7f, $4e, $01, $19
	.byte $00, $1c, $00, $14, $19, $1c, $7c, $4e, $00, $8e, $50, $2e, $19, $14, $81, $00, $50, $2e, $19, $14, $81, $00, $50, $2e
	.byte $19, $14, $81, $00, $85, $79, $4e, $02, $4f, $01, $50, $08, $33, $2c
@song4ref433:
	.byte $85, $7c, $4e, $00, $4b, .lobyte(@env9), .hibyte(@env9), $4f, $00, $1c, $83, $00, $4d, $1c, $83, $00, $4b, .lobyte(@env19)
	.byte .hibyte(@env19), $4c, $4f, $02, $86, $14, $7f, $4e, $01, $19, $00, $1c, $00, $14, $18, $14, $79, $4e, $00, $4f, $03
	.byte $8e, $09, $8d, $08, $8d, $7c, $4e, $00, $4b, .lobyte(@env9), .hibyte(@env9), $4f, $00
	.byte $41, $18
	.word @song4ref376
	.byte $79, $4e, $02, $4f, $01, $50, $03, $44, $3d
	.byte $41, $13
	.word @song4ref433
	.byte $7c, $4e, $00, $4b, .lobyte(@env9), .hibyte(@env9), $4f, $00
	.byte $41, $2c
	.word @song4ref376
	.byte $7c, $4e, $00, $4b, .lobyte(@env9), .hibyte(@env9), $4f, $00
	.byte $41, $18
	.word @song4ref376
	.byte $79, $4e, $02, $4f, $01, $50, $03, $44, $3d
	.byte $41, $13
	.word @song4ref433
	.byte $7f, $4b, .lobyte(@env30), .hibyte(@env30)
@song4ref538:
	.byte $86, $19, $7c, $4d, $88, $19, $7f, $4d, $86, $18, $7c, $4d, $88, $18, $7f, $4d, $86, $1c, $7c, $4d, $88, $1c, $7f, $4d
	.byte $86, $18, $7c, $4d, $88, $18, $7f, $4d, $86, $1b, $7c, $4d, $88, $1b, $7f, $4d, $86, $19, $7c, $4d, $88, $19, $7f, $4d
	.byte $86, $15, $7c, $4d, $88, $15, $7f, $4d, $86, $14, $7c, $4d, $88, $14, $7f, $4d, $86, $18, $7c, $4d, $88, $18, $7f, $4d
	.byte $86, $14, $7c, $4d, $88, $14, $7f, $4d, $86, $19, $7c, $4d, $88, $19, $7f, $4d, $86, $14, $7c, $4d, $88, $14, $7f, $4d
	.byte $86, $1b, $7c, $4d, $88, $1b, $7f, $4d, $86, $14, $7c, $4d, $88, $14, $7f, $4d, $86, $1c, $7c, $4d, $88, $1c, $7f, $4d
	.byte $86, $18, $7c, $4d, $88, $18, $7f, $4d
	.byte $41, $20
	.word @song4ref538
	.byte $7f, $4d
	.byte $41, $20
	.word @song4ref538
	.byte $7f, $4d
	.byte $41, $20
	.word @song4ref538
	.byte $00, $85, $44, $00
@song4ch2:
	.byte $8e, $14, $9d, $18, $9d, $15, $9d, $14, $9d, $14, $9d, $18, $9d, $15, $9d, $14, $9d, $a0
@song4ref702:
	.byte $19, $00, $19, $00, $19, $00, $19, $00, $19, $00, $19, $00, $19, $00, $19, $00, $14, $00, $14, $00, $14, $00, $14, $00
	.byte $14, $00, $14, $00, $14, $00, $14, $00
	.byte $41, $20
	.word @song4ref702
	.byte $41, $20
	.word @song4ref702
	.byte $41, $20
	.word @song4ref702
	.byte $41, $20
	.word @song4ref702
	.byte $41, $20
	.word @song4ref702
	.byte $41, $20
	.word @song4ref702
	.byte $41, $20
	.word @song4ref702
	.byte $9e
@song4ref756:
	.byte $19, $85, $25, $00, $83, $17, $85, $23, $00, $83, $14, $85, $20, $00, $83, $18, $85, $27, $00, $83
	.byte $41, $14
	.word @song4ref756
	.byte $41, $14
	.word @song4ref756
	.byte $19, $8d, $17, $8d, $14, $8d, $18, $8d, $00, $85, $44, $00
@song4ch3:
	.byte $8c, $21, $8d, $00, $8d, $9f, $9f, $9f, $9f, $9f, $8a, $1a, $81, $1a, $81, $1a, $81, $1a, $81, $1a, $81, $1a, $81, $1a
	.byte $81, $1a, $81, $1a, $1a, $1a, $1a, $1a, $1a, $1a, $1a, $82, $21, $22, $21, $22, $21, $22, $21, $22, $8c
@song4ref840:
	.byte $1d, $81, $80, $22, $22, $82, $21, $00, $80, $22, $22, $8a, $19, $00, $80, $22, $22, $82, $21, $80, $22, $22, $22, $8a
	.byte $19, $00, $80, $22, $22, $82, $21, $00, $80, $22, $22, $8a, $19, $00, $80, $22, $22, $82, $21, $80, $22, $8c, $1f, $81
	.byte $41, $20
	.word @song4ref840
	.byte $41, $20
	.word @song4ref840
	.byte $41, $20
	.word @song4ref840
	.byte $41, $20
	.word @song4ref840
	.byte $41, $20
	.word @song4ref840
	.byte $41, $20
	.word @song4ref840
	.byte $41, $20
	.word @song4ref840
	.byte $1e, $95, $00, $85, $9f, $9f, $9b, $22, $81, $21, $8d, $00, $8d, $9f, $9f, $9f, $21, $85, $44, $00
@song4ch4:
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $1e, $81, $1e, $81, $1e, $81, $1e, $81, $1e, $81, $1e, $81, $1e, $81, $1e, $81, $1e, $1e
	.byte $1e, $1e, $1e, $1e, $1e, $1e, $1e, $1e, $1e, $1e, $1e, $1e, $1e, $1e
@song4ref968:
	.byte $1e, $81, $13, $81, $33, $81, $13, $81, $1e, $81, $13, $81, $33, $81, $13, $81, $1e, $81, $12, $81, $33, $81, $12, $81
	.byte $1e, $81, $12, $81, $33, $81, $12, $81
	.byte $41, $20
	.word @song4ref968
	.byte $41, $20
	.word @song4ref968
	.byte $41, $20
	.word @song4ref968
	.byte $41, $20
	.word @song4ref968
	.byte $41, $20
	.word @song4ref968
	.byte $41, $20
	.word @song4ref968
	.byte $41, $20
	.word @song4ref968
@song4ref1021:
	.byte $13, $85, $15, $00, $83, $18, $85, $0f, $00, $83, $12, $85, $14, $00, $83, $1c, $85, $1d, $00, $83
	.byte $41, $14
	.word @song4ref1021
	.byte $41, $14
	.word @song4ref1021
	.byte $13, $8d, $18, $8d, $12, $8d, $1c, $8d, $00, $85, $44, $00
@song5ch0:
	.byte $46, $08, $89, $9a, $26, $83, $a2
@song5ref8:
	.byte $25, $83, $2a, $83, $2b, $83, $2d, $83, $28, $83, $2a, $83, $2b, $83, $26, $83, $28, $83, $2a, $83, $2b, $83, $26, $83
	.byte $28, $83, $2a, $83, $2b, $83, $26, $81, $4f, $00, $81
	.byte $41, $21
	.word @song5ref8
	.byte $4f, $01, $96
@song5ref49:
	.byte $39, $83, $37
@song5ref52:
	.byte $36, $81, $37, $83, $32, $83, $00, $81, $2d, $81, $2b, $83, $32, $87, $34, $83, $2b
	.byte $41, $0e
	.word @song5ref52
	.byte $4f, $01
	.byte $41, $14
	.word @song5ref49
	.byte $41, $0e
	.word @song5ref52
	.byte $98, $21, $00, $81, $21, $00, $81, $25
@song5ref88:
	.byte $00, $21, $00, $81, $21, $1f, $00, $81, $1f, $00, $81, $21, $00, $1f, $00, $81, $1f, $1e, $00, $81, $1e, $00, $1e, $1f
	.byte $00, $1e, $00, $81, $1e, $1a, $00, $81, $1a, $00, $1a, $00, $83, $1a, $00, $88, $0e, $98, $21, $00, $81, $21, $00, $25
	.byte $26
	.byte $41, $27
	.word @song5ref88
	.byte $88, $32, $96, $36, $34, $81, $32, $34, $81, $32, $36, $81, $37, $36, $81, $32, $2d, $83, $2b, $81, $2a, $2b, $81, $2a
	.byte $26, $81
@song5ref166:
	.byte $2a, $26
@song5ref168:
	.byte $81, $2a, $2b, $81, $2a, $83
@song5ref174:
	.byte $2b, $2d, $81, $32, $2d, $83, $2b, $81, $2a, $2b, $81, $2a, $26, $81, $2d, $2b
	.byte $41, $14
	.word @song5ref168
	.byte $41, $18
	.word @song5ref166
	.byte $41, $14
	.word @song5ref168
	.byte $41, $18
	.word @song5ref166
	.byte $81, $2a, $2b, $81, $2d, $2a, $81
	.byte $41, $0e
	.word @song5ref174
	.byte $41, $14
	.word @song5ref166
	.byte $75, $32, $7d, $81, $7f, $4f, $02, $81
@song5ref223:
	.byte $34, $81, $36, $37, $81, $36, $37, $81, $36, $37, $81, $39, $39, $81, $37, $37, $81, $36, $36, $81, $32, $32, $81, $2d
	.byte $41, $0e
	.word @song5ref223
	.byte $3b, $3b, $81, $3c, $3c, $81, $3e, $3e
@song5ref258:
	.byte $81, $39, $39
@song5ref261:
	.byte $81, $37, $37, $81, $36, $36, $81, $32, $32, $81, $36, $36, $81, $37, $37, $81, $36, $36, $81, $32, $32
	.byte $41, $18
	.word @song5ref258
	.byte $81, $31, $30
	.byte $41, $15
	.word @song5ref261
	.byte $41, $18
	.word @song5ref258
	.byte $81, $31, $30
	.byte $41, $15
	.word @song5ref261
	.byte $41, $16
	.word @song5ref258
	.byte $74, $8e, $32, $81, $45, $7f, $96, $36, $34, $81, $32, $34, $81, $32, $36, $81, $37, $36, $81, $34
@song5ref323:
	.byte $32, $81, $2d, $26, $81, $2a, $2a, $81, $2a, $83, $26, $2d, $81, $2a, $2d, $83, $2a, $81, $2d, $2b, $81, $32, $26, $81
	.byte $2d, $26, $81, $2a, $2a, $81, $2a, $83, $26, $4f, $01, $26, $87, $28, $83, $2a, $2b, $81, $2d
	.byte $41, $1e
	.word @song5ref323
	.byte $4f, $01, $9a, $2a, $83, $44, $00
@song5ch1:
	.byte $7a, $4f, $02, $a4, $26, $81, $45, $89, $25, $81, $45, $2a, $81, $45, $2b, $81, $45, $2d, $81, $45, $28, $81, $45, $2a
	.byte $81, $45, $2b, $81, $45, $26, $81, $45, $78, $86
@song5ref411:
	.byte $1e, $74, $1a, $78, $12, $1e, $74, $1a, $78, $12, $1e, $74, $1a, $78, $12, $1e, $74, $1a, $78, $12, $1a, $74, $15, $78
	.byte $0e, $1a, $74, $15, $78, $0e, $1a, $74, $15, $78, $0e, $1a, $74, $15, $78, $0e, $21, $74, $19, $78, $15, $21, $74, $19
	.byte $78, $15, $21, $74, $19, $78, $15, $21, $74, $19, $78, $15, $1f, $74, $17, $78, $13, $1f, $74, $17, $78, $13, $1f, $74
	.byte $17, $78, $13, $1f, $74, $17, $78, $13
	.byte $41, $30
	.word @song5ref411
	.byte $41, $30
	.word @song5ref411
	.byte $41, $30
	.word @song5ref411
	.byte $41, $30
	.word @song5ref411
	.byte $41, $30
	.word @song5ref411
	.byte $41, $30
	.word @song5ref411
	.byte $41, $30
	.word @song5ref411
	.byte $41, $30
	.word @song5ref411
	.byte $41, $30
	.word @song5ref411
	.byte $41, $30
	.word @song5ref411
	.byte $41, $30
	.word @song5ref411
	.byte $41, $30
	.word @song5ref411
	.byte $41, $30
	.word @song5ref411
	.byte $41, $30
	.word @song5ref411
	.byte $41, $18
	.word @song5ref411
	.byte $44, $00
@song5ch2:
	.byte $89, $9e, $0e, $83
@song5ref543:
	.byte $00, $91, $21, $81, $1f, $00, $8f, $1f, $81, $1e, $00, $8f, $1e, $81, $1a, $00, $8f, $1a, $81
	.byte $41, $13
	.word @song5ref543
	.byte $41, $13
	.word @song5ref543
	.byte $41, $13
	.word @song5ref543
	.byte $41, $13
	.word @song5ref543
	.byte $41, $13
	.word @song5ref543
@song5ref577:
	.byte $21, $00, $81, $21, $00, $81, $21, $00, $81, $21, $00, $81, $1f, $00, $81, $1f, $00, $81, $1f, $00, $81, $1f, $00, $81
	.byte $1e, $00, $81, $1e, $00, $81, $1e, $00, $81, $1e, $00, $81, $1a, $00, $81, $1a, $00, $81, $1a, $00, $81, $1a, $00, $81
	.byte $41, $30
	.word @song5ref577
	.byte $41, $30
	.word @song5ref577
	.byte $41, $30
	.word @song5ref577
	.byte $df, $df, $df, $df, $df, $df, $44, $00
@song5ch3:
	.byte $70, $90, $1f, $83, $71, $81, $74, $81, $7a, $83, $7c, $81, $7f, $82, $14, $83, $80, $22, $22, $81, $22, $22, $81, $7c
	.byte $22, $22, $81, $7b, $22, $22, $81, $22, $22, $81, $7a, $22, $22, $81, $78, $22, $22, $81, $7f
@song5ref686:
	.byte $22, $82, $14, $81, $80, $22, $22, $81, $22, $82, $14, $81, $80, $22, $84, $22, $81, $80, $22, $82, $14, $81, $80, $22
	.byte $22, $81, $22, $82, $14, $81, $80, $22, $84, $22, $81, $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $15
	.word @song5ref686
	.byte $7a, $90, $1f, $81, $7c, $81, $7f, $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $15
	.word @song5ref686
	.byte $7a, $90, $1f, $81, $7c, $81, $7f, $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $15
	.word @song5ref686
	.byte $7a, $90, $1f, $81, $7c, $81, $7f, $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $15
	.word @song5ref686
	.byte $7a, $90, $1f, $81, $7c, $81, $7f, $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $15
	.word @song5ref686
	.byte $7a, $90, $1f, $81, $7c, $81, $7f, $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $18
	.word @song5ref686
	.byte $80
	.byte $41, $15
	.word @song5ref686
	.byte $7a, $90, $1f, $81, $7c, $81, $7f, $80, $22, $82, $16, $81, $80
@song5ref857:
	.byte $22, $22, $81, $22, $22, $81, $84, $22, $83
@song5ref866:
	.byte $80, $22, $22, $81, $22, $22, $81, $22, $22, $81, $84, $22, $83, $80, $22, $22, $81
	.byte $41, $11
	.word @song5ref857
	.byte $22, $84, $22, $81
	.byte $41, $0e
	.word @song5ref866
	.byte $41, $16
	.word @song5ref857
	.byte $22, $22, $81, $22, $22, $81, $7a, $90, $1f, $81, $7c, $81, $00, $dd, $70, $1f, $d3, $71, $81, $74, $81, $7a, $83, $7c
	.byte $81, $44, $00
@song5ch4:
	.byte $1e, $8d, $33, $83, $33, $ad
@song5ref930:
	.byte $1e, $1e, $83, $33, $81, $1e, $83, $33, $83, $1e, $1e, $83, $33, $81, $1e, $83, $33, $83
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $41, $12
	.word @song5ref930
	.byte $1e, $83, $1e, $1e, $cf, $df, $00, $dd, $df, $44, $00
