#define song_okiba_crackdown 0
#define song_fingerbang 1
#define song_nine_circles 2
#define song_atthespeedoflightfull 3
#define song_thermodynamix_full 4
#define song_every_end_pt2 5
#define song_freedom_dive 6
#define song_menu_theme_e_side 7
#define song_infernoplex_full 8
#define song_dash_full 9
#define song_youve_been_trolled 10
#define song_cant_let_go 11
#define song_the_angel 12
#define song_metamorphosis 13
#define song_time_machine_full 14
#define song_clutterfunk 15
#define song_miami_hotline_vol_3 16
#define song_endorphins 17
#define song_future_funk_pt1 18
#define song_apoplexy 19
#define song_clubstep 20
#define song_accelerate 21
#define song_every_end_pt1 22
#define song_practice 23
#define song_careless 24
#define song_2nes 25
#define song_just_right_full 26
#define song_polargeist 27
#define song_theory_of_everything 28
#define song_toe_2 29
#define song_press_start 30
#define song_chaoz_airflow 31
#define song_rainbow_tylenol 32
#define song_blast_processing 33
#define song_geometrical_dominator 34
#define song_animation_warrior_theme 35
#define song_electrodynamix 36
#define song_back_on_track_full 37
#define song_bit_of_a_vibe 38
#define song_beep_beep 39
#define song_future_funk_pt2 40
#define song_eighto_full 41
#define song_hsad 42
#define song_hexagon_force 43
#define song_endgame 44
#define song_free_mind 45
#define song_magic_touch 46
#define song_astronomical_expedition 47
#define song_factory_time 48
#define song_bad_apple 49
#define song_isolation 50
#define song_clutterfunk_2 51
#define song_cryogenic 52
#define song_check_out 53
#define song_idols 54
#define song_death_moon 55
#define song_glint 56
#define song_slash_inferno 57
#define song_electroman_adventures 58
#define song_explorers 59
#define song_the_challenge 60
#define song_jack_russel 61
#define song_ninox 62
#define song_shiawase_vip 63
#define song_fantasy 64
#define song_megalovania 65
#define song_slow_down 66
#define song_haunted_woods 67
#define song_holography 68
#define song_pursuit 69
#define song_against_the_odds_redux 70
#define song_every_madness 71
#define song_final_battle 72
#define song_mayhem_re_nes 73
#define song_sonic_blaster 74
#define song_supernova 75
#define song_golden_haze_full 76
#define song_raining_tacos 77
#define song_tiny_tunes 78
#define song_fire_aura 79
#define song_snow 80
#define song_stalemate 81
#define song_menu_theme_b_sides 82
#define song_base_after_base 83
#define song_infiltration 84
#define song_power_trip 85
#define song_airborne_robots 86
#define song_emeht_unem 87
#define song_pyrophoric_xl 88
#define song_ultimatedestruction 89
#define song_deadlocked 90
#define song_dry_out_full 91
#define song_lost 92
#define song_xenogenesis 93
#define song_scheming_weasel 94
#define song_chaozfantasy 95
#define song_glitch_gremlin 96
#define song_infinite_power 97
#define song_cycles 98
#define song_blacklight 99
#define song_dance_of_the_violins 100
#define song_kesobomb 101
#define song_stereo_madness 102
#define song_ground_to_space 103
#define song_meltdown 104
#define song_subtle_oddities 105
#define song_extraordinary_excitement 106
#define song_stereo_madness_2 107
#define song_windfall 108
#define song_xo 109
#define song_menu_theme 110
#define song_xstep 111
#define song_jawbreaker 112
#define song_kratos 113
#define song_ssendam_oerets 114
#define song_candyland 115
#define song_driving_by_night 116
#define song_fairydust 117
#define song_midnight 118
#define song_the_seven_seas 119
#define song_chaoz_impact 120
#define song_jumper_full 121
#define song_meowstuff 122
#define song_select_payment_type 123
#define song_repmuj 124
#define song_menu_theme_human_capturing_mix 125
#define song_flow 126
#define song_ludicrous_speed 127
#define song_moon_fries 128
#define song_off_to_mars 129
#define song_problematic 130
#define song_max 131