sfx_death = 0
sfx_click = 1
sfx_level_complete = 2
sfx_coin = 3
sfx_chest_open = 4
sfx_orbs = 5
sfx_diamonds = 6
sfx_exit_level = 7
sfx_start_level = 8
sfx_invalid = 9
sfx_achievement_get = 10
sfx_max = 11

.if SFX_STRINGS
sfx_strings:
.asciiz "death"
.asciiz "click"
.asciiz "LEVEL COMPLETE!"
.asciiz "coin"
.asciiz "chest open"
.asciiz "orbs"
.asciiz "diamonds"
.asciiz "exit level"
.asciiz "start level"
.asciiz "invalid"
.asciiz "achievement get"
.endif
